#!/usr/bin/env python3
"""현재 JAR 한국어 후보에서 별도 대조가 필요했던 73개 키의 확정 번역."""

TRANSLATIONS: dict[str, str] = {
    "block.the_bumblezone.sugar_infused_cobblestone": "설탕이 스며든 조약돌",
    "block.the_bumblezone.sugar_infused_stone": "설탕이 스며든 돌",
    "item.the_bumblezone.honey_crystal_shield.level_tooltip": "방패 단계",
    "item.the_bumblezone.honey_compass_structure_loading": "꿀 나침반 - 구조물 찾는 중...",
    "item.the_bumblezone.honey_compass_structure_failed": "꿀 나침반 - 구조물을 찾지 못했습니다...",
    "item.the_bumblezone.honey_compass_unknown_block": "알 수 없는 블록",
    "item.the_bumblezone.honey_compass_description2": "벌집 미로 구조물을 찾으세요!",
    "item.the_bumblezone.honey_compass_description3": "또는 벌통/벌집을 우클릭해",
    "item.the_bumblezone.honey_compass_description4": "나침반을 해당 위치에 고정하세요!",
    "item.the_bumblezone.honey_compass_structure_description1": "벌통/벌집을 우클릭해",
    "item.the_bumblezone.honey_compass_structure_description2": "블록 위치 모드로 전환하세요!",
    "item.the_bumblezone.honey_compass_structure_description3": "나침반이 블록 위치를 가리킵니다.",
    "item.the_bumblezone.honey_compass_block_description2": "벌집 미로 구조물 찾기로 전환하세요!",
    "item.the_bumblezone.honey_compass_block_description3": "또는 벌통/벌집 블록을 우클릭해",
    "item.the_bumblezone.honey_compass_block_description4": "해당 위치를 추적하도록 고정하세요!",
    "item.the_bumblezone.honey_compass_throne_description": "§o§6이 나침반을 따라가세요! 여왕이 기다립니다!",
    "item.the_bumblezone.honey_compass_mystery_structure": "꿀 나침반 - 수수께끼의 구조물",
    "item.the_bumblezone.honey_compass_mystery_structure_description": "이 나침반은 어디로 이끌까요?",
    "item.the_bumblezone.essence_of_the_bees.already_essenced": "이미 벌의 정수가 깃들어 있습니다",
    "item.the_bumblezone.potion_candle.infinite": "무한",
    "enchantment.the_bumblezone.comb_cutter.desc": "벌집 조각, 벌통, 벌집, 밀랍 블록을 더 빨리 캡니다. \n벌집이나 벌통 블록의 산출량을 두 배로 늘립니다.",
    "enchantment.the_bumblezone.potent_poison.desc": "언데드가 아닌 몹을 맞히면 독을 부여합니다. \n단계가 높을수록 지속 시간과 독 단계가 증가합니다.",
    "enchantment.the_bumblezone.neurotoxins.desc": "언데드와 철·눈 골렘이 아닌 몹에게 일정 확률로 마비를 부여합니다. \n대상의 체력이 높을수록 마비 확률이 낮아집니다.",
    "effect.the_bumblezone.protection_of_the_hive.description": "이 효과를 지닌 대상에게 화난 근처의 모든 벌을 진정시킵니다. \n\n이 효과를 지닌 엔티티가 공격받으면 근처 벌이 공격자에게 화냅니다! \n\n모든 경로로 부여되는 벌집의 분노를 막는 대신 이 상태 효과를 잃습니다. \n벌, 비히모스 또는 벌집 유충 블록에 꿀 종류 먹이를 주면 때때로 이 효과를 얻습니다.",
    "effect.the_bumblezone.beenergized.description": "대부분의 비행 몹이 나는 속도를 높입니다. 호박벌 흉갑을 입은 플레이어는 더 멀리, 더 오래 날 수 있습니다.\n\n보통 벌빵, 벌 수프 또는 로열 젤리 병을 섭취하면 이 효과를 얻습니다.\n\n벌의 정수를 섭취한 뒤에는 불이 켜진 발광 밀랍 위나 로열 젤리 액체 안에 서면 짧은 벌에너지 효과를 얻습니다.",
    "effect.the_bumblezone.hidden.description": "적대적 몹에게 처음 감지되는 거리를 줄입니다. 화난 벌 떼가 플레이어를 놓치게 하는 데도 유용합니다. \n꽃가루 더미 블록 안에 숨으면 이 효과를 얻습니다.",
    "subtitles.entity.the_bumblezone.beehemoth.hurt": "비히모스가 상처를 입음",
    "subtitles.entity.the_bumblezone.beehemoth.dies": "비히모스가 죽음",
    "subtitles.entity.the_bumblezone.beehemoth.loop": "비히모스가 윙윙거림",
    "subtitles.entity.the_bumblezone.bee_queen.hurt": "여왕벌이 상처를 입음",
    "subtitles.entity.the_bumblezone.bee_queen.dies": "여왕벌이 죽음",
    "subtitles.entity.the_bumblezone.bee_queen.loop": "여왕벌이 윙윙거림",
    "subtitles.entity.the_bumblezone.bee_queen.happy": "여왕벌이 가르랑거림",
    "subtitles.entity.the_bumblezone.honey_slime.attack": "꿀 슬라임이 공격함",
    "subtitles.entity.the_bumblezone.honey_slime.hurt": "꿀 슬라임이 상처를 입음",
    "subtitles.entity.the_bumblezone.honey_slime.death": "꿀 슬라임이 죽음",
    "subtitles.entity.the_bumblezone.honey_slime.squish": "꿀 슬라임이 철퍽거림",
    "subtitles.entity.the_bumblezone.honey_slime.jump": "꿀 슬라임이 뜀",
    "subtitles.entity.the_bumblezone.honey_slime.hurt_small": "작은 꿀 슬라임이 상처를 입음",
    "subtitles.entity.the_bumblezone.honey_slime.death_small": "작은 꿀 슬라임이 죽음",
    "subtitles.entity.the_bumblezone.honey_slime.squish_small": "작은 꿀 슬라임이 철퍽거림",
    "subtitles.entity.the_bumblezone.honey_slime.jump_small": "작은 꿀 슬라임이 공격함",
    "subtitles.entity.the_bumblezone.pollen_puff.throw": "꽃가루 뭉치가 날아감",
    "subtitles.entity.the_bumblezone.stinger_spear.hit": "벌침 창이 찌름",
    "subtitles.entity.the_bumblezone.stinger_spear.hit_ground": "벌침 창이 진동함",
    "subtitles.entity.the_bumblezone.stinger_spear.return": "벌침 창이 되돌아옴",
    "subtitles.entity.the_bumblezone.stinger_spear.throw": "벌침 창이 빠르게 날아감",
    "subtitles.entity.the_bumblezone.bee_stinger.hit": "벌침이 명중함",
    "subtitles.entity.the_bumblezone.honey_crystal_shard.hit": "꿀 수정 조각이 명중함",
    "subtitles.entity.the_bumblezone.honey_crystal_shard.shatter": "꿀 수정 조각이 산산이 부서짐",
    "subtitles.item.the_bumblezone.bumble_bee_chestplate.fly": "플레이어가 윙윙거림",
    "subtitles.item.the_bumblezone.honey_compass.block_lock": "꿀 나침반이 블록에 고정됨",
    "subtitles.item.the_bumblezone.honey_compass.structure_lock": "꿀 나침반이 구조물에 고정됨",
    "subtitles.item.the_bumblezone.bee_cannon.fire": "벌 대포가 발사됨",
    "subtitles.item.the_bumblezone.crystal_cannon.fire": "수정 대포가 발사됨",
    "subtitles.item.the_bumblezone.sugar_water_bottle.drink": "꿀꺽 삼킴",
    "subtitles.item.the_bumblezone.royal_jelly_bottle.drink": "꿀꺽 삼킴",
    "subtitles.item.the_bumblezone.essence_of_the_bees.consumed": "벌의 정수가 힘을 부여함",
    "subtitles.item.the_bumblezone.essence_of_the_bees.consuming": "벌의 정수가 공명함",
    "subtitles.block.the_bumblezone.washing_honey_residues": "꿀 찌꺼기가 씻겨 나감",
    "subtitles.block.the_bumblezone.royal_jelly_block.slide": "로열 젤리 블록을 타고 미끄러짐",
    "subtitles.block.the_bumblezone.crystalline_flower.use": "결정꽃이 마법을 부여함",
    "key.the_bumblezone.beehemoth_down": "비히모스 하강",
    "key.the_bumblezone.beehemoth_up": "비히모스 상승",
    "system.the_bumblezone.failed_teleporting": "엔티티 순간이동에 실패해 중단했습니다. 다시 시도해 주세요.",
    "system.the_bumblezone.no_protection": "벌집의 보호 효과가 없었습니다...",
    "system.the_bumblezone.lost_bee_essence": "재생성하면서 벌의 정수를 잃었습니다...",
    "container.the_bumblezone.honey_cocoon": "꿀 고치",
    "container.the_bumblezone.crystalline_flower": "소비 및 마법 부여",
    "container.the_bumblezone.crystalline_flower.too_many_enchants": "마법 부여 제한: 3",
    "command.the_bumblezone.have_bee_essence": "%s에게 벌의 정수 효과가 있습니다!",
    "command.the_bumblezone.does_not_have_bee_essence": "%s에게 벌의 정수 효과가 없습니다...",
    "command.the_bumblezone.queens_desired_not_active": "%s은(는) 이 명령을 사용하기 전에 여왕의 소망 발전 과제를 시작해야 합니다...",
}
