#!/usr/bin/env python3
"""The Bumblezone 전투·UI·통계·명령 표시 문구의 검수 완료 번역."""

TRANSLATIONS: dict[str, str] = {
    "death.attack.the_bumblezone.crystalline_flower": "%1$s이(가) 결정꽃에 찔려 죽었습니다",
    "death.attack.the_bumblezone.crystalline_flower.player": "%1$s이(가) %2$s에게서 도망치려다 결정꽃에 찔려 죽었습니다",
    "death.attack.the_bumblezone.architects": "%1$s이(가) 정수 이벤트에서 도망치려다 목숨을 잃었습니다",
    "death.attack.the_bumblezone.architects.player": "%1$s이(가) 정수 이벤트에서 도망치려다 목숨을 잃었습니다",
    "death.attack.the_bumblezone.spikes": "%1$s이(가) 통찰의 정수 이벤트 중 가시에 꿰뚫렸습니다",
    "death.attack.the_bumblezone.spikes.player": "%1$s이(가) 통찰의 정수 이벤트 중 가시에 꿰뚫렸습니다",
    "death.attack.the_bumblezone.sentry_watcher_crushing": "%1$s이(가) 센트리 감시자에게 짓눌려 죽었습니다",
    "death.attack.the_bumblezone.sentry_watcher_crushing.player": "%1$s이(가) 센트리 감시자에게 짓눌려 죽었습니다",
    "death.attack.the_bumblezone.cosmic_crystal": "%1$s이(가) 코스믹 수정의 힘에 소멸했습니다",
    "death.attack.the_bumblezone.cosmic_crystal.player": "%1$s이(가) 코스믹 수정의 힘에 소멸했습니다",
    "death.attack.the_bumblezone.dirt_pellet": "%1$s이(가) %2$s에게 흙 알갱이로 두들겨 맞았습니다",
    "death.attack.the_bumblezone.dirt_pellet.item": "%1$s이(가) %3$s을(를) 사용한 %2$s에게 두들겨 맞았습니다",
    "death.attack.the_bumblezone.event_dirt_pellet": "%1$s이(가) %2$s에게 흙 알갱이로 두들겨 맞았습니다",
    "death.attack.the_bumblezone.event_dirt_pellet.item": "%1$s이(가) %3$s을(를) 사용한 %2$s에게 두들겨 맞았습니다",
    "block.the_bumblezone.string_curtain.extending_clarification": "실을 사용해 실 커튼을 늘리세요!",
    "enchantment_lore.the_bumblezone:comb_cutter.description": "벌집 조각, 벌통, 벌집과 밀랍 블록을 더 빨리 캡니다. 벌집이나 벌통 블록의 산출량이 두 배가 됩니다.",
    "enchantment_lore_forge.the_bumblezone:comb_cutter.description": "벌집 조각, 벌통, 벌집과 밀랍 블록을 더 빨리 캡니다. 벌집이나 벌통 블록의 산출량이 두 배가 됩니다.",
    "enchantment_lore.the_bumblezone:potent_poison.description": "언데드가 아닌 몹을 맞히면 독을 부여합니다. 단계가 높을수록 지속 시간과 독 단계가 증가합니다.",
    "enchantment_lore_forge.the_bumblezone:potent_poison.description": "언데드가 아닌 몹을 맞히면 독을 부여합니다. 단계가 높을수록 지속 시간과 독 단계가 증가합니다.",
    "enchantment_lore.the_bumblezone:neurotoxins.description": "언데드와 철·눈 골렘이 아닌 몹에게 일정 확률로 마비를 부여합니다. 대상의 체력이 높을수록 마비 확률이 낮아집니다.",
    "enchantment_lore_forge.the_bumblezone:neurotoxins.description": "언데드와 철·눈 골렘이 아닌 몹에게 일정 확률로 마비를 부여합니다. 대상의 체력이 높을수록 마비 확률이 낮아집니다.",
    "enchantment.the_bumblezone.hive_lifeline.desc": "플레이어가 받는 모든 공격 피해를 근처 벌이 대신 받습니다! 피해를 넘기면 마법이 부여된 갑옷에 짧은 재사용 대기시간이 생깁니다.",
    "enchantment_lore.the_bumblezone:hive_lifeline.description": "플레이어가 받는 모든 공격 피해를 근처 벌이 대신 받습니다! 피해를 넘기면 마법이 부여된 갑옷에 짧은 재사용 대기시간이 생깁니다.",
    "enchantment_lore_forge.the_bumblezone:hive_lifeline.description": "플레이어가 받는 모든 공격 피해를 근처 벌이 대신 받습니다! 피해를 넘기면 마법이 부여된 갑옷에 짧은 재사용 대기시간이 생깁니다.",
    "effect.the_bumblezone.wrath_of_the_hive.description": "The Bumblezone 차원에서 근처의 모든 벌을 강화하고 플레이어에게 화나게 합니다! \n\n근처 벌집 유충 블록도 더 빨리 성장하고 벌을 더 빠르게 생성합니다. \n벌이나 여왕벌을 해치거나, 꿀이 찬 다공성 벌집 조각 블록에서 꿀을 채취하거나, 벌집 유충 블록을 죽이거나, 꿀 블록을 캐거나, 벌집의 보호 효과 없이 벌집 미로에 들어가면 이 효과를 얻습니다.\n\n벌의 정수를 섭취한 뒤에는 벌이나 여왕벌을 해치거나 벌집 유충 블록을 죽였을 때만 이 효과를 얻습니다. 평화로움 난이도에서는 플레이어가 이 효과를 얻을 수 없습니다.",
    "effect.the_bumblezone.paralyzed.description": "몹을 움직이지 못하게 하며, 일반적으로 몹의 AI와 이동을 비활성화합니다. \n\n일부 몹은 이 효과에 저항해 마녀가 물약을 마시는 것과 같은 행동을 계속할 수 있습니다.\n\n신경독 마법이 부여된 무기에 맞거나, 벌침 투사체에 여러 번 맞거나, 드물게 벌 수프를 마시면 이 효과를 얻습니다.",
    "subtitles.entity.the_bumblezone.sentry_watcher.crash": "센트리 감시자가 충돌함",
    "subtitles.entity.the_bumblezone.sentry_watcher.activating": "센트리 감시자가 활성화됨",
    "subtitles.entity.the_bumblezone.sentry_watcher.moving": "센트리 감시자가 돌진함",
    "subtitles.entity.the_bumblezone.rootmin.cursing": "루트민이 저주함",
    "subtitles.entity.the_bumblezone.rootmin.shock": "루트민이 놀람",
    "subtitles.entity.the_bumblezone.rootmin.shoot": "루트민이 발사함",
    "subtitles.entity.the_bumblezone.dirt_pellet.throw": "흙 알갱이가 날아감",
    "subtitles.entity.the_bumblezone.dirt_pellet.hit": "흙 알갱이가 부딪힘",
    "subtitles.entity.the_bumblezone.cosmic_crystal_entity.laser": "코스믹 수정이 발사함",
    "subtitles.entity.the_bumblezone.cosmic_crystal_entity.laser_charge": "코스믹 수정이 충전함",
    "subtitles.entity.the_bumblezone.cosmic_crystal_entity.crash_charge": "코스믹 수정이 추적함",
    "subtitles.entity.the_bumblezone.cosmic_crystal_entity.crashes": "코스믹 수정이 충돌함",
    "subtitles.entity.the_bumblezone.cosmic_crystal_entity.spin": "코스믹 수정이 회전함",
    "subtitles.entity.the_bumblezone.cosmic_crystal_entity.spawn_explosion": "코스믹 수정이 나타남",
    "subtitles.item.the_bumblezone.buzzing_briefcase.releases": "윙윙거리는 서류 가방이 벌을 풀어 줌",
    "subtitles.block.the_bumblezone.honey_crystal_block.chime": "꿀 수정이 울림",
    "subtitles.block.the_bumblezone.windy_air.blows": "바람이 붊",
    "stat.the_bumblezone.carpenter_bee_boots_mined_blocks": "The Bumblezone: 어리호박벌 부츠로 캔 블록",
    "stat.the_bumblezone.carpenter_bee_boots_wall_hang_time": "The Bumblezone: 어리호박벌 부츠로 벽에 매달린 시간",
    "stat.the_bumblezone.stingless_bee_helmet_bee_rider": "The Bumblezone: 무침벌 투구에 벌이 앉은 시간",
    "stat.the_bumblezone.bumble_bee_chestplate_fly_time": "The Bumblezone: 호박벌 흉갑으로 비행한 시간",
    "stat.the_bumblezone.honey_bee_leggings_flower_pollen": "The Bumblezone: 꿀벌 레깅스에 모은 꽃가루",
    "stat.the_bumblezone.interact_with_crystalline_flower": "The Bumblezone: 결정꽃 UI를 연 횟수",
    "stat.the_bumblezone.interact_with_buzzing_briefcase": "The Bumblezone: 윙윙거리는 서류 가방 UI를 연 횟수",
    "stat.the_bumblezone.buzzing_briefcase_bee_capture": "The Bumblezone: 윙윙거리는 서류 가방으로 잡은 벌",
    "stat.the_bumblezone.windy_air_time": "The Bumblezone: 바람 부는 공기에서 보낸 시간",
    "stat.the_bumblezone.raging_event_defeated": "The Bumblezone: 격노의 정수 이벤트 완료",
    "stat.the_bumblezone.radiance_event_defeated": "The Bumblezone: 광휘의 정수 이벤트 완료",
    "stat.the_bumblezone.life_event_defeated": "The Bumblezone: 생명의 정수 이벤트 완료",
    "stat.the_bumblezone.calming_event_defeated": "The Bumblezone: 평온의 정수 이벤트 완료",
    "stat.the_bumblezone.knowing_event_defeated": "The Bumblezone: 통찰의 정수 이벤트 완료",
    "stat.the_bumblezone.continuity_event_defeated": "The Bumblezone: 지속의 정수 이벤트 완료",
    "essence.the_bumblezone.missing_essence_effect": "먼저 벌의 정수를 섭취해야 합니다...",
    "essence.the_bumblezone.red_essence_event": "§c격노의 정수§f - %s 후 §c실패§f",
    "essence.the_bumblezone.purple_essence_event": "§d통찰의 정수§f - %s 후 §6승리§f",
    "essence.the_bumblezone.blue_essence_event": "§b평온의 정수§f - %s 후 §c실패§f",
    "essence.the_bumblezone.green_essence_event": "§a생명의 정수§f - %s 후 §c실패§f",
    "essence.the_bumblezone.yellow_essence_event": "§e광휘의 정수§f - %s 후 §c실패§f",
    "essence.the_bumblezone.white_essence_event": "지속의 정수 - %s 후 §c실패§f",
    "container.the_bumblezone.honey_cocoon.item_count": "%s ×%s",
    "container.the_bumblezone.honey_cocoon.more": "외 %s개...",
    "container.the_bumblezone.crystalline_flower.level": "단계: %s",
    "container.the_bumblezone.crystalline_flower.level_star": "★",
    "container.the_bumblezone.crystalline_flower.tier_cost": "티어 비용: %s",
    "container.the_bumblezone.crystalline_flower.tier_cost_arrow": "↓%s",
    "container.the_bumblezone.crystalline_flower.sort_alphabetically": "표시 이름순 정렬",
    "container.the_bumblezone.crystalline_flower.sort_namespace": "네임스페이스(모드 ID)순 정렬",
    "container.the_bumblezone.crystalline_flower.sort_treasure_curse": "보물 및 저주순 정렬",
    "container.the_bumblezone.crystalline_flower.sort_level": "단계순 정렬",
    "command.the_bumblezone.invalid_data_arg": "data 인수가 올바르지 않습니다. 제안 목록에서 하나를 선택하세요.",
    "command.the_bumblezone.invalid_entity_arg": "이 데이터 요청에는 entity 인수가 필요합니다. 제안 목록에서 엔티티를 선택하세요.",
    "command.the_bumblezone.data_change_success": "대상 플레이어의 데이터를 변경했습니다!",
    "command.the_bumblezone.queens_desired_crafted_beehive": "%s이(가) 여왕의 소망 발전 과제를 위해 벌통 %s개를 제작했습니다",
    "command.the_bumblezone.queens_desired_bees_bred": "%s이(가) 여왕의 소망 발전 과제를 위해 벌 %s마리를 번식시켰습니다",
    "command.the_bumblezone.queens_desired_flowers_spawned": "%s이(가) 여왕의 소망 발전 과제를 위해 던진 꽃가루 뭉치로 꽃 %s송이를 생성했습니다",
    "command.the_bumblezone.queens_desired_honey_bottle_drank": "%s이(가) 여왕의 소망 발전 과제를 위해 꿀이 든 병 %s개를 마셨습니다",
    "command.the_bumblezone.queens_desired_bee_stingers_fired": "%s이(가) 여왕의 소망 발전 과제를 위해 활이나 쇠뇌로 벌침 %s개를 발사했습니다",
    "command.the_bumblezone.queens_desired_bee_saved": "%s이(가) 여왕의 소망 발전 과제를 위해 벌 %s마리에게 벌침을 되돌려 주었습니다",
    "command.the_bumblezone.queens_desired_pollen_puff_hits": "%s이(가) 여왕의 소망 발전 과제를 위해 던진 꽃가루 뭉치로 몹 %s마리를 맞혔습니다",
    "command.the_bumblezone.queens_desired_honey_slime_bred": "%s이(가) 여왕의 소망 발전 과제를 위해 꿀 슬라임 %s마리를 번식시켰습니다",
    "command.the_bumblezone.queens_desired_bees_fed": "%s이(가) 여왕의 소망 발전 과제를 위해 벌에게 꿀 종류 아이템을 %s번 먹였습니다",
    "command.the_bumblezone.queens_desired_queen_bee_trade": "%s이(가) 여왕의 소망 발전 과제를 위해 여왕벌과 %s번 거래했습니다",
    "command.the_bumblezone.queens_desired_killed_entity_counter": "%s이(가) 여왕의 소망 발전 과제를 위해 %s마리의 %s을(를) 처치했습니다",
    "command.the_bumblezone.queens_desired_killed_entity_counter_ender_dragon": "%s이(가) 여왕의 소망 발전 과제를 위해 벌 갑옷 4개를 착용하고 %s마리의 %s을(를) 처치했습니다",
    "command.the_bumblezone.queens_desired_killed_entity_counter_wither": "%s이(가) 여왕의 소망 발전 과제를 위해 벌침 창으로 %s마리의 %s을(를) 처치했습니다",
}
