#!/usr/bin/env python3
"""The Bumblezone 설정·UI·툴팁·시스템 문구의 검수 완료 번역."""

TRANSLATIONS: dict[str, str] = {
    "the_bumblezone.configuration.title": "The Bumblezone 설정",
    "the_bumblezone.configuration.section.the.bumblezone.mod.compatibility.toml.title": "The Bumblezone 모드 호환성",
    "the_bumblezone.configuration.section.the.bumblezone.worldgen.toml.title": "The Bumblezone 세계 생성",
    "the_bumblezone.configuration.section.the.bumblezone.dimension.toml.title": "The Bumblezone 차원",
    "the_bumblezone.configuration.section.the.bumblezone.bee.aggression.toml.title": "The Bumblezone 벌 공격성",
    "the_bumblezone.configuration.section.the.bumblezone.client.toml.title": "The Bumblezone 클라이언트",
    "the_bumblezone.configuration.section.the.bumblezone.general.toml.title": "The Bumblezone 일반",
    "the_bumblezone.configuration.clientdimensionoptions": "클라이언트 The Bumblezone 차원 설정",
    "the_bumblezone.configuration.fogbrightnesspercentage.tooltip": "The Bumblezone 차원 안개의 밝기입니다. 0은 칠흑같이 어둡고, 50은 기본 밝기의 절반, 100은 일반적인 주황색 밝기, 100000은 흰색으로 보입니다.",
    "the_bumblezone.configuration.fogthickness.tooltip": "The Bumblezone 안개의 농도입니다. 2는 옅은 안개, 50은 매우 짙은 안개입니다. 소수도 사용할 수 있습니다.",
    "the_bumblezone.configuration.enabledimensionfog": "차원 안개 사용",
    "the_bumblezone.configuration.enabledimensionfog.tooltip": "The Bumblezone 차원에 짙은 안개를 표시할지 정합니다.",
    "the_bumblezone.configuration.essenceitemhudrenderingconfigs": "정수 HUD 표시 설정",
    "the_bumblezone.configuration.essenceitemhudvisualeffectlayers.tooltip": "보조 손에 정수 아이템을 들었을 때 HUD에 표시할 회전 텍스처 레이어 수입니다. 0이면 표시하지 않습니다.",
    "the_bumblezone.configuration.essenceitemhudvisualeffectspeed.tooltip": "보조 손에 정수 아이템을 들었을 때 HUD 텍스처 레이어가 회전하는 속도입니다. 0.5는 절반 속도이며, 0이면 회전하지 않습니다.",
    "the_bumblezone.configuration.knowingessencehighlightingconfigs.tooltip": "§7§o(더 많은 설정은 블록 및 엔티티 태그를 확인하세요)§f",
    "the_bumblezone.configuration.knowingessencehighlightbosses.tooltip": "통찰의 정수가 보스를 보라색으로 강조 표시할지 정합니다. §7§o(강제 강조 엔티티 태그보다 우선하지 않습니다)§f",
    "the_bumblezone.configuration.knowingessencehighlightmonsters.tooltip": "통찰의 정수가 몬스터를 빨간색으로 강조 표시할지 정합니다. §7§o(강제 강조 엔티티 태그보다 우선하지 않습니다)§f",
    "the_bumblezone.configuration.knowingessencehighlighttamed.tooltip": "통찰의 정수가 자신이 길들인 몹을 초록색으로 강조 표시할지 정합니다. §7§o(강제 강조 엔티티 태그보다 우선하지 않습니다)§f",
    "the_bumblezone.configuration.knowingessencehighlightlivingentities.tooltip": "통찰의 정수가 그 밖의 생명체를 주황색으로 강조 표시할지 정합니다. §7§o(강제 강조 엔티티 태그보다 우선하지 않습니다)§f",
    "the_bumblezone.configuration.knowingessencehighlightcommonitems.tooltip": "통찰의 정수가 월드에 있는 일반 아이템을 흰색으로 강조 표시할지 정합니다.",
    "the_bumblezone.configuration.knowingessencehighlightuncommonitems.tooltip": "통찰의 정수가 월드에 있는 고급 아이템을 노란색으로 강조 표시할지 정합니다.",
    "the_bumblezone.configuration.knowingessencehighlightrareitems.tooltip": "통찰의 정수가 월드에 있는 희귀 아이템을 청록색으로 강조 표시할지 정합니다.",
    "the_bumblezone.configuration.knowingessencehighlightepicitems.tooltip": "통찰의 정수가 월드에 있는 특급 아이템을 보라색으로 강조 표시할지 정합니다.",
    "the_bumblezone.configuration.knowingessencestructurenameclient.tooltip": "통찰의 정수가 현재 들어와 있는 구조물 이름을 알려 줄지 정합니다. §7§o(서버 설정에서 끌 수 있습니다)§f",
    "the_bumblezone.configuration.knowingessencestructurenamexcoord": "구조물 이름 X 좌표",
    "the_bumblezone.configuration.knowingessencestructurenamexcoord.tooltip": "화면에 구조물 이름을 표시할 X 좌표입니다. §7§o(왼쪽 아래 모서리 기준)§f",
    "the_bumblezone.configuration.knowingessencestructurenameycoord": "구조물 이름 Y 좌표",
    "the_bumblezone.configuration.knowingessencestructurenameycoord.tooltip": "화면에 구조물 이름을 표시할 Y 좌표입니다. §7§o(왼쪽 아래 모서리 기준)§f",
    "the_bumblezone.configuration.radianceessencearmordurability.tooltip": "광휘의 정수가 착용한 갑옷의 내구도를 표시할지 정합니다.",
    "the_bumblezone.configuration.radianceessencearmordurabilityxcoord": "갑옷 내구도 X 좌표",
    "the_bumblezone.configuration.radianceessencearmordurabilityxcoord.tooltip": "화면에 갑옷 내구도를 표시할 X 좌표입니다. §7§o(왼쪽 아래 모서리 기준)§f",
    "the_bumblezone.configuration.radianceessencearmordurabilityycoord": "갑옷 내구도 Y 좌표",
    "the_bumblezone.configuration.radianceessencearmordurabilityycoord.tooltip": "화면에 갑옷 내구도를 표시할 Y 좌표입니다. §7§o(왼쪽 아래 모서리 기준)§f",
    "the_bumblezone.configuration.usebackupmodelforvariantbee.tooltip": "다른 모드나 리소스팩 때문에 변종 벌 모델이 깨질 때 사용하세요. 게임을 다시 시작해야 합니다.",
    "the_bumblezone.configuration.renderbeequeenbonustradeitem.tooltip": "여왕벌이 보너스 거래로 원하는 아이템을 몸 위에 표시할지 정합니다.",
    "the_bumblezone.configuration.playwrathofhiveeffectmusic.tooltip": "켜면 벌집의 분노 효과가 있을 때 §6Rimsky Korsakov§f의 §6Flight of the Bumblebee§f를 재생합니다.",
    "the_bumblezone.configuration.playsempiternalsanctummusic.tooltip": "켜면 영원 성소 안에 있을 때 §6LudoCrypt§f의 §6Bee-ware of the Temple§f을 재생합니다.",
    "the_bumblezone.configuration.showbeequeenspeechbubble.tooltip": "가능한 거래를 안내하는 여왕벌의 말풍선을 표시합니다.",
    "the_bumblezone.configuration.disableessenceblockshaders.tooltip": "정수 블록의 셰이더를 표시하지 않을지 정합니다. 셰이더를 끄면 일반 블록 텍스처를 사용합니다.",
    "the_bumblezone.configuration.showbeesonguiallyearround": "GUI 벌 연중 표시",
    "the_bumblezone.configuration.showbeesonguiallyearround.tooltip": "언제나 벌과 함께하는 즐거움을 누리고 싶을 때 사용하세요!",
    "the_bumblezone.configuration.showbeesonguionaprilfools": "만우절에 GUI 벌 표시",
    "the_bumblezone.configuration.showbeesonguionaprilfools.tooltip": "벌들의 장난스러운 모습을 보고 싶을 때 사용하세요!",
    "the_bumblezone.configuration.restrictbeesonguitobzdimension": "GUI 벌을 The Bumblezone에서만 표시",
    "the_bumblezone.configuration.restrictbeesonguitobzdimension.tooltip": "플레이어가 The Bumblezone 차원에 있을 때만 GUI 벌을 표시합니다.",
    "the_bumblezone.configuration.maximumbeesongui": "GUI 벌 최대 수",
    "the_bumblezone.configuration.maximumbeesongui.tooltip": "GUI에 벌 10000마리도 표시할 수 있습니다!",
    "the_bumblezone.configuration.beehemothtriggerswrath.tooltip": "켜면 비히모스의 주인이 아닌 엔티티가 비히모스를 해칠 때 그 엔티티에게 벌집의 분노 효과를 부여합니다.",
    "the_bumblezone.configuration.allowwrathofthehiveoutsidebumblezone": "The Bumblezone 밖에서 분노 허용",
    "the_bumblezone.configuration.allowwrathofthehiveoutsidebumblezone.tooltip": "The Bumblezone 밖에서 꿀 블록을 줍거나, 꿀이 찬 다공성 벌집 조각 블록에서 꿀을 얻거나, 꿀이 든 병을 마신 플레이어에게 벌집의 분노를 부여할지 정합니다.",
    "the_bumblezone.configuration.showwrathofthehiveparticles.tooltip": "The Bumblezone에서 벌을 화나게 해 벌집의 분노를 얻을 때 주황빛 입자를 표시합니다.",
    "the_bumblezone.configuration.allowwrath.tooltip": "벌집의 분노 효과를 얻을 수 있는지 정합니다. 벌은 벽 너머로 플레이어를 보고 속도 증가, 흡수와 힘 효과를 얻습니다. 차원 안에서 다른 몹을 대하는 벌의 공격성에도 영향을 줍니다. §c참고:§f 평화로움 난이도에서는 항상 벌의 공격성이 사라집니다.",
    "the_bumblezone.configuration.aggressiontriggerradius.tooltip": "The Bumblezone에서 벌집의 분노를 얻었을 때 벌이 분노해 플레이어를 추적하기 시작하는 최대 거리입니다. 차원 안에서 다른 몹을 공격하는 범위에도 영향을 줍니다.",
    "the_bumblezone.configuration.howlongwrathofthehivelasts.tooltip": "벌집의 분노 지속 시간입니다. 성난 벌이 §7§o속도 증가, 흡수와 힘§f 효과를 유지하는 시간과 같습니다. 단위는 틱이며 20틱은 1초입니다. 벌의 일반적인 분노는 그대로 남습니다.",
    "the_bumblezone.configuration.speedboostlevel.tooltip": "벌이 땅 위에서 움직이는 속도입니다. §7§o(비행 중에는 적용되지 않습니다)§f 벌은 공격 직전에 바닥에 닿는 일이 많아 이 효과로 플레이어에게 빠르게 돌진합니다. 값을 높이면 돌진 속도가 빨라집니다.",
    "the_bumblezone.configuration.absorptionboostlevel.tooltip": "벌에게 주어지고 즉시 회복되는 흡수 체력입니다. 벌의 실제 체력을 줄이려면 한 번에 더 큰 피해를 줘야 합니다. 2나 3처럼 높은 값을 사용하면 살충 V가 있어야 벌을 죽일 수 있습니다.",
    "the_bumblezone.configuration.strengthboostlevel.tooltip": "벌의 공격력이 강해지는 정도입니다. §7§o(5 이상이면 갑옷이 없을 때 즉사할 수 있습니다)§f",
    "the_bumblezone.configuration.howlongprotectionofthehivelasts.tooltip": "벌이나 유충 블록에 먹이를 준 뒤 엔티티가 벌집의 보호 효과를 유지하는 시간입니다. 벌은 이 효과가 있는 대상을 공격한 자에게 달려듭니다.",
    "the_bumblezone.configuration.enableinitialwelcomemessage.tooltip": "처음 벌통 근처에 갔을 때 The Bumblezone 발전 과제를 확인하라는 메시지를 표시할지 정합니다.",
    "the_bumblezone.configuration.enableentranceteleportation.tooltip": "The Bumblezone 모드가 The Bumblezone 차원으로 들어가는 순간이동을 처리하도록 허용합니다.",
    "the_bumblezone.configuration.enableexitteleportation.tooltip": "The Bumblezone 모드가 The Bumblezone 차원에서 나가는 순간이동을 처리하도록 허용합니다.",
    "the_bumblezone.configuration.forcebumblezoneoriginmobtooverworldcenter.tooltip": "켜면 The Bumblezone에서 처음 생성된 몹이 차원에서 나갈 때 오버월드의 0, 0 중심으로 순간이동합니다.",
    "the_bumblezone.configuration.forceexittooverworld.tooltip": "처음 들어온 차원과 관계없이 The Bumblezone에서 나가면 항상 오버월드로 돌아갑니다. 두 차원 사이에서 순간이동이 반복될 때 사용하세요.",
    "the_bumblezone.configuration.onlyoverworldhivesteleports.tooltip": "벌통이나 벌집에 엔더 진주를 던지는 방법이 오버월드에서만 작동하게 합니다. 켜면 오버월드에서만 The Bumblezone에 들어갈 수 있습니다.",
    "the_bumblezone.configuration.warnplayersofwrongblockunderhive.tooltip": "§6the_bumblezone:dimension_teleportation/required_blocks_under_beehive_to_teleport§f 블록 태그에 블록이 지정되어 있을 때, 벌통이나 벌집 아래에 잘못된 블록을 놓고 The Bumblezone으로 이동하려 하면 경고를 표시합니다.",
    "the_bumblezone.configuration.allowteleportationwithmoddedbeehives.tooltip": "다른 모드의 벌통과 벌집으로도 The Bumblezone에 들어가거나 나올 수 있게 할지 정합니다.",
    "the_bumblezone.configuration.defaultdimension.tooltip": "몹에 이전 차원이 저장되어 있지 않을 때 The Bumblezone을 나가며 이동할 기본 차원을 바꿉니다. 모드팩의 기본 차원이 오버월드가 아닐 때만 사용하세요. §6출구를 오버월드로 고정§f, §6몹을 오버월드로 보내기§f와 §6오버월드 벌집에서만 순간이동§f 설정도 새 기본 차원을 사용합니다.",
    "the_bumblezone.configuration.alternativefluidtoreplacehoneyfluid.tooltip": "차원 안에서 The Bumblezone의 액체 꿀을 대신할 액체입니다. 게임을 다시 시작해야 합니다. §c참고:§f 이미 놓인 액체 꿀은 바꾸지 않습니다.",
    "the_bumblezone.configuration.pokecubecompat": "Pokecube 호환",
    "the_bumblezone.configuration.pokecubecompat.tooltip": "Pokecube의 벌 계열 포켓몬이 The Bumblezone과 꿀 유충 블록에서 생성되게 합니다.",
    "the_bumblezone.configuration.spawnpokecubebeepokemon.tooltip": "Pokecube의 벌 계열 포켓몬이 The Bumblezone과 꿀 유충 블록에서 생성되게 합니다.",
    "the_bumblezone.configuration.beepokemongetsprotectioneffect.tooltip": "The Bumblezone에서 생성된 Pokecube의 벌 계열 포켓몬에게 벌집의 보호 효과를 줍니다. 이 포켓몬을 공격하면 벌집의 분노를 얻고 성난 벌떼의 공격을 받습니다.",
    "the_bumblezone.configuration.spawnrateofpokecubebeepokemon.tooltip": "벌집 유충 블록에서 나오는 벌이 Pokecube의 벌 포켓몬으로 바뀔 확률입니다. 0이면 포켓몬이 나오지 않고 1이면 항상 포켓몬이 나옵니다.",
    "the_bumblezone.configuration.tropicraftcompat": "Tropicraft 호환",
    "the_bumblezone.configuration.spawntropicraftbeesmob.tooltip": "일반 벌이 생성될 때 §6트로피비 생성률§f에 따라 Tropicraft의 트로피비가 The Bumblezone과 꿀 유충 블록에서 함께 생성되게 합니다.",
    "the_bumblezone.configuration.spawnrateoftropicraftbeesmobs.tooltip": "The Bumblezone의 벌집 유충 블록에서 나오는 벌이 Tropicraft의 트로피비로 바뀔 확률입니다. 0이면 나오지 않고 1이면 항상 트로피비가 나옵니다.",
    "the_bumblezone.configuration.allowtropicraftspawnfromdispenserfedbroodblock.tooltip": "발사기가 먹이를 준 벌집 유충 블록에서도 Tropicraft의 트로피비가 생성될 수 있게 합니다.",
    "the_bumblezone.configuration.resourcefulbeescompat": "Resourceful Bees 호환",
    "the_bumblezone.configuration.spawnresourcefulbeesbeesmob": "Resourceful Bees 벌 생성",
    "the_bumblezone.configuration.spawnresourcefulbeesbeesmob.tooltip": "§6Resourceful Bees 생성률§f에 따라 Resourceful Bees의 벌이 차원과 꿀 유충 블록에서 일반 벌과 함께 생성되게 합니다. 생성할 벌은 §6the_bumblezone:resourcefulbees/spawnable_from_brood_block§f 및 §6the_bumblezone:resourcefulbees/spawnable_from_chunk_creation§f 엔티티 태그로 조절할 수 있습니다.",
    "the_bumblezone.configuration.spawnrateofresourcefulbeesmobsbrood": "블록에서 나오는 Resourceful Bees 생성률",
    "the_bumblezone.configuration.spawnrateofresourcefulbeesmobsbrood.tooltip": "The Bumblezone의 벌집 유충 블록에서 나오는 벌이 Resourceful Bees의 벌로 바뀔 확률입니다. 0이면 나오지 않고 1이면 항상 바뀝니다.",
    "the_bumblezone.configuration.spawnrateofresourcefulbeesmobsother": "Resourceful Bees 생성률",
    "the_bumblezone.configuration.spawnrateofresourcefulbeesmobsother.tooltip": "The Bumblezone에서 생성되는 일반 벌이 Resourceful Bees의 벌로 바뀔 확률입니다. 0이면 바뀌지 않고 1이면 항상 바뀝니다.",
    "the_bumblezone.configuration.rborehoneycombspawnratebeedungeon.tooltip": "벌 던전에서 §6the_bumblezone:resourcefulbees/spawns_in_bee_dungeons§f 블록 태그의 벌집 조각이 차지하는 비율입니다. 0이면 없고 1이면 최대입니다.",
    "the_bumblezone.configuration.rborehoneycombspawnratespiderbeedungeon.tooltip": "거미 감염 벌 던전에서 §6the_bumblezone:resourcefulbees/spawns_in_spider_infested_bee_dungeons§f 블록 태그의 벌집 조각이 차지하는 비율입니다. 0이면 없고 1이면 최대입니다.",
    "the_bumblezone.configuration.spawnresourcefulbeeshoneycombveins.tooltip": "Resourceful Bees의 여러 벌집 조각 변형이 The Bumblezone의 다양한 높이와 고도 구간에 생성되게 합니다. 탐험하며 생성 위치를 찾아보세요! §c참고:§f 적용하려면 월드를 다시 시작해야 합니다.",
    "the_bumblezone.configuration.allowresourcefulbeesbeejarrevivingemptybroodblock.tooltip": "벌이 든 벌 단지로 빈 벌집 유충 블록을 유충이 든 일반 벌집 유충 블록으로 바꿀 수 있게 합니다!",
    "the_bumblezone.configuration.allowresourcefulbeesspawnfromdispenserfedbroodblock": "발사기 유충 블록에서 Resourceful Bees 생성",
    "the_bumblezone.configuration.allowresourcefulbeesspawnfromdispenserfedbroodblock.tooltip": "발사기가 먹이를 준 벌집 유충 블록에서도 Resourceful Bees의 벌이 생성될 수 있게 합니다.",
    "the_bumblezone.configuration.productivebeescompat": "Productive Bees 호환",
    "the_bumblezone.configuration.spawnproductivebeesbeesmob": "Productive Bees 벌 생성",
    "the_bumblezone.configuration.spawnproductivebeesbeesmob.tooltip": "일반 벌이 생성될 때 §6Productive Bees 생성률§f에 따라 Productive Bees의 벌이 The Bumblezone과 꿀 유충 블록에서 함께 생성되게 합니다.",
    "the_bumblezone.configuration.spawnrateofproductivebeesmobs": "Productive Bees 생성률",
    "the_bumblezone.configuration.spawnrateofproductivebeesmobs.tooltip": "The Bumblezone이나 벌집 유충 블록에서 나오는 벌이 Productive Bees의 벌로 바뀔 확률입니다. 0이면 바뀌지 않고 1이면 항상 바뀝니다.",
    "the_bumblezone.configuration.allowedbees": "허용할 Productive Bees 벌",
    "the_bumblezone.configuration.allowedbees.tooltip": "The Bumblezone에서 생성될 수 있는 Productive Bees 벌을 정합니다.",
    "the_bumblezone.configuration.spawnproductivebeeshoneycombvariants.tooltip": "Productive Bees의 벌집 조각 변형이 차원에 생성될지 정합니다. 생성할 벌집 조각은 §6the_bumblezone:productive_bees_combs§f 배치된 지형지물 태그로 조절합니다. §c참고:§f 적용하려면 월드를 다시 시작해야 합니다.",
    "the_bumblezone.configuration.allowedcombsfordungeons.tooltip": "The Bumblezone 던전에 생성될 수 있는 Productive Bees 벌집 조각을 정합니다.",
    "the_bumblezone.configuration.allowproductivebeesbeecagerevivingemptybroodblock.tooltip": "벌이 든 벌 우리로 빈 벌집 유충 블록을 유충이 든 일반 벌집 유충 블록으로 바꿀 수 있게 합니다!",
    "the_bumblezone.configuration.allowproductivebeesspawnfromdispenserfedbroodblock": "발사기 유충 블록에서 Productive Bees 생성",
    "the_bumblezone.configuration.allowproductivebeesspawnfromdispenserfedbroodblock.tooltip": "발사기가 먹이를 준 벌집 유충 블록에서도 Productive Bees의 벌이 생성될 수 있게 합니다.",
    "the_bumblezone.configuration.pborehoneycombspawnratebeedungeon.tooltip": "벌 던전에서 광물 기반 벌집 조각이 차지하는 비율입니다. 0이면 Productive Bees 벌집 조각이 없고 1이면 최대입니다.",
    "the_bumblezone.configuration.pborehoneycombspawnratespiderbeedungeon.tooltip": "거미 감염 벌 던전에서 광물 기반 벌집 조각이 차지하는 비율입니다. 0이면 Productive Bees 벌집 조각이 없고 1이면 최대입니다.",
    "the_bumblezone.configuration.friendsandfoescompat": "Friends and Foes 호환",
    "the_bumblezone.configuration.allowfriendsandfoesbeekeepertradescompat.tooltip": "Friends and Foes의 양봉가 거래에 The Bumblezone 아이템을 추가합니다!",
    "the_bumblezone.configuration.quarkcompat": "Quark 호환",
    "the_bumblezone.configuration.injectbzitemsintoquarkenchantmenttooltipscompat": "마법 툴팁에 The Bumblezone 아이템 표시",
    "the_bumblezone.configuration.injectbzitemsintoquarkenchantmenttooltipscompat.tooltip": "Quark의 마법 툴팁에 The Bumblezone 아이템 기호를 추가합니다!",
    "the_bumblezone.configuration.buzzierbeescompat": "Buzzier Bees 호환",
    "the_bumblezone.configuration.allowbeebottlerevivingemptybroodblock.tooltip": "벌 병으로 빈 벌집 유충 블록을 유충이 든 일반 벌집 유충 블록으로 바꿀 수 있게 합니다!",
    "the_bumblezone.configuration.forbiddenarcanuscompat": "Forbidden and Arcanus 호환",
    "the_bumblezone.configuration.allowbeebucketrevivingemptybroodblock.tooltip": "벌 양동이로 빈 벌집 유충 블록을 유충이 든 일반 벌집 유충 블록으로 바꿀 수 있게 합니다!",
    "the_bumblezone.configuration.potionofbeescompat": "Potion of Bees 호환",
    "the_bumblezone.configuration.allowpotionofbeesrevivingemptybroodblock.tooltip": "벌 물약으로 빈 벌집 유충 블록을 유충이 든 일반 벌집 유충 블록으로 바꿀 수 있게 합니다!",
    "the_bumblezone.configuration.goodallcompat": "Goodall 호환",
    "the_bumblezone.configuration.allowgoodallbottledbeesrevivingemptybroodblock.tooltip": "병에 든 벌로 빈 벌집 유충 블록을 유충이 든 일반 벌집 유충 블록으로 바꿀 수 있게 합니다!",
    "the_bumblezone.configuration.beekeepercompat": "Beekeeper 호환",
    "the_bumblezone.configuration.allowbeekeepertradescompat.tooltip": "Beekeeper 모드의 양봉가 거래에 The Bumblezone 아이템을 추가합니다!",
    "the_bumblezone.configuration.lootrcompat": "Lootr 호환",
    "the_bumblezone.configuration.allowlootrcompat": "Lootr 꿀 고치",
    "the_bumblezone.configuration.allowlootrcompat.tooltip": "전리품 꿀 고치가 Lootr와 호환되게 합니다.",
    "the_bumblezone.configuration.createcompat": "Create 호환",
    "the_bumblezone.configuration.allowcreatelimestoneforhoneylavacompat.tooltip": "꿀과 용암이 만날 때 Create의 석회암이 생성될 수 있게 합니다.",
    "the_bumblezone.configuration.bzhoneyfluidfromhoneybottles.tooltip": "꿀이 든 병에서 액체를 추출할 때 The Bumblezone의 액체 꿀을 만들지 정합니다. §7§o(액체 추출 기계를 생각하면 됩니다)§f",
    "the_bumblezone.configuration.variantbeetypes.tooltip": "생성될 수 있는 변종 벌의 외형을 정합니다! §6assets/the_bumblezone/textures/entity/bee_variants§f 폴더에 벌 텍스처를 추가하고 이 설정에 벌을 정의할 수 있습니다.",
    "the_bumblezone.configuration.beehemothspeed.tooltip": "플레이어가 탔을 때 비히모스의 기본 속도입니다.",
    "the_bumblezone.configuration.beehemothfriendlyfire.tooltip": "길들인 비히모스가 주인에게 피해를 받을 수 있게 합니다.",
    "the_bumblezone.configuration.specialbeespawning.tooltip": "The Bumblezone이 플레이어 근처에 바닐라 벌을 생성해 차원에 벌이 가득한 느낌을 줄지 정합니다. 벌집이 있거나 이름표가 붙었거나 계속 유지되도록 설정된 벌이 아니면 너무 멀어진 벌은 사라집니다.",
    "the_bumblezone.configuration.nearbybeesperplayerinbz.tooltip": "§6특수 생성 시스템 사용§f이 켜져 있을 때 The Bumblezone의 플레이어 한 명마다 근처에 둘 바닐라 벌 수입니다. 100처럼 높이면 지나치게 많고, 25가 적당합니다.",
    "the_bumblezone.configuration.beelootinjection.tooltip": "벌침이 남은 채 죽은 어른 벌에게서 벌침을 떨어뜨릴지 정합니다. 드롭 아이템은 §6the_bumblezone:entities/bee_stinger_drops§f 전리품 목록에서 가져옵니다.",
    "the_bumblezone.configuration.moddedbeelootinjection.tooltip": "벌침이 남은 채 죽은 다른 모드의 어른 벌에게서 벌침을 떨어뜨릴지 정합니다. 드롭 아이템은 §6the_bumblezone:entities/bee_stinger_drops§f 전리품 목록에서 가져옵니다.",
    "the_bumblezone.configuration.glisteringhoneybrewingrecipe.tooltip": "반짝이는 꿀 수정을 행운의 물약 양조에 사용할 수 있게 합니다.",
    "the_bumblezone.configuration.beestingerbrewingrecipe.tooltip": "벌침을 긴 독의 물약 양조에 사용할 수 있게 합니다.",
    "the_bumblezone.configuration.beesoupbrewingrecipe.tooltip": "벌 수프를 신경독 물약 양조에 사용할 수 있게 합니다.",
    "the_bumblezone.configuration.neurotoxinmaxlevel.tooltip": "실제 마법 단계와 관계없이 신경독 마법의 효과에 적용할 최대 단계입니다. 2로 설정하면 신경독 III도 II처럼 작동합니다. 표시되는 마법의 최대 단계를 바꾸려면 데이터팩으로 §6data/the_bumblezone/enchantment/neurotoxin.json§f 파일을 대체하세요.",
    "the_bumblezone.configuration.paralyzedmaxtickduration.tooltip": "엔티티에게 마비 효과를 부여할 수 있는 최대 지속 시간(틱)입니다. 마비를 다시 부여하는 행동은 타이머를 초기화해 엔티티를 계속 움직이지 못하게 할 수 있습니다.",
    "the_bumblezone.configuration.beequeenbonustraderewardmultiplier.tooltip": "보너스 거래에서 일반 거래 수량에 곱할 값입니다. 0이나 1이면 보너스 거래를 사용하지 않습니다.",
    "the_bumblezone.configuration.beequeenbonustradedurationinticks.tooltip": "여왕벌이 새 아이템을 요청하기 전까지 보너스 거래가 유지되는 시간(틱)입니다. 0이면 보너스 거래를 사용하지 않습니다. 1분§7§o(1200틱)§f보다 짧으면 요청 메시지를 플레이어에게 방송하지 않습니다.",
    "the_bumblezone.configuration.beequeenbonustradeamounttillsatified.tooltip": "보너스 거래가 소진될 때까지 강화된 수량으로 거래할 수 있는 횟수입니다. 여왕은 일정 시간 재충전한 뒤 새 보너스 거래 아이템을 요청합니다. 0이면 보너스 거래를 사용하지 않습니다.",
    "the_bumblezone.configuration.beequeenspecialdaytrades.tooltip": "특정 기념일에 특별 거래를 활성화할지 정합니다.",
    "the_bumblezone.configuration.beequeenrespawning.tooltip": "새 왕좌 꿀 나침반으로 왕좌 기둥을 찾았을 때 여왕벌이 그곳에 다시 생성될 수 있게 합니다.",
    "the_bumblezone.configuration.beequeengroundpickup.tooltip": "여왕벌이 거래를 위해 바닥에 떨어진 아이템을 주울 수 있게 합니다.",
    "the_bumblezone.configuration.crystallineflowerconsumeitementities.tooltip": "월드에서 결정꽃의 충돌 상자에 닿은 아이템 엔티티를 결정꽃이 흡수할지 정합니다.",
    "the_bumblezone.configuration.crystallineflowerconsumeexperienceorbentities.tooltip": "월드에서 결정꽃에 닿은 경험치 구슬을 끌어당겨 흡수할지 정합니다.",
    "the_bumblezone.configuration.crystallineflowerconsumeitemui": "GUI에서 아이템 흡수",
    "the_bumblezone.configuration.crystallineflowerconsumeitemui.tooltip": "결정꽃 GUI에서 플레이어가 직접 아이템을 먹일 수 있게 합니다.",
    "the_bumblezone.configuration.crystallineflowerconsumeexperienceui": "GUI에서 경험치 흡수",
    "the_bumblezone.configuration.crystallineflowerconsumeexperienceui.tooltip": "결정꽃 GUI에서 플레이어가 자신의 경험치를 직접 먹일 수 있게 합니다.",
    "the_bumblezone.configuration.crystallineflowerenchantingpowerallowedpertier.tooltip": "각 티어에서 사용할 §6마법 부여 능력§f의 양을 정해 표시할 마법을 결정합니다. 단계나 희귀도가 높은 마법은 UI에 나타나기 전에 더 많은 §6마법 부여 능력§f이 필요합니다. 책장이 많을수록 마법 부여대에 더 강하고 희귀한 마법이 나타나는 것과 같습니다. 꽃의 티어에 이 값을 곱한 수치가 표시할 마법과 단계를 정하는 기준이 됩니다.",
    "the_bumblezone.configuration.crystallineflowerextraxpneededfortiers.tooltip": "결정꽃이 다음 티어에 도달할 때 필요한 추가 경험치입니다. 꽃이 아이템을 흡수하면 경험치로 바꾸므로 아이템 흡수에도 영향을 줍니다.",
    "the_bumblezone.configuration.crystallineflowerextratiercost.tooltip": "사용 가능한 모든 마법의 티어 비용을 설정한 값만큼 늘리거나 줄입니다. 최종 티어 비용은 1에서 6 사이로 제한됩니다.",
    "the_bumblezone.configuration.dispensersdropglassbottles.tooltip": "발사기가 특정 병 아이템을 The Bumblezone 블록에 사용했을 때 유리병을 항상 떨어뜨릴지 정합니다. 예를 들어 켜면 꿀이 든 병으로 벌집 유충 블록에 먹이를 줄 때 유충이 자라고, 빈 유리병은 발사기에 돌아가지 않고 밖으로 떨어집니다.",
    "the_bumblezone.configuration.broodblocksbeespawncapacity.tooltip": "활동 중인 벌 수가 이 값에 도달할 때까지 유충 블록이 자동으로 벌을 생성합니다. 좁은 범위에 더 많은 벌을 생성하려면 높이고, 자동 생성을 끄려면 0으로 설정하세요.",
    "the_bumblezone.configuration.pileofpollenhyperfirespread.tooltip": "꽃가루 더미에서 불이 매우 빠르게 번져 넓은 범위의 꽃가루를 태울지 정합니다.",
    "the_bumblezone.configuration.supercandlesburnsmobs.tooltip": "불이 붙은 대형 양초와 물약 양초의 불꽃이 생명체를 태울 수 있게 합니다.",
    "the_bumblezone.configuration.allowwanderingtradermusicdiscstrades.tooltip": "떠돌이 상인이 The Bumblezone 음반을 희귀 거래로 제시할 수 있게 합니다.",
    "the_bumblezone.configuration.repeatableessenceevents.tooltip": "영원 성소의 정수 이벤트를 한 번 완료한 뒤 다시 도전할 수 있게 합니다.",
    "the_bumblezone.configuration.bluearenabubblesmechanic.tooltip": "영원 성소의 푸른 경기장에서 움직이는 거품 블록 기능을 사용할지 정합니다.",
    "the_bumblezone.configuration.bluearenatimeframeinticks.tooltip": "영원 성소의 푸른 경기장이 유지되는 시간(틱)입니다.",
    "the_bumblezone.configuration.greenarenatimeframeinticks.tooltip": "영원 성소의 초록색 경기장이 유지되는 시간(틱)입니다.",
    "the_bumblezone.configuration.purplearenatimeframeinticks.tooltip": "영원 성소의 보라색 경기장이 유지되는 시간(틱)입니다.",
    "the_bumblezone.configuration.redarenatimeframeinticks.tooltip": "영원 성소의 붉은 경기장이 유지되는 시간(틱)입니다.",
    "the_bumblezone.configuration.yellowarenatimeframeinticks.tooltip": "영원 성소의 노란색 경기장이 유지되는 시간(틱)입니다.",
    "the_bumblezone.configuration.whitearenatimeframeinticks.tooltip": "영원 성소의 하얀 경기장이 유지되는 시간(틱)입니다.",
    "the_bumblezone.configuration.cosmiccrystalhealth.tooltip": "코스믹 수정 엔티티의 최대 체력입니다. §7§o(하얀 영원 성소의 지속의 정수 이벤트에 사용)§f",
    "the_bumblezone.configuration.ragingessenceabilityuse.tooltip": "이 아이템의 능력이 고갈되기 전까지 사용할 수 있는 양입니다.",
    "the_bumblezone.configuration.ragingessencecooldown.tooltip": "이 아이템이 다시 충전되기까지 걸리는 재사용 대기시간(틱)입니다.",
    "the_bumblezone.configuration.ragingessencestrengthlevels.tooltip": "격노 단계 수와 각 단계에서 얻는 힘 효과의 단계를 정합니다. 목록은 강조 표시된 적을 처치할 때 플레이어가 차례로 얻는 효과 단계 순서입니다. 숫자를 추가하거나 제거하면 격노의 최대 단계 수도 바뀝니다.",
    "the_bumblezone.configuration.knowingessenceabilityuse.tooltip": "이 아이템의 능력이 고갈되기 전까지 §7§o초당§f 사용할 수 있는 양입니다.",
    "the_bumblezone.configuration.knowingessencecooldown.tooltip": "이 아이템이 다시 충전되기까지 걸리는 재사용 대기시간(틱)입니다.",
    "the_bumblezone.configuration.knowingEssenceStructureNameServer.tooltip": "클라이언트가 이 아이템으로 현재 들어와 있는 구조물 이름을 볼 수 있게 할지 정합니다.",
    "the_bumblezone.configuration.calmingessenceabilityuse.tooltip": "이 아이템의 능력이 고갈되기 전까지 §7§o초당§f 사용할 수 있는 양입니다.",
    "the_bumblezone.configuration.calmingessencecooldown.tooltip": "이 아이템이 다시 충전되기까지 걸리는 재사용 대기시간(틱)입니다.",
    "the_bumblezone.configuration.lifeessenceabilityuse.tooltip": "이 아이템의 능력이 고갈되기 전까지 사용할 수 있는 양입니다.",
    "the_bumblezone.configuration.lifeessencecooldown.tooltip": "이 아이템이 다시 충전되기까지 걸리는 재사용 대기시간(틱)입니다.",
    "the_bumblezone.configuration.radianceessenceabilityuse.tooltip": "이 아이템의 능력이 고갈되기 전까지 §7§o25틱마다§f 사용할 수 있는 양입니다.",
    "the_bumblezone.configuration.radianceessencecooldown.tooltip": "이 아이템이 다시 충전되기까지 걸리는 재사용 대기시간(틱)입니다.",
    "the_bumblezone.configuration.continuityessencecooldown.tooltip": "이 아이템이 다시 충전되기까지 걸리는 재사용 대기시간(틱)입니다.",
    "the_bumblezone.configuration.beedungeonrarity.tooltip": "벌 던전의 희귀도입니다. 값이 높을수록 드물게 생성됩니다. 기본값은 1이며 1001이면 벌 던전을 생성하지 않습니다.",
    "the_bumblezone.configuration.treedungeonrarity.tooltip": "나무 던전의 희귀도입니다. 값이 높을수록 드물게 생성됩니다. 기본값은 1이며 1001이면 나무 던전을 생성하지 않습니다.",
    "the_bumblezone.configuration.spiderinfestedbeedungeonrarity.tooltip": "거미 감염 벌 던전의 희귀도입니다. 값이 높을수록 드물게 생성됩니다. 기본값은 1이며 1001이면 거미 감염 벌 던전을 생성하지 않습니다.",
    "the_bumblezone.configuration.spawnerratespiderbeedungeon.tooltip": "거미 감염 벌 던전에서 거미와 동굴 거미 생성기가 나오는 비율입니다. 0이면 생성기가 없고 1이면 최대이며 기본값은 0.2입니다.",
    "the_bumblezone.midnightconfig.title": "§o§6    The Bumblezone 설정",
    "the_bumblezone.midnightconfig.beeAggressionComment": "§o§6    벌 공격성 설정",
    "the_bumblezone.midnightconfig.allowWrathOfTheHiveOutsideBumblezone": "The Bumblezone 밖에서 벌집의 분노 허용",
    "the_bumblezone.midnightconfig.showWrathOfTheHiveParticles": "벌집의 분노 입자 표시",
    "the_bumblezone.midnightconfig.aggressiveBees": "벌 공격성",
    "the_bumblezone.midnightconfig.aggressionTriggerRadius": "공격성 발동 범위",
    "the_bumblezone.midnightconfig.howLongWrathOfTheHiveLasts": "벌집의 분노 지속 시간",
    "the_bumblezone.midnightconfig.howLongProtectionOfTheHiveLasts": "벌집의 보호 지속 시간",
    "the_bumblezone.midnightconfig.absorptionBoostLevel": "흡수 증가 단계",
    "the_bumblezone.midnightconfig.strengthBoostLevel": "힘 증가 단계",
    "the_bumblezone.midnightconfig.blockMechanicsComment": "§o§6    블록 기능 설정",
    "the_bumblezone.midnightconfig.dispensersDropGlassBottles": "발사기가 유리병 떨어뜨리기",
    "the_bumblezone.midnightconfig.broodBlocksBeeSpawnCapacity": "유충 블록 벌 생성 한도",
    "the_bumblezone.midnightconfig.pileOfPollenHyperFireSpread": "꽃가루 더미 초고속 불 확산",
    "the_bumblezone.midnightconfig.superCandlesBurnsMobs": "대형 및 물약 양초가 몹 태우기",
    "the_bumblezone.midnightconfig.enchantmentsComment": "§o§6    마법 부여 설정",
    "the_bumblezone.midnightconfig.neurotoxinMaxLevel": "신경독 최대 단계",
    "the_bumblezone.midnightconfig.paralyzedMaxTickDuration": "마비 최대 지속 시간(틱)",
    "the_bumblezone.midnightconfig.dimensionComment": "§o§6    차원 설정",
    "the_bumblezone.midnightconfig.enableInitialWelcomeMessage": "The Bumblezone 환영 메시지 표시",
    "the_bumblezone.midnightconfig.enableDimensionFog": "차원 안개 사용",
    "the_bumblezone.midnightconfig.onlyOverworldHivesTeleports": "오버월드 벌집만 순간이동 허용",
    "the_bumblezone.midnightconfig.forceExitToOverworld": "퇴장 위치를 오버월드로 고정",
    "the_bumblezone.midnightconfig.warnPlayersOfWrongBlockUnderHive": "벌집 아래 블록 오류 경고",
    "the_bumblezone.midnightconfig.enableExitTeleportation": "퇴장 순간이동 사용",
    "the_bumblezone.midnightconfig.enableEntranceTeleportation": "입장 순간이동 사용",
    "the_bumblezone.midnightconfig.forceBumblezoneOriginMobToOverworldCenter": "The Bumblezone 출신 몹을 오버월드 중심으로 보내기",
    "the_bumblezone.midnightconfig.dungeonsComment": "§o§6    던전 설정",
    "the_bumblezone.midnightconfig.spiderInfestedBeeDungeonRarity": "거미 감염 벌 던전 희귀도",
    "the_bumblezone.midnightconfig.spawnerRateSpiderBeeDungeon": "거미 벌 던전 생성기 비율",
    "the_bumblezone.midnightconfig.brewingRecipeComment": "§o§6    양조법 설정",
    "the_bumblezone.midnightconfig.glisteringHoneyBrewingRecipe": "반짝이는 꿀 수정 물약 재료",
    "the_bumblezone.midnightconfig.beeStingerBrewingRecipe": "벌침 물약 재료",
    "the_bumblezone.midnightconfig.beeSoupBrewingRecipe": "벌 수프 물약 재료",
    "the_bumblezone.midnightconfig.generalComment": "§o§6    일반 설정",
    "the_bumblezone.midnightconfig.variantBeeAfterWorlgenSpawnRate": "변종 벌 생성률",
    "the_bumblezone.midnightconfig.variantBeeTypes": "변종 벌 종류",
    "the_bumblezone.midnightconfig.beehemothSpeed": "비히모스 속도",
    "the_bumblezone.midnightconfig.beehemothFriendlyFire": "비히모스 아군 공격",
    "the_bumblezone.midnightconfig.beeQueenBonusTradeRewardMultiplier": "여왕 보너스 거래 보상 배수",
    "the_bumblezone.midnightconfig.beeQueenBonusTradeDurationInTicks": "여왕 보너스 거래 지속 시간(틱)",
    "the_bumblezone.midnightconfig.beeQueenBonusTradeAmountTillSatified": "여왕 보너스 거래당 거래 횟수",
    "the_bumblezone.midnightconfig.beeQueenSpecialDayTrades": "기념일 비밀 거래",
    "the_bumblezone.midnightconfig.beeQueenGroundPickup": "여왕벌의 바닥 아이템 줍기",
    "the_bumblezone.midnightconfig.specialBeeSpawning": "특수 벌 생성",
    "the_bumblezone.midnightconfig.moddedBeeLootInjection": "모드 벌 전리품 추가",
    "the_bumblezone.midnightconfig.nearbyBeesPerPlayerInBz": "The Bumblezone 플레이어당 주변 벌 수",
    "the_bumblezone.midnightconfig.musicDiscComment": "§o§6    음반 설정",
    "the_bumblezone.midnightconfig.allowWanderingTraderMusicDiscsTrades": "떠돌이 상인의 음반 거래 허용",
    "the_bumblezone.midnightconfig.modCompatComment": "§o§6    모드 호환 설정",
    "the_bumblezone.midnightconfig.alternativeFluidToReplaceHoneyFluid": "액체 꿀을 대신할 액체",
    "the_bumblezone.midnightconfig.allowFriendsAndFoesBeekeeperTradesCompat": "Friends and Foes 양봉가 거래 호환 허용",
    "the_bumblezone.midnightconfig.allowGoodallBottledBeesRevivingEmptyBroodBlock": "Goodall의 병에 든 벌로 유충 블록 되살리기",
    "the_bumblezone.midnightconfig.allowLootrCompat": "전리품 꿀 고치의 Lootr 호환 허용",
    "the_bumblezone.midnightconfig.allowCreateLimestoneForHoneyLavaCompat": "꿀과 용암으로 Create 석회암 생성 허용",
    "the_bumblezone.midnightconfig.clientComment": "§o§6    클라이언트 설정",
    "the_bumblezone.midnightconfig.useBackupModelForVariantBee": "변종 벌 예비 모델 사용",
    "the_bumblezone.midnightconfig.playWrathOfHiveEffectMusic": "벌집의 분노 효과 음악 재생",
    "the_bumblezone.midnightconfig.playSempiternalSanctumMusic": "영원 성소 음악 재생",
    "the_bumblezone.midnightconfig.renderBeeQueenBonusTradeItem": "여왕벌이 원하는 아이템 표시",
    "the_bumblezone.midnightconfig.disableEssenceBlockShaders": "정수 블록 셰이더 끄기",
    "the_bumblezone.midnightconfig.crystallineFlowerComment": "§o§6    결정꽃 설정",
    "the_bumblezone.midnightconfig.crystallineFlowerConsumeItemEntities": "아이템 엔티티 흡수",
    "the_bumblezone.midnightconfig.crystallineFlowerConsumeExperienceOrbEntities": "경험치 구슬 흡수",
    "the_bumblezone.midnightconfig.crystallineFlowerConsumeItemUI": "UI에서 아이템 흡수",
    "the_bumblezone.midnightconfig.crystallineFlowerConsumeExperienceUI": "UI에서 경험치 흡수",
    "the_bumblezone.midnightconfig.crystallineFlowerExtraTierCost": "전체 티어 비용 가감",
    "the_bumblezone.midnightconfig.crystallineFlowerExtraXpNeededForTiers": "티어당 추가 경험치 요구량",
    "the_bumblezone.midnightconfig.defaultDimension": "The Bumblezone 퇴장 시 예비 차원",
    "the_bumblezone.midnightconfig.knowingEssenceComment": "§o§6    통찰의 정수 클라이언트 설정",
    "the_bumblezone.midnightconfig.knowingEssenceHighlightTamed": "자신이 길들인 몹 강조 표시",
    "the_bumblezone.midnightconfig.knowingEssenceHighlightLivingEntities": "그 밖의 모든 몹 강조 표시",
    "the_bumblezone.midnightconfig.knowingEssenceHighlightUncommonItems": "고급 아이템 강조 표시",
    "the_bumblezone.midnightconfig.knowingEssenceHighlightEpicItems": "특급 아이템 강조 표시",
    "the_bumblezone.midnightconfig.knowingEssenceStructureNameClient": "구조물 이름 표시(클라이언트)",
    "the_bumblezone.midnightconfig.knowingEssenceStructureNameServer": "구조물 이름 표시(서버)",
    "the_bumblezone.midnightconfig.knowingEssenceStructureNameXCoord": "이름 X 좌표",
    "the_bumblezone.midnightconfig.knowingEssenceStructureNameYCoord": "이름 Y 좌표",
    "the_bumblezone.midnightconfig.radianceEssenceComment": "§o§6    광휘의 정수 클라이언트 설정",
    "the_bumblezone.midnightconfig.radianceEssenceArmorDurabilityXCoord": "내구도 X 좌표",
    "the_bumblezone.midnightconfig.radianceEssenceArmorDurabilityYCoord": "내구도 Y 좌표",
    "the_bumblezone.midnightconfig.essenceItemsClientComment": "§o§6    정수 아이템 클라이언트 설정",
    "the_bumblezone.midnightconfig.essenceItemHUDVisualEffectLayers": "HUD 시각 효과 레이어 수",
    "the_bumblezone.midnightconfig.essenceItemHUDVisualEffectSpeed": "HUD 시각 효과 회전 속도",
    "the_bumblezone.midnightconfig.sillyClientComment": "§o§6    장난스러운 설정",
    "the_bumblezone.midnightconfig.showBeesOnGuiAllYearRound": "GUI 벌 연중 표시",
    "the_bumblezone.midnightconfig.showBeesOnGuiOnAprilFools": "만우절에 GUI 벌 표시",
    "the_bumblezone.midnightconfig.restrictBeesOnGuiToBzDimension": "GUI 벌을 The Bumblezone에서만 표시",
    "the_bumblezone.midnightconfig.maximumBeesOnGui": "GUI 벌 최대 수",
    "the_bumblezone.midnightconfig.essenceComment": "§o§6    정수 설정",
    "the_bumblezone.midnightconfig.repeatableEssenceEvents": "승리 후 정수 이벤트 반복 허용",
    "the_bumblezone.midnightconfig.cosmicCrystalHealth": "코스믹 수정 최대 체력",
    "the_bumblezone.midnightconfig.ragingEssenceAbilityUse": "격노의 정수 능력 사용량(초당)",
    "the_bumblezone.midnightconfig.calmingEssenceAbilityUse": "평온의 정수 능력 사용량(초당)",
    "the_bumblezone.midnightconfig.radianceEssenceAbilityUse": "광휘의 정수 능력 사용량(25틱당)",
    "item.the_bumblezone.buzzing_briefcase_bee_name": "이름: %s",
    "item.the_bumblezone.buzzing_briefcase_bee_type": "종류: %s",
    "item.the_bumblezone.buzzing_briefcase_bee_registry_name": "레지스트리 이름: %s",
    "item.the_bumblezone.buzzing_briefcase_release": "%s 풀어 주기",
    "item.the_bumblezone.buzzing_briefcase_health_1": "§6꿀이 든 병 소모",
    "item.the_bumblezone.buzzing_briefcase_health_2": "체력을 2 회복",
    "item.the_bumblezone.buzzing_briefcase_health_missing_item": "인벤토리에 §6꿀이 든 병§f이 없습니다",
    "item.the_bumblezone.buzzing_briefcase_stinger_1": "§6벌침 소모",
    "item.the_bumblezone.buzzing_briefcase_stinger_2": "벌침 다시 달기",
    "item.the_bumblezone.buzzing_briefcase_stinger_missing_item": "인벤토리에 §6벌침§f이 없습니다",
    "item.the_bumblezone.buzzing_briefcase_grow_up_1": "§6꿀이 든 병 소모",
    "item.the_bumblezone.buzzing_briefcase_grow_up_2": "아기 벌을 어른으로 성장",
    "item.the_bumblezone.buzzing_briefcase_grow_up_missing_item": "인벤토리에 §6꿀이 든 병§f이 없습니다",
    "item.the_bumblezone.buzzing_briefcase_pollen_1": "§6꽃가루 뭉치 소모",
    "item.the_bumblezone.buzzing_briefcase_pollen_2": "벌에게 꽃가루 묻히기",
    "item.the_bumblezone.buzzing_briefcase_pollen_missing_item": "인벤토리에 §6꽃가루 뭉치§f가 없습니다",
    "item.the_bumblezone.honey_compass_structure_creative": "꿀 나침반 - 새 나침반 생성됨",
    "item.the_bumblezone.honey_compass_structure_wrong_dimension": "꿀 나침반 - 구조물을 찾을 수 없는 차원...",
    "item.the_bumblezone.honey_compass_structure_failed_description": "우클릭해 다시 탐색하세요.",
    "item.the_bumblezone.honey_compass_block": "꿀 나침반 - %s",
    "item.the_bumblezone.honey_compass_description1": "The Bumblezone에서 허공을 우클릭해",
    "item.the_bumblezone.honey_compass_distance": "목표까지 거리: %s",
    "item.the_bumblezone.honey_compass_block_description1": "The Bumblezone에서 허공을 우클릭하면",
    "item.the_bumblezone.honey_compass_lesser_mystery_structure": "꿀 나침반 - 작은 수수께끼 구조물",
    "item.the_bumblezone.honey_compass_lesser_mystery_structure_description": "어디로 이어지는 걸까요?",
    "item.the_bumblezone.honey_compass_red_sanctum_structure_description": "으르렁대는 목소리가 따라오라고 명령합니다...",
    "item.the_bumblezone.honey_compass_purple_sanctum_structure_description": "현명한 목소리가 따라오라고 조언합니다...",
    "item.the_bumblezone.honey_compass_blue_sanctum_structure_description": "마음을 달래는 목소리가 따라오라고 유혹합니다...",
    "item.the_bumblezone.honey_compass_green_sanctum_structure_description": "속삭이는 목소리들이 따라와 달라고 부탁합니다...",
    "item.the_bumblezone.honey_compass_yellow_sanctum_structure_description": "전율을 일으키는 목소리들이 따라오라고 손짓합니다...",
    "item.the_bumblezone.honey_compass_white_sanctum_structure_description": "익숙한 목소리들이 따라와 달라고 애원합니다...",
    "item.the_bumblezone.potion_candle.status_effect": "효과: %s",
    "item.the_bumblezone.potion_candle.amplifier": "단계: %s",
    "item.the_bumblezone.potion_candle.max_duration": "연소 시간: %s",
    "item.the_bumblezone.potion_candle.apply_interval": "적용 간격: %s",
    "item.the_bumblezone.potion_candle.range": "범위: %s",
    "item.the_bumblezone.potion_candle.lingering_time": "잔류 시간: %s",
    "item.the_bumblezone.crystalline_flower_info_1": "티어: %s",
    "item.the_bumblezone.crystalline_flower_info_2": "경험치: %s",
    "item.the_bumblezone.crystalline_flower_cannot_place": "꽃을 놓을 공간이 부족합니다!",
    "item.the_bumblezone.essence_raging_description_1": "강해지려면 강조 표시된 몹을 처치하세요!",
    "item.the_bumblezone.essence_raging_description_2": "힘이 최대일 때 무엇이든 처치하면 힘이 초기화됩니다.",
    "item.the_bumblezone.essence_knowing_description_1": "모든 것을 아는 것이 곧 지식...",
    "item.the_bumblezone.essence_knowing_description_2": "몹과 일부 블록 엔티티를 강조 표시합니다",
    "item.the_bumblezone.essence_calming_description_1": "분노와 다툼을 버리고 평온을 유지하세요",
    "item.the_bumblezone.essence_calming_description_2": "공격하거나 공격받으면 평온이 사라집니다",
    "item.the_bumblezone.essence_calming_description_3": "달리면 힘이 빠르게 줄어듭니다...",
    "item.the_bumblezone.essence_life_description_1": "모든 생명이 번성하게 하세요",
    "item.the_bumblezone.essence_life_description_2": "아군과 반려동물을 치료하고 주변 작물을 키웁니다",
    "item.the_bumblezone.essence_radiance_description_1": "태양을 찬양하라!!!",
    "item.the_bumblezone.essence_radiance_description_2": "태양이 갑옷을 수리하고 이로운 상태 효과를 줍니다",
    "item.the_bumblezone.essence_continuity_description_1": "죽음조차 끝내지 못한다...",
    "item.the_bumblezone.essence_continuity_description_2": "죽을 상황에서 재생성 지점으로 순간이동합니다",
    "item.the_bumblezone.essence_continuity_written_book_body": "§4§l죽을 뻔한 날짜:§r\n%s\n\n§4§l사고 위치:§r\n%s, %s, %s\n%s\n\n§4§l원인 제공자:§r\n%s\n\n§4§l막아 낸 죽음:§r\n%s",
    "item.the_bumblezone.essence_continuity_written_book_body_no_causer": "§4§l죽을 뻔한 날짜:§r\n%s\n\n§4§l사고 위치:§r\n%s, %s, %s\n%s\n\n§4§l막아 낸 죽음:§r\n%s",
    "item.the_bumblezone.essence_active": "활성",
    "item.the_bumblezone.essence_ready": "준비됨",
    "item.the_bumblezone.essence_depleted": "고갈됨",
    "item.the_bumblezone.essence_locked": "잠김(사용 불가)",
    "item.the_bumblezone.essence_locked_description_1": "먼저 여왕의 소망 발전 과제를 모두 완료해",
    "item.the_bumblezone.essence_locked_description_2": "벌의 정수를 섭취해야 합니다",
    "item.the_bumblezone.essence_usage": "능력 %s/%s",
    "item.the_bumblezone.essence_cooldown": "남은 재사용 대기시간: %s초",
    "item.the_bumblezone.essence_knowing_separator": "%s, %s",
    "item.the_bumblezone.essence_knowing_within_text": "현재 구조물:",
    "item.the_bumblezone.essence_knowing_within_text_plural": "현재 구조물 목록:",
    "item.the_bumblezone.essence_radiance_durability_text": "  %s/%s",
    "item.the_bumblezone.essence_radiance_durability_low_text": "⚠%s/%s⚠",
    "item.the_bumblezone.essence_radiance_advanced_text": " 내구도",
    "item.the_bumblezone.essence_radiance_helmet_text": "  %s%s",
    "item.the_bumblezone.essence_radiance_chestplate_text": "  %s%s",
    "item.the_bumblezone.essence_radiance_leggings_text": "  %s%s",
    "item.the_bumblezone.essence_radiance_boots_text": "  %s%s",
    "entity.the_bumblezone.beehemoth_friendship_progress": "친밀도: %s/1000",
    "entity.the_bumblezone.electric_ring_entity": "전기 고리 엔티티",
    "entity.the_bumblezone.purple_spike_entity": "보라색 가시 엔티티",
    "entity.the_bumblezone.cosmic_crystal_entity": "코스믹 수정 엔티티",
    "entity.the_bumblezone.bee_queen.advancements_warning": "여왕의 소망 발전 과제를 초기화하려면 빈손으로 다시 우클릭하세요",
    "entity.the_bumblezone.bee_queen.reset_advancements": "여왕의 소망 발전 과제를 초기화했습니다!",
    "entity.the_bumblezone.bee_queen.mention_reset": "업적 달성을 축하합니다! 여왕의 소망 연속 퀘스트를 다시 하려면 빈손으로 여왕벌을 우클릭해 발전 과제를 초기화하세요",
    "entity.the_bumblezone.bee_queen.mention_bonus_trade": "윙윙! (여왕이 앞으로 %s분 동안 %s을(를) 원합니다)",
    "entity.the_bumblezone.bee_queen.mention_special_day_trade": "윙윙! (여왕이 %s을(를) 원합니다!)",
    "entity.the_bumblezone.bee_queen.mention_bonus_trade_inventory": "윙! 윙윙! (여왕이 인벤토리의 %s을(를) 원합니다!)",
    "entity.the_bumblezone.bee_queen.mention_bonus_trade_satisfied": "윙윙..! (이제 여왕이 만족했습니다)",
    "entity.the_bumblezone.bee_queen.mention_bonus_trade_performed": "거래 보너스! 보상 %s배!",
    "entity.the_bumblezone.bee_queen.mention_regular_trade_held": "윙? (여왕이 손에 든 아이템에 관심을 보입니다)",
    "entity.the_bumblezone.bee_queen.halloween_trade_performed": "과자를 안 주면 장난칠 거예요!",
    "entity.the_bumblezone.bee_queen.christmas_trade_performed": "즐거운 성탄절 보내세요!",
    "entity.the_bumblezone.bee_queen.forth_of_july_trade_performed": "즐거운 미국 독립기념일 보내세요!",
    "entity.the_bumblezone.bee_queen.thanksgiving_trade_performed": "즐거운 추수감사절 보내세요!",
    "entity.the_bumblezone.bee_queen.easter_trade_performed": "즐거운 부활절 보내세요!",
    "entity.the_bumblezone.bee_queen.new_year_trade_performed": "새해 복 많이 받으세요!",
    "system.the_bumblezone.teleporting_into_bz": "The Bumblezone으로 이동하는 중...",
    "system.the_bumblezone.teleporting_out_of_bz": "The Bumblezone에서 나가는 중...",
    "system.the_bumblezone.missing_dimension": "서버를 다시 시작해 주세요. The Bumblezone 차원이 생성되지 않았습니다. 다음 버그 때문일 수 있습니다: %s",
    "system.the_bumblezone.require_hive_blocks_failed": "The Bumblezone 순간이동에 실패했습니다. 벌집 아래에 필수 블록이 필요합니다.",
    "system.the_bumblezone.entering_dimension": "윙윙거리며 The Bumblezone으로!",
    "system.the_bumblezone.occupied_crystalline_flower": "다른 플레이어가 결정꽃을 사용하고 있습니다...",
    "system.the_bumblezone.sentry_watcher_egg_removal_hint": "엔티티를 제거하려면 빠르게 두 번 우클릭하세요",
    "system.the_bumblezone.sentry_watcher_egg_spawner_hint": "생성기 지정은 크리에이티브 모드에서만 가능합니다",
    "system.the_bumblezone.no_essence": "벌의 정수 효과가 없었습니다...",
    "system.the_bumblezone.advancement_hint": "🐝 §6The Bumblezone§r의 §a발전 과제 탭§r에서 차원 출입법, 진행 순서와 플레이 방법 등 모드의 모든 정보를 확인하세요! 🐝",
    "system.the_bumblezone.sempiternal_sanctum_red": "열정과 분노가 마음속에서 솟구칩니다...",
    "system.the_bumblezone.sempiternal_sanctum_yellow": "전율을 일으키는 활력이 온몸을 관통합니다...",
    "system.the_bumblezone.sempiternal_sanctum_green": "오래된 상처가 아물기 시작합니다...",
    "system.the_bumblezone.sempiternal_sanctum_blue": "마음속 혼란이 잦아들기 시작합니다...",
    "system.the_bumblezone.sempiternal_sanctum_purple": "지식의 속삭임이 안으로 이끕니다...",
    "system.the_bumblezone.sempiternal_sanctum_white": "강한 기시감이 마음을 어지럽힙니다...",
    "system.the_bumblezone.denied_spell": "대항 마법 발동 - 주문 차단됨",
    "system.the_bumblezone.denied_magic": "대항 마법 발동 - 마법 차단됨",
    "system.the_bumblezone.denied_jetpack": "기술 방해 마법 발동 - 제트팩 비활성화됨",
    "system.the_bumblezone.denied_jet_boots": "기술 방해 마법 발동 - 제트 부츠 비활성화됨",
    "system.the_bumblezone.denied_mek_jetpack_module": "기술 방해 마법 발동 - 제트팩 모듈 차단됨",
    "system.the_bumblezone.denied_mek_grav_module": "기술 방해 마법 발동 - 중력 모듈 차단됨",
    "system.the_bumblezone.royal_jelly_bottle.cannot_take_from_source_block": "액체를 낭비하지 마세요! 대신 양동이를 사용하세요!",
    "buzzing_briefcase.the_bumblezone.bee_typing.normal": "일반",
    "buzzing_briefcase.the_bumblezone.bee_typing.unknown": "알 수 없음",
    "buzzing_briefcase.the_bumblezone.bee_typing.redtail_bee": "붉은꼬리 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.green_bee": "초록색 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.blue_bee": "파란색 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.white_bee": "하얀색 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.ukraine_bee": "우크라이나 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.trans_bee": "트랜스젠더 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.asexual_bee": "무성애 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.agender_bee": "에이젠더 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.aroace_bee": "무로맨틱 무성애 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.aromantic_bee": "무로맨틱 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.bisexual_bee": "양성애 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.pan_bee": "범성애 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.enby_bee": "논바이너리 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.reverse_bee": "반전 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.neapolitan_bee": "나폴리탄 벌",
    "buzzing_briefcase.the_bumblezone.bee_typing.rainbow_bee": "무지개 벌",
}
