#!/usr/bin/env python3
"""The Bumblezone 발전 과제 제목과 설명의 검수 완료 번역."""

TRANSLATIONS = {
    "advancements.the_bumblezone.root.title": "The Bumblezone",
    "advancements.the_bumblezone.root.description": "이 모드에서 할 일을 알아보려면 나머지 발전 과제를 확인하세요!",
    "advancements.the_bumblezone.wiki.title": "The Bumblezone 위키 주소",
    "advancements.the_bumblezone.wiki.description": "www.github.com/TelepathicGrunt/Bumblezone/wiki",
    "advancements.the_bumblezone.is_near_beehive.title": "벌의 차원이 기다립니다!",
    "advancements.the_bumblezone.is_near_beehive.description": "용감하게 벌통이나 벌집에 다가가세요",
    "advancements.the_bumblezone.beenergized_maxed.title": "쌩쌩 날아다니는 벌!",
    "advancements.the_bumblezone.beenergized_maxed.description": "벌에게 벌빵을 먹여 최대 속도에 도달하게 하세요! 쌩쌩! 꿀과 꽃가루로 만들 수 있을지도 모릅니다...",
    "advancements.the_bumblezone.tamed_beehemoth.title": "벌 영화, 하지만 300% 더 크게",
    "advancements.the_bumblezone.tamed_beehemoth.description": "꿀 양동이로 비히모스를 길들이세요! 그런 다음 안장을 얹으면 날아다니는 탈것이 됩니다!",
    "advancements.the_bumblezone.queen_beehemoth.title": "끝까지 함께할 고귀한 친구!",
    "advancements.the_bumblezone.queen_beehemoth.description": "비히모스의 친밀도를 최대로 올려 친구가 되세요!",
    "advancements.the_bumblezone.walk_into_pollen_pile.title": "이 많은 꽃가루가 몸에 좋을 리 없잖아...",
    "advancements.the_bumblezone.walk_into_pollen_pile.description": "꽃가루 더미 속을 신나게 뛰어다니세요",
    "advancements.the_bumblezone.fall_onto_pollen_pile.title": "코는 막혀도 무릎은 멀쩡!",
    "advancements.the_bumblezone.fall_onto_pollen_pile.description": "높은 곳에서 두꺼운 꽃가루 더미로 몸을 맡기세요!",
    "advancements.the_bumblezone.bee_drop_pollen_puff.title": "벌도 깨끗하게!",
    "advancements.the_bumblezone.bee_drop_pollen_puff.description": "젖은 스펀지, 물 양동이 또는 물병으로 벌의 꽃가루를 씻어 내세요",
    "advancements.the_bumblezone.pollen_puff_pollinate_bee.title": "벌야구 홈런!",
    "advancements.the_bumblezone.pollen_puff_pollinate_bee.description": "꽃가루가 묻지 않은 벌에게 꽃가루 뭉치를 던져 캐치볼을 하세요!",
    "advancements.the_bumblezone.pollen_puff_pollinate_tall_flower.title": "환상적인 꽃가루받이",
    "advancements.the_bumblezone.pollen_puff_pollinate_tall_flower.description": "꽃가루 뭉치로 키 큰 꽃에 꽃가루받이를 해 더 많이 피우세요!",
    "advancements.the_bumblezone.pollen_puff_panda.title": "판다야, 재채기 조심!",
    "advancements.the_bumblezone.pollen_puff_panda.description": "판다에게 계절성 꽃가루 알레르기를 일으키세요!",
    "advancements.the_bumblezone.pollen_puff_fireball.title": "믿기 힘들 만큼 비효율적!",
    "advancements.the_bumblezone.pollen_puff_fireball.description": "꽃가루 뭉치로 가스트의 화염구에 맞서세요!",
    "advancements.the_bumblezone.pollen_puff_mooshroom.title": "버섯이나 꽃이나 그게 그거지",
    "advancements.the_bumblezone.pollen_puff_mooshroom.description": "무시룸에 꽃가루받이를 해 버섯을 피우세요!",
    "advancements.the_bumblezone.teleport_to_bumblezone_pearl.title": "벌더맨 침입!",
    "advancements.the_bumblezone.teleport_to_bumblezone_pearl.description": "벌통이나 벌집에 엔더 진주를 던져 The Bumblezone에 들어가세요",
    "advancements.the_bumblezone.teleport_out_of_bumblezone.title": "급강하 탈출",
    "advancements.the_bumblezone.teleport_out_of_bumblezone.description": "차원의 맨 아래나 위를 넘어 The Bumblezone에서 나가세요! 죽지 않고 다른 차원으로 이동합니다.",
    "advancements.the_bumblezone.teleport_to_bumblezone_piston.title": "꿀압 프레스",
    "advancements.the_bumblezone.teleport_to_bumblezone_piston.description": "피스톤에 밀려 벌통이나 벌집 안으로 들어가 The Bumblezone으로 이동하세요",
    "advancements.the_bumblezone.obtain_honey_bucket.title": "꿀이 더 필요해애애!!!",
    "advancements.the_bumblezone.obtain_honey_bucket.description": "꿀 양동이를 얻으세요!",
    "advancements.the_bumblezone.obtain_all_music_discs.title": "벌집에서 춤을!",
    "advancements.the_bumblezone.obtain_all_music_discs.description": "벌 테마 음반을 모두 얻으세요!",
    "advancements.the_bumblezone.sleep_in_bed.title": "더 달콤한 꿈!",
    "advancements.the_bumblezone.sleep_in_bed.description": "The Bumblezone에서 침대에 누우세요. 침대가 폭발하지 않고 재생성 지점을 설정합니다!",
    "advancements.the_bumblezone.honey_slime_creation.title": "꿀이 살아 움직인다!",
    "advancements.the_bumblezone.honey_slime_creation.description": "슬라임에 꿀을 주입하세요!",
    "advancements.the_bumblezone.honey_slime_harvest.title": "벌이 왜 필요해???",
    "advancements.the_bumblezone.honey_slime_harvest.description": "꿀 슬라임에게서 꿀을 채취하세요",
    "advancements.the_bumblezone.honey_bucket_bee_grow.title": "쑥쑥 자라요!",
    "advancements.the_bumblezone.honey_bucket_bee_grow.description": "아기 벌에게 먹이를 줘 즉시 어른으로 자라게 하세요",
    "advancements.the_bumblezone.honey_bucket_bee_love.title": "사랑이 윙윙!",
    "advancements.the_bumblezone.honey_bucket_bee_love.description": "꿀 양동이로 어른 벌 무리를 사랑에 빠지게 하세요!",
    "advancements.the_bumblezone.honey_bucket_brood.title": "벌 농부",
    "advancements.the_bumblezone.honey_bucket_brood.description": "꿀 양동이로 특정 유충 블록의 벌 유충을 키우세요",
    "advancements.the_bumblezone.getting_protection.title": "호의를 얻는 법",
    "advancements.the_bumblezone.getting_protection.description": "벌집 유충 블록이나 벌에게 먹이를 줘 벌집의 보호 효과를 받으세요!",
    "advancements.the_bumblezone.honey_permission.title": "분노는 그만! 이제 친구예요!",
    "advancements.the_bumblezone.honey_permission.description": "벌집의 보호 효과가 있을 때 꿀이 찬 다공성 벌집 조각 블록에서 꿀을 얻거나 꿀 블록을 캐세요",
    "advancements.the_bumblezone.consume_honey_crystal_shards.title": "이가 부서질 듯한 간식",
    "advancements.the_bumblezone.consume_honey_crystal_shards.description": "단단한 꿀 수정 조각을 깨물어 먹으세요",
    "advancements.the_bumblezone.obtain_honey_crystal_block.title": "벌처럼 아름다운 수정!",
    "advancements.the_bumblezone.obtain_honey_crystal_block.description": "부서지기 쉬운 꿀 수정 블록을 아이템으로 얻을 방법을 찾으세요. 섬세한 손길이 필요할지도 모릅니다...",
    "advancements.the_bumblezone.obtain_glistering_honey_crystal_block.title": "빛이 있으라!",
    "advancements.the_bumblezone.obtain_glistering_honey_crystal_block.description": "반짝이는 꿀 수정 블록을 부수지 않고 아이템으로 얻으세요. 부드러운 손길이 필요할지도 모릅니다...",
    "advancements.the_bumblezone.brew_glistering_honey_crystal_block.title": "확률을 속이는 법!",
    "advancements.the_bumblezone.brew_glistering_honey_crystal_block.description": "행운의 물약을 양조하세요! 반짝이는 꿀 수정 블록이 도움이 될지도 모릅니다...",
    "advancements.the_bumblezone.obtain_sticky_honey_residue.title": "꿀 재활용",
    "advancements.the_bumblezone.obtain_sticky_honey_residue.description": "꿀 아이템을 제련해 다른 용도로 재활용하세요",
    "advancements.the_bumblezone.obtain_sticky_honey_redstone.title": "꿀로 생각하기!",
    "advancements.the_bumblezone.obtain_sticky_honey_redstone.description": "끈적이는 꿀 찌꺼기와 레드스톤을 합치세요",
    "advancements.the_bumblezone.cleanup_sticky_honey_residue.title": "더 끈적한 문제!",
    "advancements.the_bumblezone.cleanup_sticky_honey_residue.description": "젖은 스펀지, 물 양동이 또는 물병으로 끈적이는 꿀 찌꺼기나 꿀 그물을 씻어 내세요",
    "advancements.the_bumblezone.obtain_honey_crystal_shield.title": "벌할 수 없는 방어!",
    "advancements.the_bumblezone.obtain_honey_crystal_shield.description": "꿀 수정으로 만든 방패를 제작하거나 찾으세요",
    "advancements.the_bumblezone.honey_crystal_shield_block_ineffectively.title": "막을 수 없는 공격의 승리!",
    "advancements.the_bumblezone.honey_crystal_shield_block_ineffectively.description": "도끼가 아닌 꿀 수정 방패의 또 다른 약점을 찾으세요",
    "advancements.the_bumblezone.obtain_maxed_honey_crystal_shield.title": "위대한 벌집 수호자",
    "advancements.the_bumblezone.obtain_maxed_honey_crystal_shield.description": "모루에서 수리를 거듭해 가장 강력한 꿀 수정 방패를 만드세요!",
    "advancements.the_bumblezone.comb_cutter_tool.title": "밀랍 닌자",
    "advancements.the_bumblezone.comb_cutter_tool.description": "벌집, 벌통, 둥지와 밀랍 블록을 빠르게 캐는 벌집 절단 마법이 부여된 도구를 얻으세요!",
    "advancements.the_bumblezone.craft_string_curtain_recipe.title": "60년대 후반의 귀환!",
    "advancements.the_bumblezone.craft_string_curtain_recipe.description": "아무 실 커튼이나 제작하세요!",
    "advancements.the_bumblezone.obtain_all_string_curtains.title": "무지개 커튼!!!",
    "advancements.the_bumblezone.obtain_all_string_curtains.description": "조합법에 염료를 사용해 모든 색상의 실 커튼을 모으세요",
    "advancements.the_bumblezone.extend_string_curtains.title": "벌을 막는 벽",
    "advancements.the_bumblezone.extend_string_curtains.description": "실을 들고 우클릭해 커튼을 아래로 늘리세요! 벌도 막아 줍니다!",
    "advancements.the_bumblezone.craft_beeswax_to_beehive.title": "공짜 집이에요! 벌 전용",
    "advancements.the_bumblezone.craft_beeswax_to_beehive.description": "벌집 밀랍으로 벌집을 제작하세요",
    "advancements.the_bumblezone.comb_cutter_extra_drops.title": "벌에게서 집세 더 받기",
    "advancements.the_bumblezone.comb_cutter_extra_drops.description": "벌집 절단 도구로 벌통이나 벌집에서 추가 아이템을 얻으세요",
    "advancements.the_bumblezone.sugar_water_next_to_sugar_cane.title": "머지않아... 전부 사탕수수가 될 거야!",
    "advancements.the_bumblezone.sugar_water_next_to_sugar_cane.description": "기존 사탕수수 블록 옆에 설탕물 원천 블록을 놓으세요",
    "advancements.the_bumblezone.consume_sugar_water_bottle.title": "당 충전!!!",
    "advancements.the_bumblezone.consume_sugar_water_bottle.description": "달콤한 설탕물을 벌컥 마시세요",
    "advancements.the_bumblezone.obtain_sugar_infused_stones.title": "설탕학",
    "advancements.the_bumblezone.obtain_sugar_infused_stones.description": "설탕이 스며든 이상한 돌 블록을 얻으세요. 설탕이 든 액체로 용암을 식혀 보세요. 원천과 흐르는 액체를 모두 시험해야 합니다...",
    "advancements.the_bumblezone.protection_of_the_hive_defense.title": "보아라! 나의 벌들아!",
    "advancements.the_bumblezone.protection_of_the_hive_defense.description": "벌집의 보호 효과가 있을 때 자신을 공격한 불운한 상대에게 벌떼를 풀어놓으세요",
    "advancements.the_bumblezone.bee_hit_wrath_of_the_hive.title": "안 돼, 벌은 안 돼애애!!!",
    "advancements.the_bumblezone.bee_hit_wrath_of_the_hive.description": "벌집의 분노 효과가 있는 동안 벌을 공격하는 실수를 저지르세요",
    "advancements.the_bumblezone.food_removed_wrath_of_the_hive.title": "평화를 위한 꿀 공물",
    "advancements.the_bumblezone.food_removed_wrath_of_the_hive.description": "살아남을 수 있다면... 음식으로 성난 벌떼를 달래세요",
    "advancements.the_bumblezone.variant_bee_name.title": "색다른 벌 발견!",
    "advancements.the_bumblezone.variant_bee_name.description": "이름표로 The Bumblezone 변종 벌에게 이름을 붙이세요! 벌처럼 생겼지만 모습이 다릅니다!",
    "advancements.the_bumblezone.variant_bee_briefcase_capture.title": "벌 수집가",
    "advancements.the_bumblezone.variant_bee_briefcase_capture.description": "변종 벌 14마리를 윙윙거리는 서류 가방에 넣으세요! 서로 다른 변종일 필요는 없습니다.",
    "advancements.the_bumblezone.cleanup_honey_web.title": "깔끔쟁이!",
    "advancements.the_bumblezone.cleanup_honey_web.description": "젖은 스펀지로 꿀 그물을 씻어 내세요!",
    "advancements.the_bumblezone.trigger_redstone_honey_web.title": "끈적임의 힘!",
    "advancements.the_bumblezone.trigger_redstone_honey_web.description": "특별한 꿀 그물에서 레드스톤 신호를 만들어 내세요",
    "advancements.the_bumblezone.enter_cell_maze.title": "벌집 미로에서 길을 잃다",
    "advancements.the_bumblezone.enter_cell_maze.description": "벌집 미로 구조물을 찾아 들어가세요! 벌집의 보호 효과가 없다면 조심하세요!",
    "advancements.the_bumblezone.enter_sempiternal_sanctum.title": "고대의 기원",
    "advancements.the_bumblezone.enter_sempiternal_sanctum.description": "벌의 정수를 섭취한 뒤 아무 영원 성소나 발견해 들어가세요",
    "advancements.the_bumblezone.enter_throne_pillar.title": "왕의 현전",
    "advancements.the_bumblezone.enter_throne_pillar.description": "왕좌 기둥 구조물을 찾아 들어가세요! 다른 구조물에서 얻은 왕좌 탐색 나침반을 사용하세요.",
    "advancements.the_bumblezone.honey_cocoon_silk_touch.title": "섬세한 손길",
    "advancements.the_bumblezone.honey_cocoon_silk_touch.description": "아이템이 사방으로 쏟아지지 않게 꿀 고치를 조심스럽게 캘 방법을 찾으세요!",
    "advancements.the_bumblezone.fish_rare_loot.title": "끈질긴 낚시",
    "advancements.the_bumblezone.fish_rare_loot.description": "The Bumblezone에서 낚시로 희귀한 전리품을 건지세요!",
    "advancements.the_bumblezone.consume_bee_soup.title": "침이 톡 쏘는 별미",
    "advancements.the_bumblezone.consume_bee_soup.description": "벌 수프를 후루룩 마시고 다채로운 상태 효과를 받으세요!",
    "advancements.the_bumblezone.dirt_pellet_return_to_sender.title": "흙 묻은 반송",
    "advancements.the_bumblezone.dirt_pellet_return_to_sender.description": "흙 알갱이를 쳐서 루트민에게 돌려보내세요",
    "advancements.the_bumblezone.dirt_pellet_kill_phantom.title": "하늘의 격돌",
    "advancements.the_bumblezone.dirt_pellet_kill_phantom.description": "던진 흙 알갱이로 팬텀을 죽이세요",
    "advancements.the_bumblezone.rootmin_flower_swap.title": "꽃 나눔",
    "advancements.the_bumblezone.rootmin_flower_swap.description": "벌 갑옷을 입고 작은 꽃이나 키 큰 꽃을 든 채 루트민을 우클릭하세요",
    "advancements.the_bumblezone.rootmin_rainbow_name.title": "이게 무슨 뜻이지?!",
    "advancements.the_bumblezone.rootmin_rainbow_name.description": '이름표로 루트민에게 "jeb_"이라는 이름을 붙이세요',
    "advancements.the_bumblezone.buzzing_briefcase_full.title": "이건 또 뭐지?...",
    "advancements.the_bumblezone.buzzing_briefcase_full.description": "윙윙거리는 서류 가방이 가득 찰 때까지 벌을 우클릭하세요",
    "advancements.the_bumblezone.buzzing_briefcase_heal.title": "의사 선생님 나가신다!",
    "advancements.the_bumblezone.buzzing_briefcase_heal.description": "윙윙거리는 서류 가방 안의 벌을 치료하세요! Shift + 우클릭하면 UI가 열립니다.",
    "advancements.the_bumblezone.buzzing_briefcase_release.title": "벌집의 영웅!",
    "advancements.the_bumblezone.buzzing_briefcase_release.description": "블록이나 엔티티를 왼쪽 클릭해 윙윙거리는 서류 가방의 벌을 풀어 주세요. Shift + 왼쪽 클릭하면 모두 풀어 줍니다.",
    "advancements.the_bumblezone.hide_in_pollen_pile.title": "전술적 꽃가루",
    "advancements.the_bumblezone.hide_in_pollen_pile.description": "깊은 꽃가루 더미 속에 몸을 숨기세요",
    "advancements.the_bumblezone.brush_pollen_pollen_suspicious.title": "수상한 유물...",
    "advancements.the_bumblezone.brush_pollen_pollen_suspicious.description": "수상한 꽃가루 더미를 솔질하세요",
    "advancements.the_bumblezone.obtain_windy_air.title": "설치 가능한 제트 기류!",
    "advancements.the_bumblezone.obtain_windy_air.description": "여왕벌에게서 블록으로 놓을 수 있는 바람 부는 공기 아이템을 얻으세요!",
    "advancements.the_bumblezone.obtain_stinger_spear.title": "모든 무기를 뛰어넘을...",
    "advancements.the_bumblezone.obtain_stinger_spear.description": "끝에 벌침이 달린 창을 찾아 얻으세요",
    "advancements.the_bumblezone.stinger_spear_poisoning.title": "벌이 되어 보기!",
    "advancements.the_bumblezone.stinger_spear_poisoning.description": "신경독 마법이 부여된 벌침 창으로 대상에게 독을 거세요!",
    "advancements.the_bumblezone.stinger_spear_paralyzing.title": "그 자리에서 멈춰!",
    "advancements.the_bumblezone.stinger_spear_paralyzing.description": "신경독 마법이 부여된 벌침 창으로 대상을 마비시키세요!",
    "advancements.the_bumblezone.stinger_spear_paralyze_boss.title": "승산 높이기",
    "advancements.the_bumblezone.stinger_spear_paralyze_boss.description": "벌침 창으로 체력이 아주 높은 몹을 마비시키세요!",
    "advancements.the_bumblezone.stinger_spear_long_range_kill.title": "훌륭한 투창",
    "advancements.the_bumblezone.stinger_spear_long_range_kill.description": "벌침 창을 아주 멀리 던져 몹을 죽이세요",
    "advancements.the_bumblezone.craft_flower_headwear.title": "꽃이 되어라!",
    "advancements.the_bumblezone.craft_flower_headwear.description": "꽃 머리 장식을 제작하거나 얻으세요! 착용하면 벌을 끌어들입니다!",
    "advancements.the_bumblezone.dye_flower_headwear.title": "이게 바로 개성이지!",
    "advancements.the_bumblezone.dye_flower_headwear.description": "꽃 머리 장식을 다른 색으로 염색해 대담한 패션 감각을 뽐내세요!",
    "advancements.the_bumblezone.flower_headwear_wrath_structure.title": "벌처럼 호기심 많게",
    "advancements.the_bumblezone.flower_headwear_wrath_structure.description": "꽃 머리 장식을 쓰고 벌집 미로에 들어가세요. 이제 안에서 벌집의 분노 효과를 받지 않습니다!",
    "advancements.the_bumblezone.warrior_bee.title": "벌 전사의 등장!",
    "advancements.the_bumblezone.warrior_bee.description": "벌이 선사하는 최고의 무기와 갑옷으로 무장하세요!",
    "advancements.the_bumblezone.carpenter_bee_boots_mined_blocks.title": "강철 허벅지!",
    "advancements.the_bumblezone.carpenter_bee_boots_mined_blocks.description": "어리호박벌 부츠를 신고 웅크린 채 원목, 나뭇잎, 벌집 조각 같은 블록 64개를 파헤치세요!",
    "advancements.the_bumblezone.carpenter_bee_boots_wall_hanging.title": "바닥은 용암이야!",
    "advancements.the_bumblezone.carpenter_bee_boots_wall_hanging.description": "어리호박벌 부츠를 신고 원목, 나뭇잎, 벌집 조각 같은 특정 블록의 벽에 오랫동안 매달리세요",
    "advancements.the_bumblezone.honey_bee_leggings_flower_pollen.title": "벌 무릎보다 멋진 레깅스!",
    "advancements.the_bumblezone.honey_bee_leggings_flower_pollen.description": "꽃 사이를 걷거나 달려 꿀벌 레깅스에 꽃가루를 모으세요!",
    "advancements.the_bumblezone.honey_bee_leggings_pollen_removal.title": "목욕 시간!",
    "advancements.the_bumblezone.honey_bee_leggings_pollen_removal.description": "젖은 스펀지 위를 걷거나 물에 들어가 꿀벌 레깅스의 꽃가루를 제거하세요!",
    "advancements.the_bumblezone.bumble_bee_chestplate_max_flight.title": "새인가! 비행기인가! 아니, 저건...",
    "advancements.the_bumblezone.bumble_bee_chestplate_max_flight.description": "호박벌 흉갑과 다른 벌 갑옷 또는 벌 장신구를 3개 이상 착용한 채 날개를 퍼덕이세요!",
    "advancements.the_bumblezone.stingless_bee_helmet_super_sight.title": "겹눈",
    "advancements.the_bumblezone.stingless_bee_helmet_super_sight.description": "무침벌 투구의 힘으로 벌을 한 번에 50마리 이상 강조 표시하세요!",
    "advancements.the_bumblezone.craft_honey_compass.title": "이게 아직도 나침반이 맞나...?",
    "advancements.the_bumblezone.craft_honey_compass.description": "매혹적인 꿀 나침반을 제작하거나 찾으세요!",
    "advancements.the_bumblezone.honey_compass_use.title": "벌험가 도라",
    "advancements.the_bumblezone.honey_compass_use.description": "꿀 나침반의 추적 또는 탐색 능력을 활성화하세요!",
    "advancements.the_bumblezone.obtain_throne_honey_compass.title": "여왕을 만나러 갑시다!",
    "advancements.the_bumblezone.obtain_throne_honey_compass.description": "구조물의 꿀 고치에서 왕좌 기둥을 가리키는 희귀한 꿀 나침반을 얻으세요!",
    "advancements.the_bumblezone.bee_cannon_full.title": "이제 얌전히 벌어!",
    "advancements.the_bumblezone.bee_cannon_full.description": "벌 대포를 가득 장전해 발사하세요!",
    "advancements.the_bumblezone.crystal_cannon_full.title": "극단적인 군중 제어",
    "advancements.the_bumblezone.crystal_cannon_full.description": "수정 대포를 가득 장전해 발사하세요!",
    "advancements.the_bumblezone.bee_stinger_paralysis.title": "끝없는 벌침",
    "advancements.the_bumblezone.bee_stinger_paralysis.description": "활이나 쇠뇌로 벌침을 계속 쏴 몹을 마비시키세요",
    "advancements.the_bumblezone.brew_bee_stinger.title": "농축 독소",
    "advancements.the_bumblezone.brew_bee_stinger.description": "긴 독의 물약을 양조하세요! 벌침을 양조기에서 정제할 수 있을지도 모릅니다...",
    "advancements.the_bumblezone.brew_bee_soup.title": "위험한 양조",
    "advancements.the_bumblezone.brew_bee_soup.description": "신경독 물약을 양조하세요! 벌 수프를 양조기에서 정제할 수 있을지도 모릅니다...",
    "advancements.the_bumblezone.bee_essence_infusion.title": "희망, 사랑, 꿈, 그리고 벌!!!",
    "advancements.the_bumblezone.bee_essence_infusion.description": "벌의 정수를 섭취하세요! 여왕의 소망 퀘스트를 완료한 것을 축하합니다!",
    "advancements.the_bumblezone.drink_royal_jelly_bottle.title": "왕실의 힘 얻기",
    "advancements.the_bumblezone.drink_royal_jelly_bottle.description": "로열 젤리 병을 마시고 힘을 얻으세요! 여왕벌의 발전 과제에서 얻을 수 있습니다.",
    "advancements.the_bumblezone.obtain_royal_jelly_bucket.title": "능숙한 수집가",
    "advancements.the_bumblezone.obtain_royal_jelly_bucket.description": "로열 젤리 한 양동이를 얻으세요. 여왕벌이 좋아할 것 같습니다...",
    "advancements.the_bumblezone.royal_jelly_block_piston.title": "밀지 말고 당겨!",
    "advancements.the_bumblezone.royal_jelly_block_piston.description": "로열 젤리 블록을 끈끈이 피스톤 옆에 놓으세요",
    "advancements.the_bumblezone.carve_wax.title": "대담하고 뻔뻔하게!",
    "advancements.the_bumblezone.carve_wax.description": "가위나 검으로 조각용 밀랍 블록의 모든 무늬를 조각하세요!",
    "advancements.the_bumblezone.carve_ancient_wax.title": "완벽한 디자인",
    "advancements.the_bumblezone.carve_ancient_wax.description": "가위나 검으로 아무 고대 밀랍 블록이나 조각하세요!",
    "advancements.the_bumblezone.carve_luminescent_wax.title": "올바른 방향",
    "advancements.the_bumblezone.carve_luminescent_wax.description": "가위나 검으로 아무 발광 밀랍 블록이나 조각하세요!",
    "advancements.the_bumblezone.sentry_watcher_use_egg.title": "개인 수호자",
    "advancements.the_bumblezone.sentry_watcher_use_egg.description": "센트리 감시자 생성 알을 제작해 사용하세요! 자신을 소환한 사람에게는 돌진하지 않습니다.",
    "advancements.the_bumblezone.multi_potion_potion_candle.title": "마법의 양초",
    "advancements.the_bumblezone.multi_potion_potion_candle.description": "물약을 2개 이상 사용해 물약 양초를 제작하세요! 양초의 능력치는 물약 능력치가 섞여 정해집니다.",
    "advancements.the_bumblezone.light_soul_super_candle.title": "분위기 잡기",
    "advancements.the_bumblezone.light_soul_super_candle.description": "대형 양초나 물약 양초에 푸른 불꽃을 붙이세요! 영혼과 관련이 있을지도 모릅니다...",
    "advancements.the_bumblezone.obtain_all_colored_super_candles.title": "무지개 너머로!",
    "advancements.the_bumblezone.obtain_all_colored_super_candles.description": "모든 색상의 대형 양초를 모으세요!",
    "advancements.the_bumblezone.projectile_light_instant_potion_candle.title": "함정 양초 발동!",
    "advancements.the_bumblezone.projectile_light_instant_potion_candle.description": "해로운 즉시 효과가 든 물약 양초에 불붙은 발사체로 불을 붙이세요",
    "advancements.the_bumblezone.enter_garden.title": "정원사와 벌들",
    "advancements.the_bumblezone.enter_garden.description": "위를 보세요! 아래로 매달린 거대한 정원 구조물을 찾을 수 있습니다!",
    "advancements.the_bumblezone.enter_all_structures.title": "벌경꾼",
    "advancements.the_bumblezone.enter_all_structures.description": "놀랍습니다! The Bumblezone의 모든 구조물을 발견했어요!",
    "advancements.the_bumblezone.obtain_all_banner_patterns.title": "유행 선도자!",
    "advancements.the_bumblezone.obtain_all_banner_patterns.description": "The Bumblezone의 현수막 무늬 아이템을 모두 모았어요!",
    "advancements.the_bumblezone.discover_all_biomes.title": "벌지리학",
    "advancements.the_bumblezone.discover_all_biomes.description": "The Bumblezone의 모든 생물군계를 발견했어요!",
    "advancements.the_bumblezone.grow_crystalline_flower.title": "먹어라, 먹어라, 먹어라",
    "advancements.the_bumblezone.grow_crystalline_flower.description": "결정꽃에 아이템과 경험치를 줘 완전히 키우세요! 결정꽃을 우클릭하면 UI가 열립니다.",
    "advancements.the_bumblezone.enchant_crystalline_flower.title": "현명한 선택",
    "advancements.the_bumblezone.enchant_crystalline_flower.description": "티어가 5 이상 드는 마법으로 책이나 마법이 부여된 책에 마법을 부여하세요. 결정꽃을 우클릭하면 UI가 열립니다.",
    "advancements.the_bumblezone.essence_raging.title": "멈출 수 없는 분노",
    "advancements.the_bumblezone.essence_raging.description": "붉은 영원 성소의 특별 이벤트를 완료하세요!",
    "advancements.the_bumblezone.essence_calming.title": "평화와 사랑",
    "advancements.the_bumblezone.essence_calming.description": "푸른 영원 성소의 특별 이벤트를 완료하세요!",
    "advancements.the_bumblezone.essence_continuity.title": "현실의 오류",
    "advancements.the_bumblezone.essence_continuity.description": "하얀 영원 성소의 특별 이벤트를 완료하세요!",
    "advancements.the_bumblezone.essence_knowing.title": "모든 것을 보는 자",
    "advancements.the_bumblezone.essence_knowing.description": "보라색 영원 성소의 특별 이벤트를 완료하세요!",
    "advancements.the_bumblezone.essence_life.title": "생명의 축복",
    "advancements.the_bumblezone.essence_life.description": "초록색 영원 성소의 특별 이벤트를 완료하세요!",
    "advancements.the_bumblezone.essence_radiance.title": "태양광 충전",
    "advancements.the_bumblezone.essence_radiance.description": "노란색 영원 성소의 특별 이벤트를 완료하세요!",
    "advancements.the_bumblezone.the_queens_desire.back_in_action.title": "다시 활동 시작",
    "advancements.the_bumblezone.the_queens_desire.back_in_action.description": "벌 12마리에게 벌침을 다시 달아 확실한 죽음에서 구하세요",
    "advancements.the_bumblezone.the_queens_desire.fighting_the_swarm.title": "떼와의 싸움",
    "advancements.the_bumblezone.the_queens_desire.fighting_the_swarm.description": "사방을 기어 다니고 파고드는 좀벌레 8마리를 죽이세요",
    "advancements.the_bumblezone.the_queens_desire.flooding_the_housing_market.title": "주택 시장 공급 과잉",
    "advancements.the_bumblezone.the_queens_desire.flooding_the_housing_market.description": "벌집 또는 벌통 6개를 제작하세요",
    "advancements.the_bumblezone.the_queens_desire.honey_drunk.title": "꿀에 취하다",
    "advancements.the_bumblezone.the_queens_desire.honey_drunk.description": "꿀이 든 병 8개를 벌컥벌컥 마시세요!",
    "advancements.the_bumblezone.the_queens_desire.hungry_hungry_bees.title": "배고픈 벌들",
    "advancements.the_bumblezone.the_queens_desire.hungry_hungry_bees.description": "벌에게 설탕물이나 꿀과 비슷한 것을 48번 먹여 배를 채우세요! 같은 벌이어도, 서로 다른 벌이어도 됩니다.",
    "advancements.the_bumblezone.the_queens_desire.intimidation.title": "위협",
    "advancements.the_bumblezone.the_queens_desire.intimidation.description": "벌 대포로 엔더 드래곤에게 벌을 발사해 결의를 보여 주세요",
    "advancements.the_bumblezone.the_queens_desire.journeys_end.title": "여정의 끝",
    "advancements.the_bumblezone.the_queens_desire.journeys_end.description": "여왕의 소망 발전 과제를 모두 완료하세요! 여왕벌을 우클릭해 마지막 큰 보상을 받으세요!",
    "advancements.the_bumblezone.the_queens_desire.love_bees.title": "벌을 사랑하세요",
    "advancements.the_bumblezone.the_queens_desire.love_bees.description": "아기 벌이 모두 8마리 태어날 때까지 벌을 번식시키세요",
    "advancements.the_bumblezone.the_queens_desire.otherworldly_mites.title": "이세계의 진드기",
    "advancements.the_bumblezone.the_queens_desire.otherworldly_mites.description": "존재의 질서를 어긴 엔더마이트 4마리를 처치하세요",
    "advancements.the_bumblezone.the_queens_desire.peak_inefficiency.title": "비효율의 극치",
    "advancements.the_bumblezone.the_queens_desire.peak_inefficiency.description": "어떻게든 벌침 창으로 위더를 죽이세요...",
    "advancements.the_bumblezone.the_queens_desire.poison_warfare.title": "독성 전쟁",
    "advancements.the_bumblezone.the_queens_desire.poison_warfare.description": "활이나 쇠뇌로 벌침 32개를 발사하세요",
    "advancements.the_bumblezone.the_queens_desire.pollen_fight.title": "꽃가루 싸움",
    "advancements.the_bumblezone.the_queens_desire.pollen_fight.description": "꽃가루 뭉치를 던져 엔티티 24마리를 맞히세요. 다른 플레이어도 포함됩니다!",
    "advancements.the_bumblezone.the_queens_desire.slimy_mitosis.title": "끈적한 유사 분열",
    "advancements.the_bumblezone.the_queens_desire.slimy_mitosis.description": "꿀 슬라임을 6번 번식시키세요. 설탕을 정말 좋아합니다!",
    "advancements.the_bumblezone.the_queens_desire.terror_fangs.title": "공포의 송곳니",
    "advancements.the_bumblezone.the_queens_desire.terror_fangs.description": "깊은 곳의 동굴 거미 16마리를 처치하세요",
    "advancements.the_bumblezone.the_queens_desire.the_beginning.title": "여왕의 소망",
    "advancements.the_bumblezone.the_queens_desire.the_beginning.description": "여왕벌을 만나 부여받은 연속 발전 과제입니다. 완료해 로열 젤리 병을 보상으로 받으세요!",
    "advancements.the_bumblezone.the_queens_desire.the_crazy_florist.title": "광기 어린 꽃집 주인",
    "advancements.the_bumblezone.the_queens_desire.the_crazy_florist.description": "꽃가루 뭉치로 꽃에 꽃가루받이를 해 꽃 8송이를 피우세요",
    "advancements.the_bumblezone.the_queens_desire.the_great_dragon_slayer.title": "위대한 드래곤 사냥꾼",
    "advancements.the_bumblezone.the_queens_desire.the_great_dragon_slayer.description": "벌 갑옷을 모두 착용하고 엔더 드래곤을 처치해 전설이 되세요",
    "advancements.the_bumblezone.the_queens_desire.too_many_legs.title": "다리가 너무 많아",
    "advancements.the_bumblezone.the_queens_desire.too_many_legs.description": "징그러운 거미 32마리를 때려잡으세요. 동굴 거미는 포함되지 않습니다.",
    "advancements.the_bumblezone.the_queens_desire.crazy_trader.title": "광적인 거래가",
    "advancements.the_bumblezone.the_queens_desire.crazy_trader.description": "여왕벌과 128번 거래하세요. 보너스 거래가 아니어도 되며, 어떤 거래든 인정됩니다!",
}
