#!/usr/bin/env python3
"""Create 계열 언어 작업본을 단계별로 정규화하고 검증한다."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from five_family_goal import PROJECT_ROOT, load_json, validate_value

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

WORK_ROOT = PROJECT_ROOT / "working/create"

OVERRIDES = {
    "create": {
        "advancement.create.lava_wheel_00000.desc": "이런 게 작동해서는 안 되는데...\n§7(숨겨진 발전과제)",
        "block.create.andesite_belt_funnel": "안산암 벨트 깔때기",
        "block.create.andesite_funnel": "안산암 깔때기",
        "block.create.brass_belt_funnel": "황동 벨트 깔때기",
        "block.create.brass_casing": "황동 케이싱",
        "block.create.brass_funnel": "황동 깔때기",
        "block.create.chain_conveyor": "체인 컨베이어",
        "block.create.cherry_window": "벚나무 창",
        "block.create.cherry_window_pane": "벚나무 창유리판",
        "block.create.deployer": "배치기",
        "block.create.depot": "보관소",
        "block.create.gearshift": "기어변환기",
        "block.create.hand_crank": "손 크랭크",
        "block.create.mechanical_arm": "기계식 팔",
        "block.create.mechanical_bearing": "기계식 베어링",
        "block.create.mechanical_crafter": "기계식 조합기",
        "block.create.mechanical_drill": "기계식 드릴",
        "block.create.mechanical_harvester": "기계식 수확기",
        "block.create.mechanical_mixer": "기계식 혼합기",
        "block.create.mechanical_plough": "기계식 쟁기",
        "block.create.mechanical_press": "기계식 압착기",
        "block.create.mechanical_pump": "기계식 펌프",
        "block.create.mechanical_saw": "기계식 톱",
        "block.create.package_frogport": "소포 개구리항",
        "block.create.schematic_table.tooltip.behaviour1": "설계도 폴더에서 선택한 파일을 업로드합니다.",
        "block.create.sequenced_gearshift": "순차 기어변환기",
        "block.create.spout": "주입구",
        "block.create.steam_engine": "증기 기관",
        "block.create.stock_link": "재고 연결기",
        "block.create.stock_ticker": "재고 표시기",
        "block.create.track_observer": "열차 감지기",
        "block.create.weighted_ejector": "무게 추 달린 배출기",
        "create.command.killTPSCommand.status.usage.1": "[Create]: /killtps start <tickTime> 명령어를 사용해 서버 틱을 인위적으로 늦추세요",
        "create.gui.pojav.title": "Create는 PojavLauncher를 지원하지 않습니다.",
        "create.gui.stock_ticker.shift_moves_bottom": "Shift 키를 누르면 맨 아래로 이동",
        "create.gui.stock_ticker.shift_moves_top": "Shift 키를 누르면 맨 위로 이동",
        "create.item_attributes.color": "%1$s색으로 염색됨",
        "create.item_attributes.color.inverted": "%1$s색으로 염색되지 않음",
        "create.gui.stock_keeper.click_to_cycle": "클릭하여 전환",
        "create.gui.stock_keeper.jei_sync.none": "동기화 안 함",
        "create.gui.stock_keeper.jei_sync.none.description": "재고 관리자와 조합법 뷰어의 검색을 서로 독립적으로 유지합니다",
        "create.gui.stock_keeper.jei_sync.sync_both": "조합법 뷰어와 양방향 동기화",
        "create.gui.stock_keeper.jei_sync.sync_both.description": "재고 관리자와 조합법 뷰어의 검색을 서로 동기화합니다",
        "create.gui.stock_keeper.jei_sync.sync_from_jei": "조합법 뷰어에서 동기화",
        "create.gui.stock_keeper.jei_sync.sync_from_jei.description": "조합법 뷰어의 검색을 재고 관리자에 반영합니다",
        "create.gui.stock_keeper.jei_sync.sync_from_stock_keeper": "재고 관리자에서 동기화",
        "create.gui.stock_keeper.jei_sync.sync_from_stock_keeper.description": "재고 관리자의 검색을 조합법 뷰어에 반영합니다",
        "create.keyinfo.alt_modifier": "Alt 보조 키",
        "create.keyinfo.ctrl_modifier": "Ctrl 보조 키",
        "create.keyinfo.shift_modifier": "Shift 보조 키",
        "item.create.schematic_and_quill.tooltip.behaviour1": "_우클릭_으로 _두 꼭짓점_을 선택하세요. _Ctrl_을 누른 채 스크롤하면 허공의 위치를 선택할 수 있습니다.",
        "item.create.schematic_and_quill.tooltip.summary": "세계의 _구조물을_ _.nbt 파일_로 _저장_할 때 사용합니다.",
        "item.create.belt_connector": "기계식 벨트",
        "item.create.goggles": "기술자의 고글",
        "item.create.linked_controller.tooltip.behaviour2": "수동 _설정_ _창_을 엽니다.",
        "tag.item.c.foods.dough.wheat": "밀 반죽",
    },
    "createaddition": {
        "createaddition.tooltip.liquid_burning.info": "액체 블레이즈 버너 정보:",
        "createaddition.tooltip.liquid_burning.time_remaining": "남은 연소 시간:",
        "createaddition.tooltip.charging.info": "테슬라 코일 정보:",
        "createaddition.tooltip.charging.time_remaining": "남은 충전 시간:",
        "createaddition.tooltip.alternator.info": "교류 발전기 정보:",
        "item.createaddition.diamond_grit_sandpaper.tooltip.condition1": "사용 시",
        "item.createaddition.diamond_grit_sandpaper.tooltip.summary": "재료를 _연마_하는 데 사용합니다. 배치기로 자동화할 수 있습니다.",
        "item.createaddition.diamond_grit_sandpaper.tooltip.behaviour1": "_보조 손_에 들고 있거나 _바닥_에 놓인 아이템을 _바라보며_ 사용하면 광택을 냅니다",
        "item.createaddition.copper_spool.tooltip.summary": "전선을 보관하는 데 사용합니다.",
        "item.createaddition.festive_spool.tooltip.summary": "전선을 보관하는 데 사용합니다.",
        "item.createaddition.gold_spool.tooltip.summary": "전선을 보관하는 데 사용합니다.",
        "item.createaddition.electrum_spool.tooltip.summary": "전선을 보관하는 데 사용합니다.",
        "item.createaddition.spool.tooltip.summary": "전선을 보관하는 데 사용합니다.",
        "item.createaddition.brass_figurine": "황동 조각상",
        "item.createaddition.brass_figurine.tooltip": "황동 조각상",
        "item.createaddition.brass_figurine.tooltip.summary": ".",
        "item.createaddition.copper_goblet": "구리 잔",
        "item.createaddition.copper_goblet.tooltip": "구리 잔",
        "item.createaddition.copper_goblet.tooltip.summary": "이 _잔_의 뛰어난 열전도 능력은 가장 필요할 때 몸을 시원하게 해 줍니다.",
        "item.createaddition.gold_goblet": "화려한 잔",
        "item.createaddition.gold_goblet.tooltip": "화려한 잔",
        "item.createaddition.gold_goblet.tooltip.summary": "이 _잔_으로 마시면 평범한 병보다 갈증을 더 많이 해소합니다.",
        "block.createaddition.electrum_block": "일렉트럼 블록",
        "block.createaddition.modular_accumulator": "모듈식 축전지",
        "createaddition.display_source.digital_adapter_source_digital_adapter": "디지털 어댑터",
        "createaddition.subtitle.loud_zap": "테슬라 코일이 큰 전기 충격을 냄",
        "createaddition.subtitle.little_zap": "테슬라 코일에서 전기 불꽃이 튐",
        "createaddition.schedule.condition.threshold.unit": "K⚡",
    },
    "create_hypertube": {
        "itemGroup.create_hypertube": "Create: Hypertube",
        "subtitles.create_hypertube.chose_direction": "방향 선택",
        "subtitles.create_hypertube.entrance_open": "하이퍼튜브 입구 열림",
        "subtitles.create_hypertube.entrance_close": "하이퍼튜브 입구 닫힘",
        "placement.create_hypertube.no_valid_points": "두 위치를 모두 지정해야 합니다",
        "block.hypertube.hyper_entrance.manual_lock": "수동 잠금 모드",
        "block.hypertube.hyper_entrance.automatic_lock": "자동 잠금 모드",
        "item.create_hypertube.hypertube_funnel": "하이퍼튜브 깔때기",
        "create_hypertube.ponder.simple_tube.text_1": "다른 튜브를 든 채 하이퍼튜브를 우클릭하고...",
        "create_hypertube.ponder.simple_tube.text_2": "...두 번째 하이퍼튜브를 설치하면...",
        "create_hypertube.ponder.simple_tube.text_3": "...하이퍼튜브가 연결됩니다!",
        "create_hypertube.ponder.entrance.text_1": "하이퍼튜브 입구를 하이퍼튜브 네트워크에 연결하면 빠르게 이동할 수 있습니다.",
        "create_hypertube.ponder.entrance.text_2": "하이퍼튜브에 들어가려면 입구에 최소 16 RPM의 회전력을 공급해야 합니다.",
        "create_hypertube.ponder.accelerator.text_2": "가속기를 우클릭하면 감속 모드로 전환할 수 있습니다.",
        "create_hypertube.ponder.attachments.text_1": "스캐너 부착물은 하이퍼튜브로 이동하는 개체를 감지합니다. 신호 세기는 아기일 때 8, 성체일 때 15입니다.",
        "create_hypertube.ponder.attachments.text_2": "가속기의 어느 면에든 여러 부착물을 동시에 설치할 수 있습니다.",
        "create_hypertube.ponder.attachments.text_3": "레드스톤 감지 부착물을 사용하면 레드스톤 신호로 가속기 또는 입구의 모드를 바꿀 수 있습니다.",
        "block.create_hypertube.hypertube_junction": "하이퍼튜브 분기기",
    },
    "bellsandwhistles": {
        "block.bellsandwhistles.andesite_grab_rails": "안산암 손잡이",
        "block.bellsandwhistles.brass_grab_rails": "황동 손잡이",
        "block.bellsandwhistles.copper_grab_rails": "구리 손잡이",
        "block.bellsandwhistles.andesite_bogie_steps": "안산암 발판",
        "block.bellsandwhistles.brass_bogie_steps": "황동 발판",
        "block.bellsandwhistles.copper_bogie_steps": "구리 발판",
        "block.bellsandwhistles.andesite_door_step": "안산암 문 발판",
        "block.bellsandwhistles.brass_door_step": "황동 문 발판",
        "block.bellsandwhistles.copper_door_step": "구리 문 발판",
        "block.bellsandwhistles.headlight": "전조등",
        "block.bellsandwhistles.ornate_iron_trapdoor": "장식된 철 다락문",
        "block.bellsandwhistles.station_platform": "역 승강장",
        "block.bellsandwhistles.metro_casing": "지하철 케이싱",
        "block.bellsandwhistles.corrugated_metro_casing": "골판형 지하철 케이싱",
        "block.bellsandwhistles.metro_panel": "지하철 패널",
        "block.bellsandwhistles.corrugated_metro_panel": "골판형 지하철 패널",
        "block.bellsandwhistles.metro_window": "지하철 창",
        "block.bellsandwhistles.metro_trapdoor": "지하철 다락문",
        "block.bellsandwhistles.metal_pilot": "금속 배장기",
        "block.bellsandwhistles.andesite_pilot": "안산암 배장기",
        "block.bellsandwhistles.brass_pilot": "황동 배장기",
        "block.bellsandwhistles.copper_pilot": "구리 배장기",
        "block.bellsandwhistles.polished_andesite_pilot": "윤나는 안산암 배장기",
        "block.bellsandwhistles.polished_asurine_pilot": "윤나는 담청암 배장기",
        "block.bellsandwhistles.polished_calcite_pilot": "윤나는 방해석 배장기",
        "block.bellsandwhistles.polished_crimsite_pilot": "윤나는 진홍암 배장기",
        "block.bellsandwhistles.polished_deepslate_pilot": "윤나는 심층암 배장기",
        "block.bellsandwhistles.polished_diorite_pilot": "윤나는 섬록암 배장기",
        "block.bellsandwhistles.polished_dripstone_pilot": "윤나는 점적석 배장기",
        "block.bellsandwhistles.polished_granite_pilot": "윤나는 화강암 배장기",
        "block.bellsandwhistles.polished_limestone_pilot": "윤나는 석회암 배장기",
        "block.bellsandwhistles.polished_ochrum_pilot": "윤나는 황토암 배장기",
        "block.bellsandwhistles.polished_scorchia_pilot": "윤나는 그을린 스코리아 배장기",
        "block.bellsandwhistles.polished_scoria_pilot": "윤나는 스코리아 배장기",
        "block.bellsandwhistles.polished_tuff_pilot": "윤나는 응회암 배장기",
        "block.bellsandwhistles.polished_veridium_pilot": "윤나는 심록암 배장기",
        "itemGroup.bellsandwhistlestab": "Bells & Whistles",
        "creativetab.bellsandwhistlestab": "Bells & Whistles",
        "creativetab.bellsandwhistles.bells_and_whistles": "Bells & Whistles",
    },
    "create_aquatic_ambitions": {
        "itemGroup.create_aquatic_ambitions": "Create: Aquatic Ambitions",
        "block.create_aquatic_ambitions.mechanical_conduit": "전달체 케이지",
        "block.create_aquatic_ambitions.prismarine_alloy_block": "프리즈머린 합금 블록",
        "item.create_aquatic_ambitions.prismarine_alloy": "프리즈머린 합금",
        "item.create_aquatic_ambitions.prismarine_alloy_rod": "프리즈머린 합금 막대기",
        "item.create_aquatic_ambitions.nautilus_shard": "앵무조개 파편",
        "item.create_aquatic_ambitions.suspicious_rock": "수상한 바위",
        "item.create_aquatic_ambitions.spiky_shell": "가시 돋친 껍데기",
        "item.create_aquatic_ambitions.calcium_rich_powder": "칼슘이 풍부한 가루",
        "recipe.create_aquatic_ambitions.fan_channeling": "전달체 활성화",
        "recipe.create_aquatic_ambitions.fan_channeling.fan": "전달체 활성화",
        "create_aquatic_ambitions.tooltip.conduitcage.header": "전달체 케이지 정보",
        "tooltip.create_aquatic_ambitions.effect.cleansing": "정화",
        "tooltip.create_aquatic_ambitions.effect.burning": "연소",
        "create.item_attributes.can_be_channeled": "전달체로 처리 가능",
        "create_aquatic_ambitions.mechanical_conduit.entity_filter.title": "개체 필터",
        "mechanical_conduit.selection_mode.everyone": "모두",
        "mechanical_conduit.selection_mode.players": "플레이어",
        "mechanical_conduit.selection_mode.friendly_mobs": "우호적 몹",
        "mechanical_conduit.selection_mode.players_friendly_mobs": "플레이어와 우호적 몹",
        "mechanical_conduit.selection_mode.monsters": "몬스터",
        "create_aquatic_ambitions.ponder.conduit_processing.header": "전달체 장치로 아이템 처리",
        "create_aquatic_ambitions.ponder.conduit_processing.text_1": "각성한 전달체를 선풍기 가공에 사용할 수 있습니다.",
        "create_aquatic_ambitions.ponder.conduit_processing.text_2": "전달체의 물을 통과한 바람은 활성화 가공 장치를 만듭니다.",
        "create_aquatic_ambitions.ponder.conduit_processing.text_3": "물층을 더 쌓으면 전달체의 힘이 약해져 대신 세척 가공 장치가 됩니다.",
        "create_aquatic_ambitions.ponder.conduit_processing.text_4": "활성화 흐름에 닿은 아이템이 처리됩니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_awaken.header": "전달체 케이지 깨우기",
        "create_aquatic_ambitions.ponder.mechanical_conduit_awaken.text_1": "전달체 케이지는 전달체의 프리즈머린 고리를 더 작게 대신할 수 있습니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_awaken.text_2": "아래쪽 면을 통해 전달체 케이지로 유체를 공급할 수 있습니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_awaken.text_3": "전달체 케이지에 유체를 공급하면 케이지가 깨어납니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_processing.header": "전달체 케이지로 아이템 처리",
        "create_aquatic_ambitions.ponder.mechanical_conduit_processing.text_1": "전달체 케이지도 선풍기 가공에 사용할 수 있습니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_processing.text_2": "전달체 케이지를 통과한 바람은 활성화 가공 장치를 만듭니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_processing.text_3": "활성화 흐름에 닿은 아이템이 처리됩니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_effects.header": "전달체 케이지로 효과 부여",
        "create_aquatic_ambitions.ponder.mechanical_conduit_effects.text_1": "각성한 전달체 케이지는 주변 개체에 영향을 줄 수 있습니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_effects.text_2": "물로 깨운 전달체 케이지는 전달체의 힘 효과를 부여합니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_effects.text_3": "다른 유체는 서로 다른 효과를 부여합니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_effects.text_4": "모드 슬롯에서 영향을 받을 개체를 선택할 수 있습니다.",
    },
}


DRAGONS_PLUS_DYES = {
    "arts_and_crafts_bleached": ("Arts and Crafts 표백색", "블리치듀"),
    "black": ("검은색", "검은색"),
    "blue": ("파란색", "파란색"),
    "brown": ("갈색", "갈색"),
    "cyan": ("청록색", "청록색"),
    "dye_depot_amber": ("Dye Depot 호박색", "호박색"),
    "dye_depot_aqua": ("Dye Depot 물색", "물색"),
    "dye_depot_beige": ("Dye Depot 베이지색", "베이지색"),
    "dye_depot_coral": ("Dye Depot 산호색", "산호색"),
    "dye_depot_forest": ("Dye Depot 숲색", "숲색"),
    "dye_depot_ginger": ("Dye Depot 생강색", "생강색"),
    "dye_depot_indigo": ("Dye Depot 쪽빛", "쪽빛"),
    "dye_depot_maroon": ("Dye Depot 적갈색", "적갈색"),
    "dye_depot_mint": ("Dye Depot 민트색", "민트색"),
    "dye_depot_navy": ("Dye Depot 남색", "남색"),
    "dye_depot_olive": ("Dye Depot 올리브색", "올리브색"),
    "dye_depot_rose": ("Dye Depot 장미색", "장미색"),
    "dye_depot_slate": ("Dye Depot 슬레이트색", "슬레이트색"),
    "dye_depot_tan": ("Dye Depot 황갈색", "황갈색"),
    "dye_depot_teal": ("Dye Depot 틸색", "틸색"),
    "dye_depot_verdant": ("Dye Depot 진초록색", "진초록색"),
    "dyenamics_amber": ("Dyenamics 호박색", "호박색"),
    "dyenamics_aquamarine": ("Dyenamics 아쿠아마린색", "아쿠아마린색"),
    "dyenamics_bubblegum": ("Dyenamics 풍선껌색", "풍선껌색"),
    "dyenamics_cherenkov": ("Dyenamics 체렌코프색", "체렌코프색"),
    "dyenamics_conifer": ("Dyenamics 침엽수색", "침엽수색"),
    "dyenamics_fluorescent": ("Dyenamics 형광색", "형광색"),
    "dyenamics_honey": ("Dyenamics 꿀색", "꿀색"),
    "dyenamics_icy_blue": ("Dyenamics 얼음빛 파란색", "얼음빛 파란색"),
    "dyenamics_lavender": ("Dyenamics 라벤더색", "라벤더색"),
    "dyenamics_maroon": ("Dyenamics 적갈색", "적갈색"),
    "dyenamics_mint": ("Dyenamics 민트색", "민트색"),
    "dyenamics_navy": ("Dyenamics 남색", "남색"),
    "dyenamics_peach": ("Dyenamics 복숭아색", "복숭아색"),
    "dyenamics_persimmon": ("Dyenamics 감색", "감색"),
    "dyenamics_rose": ("Dyenamics 장미색", "장미색"),
    "dyenamics_spring_green": ("Dyenamics 봄 초록색", "봄 초록색"),
    "dyenamics_ultramarine": ("Dyenamics 울트라마린색", "울트라마린색"),
    "dyenamics_wine": ("Dyenamics 와인색", "와인색"),
    "gray": ("회색", "회색"),
    "green": ("초록색", "초록색"),
    "light_blue": ("하늘색", "하늘색"),
    "light_gray": ("회백색", "회백색"),
    "lime": ("연두색", "연두색"),
    "magenta": ("자홍색", "자홍색"),
    "orange": ("주황색", "주황색"),
    "pink": ("분홍색", "분홍색"),
    "purple": ("보라색", "보라색"),
    "red": ("빨간색", "빨간색"),
    "white": ("하얀색", "하얀색"),
    "yellow": ("노란색", "노란색"),
}


def build_dragons_plus_overrides() -> dict[str, str]:
    """검수한 색상 표와 기능 문장으로 Dragons Plus 전체 언어를 만든다."""
    fixed = {
        "block.create_dragons_plus.dragon_breath": "용의 숨결",
        "block.create_dragons_plus.dragon_breath_cauldron": "용의 숨결 가마솥",
        "block.create_dragons_plus.fluid_hatch": "유체 해치",
        "block.create_dragons_plus.fluid_hatch.tooltip.behaviour1": "설치된 _탱크_에 _손에 든 아이템_의 _유체를 넣습니다_. 아이템을 비울 수 없으면 반대로 _탱크_에서 아이템을 _채웁니다_.",
        "block.create_dragons_plus.fluid_hatch.tooltip.behaviour2": "먼저 _탱크_에서 _손에 든 유체 용기_를 _채웁니다_. 채울 수 없으면 반대로 용기의 유체를 _탱크_에 _넣습니다_.",
        "block.create_dragons_plus.fluid_hatch.tooltip.condition1": "우클릭 시",
        "block.create_dragons_plus.fluid_hatch.tooltip.condition2": "웅크리고 우클릭 시",
        "block.create_dragons_plus.fluid_hatch.tooltip.summary": "_유체 용기_로 _탱크_와 _간편하게 상호작용_할 수 있습니다.",
        "block.create_dragons_plus.fragile_fluid_tank": "깨지기 쉬운 유체 탱크",
        "block.create_dragons_plus.levitite_fragile_fluid_tank": "레비타이트 깨지기 쉬운 유체 탱크",
        "create.item_attributes.create_dragons_plus.aether_enchantable": "대량 마법 부여 가능",
        "create.item_attributes.create_dragons_plus.aether_enchantable.inverted": "대량 마법 부여 불가",
        "create.item_attributes.create_dragons_plus.endable": "엔딩 가능",
        "create.item_attributes.create_dragons_plus.endable.inverted": "엔딩 불가",
        "create.item_attributes.create_dragons_plus.freezable": "냉동 가능",
        "create.item_attributes.create_dragons_plus.freezable.inverted": "냉동 불가",
        "create.item_attributes.create_dragons_plus.sandable": "사포질 가능",
        "create.item_attributes.create_dragons_plus.sandable.inverted": "사포질 불가",
        "create.item_attributes.create_dragons_plus.stainable": "염색 가능",
        "create.item_attributes.create_dragons_plus.stainable.inverted": "염색 불가",
        "create_dragons_plus.fragile_fluid_tank.effect.dragon_breath": "주변 생명체에 용의 숨결 피해를 줍니다",
        "create_dragons_plus.fragile_fluid_tank.effect.dye": "주변 개체와 호환되는 블록을 물들입니다",
        "create_dragons_plus.fragile_fluid_tank.effect.explosive": "충돌 시 폭발합니다",
        "create_dragons_plus.fragile_fluid_tank.effect.header": "충돌 효과",
        "create_dragons_plus.fragile_fluid_tank.effect.lava": "블록에 불을 붙이고 불을 퍼뜨리며 범위 안의 개체를 태웁니다",
        "create_dragons_plus.fragile_fluid_tank.effect.milk": "범위 안의 물약 효과를 제거합니다",
        "create_dragons_plus.fragile_fluid_tank.effect.none": "특별한 충돌 효과가 없습니다",
        "create_dragons_plus.fragile_fluid_tank.effect.potion": "범위 안에 담긴 물약 효과를 적용합니다",
        "create_dragons_plus.fragile_fluid_tank.effect.tea": "주변 생명체에 성급함을 부여합니다",
        "create_dragons_plus.fragile_fluid_tank.effect.water": "불을 끄고 지원되는 블록에 수분을 공급하거나 식힙니다",
        "create_dragons_plus.ponder.air_current_interact_with_block.header": "가상 장치의 대량 가공 바람",
        "create_dragons_plus.ponder.air_current_interact_with_block.text_1": "가상 장치에서 나온 대량 가공 바람은 블록에 영향을 줄 수 있습니다",
        "create_dragons_plus.ponder.air_current_interact_with_block.text_2": "새 플레이어가 실수로 건물을 태우지 않도록 '대량 제련 바람이 불을 퍼뜨림' 설정은 기본적으로 꺼져 있습니다",
        "create_dragons_plus.ponder.bulk_coloring.header": "대량 염색",
        "create_dragons_plus.ponder.bulk_coloring.text_1": "액체 염료를 통과한 바람은 염색 가공 장치를 만듭니다",
        "create_dragons_plus.ponder.bulk_coloring.text_2": "대량 제련 및 대량 훈연처럼 대량 염색도 염료를 사용하는 일부 조합법과 자동으로 호환됩니다",
        "create_dragons_plus.ponder.bulk_coloring.text_3": "염색 바람은 개체의 색도 바꿀 수 있습니다.",
        "create_dragons_plus.ponder.bulk_coloring.text_4": "착용한 방어구도 염색됩니다.",
        "create_dragons_plus.ponder.bulk_enchanting.header": "대량 마법 부여",
        "create_dragons_plus.ponder.bulk_enchanting.text_1": "황금 에어클라우드를 통과한 바람은 대량 마법 부여 장치를 만듭니다",
        "create_dragons_plus.ponder.bulk_enchanting.text_2": "대량 마법 부여는 팬 가공으로 The Aether 마법 부여기 조합법을 처리합니다",
        "create_dragons_plus.ponder.bulk_enchanting.text_3": "일부 조합법은 장비의 내구도를 수리하므로 입력과 출력이 같은 아이템일 수 있습니다",
        "create_dragons_plus.ponder.bulk_enchanting.text_4": "같은 바람으로 모아 알을 아이템 가공하듯 부화시킬 수도 있습니다",
        "create_dragons_plus.ponder.bulk_ending.header": "대량 엔딩",
        "create_dragons_plus.ponder.bulk_ending.text_1": "드래곤 머리 또는 용의 숨결을 통과한 바람은 엔딩 가공 장치를 만듭니다",
        "create_dragons_plus.ponder.bulk_freezing.header": "대량 냉동",
        "create_dragons_plus.ponder.bulk_freezing.text_1": "가루눈을 통과한 바람은 냉동 가공 장치를 만듭니다",
        "create_dragons_plus.ponder.bulk_sanding.header": "대량 사포질",
        "create_dragons_plus.ponder.bulk_sanding.text_1": "대량 사포질 촉매(예: 유사)를 통과한 바람은 사포질 가공 장치를 만듭니다",
        "create_dragons_plus.ponder.bulk_sanding.text_2": "대량 제련 및 대량 훈연처럼 대량 사포질도 사포 조합법과 자동으로 호환됩니다",
        "create_dragons_plus.ponder.dragon_breath_fluid.header": "용의 숨결 유체",
        "create_dragons_plus.ponder.dragon_breath_fluid.text_1": "용의 숨결은 가마솥 동작을 지원합니다",
        "create_dragons_plus.ponder.dragon_breath_fluid.text_2": "흐르는 용의 숨결이 용암과 만나면 엔드 돌이 됩니다",
        "create_dragons_plus.ponder.dye_fluids.header": "액체 염료",
        "create_dragons_plus.ponder.dye_fluids.text_1": "염료와 물을 혼합하면 액체 염료가 됩니다",
        "create_dragons_plus.ponder.dye_fluids.text_2": "가열 혼합하면 유체에서 염료 아이템을 회수할 수 있습니다",
        "create_dragons_plus.ponder.dye_fluids.text_3": "액체 염료에 닿은 아이템과 생명체는 물듭니다",
        "create_dragons_plus.ponder.dye_fluids.text_4": "액체 염료가 용암과 만나면 같은 색의 콘크리트가 됩니다",
        "create_dragons_plus.ponder.fragile_fluid_tank.header": "깨지기 쉬운 유체 탱크",
        "create_dragons_plus.ponder.fragile_fluid_tank.text_1": "이 탱크는 깨지기 쉬워서 충돌하면 부서집니다",
        "create_dragons_plus.ponder.fragile_fluid_tank.text_2": "깨지기 쉬운 유체 탱크가 부서지면 주변에 유체 효과가 적용됩니다",
        "fluid.create_dragons_plus.dragon_breath": "용의 숨결",
        "item.create_dragons_plus.blaze_upgrade_smithing_template": "대장장이 형판",
        "item.create_dragons_plus.dragon_breath_bucket": "용의 숨결 양동이",
        "item.create_dragons_plus.smithing_template.blaze_upgrade.additions_slot_description": "블레이즈용 작업 블록을 추가하세요",
        "item.create_dragons_plus.smithing_template.blaze_upgrade.applies_to": "블레이즈 버너",
        "item.create_dragons_plus.smithing_template.blaze_upgrade.base_slot_description": "블레이즈 버너를 추가하세요",
        "item.create_dragons_plus.smithing_template.blaze_upgrade.ingredients": "블레이즈용 작업 블록",
        "itemGroup.create_dragons_plus.base": "Create: Dragons Plus",
        "pack.create_dragons_plus.runtime": "Create: Dragons Plus",
        "pack.create_dragons_plus.runtime.description": "Create: Dragons Plus 런타임 생성 리소스",
        "recipe.create_dragons_plus.aether_fan_enchanting": "대량 마법 부여",
        "recipe.create_dragons_plus.aether_fan_enchanting.fan": "황금 에어클라우드 뒤의 팬",
        "recipe.create_dragons_plus.aether_fan_enchanting.repairing": "아이템 내구도 수리",
        "recipe.create_dragons_plus.aether_fan_incubation": "대량 마법 부여 부화",
        "recipe.create_dragons_plus.aether_fan_incubation.entity": "생성 대상: %s",
        "recipe.create_dragons_plus.aether_fan_incubation.fan": "황금 에어클라우드 뒤의 팬",
        "recipe.create_dragons_plus.fan_coloring": "대량 염색",
        "recipe.create_dragons_plus.fan_coloring.fan": "액체 염료 뒤의 팬",
        "recipe.create_dragons_plus.fan_ending": "대량 엔딩",
        "recipe.create_dragons_plus.fan_ending.fan": "드래곤 머리 뒤의 팬",
        "recipe.create_dragons_plus.fan_freezing": "대량 냉동",
        "recipe.create_dragons_plus.fan_freezing.fan": "가루눈 뒤의 팬",
        "recipe.create_dragons_plus.fan_sanding": "대량 사포질",
        "recipe.create_dragons_plus.fan_sanding.fan": "유사 뒤의 팬",
        "tag.block.create_dragons_plus.fan_processing_catalysts.ending": "대량 엔딩 촉매",
        "tag.block.create_dragons_plus.fan_processing_catalysts.sanding": "대량 사포질 촉매",
        "tag.block.create_dragons_plus.not_applicable_for_polishing": "자동 광택 블록 사포질 조합법에 적용되지 않음",
        "tag.block.create_dragons_plus.passive_block_freezers": "수동 블록 냉동 촉매",
        "tag.fluid.c.dragon_breath": "용의 숨결",
        "tag.fluid.c.dyes": "염료",
        "tag.fluid.create_dragons_plus.fan_processing_catalysts.ending": "대량 엔딩 촉매",
        "tag.item.c.buckets.dragon_breath": "용의 숨결 양동이",
        "tag.item.c.buckets.dye": "염료 양동이",
        "tag.item.create_dragons_plus.not_applicable_for_coloring": "자동 염색 조합법에 적용되지 않음",
        "upgrade.create_dragons_plus.blaze_upgrade": "블레이즈 업그레이드",
    }
    english = load_json(WORK_ROOT / "create_dragons_plus/en_us.json")
    translated = dict(fixed)
    for dye_id, (qualified_name, tag_name) in DRAGONS_PLUS_DYES.items():
        translated[f"block.create_dragons_plus.{dye_id}_dye"] = f"{qualified_name} 염료"
        translated[f"fluid.create_dragons_plus.{dye_id}_dye"] = f"{qualified_name} 염료"
        translated[f"item.create_dragons_plus.{dye_id}_dye_bucket"] = (
            f"{qualified_name} 염료 양동이"
        )
        translated[f"tag.fluid.c.dyes.{dye_id}"] = f"{tag_name} 염료"
        translated[f"tag.item.c.buckets.dye.{dye_id}"] = f"{tag_name} 염료 양동이"
    missing = sorted(set(english) - set(translated))
    extra = sorted(set(translated) - set(english))
    if missing or extra:
        raise KeyError(
            f"Dragons Plus 번역 범위 불일치: missing={missing}, extra={extra}"
        )
    return translated


OVERRIDES["create_dragons_plus"] = build_dragons_plus_overrides()


CEI_NEW: dict[str, str] = {
    "advancement.create_enchantment_industry.a_shower_experience": "경험치 샤워",
    "advancement.create_enchantment_industry.a_shower_experience.desc": "유체 파이프를 부수고 새어 나온 경험치를 뒤집어쓰세요\n§7(숨겨진 발전과제)",
    "advancement.create_enchantment_industry.assembly_aesthetics": "조립 미학",
    "advancement.create_enchantment_industry.assembly_aesthetics.desc": "인쇄기로 소포의 무늬를 바꾸세요",
    "advancement.create_enchantment_industry.blaze_enchantery": "블레이즈 마법 공학",
    "advancement.create_enchantment_industry.blaze_enchantery.desc": "블레이즈는 물만 끓이지 않습니다. 블레이즈 마법 부여기를 얻으세요",
    "advancement.create_enchantment_industry.blazing_centurion": "불타는 백인대장",
    "advancement.create_enchantment_industry.blazing_centurion.desc": "블레이즈 단조기를 1,000번 사용하세요",
    "advancement.create_enchantment_industry.blazing_enchantment": "불타는 마법 부여",
    "advancement.create_enchantment_industry.blazing_enchantment.desc": "블레이즈 마법 부여기로 마법이 없는 아이템에 마법을 부여하세요",
    "advancement.create_enchantment_industry.blazing_fusion": "불타는 융합",
    "advancement.create_enchantment_industry.blazing_fusion.desc": "블레이즈 단조기로 같은 아이템 두 개를 합치세요",
    "advancement.create_enchantment_industry.born_talent_of_fire": "불의 타고난 재능",
    "advancement.create_enchantment_industry.born_talent_of_fire.desc": "블레이즈는 이 일을 위해 태어났습니다. 블레이즈 단조기를 얻으세요",
    "advancement.create_enchantment_industry.brand_registry": "상표 등록",
    "advancement.create_enchantment_industry.brand_registry.desc": "인쇄기로 아이템의 이름을 바꾸세요",
    "advancement.create_enchantment_industry.copiable_masterpiece": "복사 가능한 걸작",
    "advancement.create_enchantment_industry.copiable_masterpiece.desc": "인쇄기로 쓰인 책을 복사하세요",
    "advancement.create_enchantment_industry.copiable_mystery": "복사 가능한 신비",
    "advancement.create_enchantment_industry.copiable_mystery.desc": "인쇄기로 마법이 부여된 책을 복사하세요",
    "advancement.create_enchantment_industry.experienced_engineer": "경험 많은 기술자",
    "advancement.create_enchantment_industry.experienced_engineer.desc": "경험치 조각을 얻으세요",
    "advancement.create_enchantment_industry.experienced_recycler": "경험 많은 재활용가",
    "advancement.create_enchantment_industry.experienced_recycler.desc": "기계식 숫돌로 액체 경험치 1,000,000 mB를 얻으세요",
    "advancement.create_enchantment_industry.gone_with_the_foil": "광택과 함께 사라지다",
    "advancement.create_enchantment_industry.gone_with_the_foil.desc": "마법이 부여된 아이템이 기계식 숫돌에서 마법 해제되는 모습을 보세요",
    "advancement.create_enchantment_industry.great_publisher": "위대한 출판업자",
    "advancement.create_enchantment_industry.great_publisher.desc": "인쇄기를 1,000번 사용하세요",
    "advancement.create_enchantment_industry.grind_to_polish": "갈아서 윤내기",
    "advancement.create_enchantment_industry.grind_to_polish.desc": "사포라고요? 더 좋은 게 있습니다",
    "advancement.create_enchantment_industry.legacy_ignition": "과거의 불꽃",
    "advancement.create_enchantment_industry.legacy_ignition.desc": "지난 시대의 물건입니다. 클래식 블레이즈 마법 부여기를 얻으세요",
    "advancement.create_enchantment_industry.lightning_catalysis": "번개 촉매",
    "advancement.create_enchantment_industry.lightning_catalysis.desc": "슈퍼 경험치를 얻으세요",
    "advancement.create_enchantment_industry.lumen_nexus": "빛의 중심",
    "advancement.create_enchantment_industry.lumen_nexus.desc": "경험치 랜턴을 얻으세요",
    "advancement.create_enchantment_industry.magic_unbinding": "마법 분리",
    "advancement.create_enchantment_industry.magic_unbinding.desc": "블레이즈 단조기로 아이템에서 마법을 떼어 내세요",
    "advancement.create_enchantment_industry.omni_enchanter": "전능한 마법 부여사",
    "advancement.create_enchantment_industry.omni_enchanter.desc": "놀랍습니다! 슈퍼 마법 부여를 1,000번 했어요! 이제 숫자가 모든 걸 말해 줍니다",
    "advancement.create_enchantment_industry.osha_violation": "산업 안전 규정 위반",
    "advancement.create_enchantment_industry.osha_violation.desc": "이런 일이 일어나게 두면 안 됐습니다!!!\n§7(숨겨진 발전과제)",
    "advancement.create_enchantment_industry.paradox_fusion": "역설적 융합",
    "advancement.create_enchantment_industry.paradox_fusion.desc": "어떻게 가능한 거죠? 둘은 동시에 나타나면 안 되는데요!",
    "advancement.create_enchantment_industry.probability_spike": "확률 급등",
    "advancement.create_enchantment_industry.probability_spike.desc": "이 보물들은 대체 어디서 나온 걸까요?",
    "advancement.create_enchantment_industry.root": "Create: Enchantment Industry에 오신 것을 환영합니다",
    "advancement.create_enchantment_industry.root.desc": "마법 부여의 달인이 되는 길이 시작됩니다",
    "advancement.create_enchantment_industry.sigil_casting": "인장 새기기",
    "advancement.create_enchantment_industry.sigil_casting.desc": "블레이즈 단조기로 마법 부여 형판을 적용하세요",
    "advancement.create_enchantment_industry.sigil_forging": "인장 단조",
    "advancement.create_enchantment_industry.sigil_forging.desc": "블레이즈 마법 부여기로 마법 부여 형판에 새 마법을 추가하세요",
    "advancement.create_enchantment_industry.spirit_taking": "영혼 담기",
    "advancement.create_enchantment_industry.spirit_taking.desc": "경험치 해치로 경험치를 보관하세요",
    "advancement.create_enchantment_industry.spiritual_return": "영혼 되찾기",
    "advancement.create_enchantment_industry.spiritual_return.desc": "경험치 해치로 경험치를 꺼내세요",
    "advancement.create_enchantment_industry.supply_chain_refactor": "공급망 개편",
    "advancement.create_enchantment_industry.supply_chain_refactor.desc": "인쇄기로 소포의 주소를 바꾸세요",
    "advancement.create_enchantment_industry.thousand_runes": "천 개의 룬",
    "advancement.create_enchantment_industry.thousand_runes.desc": "블레이즈 마법 부여기를 1,000번 사용하세요",
    "advancement.create_enchantment_industry.thousandfold_everchant": "천 번의 영원한 마법",
    "advancement.create_enchantment_industry.thousandfold_everchant.desc": "클래식 블레이즈 마법 부여기로 1,000번 마법을 부여하세요",
    "advancement.create_enchantment_industry.transcendent_overclock": "초월적 오버클럭",
    "advancement.create_enchantment_industry.transcendent_overclock.desc": "어떻게 가능한 거죠? 마법 레벨 상한이 사라졌다고요?",
    "block.create_enchantment_industry.blaze_composer": "블레이즈 조율기",
    "block.create_enchantment_industry.blaze_enchanter": "블레이즈 마법 부여기",
    "block.create_enchantment_industry.blaze_forger": "블레이즈 단조기",
    "block.create_enchantment_industry.brass_bookshelf": "황동 책장",
    "block.create_enchantment_industry.classic_blaze_enchanter": "클래식 블레이즈 마법 부여기",
    "block.create_enchantment_industry.creative_bookshelf": "크리에이티브 책장",
    "block.create_enchantment_industry.crystal_essence": "수정 정수",
    "block.create_enchantment_industry.ender_woven_bag": "엔더 직조 가방",
    "block.create_enchantment_industry.experience": "액체 경험치",
    "block.create_enchantment_industry.experience_hatch": "경험치 해치",
    "block.create_enchantment_industry.experience_lantern": "경험치 랜턴",
    "block.create_enchantment_industry.grindstone_drain": "숫돌 배수구",
    "block.create_enchantment_industry.infused_dragon_breath": "주입된 드래곤의 숨결",
    "block.create_enchantment_industry.infuser": "주입기",
    "block.create_enchantment_industry.mechanical_grindstone": "기계식 숫돌",
    "block.create_enchantment_industry.printer": "인쇄기",
    "block.create_enchantment_industry.super_experience_block": "슈퍼 경험치 블록",
    "create.item_attributes.create_enchantment_industry.can_be_infused": "주입 가능",
    "create.item_attributes.create_enchantment_industry.can_be_infused.inverted": "주입 불가",
    "create.item_attributes.create_enchantment_industry.can_be_salvaged": "분해 가능",
    "create.item_attributes.create_enchantment_industry.can_be_salvaged.inverted": "분해 불가",
    "create.item_attributes.create_enchantment_industry.gem_purity": "%1$s 순도의 보석임",
    "create.item_attributes.create_enchantment_industry.gem_purity.inverted": "%1$s 순도의 보석이 아님",
    "create.item_attributes.create_enchantment_industry.has_empty_socket": "빈 소켓이 있음",
    "create.item_attributes.create_enchantment_industry.has_empty_socket.inverted": "빈 소켓이 없음",
    "create.item_attributes.create_enchantment_industry.has_gem": "보석이 소켓에 장착됨",
    "create.item_attributes.create_enchantment_industry.has_gem.inverted": "소켓에 장착된 보석이 없음",
    "create.item_attributes.create_enchantment_industry.is_upgradable_gem": "업그레이드 가능한 보석임",
    "create.item_attributes.create_enchantment_industry.is_upgradable_gem.inverted": "업그레이드 가능한 보석이 아님",
    "create.item_attributes.create_enchantment_industry.processable_by_mechanical_grindstone": "기계식 숫돌로 처리 가능",
    "create.item_attributes.create_enchantment_industry.processable_by_mechanical_grindstone.inverted": "기계식 숫돌로 처리 불가",
    "create_enchantment_industry.bookshelf.type.arcana": "아르카나",
    "create_enchantment_industry.bookshelf.type.eterna": "이터나",
    "create_enchantment_industry.bookshelf.type.quanta": "퀀타",
    "create_enchantment_industry.gui.blaze_composer.mode": "블레이즈 조율기: %1$s",
    "create_enchantment_industry.gui.blaze_composer.mode.apply": "적용",
    "create_enchantment_industry.gui.blaze_composer.mode.extract": "추출",
    "create_enchantment_industry.gui.blaze_composer.mode.merge": "병합",
    "create_enchantment_industry.gui.blaze_composer.mode_selector": "조율 모드",
    "create_enchantment_industry.gui.blaze_composer.super_mode.normal": "일반",
    "create_enchantment_industry.gui.blaze_composer.super_mode.super": "슈퍼",
    "create_enchantment_industry.gui.blaze_enchanter.blaze_mode.normal": "일반",
    "create_enchantment_industry.gui.blaze_enchanter.blaze_mode.super": "슈퍼",
    "create_enchantment_industry.gui.blaze_enchanter.level": "마법 부여 레벨",
    "create_enchantment_industry.gui.blaze_enchanter.mode.direct": "직접",
    "create_enchantment_industry.gui.blaze_enchanter.mode.template": "형판",
    "create_enchantment_industry.gui.blaze_enchanter.template.invalid": "이 아이템은 형판으로 사용할 수 없습니다.",
    "create_enchantment_industry.gui.blaze_forger.blaze_mode.normal": "일반",
    "create_enchantment_industry.gui.blaze_forger.blaze_mode.super": "슈퍼",
    "create_enchantment_industry.gui.blaze_forger.mode.apply": "적용",
    "create_enchantment_industry.gui.blaze_forger.mode.extract": "추출",
    "create_enchantment_industry.gui.blaze_forger.mode.merge": "병합",
    "create_enchantment_industry.gui.blaze_forger.mode_selector": "단조 모드",
    "create_enchantment_industry.gui.bookshelf.stat_type": "능력치 종류",
    "create_enchantment_industry.gui.bookshelf.stat_value": "능력치 값",
    "create_enchantment_industry.gui.experience_hatch.all": "전부",
    "create_enchantment_industry.gui.experience_hatch.exchange": "경험치 교환",
    "create_enchantment_industry.gui.experience_hatch.points": "포인트",
    "create_enchantment_industry.gui.goggles.blaze_experience.experience": "액체 경험치",
    "create_enchantment_industry.gui.goggles.blaze_experience.super_experience": "슈퍼 액체 경험치",
    "create_enchantment_industry.gui.goggles.bookshelf.allow_treasure": " - 보물 마법 허용",
    "create_enchantment_industry.gui.goggles.bookshelf.inactive": " (비활성)",
    "create_enchantment_industry.gui.goggles.captured_mob": "포획한 몹:",
    "create_enchantment_industry.gui.goggles.classic_enchanting.available_target": "사용 가능한 마법 부여 대상:",
    "create_enchantment_industry.gui.goggles.classic_enchanting.available_targets": "사용 가능한 마법 부여 대상:",
    "create_enchantment_industry.gui.goggles.enchanting.available_targets": "사용 가능한 마법:",
    "create_enchantment_industry.gui.goggles.enchanting.available_targets.more": "...외 %1$s개",
    "create_enchantment_industry.gui.goggles.enchanting.blaze_mode": "블레이즈 모드: %1$s",
    "create_enchantment_industry.gui.goggles.enchanting.blocked_super_penalty": "번개 경로가 막힘: 슈퍼 마법 부여 결과에 저주가 붙을 수 있습니다.",
    "create_enchantment_industry.gui.goggles.enchanting.completed": "마법 부여 완료!",
    "create_enchantment_industry.gui.goggles.enchanting.cost": "마법 부여 시 소모: %1$s",
    "create_enchantment_industry.gui.goggles.enchanting.insufficient_experience": "액체 경험치 부족: %1$s / %2$s",
    "create_enchantment_industry.gui.goggles.enchanting.insufficient_super_experience": "슈퍼 액체 경험치 부족: %1$s / %2$s",
    "create_enchantment_industry.gui.goggles.enchanting.invalid_item": "마법을 부여할 수 없는 아이템입니다!",
    "create_enchantment_industry.gui.goggles.enchanting.level": "마법 부여 레벨: %1$s",
    "create_enchantment_industry.gui.goggles.enchanting.level.not_set": "마법 부여 레벨이 설정되지 않았습니다!",
    "create_enchantment_industry.gui.goggles.enchanting.mode": "마법 부여 모드: %1$s",
    "create_enchantment_industry.gui.goggles.enchanting.mode_help.direct": "선택한 마법 부여 레벨로 호환되는 아이템에 무작위 마법을 부여합니다.",
    "create_enchantment_industry.gui.goggles.enchanting.mode_help.template": "형판 아이템에 맞는 마법 하나를 빈 마법 부여 형판에 기록합니다.",
    "create_enchantment_industry.gui.goggles.enchanting.requires": "필요한 입력:",
    "create_enchantment_industry.gui.goggles.enchanting.requires.direct": "마법을 부여할 수 있는 아이템 또는 책",
    "create_enchantment_industry.gui.goggles.enchanting.requires.template": "현재 블레이즈 모드와 일치하는 빈 마법 부여 형판",
    "create_enchantment_industry.gui.goggles.enchanting.template": "사용할 마법 부여 형판:",
    "create_enchantment_industry.gui.goggles.forging.blaze_mode": "블레이즈 모드: %1$s",
    "create_enchantment_industry.gui.goggles.forging.blocked_super_penalty": "번개 경로가 막힘: 슈퍼 단조 시 결과의 수리 비용이 증가합니다.",
    "create_enchantment_industry.gui.goggles.forging.completed": "단조 완료!",
    "create_enchantment_industry.gui.goggles.forging.conflicting": "결과에 원래 함께 붙을 수 없는 마법이 포함되어 있습니다.",
    "create_enchantment_industry.gui.goggles.forging.cost": "단조 시 소모: %1$s",
    "create_enchantment_industry.gui.goggles.forging.failure.apply_requires_enchanted_addition": "적용 모드의 두 번째 입력에는 마법이 부여된 책이나 마법이 든 형판이 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.apply_requires_target_item": "적용 모드에는 마법을 받을 수 있는 아이템이 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.curse_extraction_requires_super_mode": "저주만 남았습니다. 저주를 추출하려면 슈퍼 모드가 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.enchantment_cannot_apply": "두 번째 입력의 마법 중 첫 번째 입력에 적용할 수 있는 것이 없습니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.merge_requires_filled_templates": "병합 모드에는 마법이 든 형판 두 개가 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.merge_requires_matching_carriers": "병합 모드에는 서로 맞는 마법 운반체 또는 같은 장비 두 개가 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.missing_first_input": "첫 번째 입력이 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.missing_second_input": "두 번째 입력이 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.normal_template_requires_normal_mode": "일반 마법 부여 형판은 일반 모드에서 처리해야 합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.requires_blank_template": "추출 모드의 두 번째 입력에는 빈 마법 부여 형판이 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.requires_enchanted_addition": "두 번째 입력에 저장된 마법이 없습니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.requires_filled_template": "이 작업에는 마법이 든 형판이 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.source_has_no_enchantments": "첫 번째 입력에 추출할 마법이 없습니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.source_has_no_extractable_enchantments": "첫 번째 입력에서 추출할 수 있는 마법이 없습니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.super_template_requires_super_mode": "슈퍼 마법 부여 형판은 슈퍼 모드에서 처리해야 합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.template_type_mismatch": "두 형판의 종류가 같아야 합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.would_not_improve": "이 조합으로는 결과가 향상되지 않습니다.",
    "create_enchantment_industry.gui.goggles.forging.insufficient_experience": "액체 경험치 부족: %1$s / %2$s",
    "create_enchantment_industry.gui.goggles.forging.insufficient_super_experience": "슈퍼 액체 경험치 부족: %1$s / %2$s",
    "create_enchantment_industry.gui.goggles.forging.invalid_items": "단조 아이템 조합이 잘못되었습니다!",
    "create_enchantment_industry.gui.goggles.forging.invalid_template_type.normal": "일반 마법 부여 형판은 슈퍼 마법 부여 모드에서 사용할 수 없습니다!",
    "create_enchantment_industry.gui.goggles.forging.invalid_template_type.special": "슈퍼 마법 부여 형판을 사용하려면 슈퍼 마법 부여 모드가 필요합니다!",
    "create_enchantment_industry.gui.goggles.forging.lost_enchantments": "손실된 마법:",
    "create_enchantment_industry.gui.goggles.forging.lost_reason.cannot_apply_to_item": "%1$s에 적용할 수 없음",
    "create_enchantment_industry.gui.goggles.forging.lost_reason.incompatible_with_output": "%1$s와 충돌함",
    "create_enchantment_industry.gui.goggles.forging.lost_reason.would_not_improve": "결과가 향상되지 않음",
    "create_enchantment_industry.gui.goggles.forging.mode": "단조 모드: %1$s",
    "create_enchantment_industry.gui.goggles.forging.mode_help.apply": "마법이 부여된 책이나 마법이 든 형판을 대상 아이템에 적용합니다.",
    "create_enchantment_industry.gui.goggles.forging.mode_help.extract": "아이템, 책 또는 형판에서 마법 하나를 추출해 빈 마법 부여 형판에 담습니다.",
    "create_enchantment_industry.gui.goggles.forging.mode_help.merge": "서로 맞는 마법 운반체, 책, 형판 또는 같은 장비를 합칩니다.",
    "create_enchantment_industry.gui.goggles.forging.output_blocked": "다른 작업을 시작하기 전에 단조 결과를 꺼내세요.",
    "create_enchantment_industry.gui.goggles.forging.over_cap": "결과가 기본 마법 레벨 상한을 넘습니다.",
    "create_enchantment_industry.gui.goggles.forging.rejected_enchantments": "거부된 마법:",
    "create_enchantment_industry.gui.goggles.forging.repair_cost_penalty": "수리 비용: %1$s -> %2$s",
    "create_enchantment_industry.gui.goggles.forging.requires": "필요한 입력:",
    "create_enchantment_industry.gui.goggles.forging.requires.apply.first": "호환되는 대상 아이템",
    "create_enchantment_industry.gui.goggles.forging.requires.apply.second": "마법이 부여된 책 또는 마법이 든 형판",
    "create_enchantment_industry.gui.goggles.forging.requires.extract.first": "마법이 있는 아이템, 책 또는 형판",
    "create_enchantment_industry.gui.goggles.forging.requires.extract.second": "빈 마법 부여 형판",
    "create_enchantment_industry.gui.goggles.forging.requires.first": "첫 번째: %1$s",
    "create_enchantment_industry.gui.goggles.forging.requires.merge.first": "마법 운반체 또는 수리 대상",
    "create_enchantment_industry.gui.goggles.forging.requires.merge.second": "서로 맞는 마법 운반체 또는 수리 재료",
    "create_enchantment_industry.gui.goggles.forging.requires.second": "두 번째: %1$s",
    "create_enchantment_industry.gui.goggles.forging.result": "단조 결과:",
    "create_enchantment_industry.gui.goggles.forging.result.lost_enchantment": "%1$s 손실: %2$s",
    "create_enchantment_industry.gui.goggles.forging.result.rejected_enchantment": "%1$s: %2$s",
    "create_enchantment_industry.gui.goggles.infuser.incorrect_liquid": "잘못된 주입 시약입니다!",
    "create_enchantment_industry.gui.goggles.no_captured_entity": "비어 있음",
    "create_enchantment_industry.gui.goggles.printer.banner_pattern": "현수막 무늬 인쇄:",
    "create_enchantment_industry.gui.goggles.printing": "인쇄 중:",
    "create_enchantment_industry.gui.goggles.printing.address": "주소 인쇄 중:",
    "create_enchantment_industry.gui.goggles.printing.copy": "복사 중:",
    "create_enchantment_industry.gui.goggles.printing.cost": "인쇄 비용: %1$s",
    "create_enchantment_industry.gui.goggles.printing.custom_name": "사용자 지정 이름 인쇄 중:",
    "create_enchantment_industry.gui.goggles.printing.incorrect_liquid": "잘못된 유체입니다!",
    "create_enchantment_industry.gui.goggles.printing.pattern": "소포 무늬 변경 중",
    "create_enchantment_industry.gui.goggles.printing.template": "사용할 인쇄 형판:",
    "create_enchantment_industry.gui.printer.banner_pattern.multiple_pattern": "이 현수막에는 복사할 무늬가 여러 개 있습니다.",
    "create_enchantment_industry.gui.printer.banner_pattern.no_pattern": "이 현수막에는 복사할 무늬가 없습니다.",
    "create_enchantment_industry.gui.printer.copy.invalid": "이 아이템에는 복사할 수 있는 내용이 없습니다.",
    "create_enchantment_industry.gui.printer.enchanted_book.all_denied": "이 책에는 복사할 수 있는 마법이 없습니다.",
    "create_enchantment_industry.gui.printer.enchanted_book.denied": "이 책에 복사할 수 없는 마법이 들어 있습니다.",
    "create_enchantment_industry.gui.printer.enchanted_book.invalid": "이 책에는 복사할 마법이 없습니다.",
    "create_enchantment_industry.gui.printer.written_book.invalid": "이 책에는 복사할 내용이 없습니다.",
    "create_enchantment_industry.ponder.blaze_enchanter.automate.header": "기계식 팔로 자동화하기",
    "create_enchantment_industry.ponder.blaze_enchanter.automate.text_1": "블레이즈 마법 부여기는 기계식 팔로 자동화할 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.automate.text_2": "기계식 팔로 마법을 부여할 아이템을 넣을 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.automate.text_3": "기계식 팔로 경험치 연료도 공급할 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.automate.text_4": "기계식 팔로 마법이 부여된 아이템과 유효하지 않은 아이템을 꺼낼 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.header": "블레이즈 마법 부여기 소개",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_1": "블레이즈 마법 부여기입니다. 마법 부여대처럼 작동합니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_10": "금 흉갑은 다이아몬드 흉갑보다 마법 부여 적성이 높아 비교적 더 좋은 마법이 붙습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_11": "하지만 마법 부여 레벨이 항상 높다고 좋은 것은 아닙니다. 너무 높으면 나타나지 않는 마법도 있습니다!",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_2": "액체 경험치를 공급해 활성화하세요",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_3": "마법을 부여하기 전에 패널에서 레벨을 설정해야 합니다. 기본 마법 부여대의 레벨 상한은 30입니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_4": "패널은 필터 슬롯이기도 합니다. 아이템을 든 채 슬롯을 우클릭하면 형판으로 지정되며, 이를 형판 마법 부여 모드라고 합니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_5": "형판 마법 부여 모드에서는 마법 부여 형판에 마법을 부여할 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_6": "형판 마법 부여 모드는 형판 아이템이 지원하는 마법만 만들 때 사용합니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_7": "예를 들어 필터 슬롯에 다이아몬드 흉갑을 놓으면 다이아몬드 흉갑용 마법만 생성됩니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_8": "빈 마법 부여 형판을 넣으면 앞서 설명한 마법이 형판에 추가됩니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_9": "재료와 형판 아이템의 종류에 따라 서로 다른 마법이 생성됩니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.header": "블레이즈 마법 부여기로 슈퍼 마법 부여하기",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_1": "블레이즈 마법 부여기에는 '배'가 두 개 있습니다. 마법 부여 케이크를 먹이면...",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_2": "...들끓기 시작하며 슈퍼 마법 부여 모드가 됩니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_3": "두 번째 탱크에는 파이프로 액체 경험치를 넣을 수 없습니다. 마법 부여 케이크 같은 적합한 슈퍼 경험치 아이템을 사용해야 합니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_4": "슈퍼 마법 부여 모드에서는 마법 레벨 상한이 크게 오르고 보물 마법도 만들 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_5": "슈퍼 마법 부여 모드에서는 슈퍼 마법 부여 형판만 처리합니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_6": "근처에 피뢰침을 설치하세요",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_7": "슈퍼 마법 부여는 번개를 일으킬 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_8": "블레이즈 마법 부여기를 블록으로 덮어 번개를 막을 수 있지만 저주가 붙을 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_9": "피뢰침이 없으면...",
    "create_enchantment_industry.ponder.blaze_forger.automate.header": "기계식 팔로 자동화하기",
    "create_enchantment_industry.ponder.blaze_forger.automate.text_1": "블레이즈 단조기는 기계식 팔로 자동화할 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.automate.text_2": "기계식 팔로 단조할 아이템을 넣을 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.automate.text_3": "기계식 팔로 경험치 연료도 공급할 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.automate.text_4": "기계식 팔로 단조된 아이템과 유효하지 않은 아이템을 꺼낼 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.intro.header": "블레이즈 단조기 소개",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_1": "블레이즈 단조기입니다. 모루처럼 작동합니다",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_2": "액체 경험치를 공급해 활성화하세요",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_3": "블레이즈 단조기는 모루처럼 같은 아이템의 마법을 합치지만 수리 비용이 들지 않습니다",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_4": "마법 부여 형판도 합칠 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_5": "옆면 패널에서 작업 모드를 바꿀 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_6": "적용 모드로 바꾸면 마법 부여 형판을 아이템에 적용할 수 있습니다!",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_7": "추출 모드로 바꾸면 장비, 책 또는 형판의 마법 하나를 빈 마법 부여 형판에 옮길 수 있습니다!",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.header": "블레이즈 단조기로 슈퍼 마법 부여하기",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_1": "블레이즈 단조기에는 '배'가 두 개 있습니다. 마법 부여 케이크를 먹이면...",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_2": "...들끓기 시작하며 슈퍼 마법 부여 모드가 됩니다",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_3": "두 번째 탱크에는 파이프로 액체 경험치를 넣을 수 없습니다. 마법 부여 케이크 같은 적합한 슈퍼 경험치 아이템을 사용해야 합니다",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_4": "슈퍼 마법 부여 모드에서는 마법을 합칠 때 기본 레벨 상한을 넘을 수 있고 서로 충돌하는 마법도 합칠 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_5": "슈퍼 마법 부여 모드에서는 슈퍼 마법 부여 형판만 처리하고 적용합니다",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_6": "근처에 피뢰침을 설치하세요",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_7": "슈퍼 마법 부여는 번개를 일으킬 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_8": "블레이즈 단조기를 블록으로 덮어 번개를 막을 수 있지만 수리 비용이 생길 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_9": "피뢰침이 없으면...",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.automate.header": "자동화하기",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.automate.text_1": "클래식 블레이즈 마법 부여기는 기계식 팔로 자동화할 수 있습니다. 마법을 부여할 아이템과 경험치 연료를 넣을 수 있습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.automate.text_2": "벨트로도 자동화할 수 있습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.automate.text_3": "경험치 연료는 벨트로 공급할 수 없습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.header": "클래식 블레이즈 마법 부여기 소개",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_1": "클래식 블레이즈 마법 부여기입니다. 지정한 마법 부여 형판에 따라 아이템에 계속 마법을 부여합니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_10": "슈퍼 마법 부여는 번개를 일으킬 수 있습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_11": "블록으로 덮어 번개를 막을 수 있지만 기존 마법의 레벨이 낮아질 수 있습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_2": "액체 경험치를 공급해 활성화하세요",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_3": "마법을 부여하기 전에 필터 슬롯에 마법 부여 형판을 설정해야 합니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_4": "형판의 마법이 아이템에 부여되며 형판이나 형판의 마법은 소모되지 않습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_5": "적용할 수 있는 마법이 여러 개면 하나가 무작위로 적용됩니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_6": "클래식 블레이즈 마법 부여기도 마법 부여 케이크를 먹여 같은 방식으로 슈퍼 마법 부여 모드에 들어갑니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_7": "슈퍼 마법 부여 모드에서는 슈퍼 마법 부여 형판만 사용할 수 있습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_8": "아이템에 같은 종류와 레벨의 마법이 이미 있으면 레벨이 하나 오르며 기본 마법 레벨 상한도 넘을 수 있습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_9": "근처에 피뢰침을 설치하세요",
    "create_enchantment_industry.ponder.ender_woven_bag.header": "엔더 직조 가방으로 몹 포획하기",
    "create_enchantment_industry.ponder.ender_woven_bag.text_1": "엔더 끈으로 만드는 장치인 엔더 직조 가방입니다",
    "create_enchantment_industry.ponder.ender_woven_bag.text_2": "주변 몹을 끌어당겨 포획합니다",
    "create_enchantment_industry.ponder.ender_woven_bag.text_3": "가방이 가득 차면 표시등이 켜집니다",
    "create_enchantment_industry.ponder.ender_woven_bag.text_4": "레드스톤 신호를 받으면 포획한 몹을 풀어 줍니다",
    "create_enchantment_industry.ponder.ender_woven_bag_on_contraption.header": "움직이는 장치에서 엔더 직조 가방 사용하기",
    "create_enchantment_industry.ponder.ender_woven_bag_on_contraption.text_1": "엔더 직조 가방은 움직이는 장치에서도 작동합니다",
    "create_enchantment_industry.ponder.ender_woven_bag_on_contraption.text_2": "움직이는 장치의 엔더 직조 가방이 레드스톤 블록을 향하면 포획한 몹을 풀어 줍니다",
    "create_enchantment_industry.ponder.experience.advance.header": "알아 두면 좋은 것",
    "create_enchantment_industry.ponder.experience.advance.text_1": "Enchantment Industry를 사용하기 전에 몇 가지를 더 알아야 합니다",
    "create_enchantment_industry.ponder.experience.advance.text_2": "경험치 블록은 이제 장식과 저장만을 위한 블록이 아닙니다. 나중에 필요합니다",
    "create_enchantment_industry.ponder.experience.advance.text_3": "마법 부여 형판과 슈퍼 경험치 블록을 만들려면 경험치 블록이 필요합니다",
    "create_enchantment_industry.ponder.experience.advance.text_4": "슈퍼 마법 부여 형판을 만드는 데 사용하는 슈퍼 경험치 블록입니다",
    "create_enchantment_industry.ponder.experience.advance.text_5": "블레이즈 마법 부여기",
    "create_enchantment_industry.ponder.experience.advance.text_6": "블레이즈 단조기",
    "create_enchantment_industry.ponder.experience.advance.text_7": "들끓는 블레이즈 단조기와 마법 부여기는 슈퍼 마법 부여 모드입니다",
    "create_enchantment_industry.ponder.experience.advance.text_8": "슈퍼 마법 부여를 사용하면 기존 마법 부여의 한계를 넘을 수 있습니다",
    "create_enchantment_industry.ponder.experience.advance.text_9": "기본 마법 레벨 상한을 넘고, 충돌하는 마법을 합치며, 보물 마법을 직접 얻을 수 있습니다",
    "create_enchantment_industry.ponder.experience.beacon_base_block.header": "신호기 기반 블록으로 사용하기",
    "create_enchantment_industry.ponder.experience.intro.header": "경험치 처리 소개",
    "create_enchantment_industry.ponder.experience.intro.text_1": "액체 경험치 탱크입니다. Enchantment Industry에서 경험치를 주로 다루는 형태입니다",
    "create_enchantment_industry.ponder.experience.intro.text_10": "주입구로 액체 경험치를 용기 아이템에 다시 채우세요",
    "create_enchantment_industry.ponder.experience.intro.text_11": "파이프에서 새어 나온 액체 경험치는 경험치 구슬이 됩니다",
    "create_enchantment_industry.ponder.experience.intro.text_2": "보유한 경험치를 액체로 바꾸려면 두 구성 요소가 필요합니다",
    "create_enchantment_industry.ponder.experience.intro.text_3": "아이템의 유체에 직접 접근하는 유체 해치",
    "create_enchantment_industry.ponder.experience.intro.text_4": "플레이어의 경험치에 직접 접근하는 경험치 해치",
    "create_enchantment_industry.ponder.experience.intro.text_5": "하지만 Create의 일부인 만큼 자동화가 빠질 수는 없겠죠?",
    "create_enchantment_industry.ponder.experience.intro.text_6": "아이템 배수구로 아이템에서 액체 경험치를 빼내세요",
    "create_enchantment_industry.ponder.experience.intro.text_7": "기계식 숫돌은 아이템도 분쇄합니다. 예를 들어 경험치 조각을 액체 경험치로 바꿀 수 있습니다",
    "create_enchantment_industry.ponder.experience.intro.text_8": "분쇄 바퀴에 새로운 기능이 생겼습니다. 생물을 처치하면 낮은 확률로 경험치 조각을 소량 떨어뜨립니다",
    "create_enchantment_industry.ponder.experience.intro.text_9": "배치기도 생물을 처치하면 경험치 조각을 떨어뜨립니다",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.header": "슈퍼 마법 부여 재료 준비하기",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_1": "먼저 슈퍼 마법 부여 형판의 재료인 슈퍼 경험치 블록을 얻으세요. 경험치 블록이 필요합니다",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_2": "다음으로 피뢰침을 설치하세요",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_3": "번개가 내리칩니다!",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_4": "대부분의 번개는 일정 확률로만 경험치 블록을 변환하지만 슈퍼 마법 부여로 생긴 번개는 반드시 변환합니다",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_5": "두 번째로 마법 부여 케이크를 얻으세요. '슈퍼 경험치'로 작동해 블레이즈를 슈퍼 마법 부여 모드로 만듭니다.",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_6": "마법 부여 케이크가 블레이즈를 슈퍼 마법 부여 모드로 만든다면 슈퍼 경험치 블록은 어디에 쓸까요?",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_7": "정답: 슈퍼 마법 부여 형판 제작",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_8": "슈퍼 마법 부여 모드의 블레이즈 단조기와 마법 부여기는 일반 형판을 받지 않으며 슈퍼 마법 부여 형판만 사용합니다",
    "create_enchantment_industry.ponder.experience_hatch.intro.header": "경험치 해치 소개",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_1": "경험치 해치는 사용하기 쉽습니다. 우클릭하면 경험치를 보관하고...",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_2": "...Shift를 누른 채 우클릭하면 보관된 경험치를 꺼냅니다",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_3": "해치에는 필터 슬롯과 스크롤 패널이 있습니다. 패널에서 상호작용 한 번에 넣거나 꺼낼 경험치 양을 설정할 수 있습니다",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_4": "필터 슬롯은 다른 모드의 경험치 유체를 다룰 때 사용합니다",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_5": "예를 들어 액체 청록색 염료가 다른 모드의 경험치 유체라고 가정해 봅시다",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_6": "필터 슬롯에 청록색 염료 양동이를 놓으세요",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_7": "이제 청록색 염료를 '청록색 경험치'로 직접 넣고 꺼낼 수 있습니다",
    "create_enchantment_industry.ponder.experience_lantern.intro.header": "경험치 랜턴 소개",
    "create_enchantment_industry.ponder.experience_lantern.intro.text_1": "경험치 랜턴은 주변 플레이어와 경험치 구슬의 경험치를 흡수합니다. 내부에 저장된 양에 따라 빛납니다",
    "create_enchantment_industry.ponder.experience_lantern.intro.text_2": "경험치 랜턴은 움직이는 장치에서도 작동합니다",
    "create_enchantment_industry.ponder.mechanical_grindstone.extra.header": "기계식 숫돌로 사포질하기",
    "create_enchantment_industry.ponder.mechanical_grindstone.extra.text_1": "기계식 숫돌은 숫돌의 모든 기능을 갖췄을 뿐만 아니라...",
    "create_enchantment_industry.ponder.mechanical_grindstone.extra.text_2": "...사포의 기능도 갖추고 있습니다",
    "create_enchantment_industry.ponder.mechanical_grindstone.extra.text_3": "아이템을 기계식 숫돌에 직접 사용할 수 있습니다",
    "create_enchantment_industry.ponder.mechanical_grindstone.intro.header": "기계식 숫돌 소개",
    "create_enchantment_industry.ponder.mechanical_grindstone.intro.text_1": "기계식 숫돌을 든 채 아이템 배수구를 우클릭하면...",
    "create_enchantment_industry.ponder.mechanical_grindstone.intro.text_2": "숫돌 배수구가 됩니다. 사용하려면 위에 기계식 숫돌을 하나 더 놓으세요",
    "create_enchantment_industry.ponder.mechanical_grindstone.intro.text_3": "아이템 형태의 경험치를 기계식 숫돌로 분쇄해 액체로 바꿀 수 있습니다",
    "create_enchantment_industry.ponder.printer.intro.header": "인쇄기 소개",
    "create_enchantment_industry.ponder.printer.intro.text_1": "인쇄기입니다",
    "create_enchantment_industry.ponder.printer.intro.text_2": "사용하기 전에 필터 슬롯에서 인쇄할 아이템을 설정하고...",
    "create_enchantment_industry.ponder.printer.intro.text_3": "...알맞은 유체를 공급하세요",
    "create_enchantment_industry.ponder.printer.intro.text_4": "쓰인 책 복사",
    "create_enchantment_industry.ponder.printer.intro.text_5": "소포 무늬 변경",
    "create_enchantment_industry.ponder.printer.intro.text_6": "마법이 부여된 책 복제",
    "create_enchantment_industry.ponder.printer.intro.text_7": "아이템 이름 지정, 열차 운행 일정 복사, 클립보드 복사, 소포 주소 변경 등도 할 수 있습니다. JEI에서 인쇄 조합법을 확인하세요",
    "create_enchantment_industry.ponder.tag.experience_appliances": "경험치 관련 장치",
    "create_enchantment_industry.ponder.tag.experience_appliances.description": "경험치를 처리하고 적용할 때 사용하는 구성 요소",
    "create_enchantment_industry.ponder.tag.super_experience_related": "슈퍼 경험치 관련 장치",
    "create_enchantment_industry.ponder.tag.super_experience_related.description": "슈퍼 경험치를 처리하고 적용할 때 사용하는 구성 요소",
    "create_enchantment_industry.recipe.assembly.grinding": "숫돌로 갈기",
    "create_enchantment_industry.recipe.assembly.grinding.needs_fluid": "숫돌로 갈기, %1$s 소모",
    "create_enchantment_industry.recipe.assembly.printing": "형판으로 인쇄: %1$s, %2$s 소모",
    "create_enchantment_industry.recipe.grinding": "분쇄",
    "create_enchantment_industry.recipe.infusing": "주입",
    "create_enchantment_industry.recipe.printing": "인쇄",
    "create_enchantment_industry.recipe.printing.banner_pattern.base": "아무 현수막",
    "create_enchantment_industry.recipe.printing.banner_pattern.color_follow_dye": "인쇄된 무늬의 색은 유체 염료를 따름",
    "create_enchantment_industry.recipe.printing.banner_pattern.template": "단일 현수막 무늬",
    "create_enchantment_industry.recipe.printing.copy.template": "복사 가능한 내용",
    "create_enchantment_industry.recipe.printing.custom_name.base": "모든 아이템 사용 가능",
    "create_enchantment_industry.recipe.printing.custom_name.template": "사용자 지정 이름",
    "death.attack.create_enchantment_industry.grind": "기계식 숫돌이 %1$s의 손을 날려 버렸습니다.",
    "fluid.create_enchantment_industry.infused_dragon_breath": "주입된 드래곤의 숨결",
    "item.create_enchantment_industry.blazes_enchanting_handbook": "블레이즈의 마법 부여 안내서",
    "item.create_enchantment_industry.crystal_essence_bucket": "수정 정수 양동이",
    "item.create_enchantment_industry.enchanting_template": "마법 부여 형판",
    "item.create_enchantment_industry.experience_bucket": "마법 부여 양동이",
    "item.create_enchantment_industry.experience_cake": "마법 부여 케이크",
    "item.create_enchantment_industry.experience_cake_base": "마법 부여 케이크 바탕",
    "item.create_enchantment_industry.experience_cake_slice": "마법 부여 케이크 조각",
    "item.create_enchantment_industry.incomplete_brass_bookshelf": "미완성 황동 책장",
    "item.create_enchantment_industry.infused_dragon_breath_bucket": "주입된 드래곤의 숨결 양동이",
    "item.create_enchantment_industry.super_enchanting_template": "슈퍼 마법 부여 형판",
    "item.create_enchantment_industry.super_experience_nugget": "슈퍼 경험치 조각",
    "itemGroup.create_enchantment_industry.base": "Create: Enchantment Industry",
    "stat.create_enchantment_industry.classic_enchant": "클래식 블레이즈 마법 부여기 사용",
    "stat.create_enchantment_industry.enchant": "블레이즈 마법 부여기 사용",
    "stat.create_enchantment_industry.forge": "블레이즈 단조기 사용",
    "stat.create_enchantment_industry.mechanical_grindstone_experience": "생산한 경험치(기계식 숫돌)",
    "stat.create_enchantment_industry.print": "인쇄기 사용",
    "stat.create_enchantment_industry.super_enchant": "슈퍼 마법 부여",
    "tag.block.create_enchantment_industry.fan_processing_catalysts.salvaging": "대량 분해 촉매",
    "tag.fluid.create_enchantment_industry.fan_processing_catalysts.salvaging": "대량 분해 촉매",
    "tag.fluid.create_enchantment_industry.infusing.ingredients": "주입 시약",
    "tag.item.create_enchantment_industry.blaze_composer.super_activators": "블레이즈 조율기 슈퍼 활성화 아이템",
}


def build_cei_overrides() -> dict[str, str]:
    """검수된 프로젝트 연동 번역을 보존하고 CEI 신규 원문을 직접 번역한다."""
    root = WORK_ROOT / "create_enchantment_industry"
    english = load_json(root / "en_us.json")
    korean = load_json(root / "ko_kr.json")
    sources = load_json(root / "candidate_sources.json")
    translated = {
        key: korean[key]
        for key, source_kind in sources.items()
        if source_kind == "project_output_review"
    }
    translated.update(CEI_NEW)
    missing = sorted(set(english) - set(translated))
    extra = sorted(set(translated) - set(english))
    if missing or extra:
        raise KeyError(
            f"Enchantment Industry 번역 범위 불일치: missing={missing}, extra={extra}"
        )
    return translated


OVERRIDES["create_enchantment_industry"] = build_cei_overrides()


ALLOWED_ORIGINALS = {
    "",
    ".",
    '"%1$s"',
    "%1$s: %2$s",
    "%1$s -> %2$s",
    "%1$s: %2$s -> %3$s",
    " - %1$s",
    "%1$s:%3$s %4$s",
    "> %1$s x%2$s",
    " >| %1$s",
    " >> %1$s (%2$sm)",
    " ; ",
    " ;0;1;2;3;4;5;6;7;8;9",
    " ;A;B;C;D;E;F;G;H;I;J;K;L;M;N;O;P;Q;R;S;T;U;V;X;Y;Z",
    " ;K;M",
    "█;▓;▒",
    "3:00",
    "4:00",
    "8 RPM",
    "12 RPM",
    "16 RPM",
    "32 RPM",
    "Alt",
    "B",
    "Create",
    "Create Crafts & Additions",
    "Create: Dragons Plus",
    "Create: Enchantment Industry",
    "killtps",
    "tickTime",
    "Ctrl",
    "F#;F;E;D#;D;C#;C;B;A#;A;G#;G",
    "K;M",
    "K⚡",
    "m",
    "mB",
    "mB;B ",
    "pm",
    "RPM",
    "Shift",
    "su",
    "am",
    "k",
    "°",
    "Bells & Whistles",
    "Create: Aquatic Ambitions",
    "Create: Hypertube",
}


def dump_json(path: Path, value: object) -> None:
    """UTF-8 JSON을 안정된 형식으로 기록한다."""
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def normalize() -> dict[str, object]:
    """검수가 끝난 소규모 네임스페이스와 본체 신규 키를 반영한다."""
    rows = []
    for namespace, overrides in OVERRIDES.items():
        root = WORK_ROOT / namespace
        english = load_json(root / "en_us.json")
        korean = load_json(root / "ko_kr.json")
        unknown = sorted(set(overrides) - set(english))
        if unknown:
            raise KeyError(f"{namespace} 원문에 없는 키: {unknown}")
        changed = 0
        for key, translated in overrides.items():
            errors = validate_value(key, english[key], translated)
            if errors:
                raise ValueError("; ".join(errors))
            if korean[key] != translated:
                korean[key] = translated
                changed += 1
        dump_json(root / "ko_kr.json", korean)
        rows.append(
            {
                "namespace": namespace,
                "keys": len(english),
                "reviewed_overrides": len(overrides),
                "changed": changed,
            }
        )
    return {"namespaces": rows}


def verify_selected() -> tuple[dict[str, object], list[str]]:
    """현재 완성 대상으로 선택한 네임스페이스의 미번역과 형식을 검사한다."""
    errors = []
    rows = []
    complete_namespaces = {
        "create",
        "createaddition",
        "create_hypertube",
        "bellsandwhistles",
        "create_aquatic_ambitions",
        "create_dragons_plus",
        "create_enchantment_industry",
    }
    for namespace in OVERRIDES:
        root = WORK_ROOT / namespace
        english = load_json(root / "en_us.json")
        korean = load_json(root / "ko_kr.json")
        if list(english) != list(korean):
            errors.append(f"키 또는 순서 불일치: {namespace}")
            continue
        untranslated = []
        for key, source in english.items():
            target = korean[key]
            errors.extend(validate_value(key, source, target))
            if source == target and source not in ALLOWED_ORIGINALS:
                untranslated.append(key)
        if namespace in complete_namespaces and untranslated:
            errors.append(f"미번역: {namespace}:{untranslated[:30]}")
        rows.append(
            {
                "namespace": namespace,
                "keys": len(english),
                "untranslated": len(untranslated),
                "complete": namespace in complete_namespaces and not untranslated,
            }
        )
    report = {
        "namespaces": rows,
        "errors": errors,
        "status": "complete" if not errors else "incomplete",
    }
    dump_json(WORK_ROOT / "selected_validation.json", report)
    return report, errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("normalize", "verify-selected"))
    args = parser.parse_args()
    if args.command == "normalize":
        report = normalize()
        errors = []
    else:
        report, errors = verify_selected()
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
