#!/usr/bin/env python3
"""Create 계열 언어 작업본을 단계별로 정규화하고 검증한다."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from five_family_goal import PROJECT_ROOT, load_json, validate_value

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

WORK_ROOT = PROJECT_ROOT / "working/create"

OVERRIDES = {
    "create": {
        "advancement.create.lava_wheel_00000.desc": "이런 게 작동해서는 안 되는데...\n§7(숨겨진 발전과제)",
        "block.create.andesite_belt_funnel": "안산암 벨트 깔때기",
        "block.create.andesite_funnel": "안산암 깔때기",
        "block.create.brass_belt_funnel": "황동 벨트 깔때기",
        "block.create.brass_casing": "황동 케이싱",
        "block.create.brass_funnel": "황동 깔때기",
        "block.create.chain_conveyor": "체인 컨베이어",
        "block.create.cherry_window": "벚나무 창",
        "block.create.cherry_window_pane": "벚나무 창유리판",
        "block.create.deployer": "배치기",
        "block.create.depot": "보관소",
        "block.create.gearshift": "기어변환기",
        "block.create.hand_crank": "손 크랭크",
        "block.create.mechanical_arm": "기계식 팔",
        "block.create.mechanical_bearing": "기계식 베어링",
        "block.create.mechanical_crafter": "기계식 조합기",
        "block.create.mechanical_drill": "기계식 드릴",
        "block.create.mechanical_harvester": "기계식 수확기",
        "block.create.mechanical_mixer": "기계식 혼합기",
        "block.create.mechanical_plough": "기계식 쟁기",
        "block.create.mechanical_press": "기계식 압착기",
        "block.create.mechanical_pump": "기계식 펌프",
        "block.create.mechanical_saw": "기계식 톱",
        "block.create.package_frogport": "소포 개구리항",
        "block.create.schematic_table.tooltip.behaviour1": "설계도 폴더에서 선택한 파일을 업로드합니다.",
        "block.create.sequenced_gearshift": "순차 기어변환기",
        "block.create.spout": "주입구",
        "block.create.steam_engine": "증기 기관",
        "block.create.stock_link": "재고 연결기",
        "block.create.stock_ticker": "재고 표시기",
        "block.create.track_observer": "열차 감지기",
        "block.create.weighted_ejector": "무게 추 달린 배출기",
        "create.command.killTPSCommand.status.usage.1": "[Create]: /killtps start <tickTime> 명령어를 사용해 서버 틱을 인위적으로 늦추세요",
        "create.gui.pojav.title": "Create는 PojavLauncher를 지원하지 않습니다.",
        "create.gui.stock_ticker.shift_moves_bottom": "Shift 키를 누르면 맨 아래로 이동",
        "create.gui.stock_ticker.shift_moves_top": "Shift 키를 누르면 맨 위로 이동",
        "create.item_attributes.color": "%1$s색으로 염색됨",
        "create.item_attributes.color.inverted": "%1$s색으로 염색되지 않음",
        "create.gui.stock_keeper.click_to_cycle": "클릭하여 전환",
        "create.gui.stock_keeper.jei_sync.none": "동기화 안 함",
        "create.gui.stock_keeper.jei_sync.none.description": "재고 관리자와 조합법 뷰어의 검색을 서로 독립적으로 유지합니다",
        "create.gui.stock_keeper.jei_sync.sync_both": "조합법 뷰어와 양방향 동기화",
        "create.gui.stock_keeper.jei_sync.sync_both.description": "재고 관리자와 조합법 뷰어의 검색을 서로 동기화합니다",
        "create.gui.stock_keeper.jei_sync.sync_from_jei": "조합법 뷰어에서 동기화",
        "create.gui.stock_keeper.jei_sync.sync_from_jei.description": "조합법 뷰어의 검색을 재고 관리자에 반영합니다",
        "create.gui.stock_keeper.jei_sync.sync_from_stock_keeper": "재고 관리자에서 동기화",
        "create.gui.stock_keeper.jei_sync.sync_from_stock_keeper.description": "재고 관리자의 검색을 조합법 뷰어에 반영합니다",
        "create.keyinfo.alt_modifier": "Alt 보조 키",
        "create.keyinfo.ctrl_modifier": "Ctrl 보조 키",
        "create.keyinfo.shift_modifier": "Shift 보조 키",
        "item.create.schematic_and_quill.tooltip.behaviour1": "_우클릭_으로 _두 꼭짓점_을 선택하세요. _Ctrl_을 누른 채 스크롤하면 허공의 위치를 선택할 수 있습니다.",
        "item.create.schematic_and_quill.tooltip.summary": "세계의 _구조물을_ _.nbt 파일_로 _저장_할 때 사용합니다.",
        "item.create.belt_connector": "기계식 벨트",
        "item.create.goggles": "기술자의 고글",
        "item.create.linked_controller.tooltip.behaviour2": "수동 _설정_ _창_을 엽니다.",
        "tag.item.c.foods.dough.wheat": "밀 반죽",
    },
    "createaddition": {
        "createaddition.tooltip.liquid_burning.info": "액체 블레이즈 버너 정보:",
        "createaddition.tooltip.liquid_burning.time_remaining": "남은 연소 시간:",
        "createaddition.tooltip.charging.info": "테슬라 코일 정보:",
        "createaddition.tooltip.charging.time_remaining": "남은 충전 시간:",
        "createaddition.tooltip.alternator.info": "교류 발전기 정보:",
        "item.createaddition.diamond_grit_sandpaper.tooltip.condition1": "사용 시",
        "item.createaddition.diamond_grit_sandpaper.tooltip.summary": "재료를 _연마_하는 데 사용합니다. 배치기로 자동화할 수 있습니다.",
        "item.createaddition.diamond_grit_sandpaper.tooltip.behaviour1": "_보조 손_에 들고 있거나 _바닥_에 놓인 아이템을 _바라보며_ 사용하면 광택을 냅니다",
        "item.createaddition.copper_spool.tooltip.summary": "전선을 보관하는 데 사용합니다.",
        "item.createaddition.festive_spool.tooltip.summary": "전선을 보관하는 데 사용합니다.",
        "item.createaddition.gold_spool.tooltip.summary": "전선을 보관하는 데 사용합니다.",
        "item.createaddition.electrum_spool.tooltip.summary": "전선을 보관하는 데 사용합니다.",
        "item.createaddition.spool.tooltip.summary": "전선을 보관하는 데 사용합니다.",
        "item.createaddition.brass_figurine": "황동 조각상",
        "item.createaddition.brass_figurine.tooltip": "황동 조각상",
        "item.createaddition.brass_figurine.tooltip.summary": ".",
        "item.createaddition.copper_goblet": "구리 잔",
        "item.createaddition.copper_goblet.tooltip": "구리 잔",
        "item.createaddition.copper_goblet.tooltip.summary": "이 _잔_의 뛰어난 열전도 능력은 가장 필요할 때 몸을 시원하게 해 줍니다.",
        "item.createaddition.gold_goblet": "화려한 잔",
        "item.createaddition.gold_goblet.tooltip": "화려한 잔",
        "item.createaddition.gold_goblet.tooltip.summary": "이 _잔_으로 마시면 평범한 병보다 갈증을 더 많이 해소합니다.",
        "block.createaddition.electrum_block": "일렉트럼 블록",
        "block.createaddition.modular_accumulator": "모듈식 축전지",
        "createaddition.display_source.digital_adapter_source_digital_adapter": "디지털 어댑터",
        "createaddition.subtitle.loud_zap": "테슬라 코일이 큰 전기 충격을 냄",
        "createaddition.subtitle.little_zap": "테슬라 코일에서 전기 불꽃이 튐",
        "createaddition.schedule.condition.threshold.unit": "K⚡",
    },
    "create_hypertube": {
        "itemGroup.create_hypertube": "Create: Hypertube",
        "subtitles.create_hypertube.chose_direction": "방향 선택",
        "subtitles.create_hypertube.entrance_open": "하이퍼튜브 입구 열림",
        "subtitles.create_hypertube.entrance_close": "하이퍼튜브 입구 닫힘",
        "placement.create_hypertube.no_valid_points": "두 위치를 모두 지정해야 합니다",
        "block.hypertube.hyper_entrance.manual_lock": "수동 잠금 모드",
        "block.hypertube.hyper_entrance.automatic_lock": "자동 잠금 모드",
        "item.create_hypertube.hypertube_funnel": "하이퍼튜브 깔때기",
        "create_hypertube.ponder.simple_tube.text_1": "다른 튜브를 든 채 하이퍼튜브를 우클릭하고...",
        "create_hypertube.ponder.simple_tube.text_2": "...두 번째 하이퍼튜브를 설치하면...",
        "create_hypertube.ponder.simple_tube.text_3": "...하이퍼튜브가 연결됩니다!",
        "create_hypertube.ponder.entrance.text_1": "하이퍼튜브 입구를 하이퍼튜브 네트워크에 연결하면 빠르게 이동할 수 있습니다.",
        "create_hypertube.ponder.entrance.text_2": "하이퍼튜브에 들어가려면 입구에 최소 16 RPM의 회전력을 공급해야 합니다.",
        "create_hypertube.ponder.accelerator.text_2": "가속기를 우클릭하면 감속 모드로 전환할 수 있습니다.",
        "create_hypertube.ponder.attachments.text_1": "스캐너 부착물은 하이퍼튜브로 이동하는 개체를 감지합니다. 신호 세기는 아기일 때 8, 성체일 때 15입니다.",
        "create_hypertube.ponder.attachments.text_2": "가속기의 어느 면에든 여러 부착물을 동시에 설치할 수 있습니다.",
        "create_hypertube.ponder.attachments.text_3": "레드스톤 감지 부착물을 사용하면 레드스톤 신호로 가속기 또는 입구의 모드를 바꿀 수 있습니다.",
        "block.create_hypertube.hypertube_junction": "하이퍼튜브 분기기",
    },
    "bellsandwhistles": {
        "block.bellsandwhistles.andesite_grab_rails": "안산암 손잡이",
        "block.bellsandwhistles.brass_grab_rails": "황동 손잡이",
        "block.bellsandwhistles.copper_grab_rails": "구리 손잡이",
        "block.bellsandwhistles.andesite_bogie_steps": "안산암 발판",
        "block.bellsandwhistles.brass_bogie_steps": "황동 발판",
        "block.bellsandwhistles.copper_bogie_steps": "구리 발판",
        "block.bellsandwhistles.andesite_door_step": "안산암 문 발판",
        "block.bellsandwhistles.brass_door_step": "황동 문 발판",
        "block.bellsandwhistles.copper_door_step": "구리 문 발판",
        "block.bellsandwhistles.headlight": "전조등",
        "block.bellsandwhistles.ornate_iron_trapdoor": "장식된 철 다락문",
        "block.bellsandwhistles.station_platform": "역 승강장",
        "block.bellsandwhistles.metro_casing": "지하철 케이싱",
        "block.bellsandwhistles.corrugated_metro_casing": "골판형 지하철 케이싱",
        "block.bellsandwhistles.metro_panel": "지하철 패널",
        "block.bellsandwhistles.corrugated_metro_panel": "골판형 지하철 패널",
        "block.bellsandwhistles.metro_window": "지하철 창",
        "block.bellsandwhistles.metro_trapdoor": "지하철 다락문",
        "block.bellsandwhistles.metal_pilot": "금속 배장기",
        "block.bellsandwhistles.andesite_pilot": "안산암 배장기",
        "block.bellsandwhistles.brass_pilot": "황동 배장기",
        "block.bellsandwhistles.copper_pilot": "구리 배장기",
        "block.bellsandwhistles.polished_andesite_pilot": "윤나는 안산암 배장기",
        "block.bellsandwhistles.polished_asurine_pilot": "윤나는 담청암 배장기",
        "block.bellsandwhistles.polished_calcite_pilot": "윤나는 방해석 배장기",
        "block.bellsandwhistles.polished_crimsite_pilot": "윤나는 진홍암 배장기",
        "block.bellsandwhistles.polished_deepslate_pilot": "윤나는 심층암 배장기",
        "block.bellsandwhistles.polished_diorite_pilot": "윤나는 섬록암 배장기",
        "block.bellsandwhistles.polished_dripstone_pilot": "윤나는 점적석 배장기",
        "block.bellsandwhistles.polished_granite_pilot": "윤나는 화강암 배장기",
        "block.bellsandwhistles.polished_limestone_pilot": "윤나는 석회암 배장기",
        "block.bellsandwhistles.polished_ochrum_pilot": "윤나는 황토암 배장기",
        "block.bellsandwhistles.polished_scorchia_pilot": "윤나는 그을린 스코리아 배장기",
        "block.bellsandwhistles.polished_scoria_pilot": "윤나는 스코리아 배장기",
        "block.bellsandwhistles.polished_tuff_pilot": "윤나는 응회암 배장기",
        "block.bellsandwhistles.polished_veridium_pilot": "윤나는 심록암 배장기",
        "itemGroup.bellsandwhistlestab": "Bells & Whistles",
        "creativetab.bellsandwhistlestab": "Bells & Whistles",
        "creativetab.bellsandwhistles.bells_and_whistles": "Bells & Whistles",
    },
    "create_aquatic_ambitions": {
        "itemGroup.create_aquatic_ambitions": "Create: Aquatic Ambitions",
        "block.create_aquatic_ambitions.mechanical_conduit": "전달체 케이지",
        "block.create_aquatic_ambitions.prismarine_alloy_block": "프리즈머린 합금 블록",
        "item.create_aquatic_ambitions.prismarine_alloy": "프리즈머린 합금",
        "item.create_aquatic_ambitions.prismarine_alloy_rod": "프리즈머린 합금 막대기",
        "item.create_aquatic_ambitions.nautilus_shard": "앵무조개 파편",
        "item.create_aquatic_ambitions.suspicious_rock": "수상한 바위",
        "item.create_aquatic_ambitions.spiky_shell": "가시 돋친 껍데기",
        "item.create_aquatic_ambitions.calcium_rich_powder": "칼슘이 풍부한 가루",
        "recipe.create_aquatic_ambitions.fan_channeling": "전달체 활성화",
        "recipe.create_aquatic_ambitions.fan_channeling.fan": "전달체 활성화",
        "create_aquatic_ambitions.tooltip.conduitcage.header": "전달체 케이지 정보",
        "tooltip.create_aquatic_ambitions.effect.cleansing": "정화",
        "tooltip.create_aquatic_ambitions.effect.burning": "연소",
        "create.item_attributes.can_be_channeled": "전달체로 처리 가능",
        "create_aquatic_ambitions.mechanical_conduit.entity_filter.title": "개체 필터",
        "mechanical_conduit.selection_mode.everyone": "모두",
        "mechanical_conduit.selection_mode.players": "플레이어",
        "mechanical_conduit.selection_mode.friendly_mobs": "우호적 몹",
        "mechanical_conduit.selection_mode.players_friendly_mobs": "플레이어와 우호적 몹",
        "mechanical_conduit.selection_mode.monsters": "몬스터",
        "create_aquatic_ambitions.ponder.conduit_processing.header": "전달체 장치로 아이템 처리",
        "create_aquatic_ambitions.ponder.conduit_processing.text_1": "각성한 전달체를 선풍기 가공에 사용할 수 있습니다.",
        "create_aquatic_ambitions.ponder.conduit_processing.text_2": "전달체의 물을 통과한 바람은 활성화 가공 장치를 만듭니다.",
        "create_aquatic_ambitions.ponder.conduit_processing.text_3": "물층을 더 쌓으면 전달체의 힘이 약해져 대신 세척 가공 장치가 됩니다.",
        "create_aquatic_ambitions.ponder.conduit_processing.text_4": "활성화 흐름에 닿은 아이템이 처리됩니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_awaken.header": "전달체 케이지 깨우기",
        "create_aquatic_ambitions.ponder.mechanical_conduit_awaken.text_1": "전달체 케이지는 전달체의 프리즈머린 고리를 더 작게 대신할 수 있습니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_awaken.text_2": "아래쪽 면을 통해 전달체 케이지로 유체를 공급할 수 있습니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_awaken.text_3": "전달체 케이지에 유체를 공급하면 케이지가 깨어납니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_processing.header": "전달체 케이지로 아이템 처리",
        "create_aquatic_ambitions.ponder.mechanical_conduit_processing.text_1": "전달체 케이지도 선풍기 가공에 사용할 수 있습니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_processing.text_2": "전달체 케이지를 통과한 바람은 활성화 가공 장치를 만듭니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_processing.text_3": "활성화 흐름에 닿은 아이템이 처리됩니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_effects.header": "전달체 케이지로 효과 부여",
        "create_aquatic_ambitions.ponder.mechanical_conduit_effects.text_1": "각성한 전달체 케이지는 주변 개체에 영향을 줄 수 있습니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_effects.text_2": "물로 깨운 전달체 케이지는 전달체의 힘 효과를 부여합니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_effects.text_3": "다른 유체는 서로 다른 효과를 부여합니다.",
        "create_aquatic_ambitions.ponder.mechanical_conduit_effects.text_4": "모드 슬롯에서 영향을 받을 개체를 선택할 수 있습니다.",
    },
}


DRAGONS_PLUS_DYES = {
    "arts_and_crafts_bleached": ("Arts and Crafts 표백색", "블리치듀"),
    "black": ("검은색", "검은색"),
    "blue": ("파란색", "파란색"),
    "brown": ("갈색", "갈색"),
    "cyan": ("청록색", "청록색"),
    "dye_depot_amber": ("Dye Depot 호박색", "호박색"),
    "dye_depot_aqua": ("Dye Depot 물색", "물색"),
    "dye_depot_beige": ("Dye Depot 베이지색", "베이지색"),
    "dye_depot_coral": ("Dye Depot 산호색", "산호색"),
    "dye_depot_forest": ("Dye Depot 숲색", "숲색"),
    "dye_depot_ginger": ("Dye Depot 생강색", "생강색"),
    "dye_depot_indigo": ("Dye Depot 쪽빛", "쪽빛"),
    "dye_depot_maroon": ("Dye Depot 적갈색", "적갈색"),
    "dye_depot_mint": ("Dye Depot 민트색", "민트색"),
    "dye_depot_navy": ("Dye Depot 남색", "남색"),
    "dye_depot_olive": ("Dye Depot 올리브색", "올리브색"),
    "dye_depot_rose": ("Dye Depot 장미색", "장미색"),
    "dye_depot_slate": ("Dye Depot 슬레이트색", "슬레이트색"),
    "dye_depot_tan": ("Dye Depot 황갈색", "황갈색"),
    "dye_depot_teal": ("Dye Depot 틸색", "틸색"),
    "dye_depot_verdant": ("Dye Depot 진초록색", "진초록색"),
    "dyenamics_amber": ("Dyenamics 호박색", "호박색"),
    "dyenamics_aquamarine": ("Dyenamics 아쿠아마린색", "아쿠아마린색"),
    "dyenamics_bubblegum": ("Dyenamics 풍선껌색", "풍선껌색"),
    "dyenamics_cherenkov": ("Dyenamics 체렌코프색", "체렌코프색"),
    "dyenamics_conifer": ("Dyenamics 침엽수색", "침엽수색"),
    "dyenamics_fluorescent": ("Dyenamics 형광색", "형광색"),
    "dyenamics_honey": ("Dyenamics 꿀색", "꿀색"),
    "dyenamics_icy_blue": ("Dyenamics 얼음빛 파란색", "얼음빛 파란색"),
    "dyenamics_lavender": ("Dyenamics 라벤더색", "라벤더색"),
    "dyenamics_maroon": ("Dyenamics 적갈색", "적갈색"),
    "dyenamics_mint": ("Dyenamics 민트색", "민트색"),
    "dyenamics_navy": ("Dyenamics 남색", "남색"),
    "dyenamics_peach": ("Dyenamics 복숭아색", "복숭아색"),
    "dyenamics_persimmon": ("Dyenamics 감색", "감색"),
    "dyenamics_rose": ("Dyenamics 장미색", "장미색"),
    "dyenamics_spring_green": ("Dyenamics 봄 초록색", "봄 초록색"),
    "dyenamics_ultramarine": ("Dyenamics 울트라마린색", "울트라마린색"),
    "dyenamics_wine": ("Dyenamics 와인색", "와인색"),
    "gray": ("회색", "회색"),
    "green": ("초록색", "초록색"),
    "light_blue": ("하늘색", "하늘색"),
    "light_gray": ("회백색", "회백색"),
    "lime": ("연두색", "연두색"),
    "magenta": ("자홍색", "자홍색"),
    "orange": ("주황색", "주황색"),
    "pink": ("분홍색", "분홍색"),
    "purple": ("보라색", "보라색"),
    "red": ("빨간색", "빨간색"),
    "white": ("하얀색", "하얀색"),
    "yellow": ("노란색", "노란색"),
}


def build_dragons_plus_overrides() -> dict[str, str]:
    """검수한 색상 표와 기능 문장으로 Dragons Plus 전체 언어를 만든다."""
    fixed = {
        "block.create_dragons_plus.dragon_breath": "용의 숨결",
        "block.create_dragons_plus.dragon_breath_cauldron": "용의 숨결 가마솥",
        "block.create_dragons_plus.fluid_hatch": "유체 해치",
        "block.create_dragons_plus.fluid_hatch.tooltip.behaviour1": "설치된 _탱크_에 _손에 든 아이템_의 _유체를 넣습니다_. 아이템을 비울 수 없으면 반대로 _탱크_에서 아이템을 _채웁니다_.",
        "block.create_dragons_plus.fluid_hatch.tooltip.behaviour2": "먼저 _탱크_에서 _손에 든 유체 용기_를 _채웁니다_. 채울 수 없으면 반대로 용기의 유체를 _탱크_에 _넣습니다_.",
        "block.create_dragons_plus.fluid_hatch.tooltip.condition1": "우클릭 시",
        "block.create_dragons_plus.fluid_hatch.tooltip.condition2": "웅크리고 우클릭 시",
        "block.create_dragons_plus.fluid_hatch.tooltip.summary": "_유체 용기_로 _탱크_와 _간편하게 상호작용_할 수 있습니다.",
        "block.create_dragons_plus.fragile_fluid_tank": "깨지기 쉬운 유체 탱크",
        "block.create_dragons_plus.levitite_fragile_fluid_tank": "레비타이트 깨지기 쉬운 유체 탱크",
        "create.item_attributes.create_dragons_plus.aether_enchantable": "대량 마법 부여 가능",
        "create.item_attributes.create_dragons_plus.aether_enchantable.inverted": "대량 마법 부여 불가",
        "create.item_attributes.create_dragons_plus.endable": "엔딩 가능",
        "create.item_attributes.create_dragons_plus.endable.inverted": "엔딩 불가",
        "create.item_attributes.create_dragons_plus.freezable": "냉동 가능",
        "create.item_attributes.create_dragons_plus.freezable.inverted": "냉동 불가",
        "create.item_attributes.create_dragons_plus.sandable": "사포질 가능",
        "create.item_attributes.create_dragons_plus.sandable.inverted": "사포질 불가",
        "create.item_attributes.create_dragons_plus.stainable": "염색 가능",
        "create.item_attributes.create_dragons_plus.stainable.inverted": "염색 불가",
        "create_dragons_plus.fragile_fluid_tank.effect.dragon_breath": "주변 생명체에 용의 숨결 피해를 줍니다",
        "create_dragons_plus.fragile_fluid_tank.effect.dye": "주변 개체와 호환되는 블록을 물들입니다",
        "create_dragons_plus.fragile_fluid_tank.effect.explosive": "충돌 시 폭발합니다",
        "create_dragons_plus.fragile_fluid_tank.effect.header": "충돌 효과",
        "create_dragons_plus.fragile_fluid_tank.effect.lava": "블록에 불을 붙이고 불을 퍼뜨리며 범위 안의 개체를 태웁니다",
        "create_dragons_plus.fragile_fluid_tank.effect.milk": "범위 안의 물약 효과를 제거합니다",
        "create_dragons_plus.fragile_fluid_tank.effect.none": "특별한 충돌 효과가 없습니다",
        "create_dragons_plus.fragile_fluid_tank.effect.potion": "범위 안에 담긴 물약 효과를 적용합니다",
        "create_dragons_plus.fragile_fluid_tank.effect.tea": "주변 생명체에 성급함을 부여합니다",
        "create_dragons_plus.fragile_fluid_tank.effect.water": "불을 끄고 지원되는 블록에 수분을 공급하거나 식힙니다",
        "create_dragons_plus.ponder.air_current_interact_with_block.header": "가상 장치의 대량 가공 바람",
        "create_dragons_plus.ponder.air_current_interact_with_block.text_1": "가상 장치에서 나온 대량 가공 바람은 블록에 영향을 줄 수 있습니다",
        "create_dragons_plus.ponder.air_current_interact_with_block.text_2": "새 플레이어가 실수로 건물을 태우지 않도록 '대량 제련 바람이 불을 퍼뜨림' 설정은 기본적으로 꺼져 있습니다",
        "create_dragons_plus.ponder.bulk_coloring.header": "대량 염색",
        "create_dragons_plus.ponder.bulk_coloring.text_1": "액체 염료를 통과한 바람은 염색 가공 장치를 만듭니다",
        "create_dragons_plus.ponder.bulk_coloring.text_2": "대량 제련 및 대량 훈연처럼 대량 염색도 염료를 사용하는 일부 조합법과 자동으로 호환됩니다",
        "create_dragons_plus.ponder.bulk_coloring.text_3": "염색 바람은 개체의 색도 바꿀 수 있습니다.",
        "create_dragons_plus.ponder.bulk_coloring.text_4": "착용한 방어구도 염색됩니다.",
        "create_dragons_plus.ponder.bulk_enchanting.header": "대량 마법 부여",
        "create_dragons_plus.ponder.bulk_enchanting.text_1": "황금 에어클라우드를 통과한 바람은 대량 마법 부여 장치를 만듭니다",
        "create_dragons_plus.ponder.bulk_enchanting.text_2": "대량 마법 부여는 팬 가공으로 The Aether 마법 부여기 조합법을 처리합니다",
        "create_dragons_plus.ponder.bulk_enchanting.text_3": "일부 조합법은 장비의 내구도를 수리하므로 입력과 출력이 같은 아이템일 수 있습니다",
        "create_dragons_plus.ponder.bulk_enchanting.text_4": "같은 바람으로 모아 알을 아이템 가공하듯 부화시킬 수도 있습니다",
        "create_dragons_plus.ponder.bulk_ending.header": "대량 엔딩",
        "create_dragons_plus.ponder.bulk_ending.text_1": "드래곤 머리 또는 용의 숨결을 통과한 바람은 엔딩 가공 장치를 만듭니다",
        "create_dragons_plus.ponder.bulk_freezing.header": "대량 냉동",
        "create_dragons_plus.ponder.bulk_freezing.text_1": "가루눈을 통과한 바람은 냉동 가공 장치를 만듭니다",
        "create_dragons_plus.ponder.bulk_sanding.header": "대량 사포질",
        "create_dragons_plus.ponder.bulk_sanding.text_1": "대량 사포질 촉매(예: 유사)를 통과한 바람은 사포질 가공 장치를 만듭니다",
        "create_dragons_plus.ponder.bulk_sanding.text_2": "대량 제련 및 대량 훈연처럼 대량 사포질도 사포 조합법과 자동으로 호환됩니다",
        "create_dragons_plus.ponder.dragon_breath_fluid.header": "용의 숨결 유체",
        "create_dragons_plus.ponder.dragon_breath_fluid.text_1": "용의 숨결은 가마솥 동작을 지원합니다",
        "create_dragons_plus.ponder.dragon_breath_fluid.text_2": "흐르는 용의 숨결이 용암과 만나면 엔드 돌이 됩니다",
        "create_dragons_plus.ponder.dye_fluids.header": "액체 염료",
        "create_dragons_plus.ponder.dye_fluids.text_1": "염료와 물을 혼합하면 액체 염료가 됩니다",
        "create_dragons_plus.ponder.dye_fluids.text_2": "가열 혼합하면 유체에서 염료 아이템을 회수할 수 있습니다",
        "create_dragons_plus.ponder.dye_fluids.text_3": "액체 염료에 닿은 아이템과 생명체는 물듭니다",
        "create_dragons_plus.ponder.dye_fluids.text_4": "액체 염료가 용암과 만나면 같은 색의 콘크리트가 됩니다",
        "create_dragons_plus.ponder.fragile_fluid_tank.header": "깨지기 쉬운 유체 탱크",
        "create_dragons_plus.ponder.fragile_fluid_tank.text_1": "이 탱크는 깨지기 쉬워서 충돌하면 부서집니다",
        "create_dragons_plus.ponder.fragile_fluid_tank.text_2": "깨지기 쉬운 유체 탱크가 부서지면 주변에 유체 효과가 적용됩니다",
        "fluid.create_dragons_plus.dragon_breath": "용의 숨결",
        "item.create_dragons_plus.blaze_upgrade_smithing_template": "대장장이 형판",
        "item.create_dragons_plus.dragon_breath_bucket": "용의 숨결 양동이",
        "item.create_dragons_plus.smithing_template.blaze_upgrade.additions_slot_description": "블레이즈용 작업 블록을 추가하세요",
        "item.create_dragons_plus.smithing_template.blaze_upgrade.applies_to": "블레이즈 버너",
        "item.create_dragons_plus.smithing_template.blaze_upgrade.base_slot_description": "블레이즈 버너를 추가하세요",
        "item.create_dragons_plus.smithing_template.blaze_upgrade.ingredients": "블레이즈용 작업 블록",
        "itemGroup.create_dragons_plus.base": "Create: Dragons Plus",
        "pack.create_dragons_plus.runtime": "Create: Dragons Plus",
        "pack.create_dragons_plus.runtime.description": "Create: Dragons Plus 런타임 생성 리소스",
        "recipe.create_dragons_plus.aether_fan_enchanting": "대량 마법 부여",
        "recipe.create_dragons_plus.aether_fan_enchanting.fan": "황금 에어클라우드 뒤의 팬",
        "recipe.create_dragons_plus.aether_fan_enchanting.repairing": "아이템 내구도 수리",
        "recipe.create_dragons_plus.aether_fan_incubation": "대량 마법 부여 부화",
        "recipe.create_dragons_plus.aether_fan_incubation.entity": "생성 대상: %s",
        "recipe.create_dragons_plus.aether_fan_incubation.fan": "황금 에어클라우드 뒤의 팬",
        "recipe.create_dragons_plus.fan_coloring": "대량 염색",
        "recipe.create_dragons_plus.fan_coloring.fan": "액체 염료 뒤의 팬",
        "recipe.create_dragons_plus.fan_ending": "대량 엔딩",
        "recipe.create_dragons_plus.fan_ending.fan": "드래곤 머리 뒤의 팬",
        "recipe.create_dragons_plus.fan_freezing": "대량 냉동",
        "recipe.create_dragons_plus.fan_freezing.fan": "가루눈 뒤의 팬",
        "recipe.create_dragons_plus.fan_sanding": "대량 사포질",
        "recipe.create_dragons_plus.fan_sanding.fan": "유사 뒤의 팬",
        "tag.block.create_dragons_plus.fan_processing_catalysts.ending": "대량 엔딩 촉매",
        "tag.block.create_dragons_plus.fan_processing_catalysts.sanding": "대량 사포질 촉매",
        "tag.block.create_dragons_plus.not_applicable_for_polishing": "자동 광택 블록 사포질 조합법에 적용되지 않음",
        "tag.block.create_dragons_plus.passive_block_freezers": "수동 블록 냉동 촉매",
        "tag.fluid.c.dragon_breath": "용의 숨결",
        "tag.fluid.c.dyes": "염료",
        "tag.fluid.create_dragons_plus.fan_processing_catalysts.ending": "대량 엔딩 촉매",
        "tag.item.c.buckets.dragon_breath": "용의 숨결 양동이",
        "tag.item.c.buckets.dye": "염료 양동이",
        "tag.item.create_dragons_plus.not_applicable_for_coloring": "자동 염색 조합법에 적용되지 않음",
        "upgrade.create_dragons_plus.blaze_upgrade": "블레이즈 업그레이드",
    }
    english = load_json(WORK_ROOT / "create_dragons_plus/en_us.json")
    translated = dict(fixed)
    for dye_id, (qualified_name, tag_name) in DRAGONS_PLUS_DYES.items():
        translated[f"block.create_dragons_plus.{dye_id}_dye"] = f"{qualified_name} 염료"
        translated[f"fluid.create_dragons_plus.{dye_id}_dye"] = f"{qualified_name} 염료"
        translated[f"item.create_dragons_plus.{dye_id}_dye_bucket"] = (
            f"{qualified_name} 염료 양동이"
        )
        translated[f"tag.fluid.c.dyes.{dye_id}"] = f"{tag_name} 염료"
        translated[f"tag.item.c.buckets.dye.{dye_id}"] = f"{tag_name} 염료 양동이"
    missing = sorted(set(english) - set(translated))
    extra = sorted(set(translated) - set(english))
    if missing or extra:
        raise KeyError(
            f"Dragons Plus 번역 범위 불일치: missing={missing}, extra={extra}"
        )
    return translated


OVERRIDES["create_dragons_plus"] = build_dragons_plus_overrides()


CEI_NEW: dict[str, str] = {
    "advancement.create_enchantment_industry.a_shower_experience": "경험치 샤워",
    "advancement.create_enchantment_industry.a_shower_experience.desc": "유체 파이프를 부수고 새어 나온 경험치를 뒤집어쓰세요\n§7(숨겨진 발전과제)",
    "advancement.create_enchantment_industry.assembly_aesthetics": "조립 미학",
    "advancement.create_enchantment_industry.assembly_aesthetics.desc": "인쇄기로 소포의 무늬를 바꾸세요",
    "advancement.create_enchantment_industry.blaze_enchantery": "블레이즈 마법 공학",
    "advancement.create_enchantment_industry.blaze_enchantery.desc": "블레이즈는 물만 끓이지 않습니다. 블레이즈 마법 부여기를 얻으세요",
    "advancement.create_enchantment_industry.blazing_centurion": "불타는 백인대장",
    "advancement.create_enchantment_industry.blazing_centurion.desc": "블레이즈 단조기를 1,000번 사용하세요",
    "advancement.create_enchantment_industry.blazing_enchantment": "불타는 마법 부여",
    "advancement.create_enchantment_industry.blazing_enchantment.desc": "블레이즈 마법 부여기로 마법이 없는 아이템에 마법을 부여하세요",
    "advancement.create_enchantment_industry.blazing_fusion": "불타는 융합",
    "advancement.create_enchantment_industry.blazing_fusion.desc": "블레이즈 단조기로 같은 아이템 두 개를 합치세요",
    "advancement.create_enchantment_industry.born_talent_of_fire": "불의 타고난 재능",
    "advancement.create_enchantment_industry.born_talent_of_fire.desc": "블레이즈는 이 일을 위해 태어났습니다. 블레이즈 단조기를 얻으세요",
    "advancement.create_enchantment_industry.brand_registry": "상표 등록",
    "advancement.create_enchantment_industry.brand_registry.desc": "인쇄기로 아이템의 이름을 바꾸세요",
    "advancement.create_enchantment_industry.copiable_masterpiece": "복사 가능한 걸작",
    "advancement.create_enchantment_industry.copiable_masterpiece.desc": "인쇄기로 쓰인 책을 복사하세요",
    "advancement.create_enchantment_industry.copiable_mystery": "복사 가능한 신비",
    "advancement.create_enchantment_industry.copiable_mystery.desc": "인쇄기로 마법이 부여된 책을 복사하세요",
    "advancement.create_enchantment_industry.experienced_engineer": "경험 많은 기술자",
    "advancement.create_enchantment_industry.experienced_engineer.desc": "경험치 조각을 얻으세요",
    "advancement.create_enchantment_industry.experienced_recycler": "경험 많은 재활용가",
    "advancement.create_enchantment_industry.experienced_recycler.desc": "기계식 숫돌로 액체 경험치 1,000,000 mB를 얻으세요",
    "advancement.create_enchantment_industry.gone_with_the_foil": "광택과 함께 사라지다",
    "advancement.create_enchantment_industry.gone_with_the_foil.desc": "마법이 부여된 아이템이 기계식 숫돌에서 마법 해제되는 모습을 보세요",
    "advancement.create_enchantment_industry.great_publisher": "위대한 출판업자",
    "advancement.create_enchantment_industry.great_publisher.desc": "인쇄기를 1,000번 사용하세요",
    "advancement.create_enchantment_industry.grind_to_polish": "갈아서 윤내기",
    "advancement.create_enchantment_industry.grind_to_polish.desc": "사포라고요? 더 좋은 게 있습니다",
    "advancement.create_enchantment_industry.legacy_ignition": "과거의 불꽃",
    "advancement.create_enchantment_industry.legacy_ignition.desc": "지난 시대의 물건입니다. 클래식 블레이즈 마법 부여기를 얻으세요",
    "advancement.create_enchantment_industry.lightning_catalysis": "번개 촉매",
    "advancement.create_enchantment_industry.lightning_catalysis.desc": "슈퍼 경험치를 얻으세요",
    "advancement.create_enchantment_industry.lumen_nexus": "빛의 중심",
    "advancement.create_enchantment_industry.lumen_nexus.desc": "경험치 랜턴을 얻으세요",
    "advancement.create_enchantment_industry.magic_unbinding": "마법 분리",
    "advancement.create_enchantment_industry.magic_unbinding.desc": "블레이즈 단조기로 아이템에서 마법을 떼어 내세요",
    "advancement.create_enchantment_industry.omni_enchanter": "전능한 마법 부여사",
    "advancement.create_enchantment_industry.omni_enchanter.desc": "놀랍습니다! 슈퍼 마법 부여를 1,000번 했어요! 이제 숫자가 모든 걸 말해 줍니다",
    "advancement.create_enchantment_industry.osha_violation": "산업 안전 규정 위반",
    "advancement.create_enchantment_industry.osha_violation.desc": "이런 일이 일어나게 두면 안 됐습니다!!!\n§7(숨겨진 발전과제)",
    "advancement.create_enchantment_industry.paradox_fusion": "역설적 융합",
    "advancement.create_enchantment_industry.paradox_fusion.desc": "어떻게 가능한 거죠? 둘은 동시에 나타나면 안 되는데요!",
    "advancement.create_enchantment_industry.probability_spike": "확률 급등",
    "advancement.create_enchantment_industry.probability_spike.desc": "이 보물들은 대체 어디서 나온 걸까요?",
    "advancement.create_enchantment_industry.root": "Create: Enchantment Industry에 오신 것을 환영합니다",
    "advancement.create_enchantment_industry.root.desc": "마법 부여의 달인이 되는 길이 시작됩니다",
    "advancement.create_enchantment_industry.sigil_casting": "인장 새기기",
    "advancement.create_enchantment_industry.sigil_casting.desc": "블레이즈 단조기로 마법 부여 형판을 적용하세요",
    "advancement.create_enchantment_industry.sigil_forging": "인장 단조",
    "advancement.create_enchantment_industry.sigil_forging.desc": "블레이즈 마법 부여기로 마법 부여 형판에 새 마법을 추가하세요",
    "advancement.create_enchantment_industry.spirit_taking": "영혼 담기",
    "advancement.create_enchantment_industry.spirit_taking.desc": "경험치 해치로 경험치를 보관하세요",
    "advancement.create_enchantment_industry.spiritual_return": "영혼 되찾기",
    "advancement.create_enchantment_industry.spiritual_return.desc": "경험치 해치로 경험치를 꺼내세요",
    "advancement.create_enchantment_industry.supply_chain_refactor": "공급망 개편",
    "advancement.create_enchantment_industry.supply_chain_refactor.desc": "인쇄기로 소포의 주소를 바꾸세요",
    "advancement.create_enchantment_industry.thousand_runes": "천 개의 룬",
    "advancement.create_enchantment_industry.thousand_runes.desc": "블레이즈 마법 부여기를 1,000번 사용하세요",
    "advancement.create_enchantment_industry.thousandfold_everchant": "천 번의 영원한 마법",
    "advancement.create_enchantment_industry.thousandfold_everchant.desc": "클래식 블레이즈 마법 부여기로 1,000번 마법을 부여하세요",
    "advancement.create_enchantment_industry.transcendent_overclock": "초월적 오버클럭",
    "advancement.create_enchantment_industry.transcendent_overclock.desc": "어떻게 가능한 거죠? 마법 레벨 상한이 사라졌다고요?",
    "block.create_enchantment_industry.blaze_composer": "블레이즈 조율기",
    "block.create_enchantment_industry.blaze_enchanter": "블레이즈 마법 부여기",
    "block.create_enchantment_industry.blaze_forger": "블레이즈 단조기",
    "block.create_enchantment_industry.brass_bookshelf": "황동 책장",
    "block.create_enchantment_industry.classic_blaze_enchanter": "클래식 블레이즈 마법 부여기",
    "block.create_enchantment_industry.creative_bookshelf": "크리에이티브 책장",
    "block.create_enchantment_industry.crystal_essence": "수정 정수",
    "block.create_enchantment_industry.ender_woven_bag": "엔더 직조 가방",
    "block.create_enchantment_industry.experience": "액체 경험치",
    "block.create_enchantment_industry.experience_hatch": "경험치 해치",
    "block.create_enchantment_industry.experience_lantern": "경험치 랜턴",
    "block.create_enchantment_industry.grindstone_drain": "숫돌 배수구",
    "block.create_enchantment_industry.infused_dragon_breath": "주입된 드래곤의 숨결",
    "block.create_enchantment_industry.infuser": "주입기",
    "block.create_enchantment_industry.mechanical_grindstone": "기계식 숫돌",
    "block.create_enchantment_industry.printer": "인쇄기",
    "block.create_enchantment_industry.super_experience_block": "슈퍼 경험치 블록",
    "create.item_attributes.create_enchantment_industry.can_be_infused": "주입 가능",
    "create.item_attributes.create_enchantment_industry.can_be_infused.inverted": "주입 불가",
    "create.item_attributes.create_enchantment_industry.can_be_salvaged": "분해 가능",
    "create.item_attributes.create_enchantment_industry.can_be_salvaged.inverted": "분해 불가",
    "create.item_attributes.create_enchantment_industry.gem_purity": "%1$s 순도의 보석임",
    "create.item_attributes.create_enchantment_industry.gem_purity.inverted": "%1$s 순도의 보석이 아님",
    "create.item_attributes.create_enchantment_industry.has_empty_socket": "빈 소켓이 있음",
    "create.item_attributes.create_enchantment_industry.has_empty_socket.inverted": "빈 소켓이 없음",
    "create.item_attributes.create_enchantment_industry.has_gem": "보석이 소켓에 장착됨",
    "create.item_attributes.create_enchantment_industry.has_gem.inverted": "소켓에 장착된 보석이 없음",
    "create.item_attributes.create_enchantment_industry.is_upgradable_gem": "업그레이드 가능한 보석임",
    "create.item_attributes.create_enchantment_industry.is_upgradable_gem.inverted": "업그레이드 가능한 보석이 아님",
    "create.item_attributes.create_enchantment_industry.processable_by_mechanical_grindstone": "기계식 숫돌로 처리 가능",
    "create.item_attributes.create_enchantment_industry.processable_by_mechanical_grindstone.inverted": "기계식 숫돌로 처리 불가",
    "create_enchantment_industry.bookshelf.type.arcana": "아르카나",
    "create_enchantment_industry.bookshelf.type.eterna": "이터나",
    "create_enchantment_industry.bookshelf.type.quanta": "퀀타",
    "create_enchantment_industry.gui.blaze_composer.mode": "블레이즈 조율기: %1$s",
    "create_enchantment_industry.gui.blaze_composer.mode.apply": "적용",
    "create_enchantment_industry.gui.blaze_composer.mode.extract": "추출",
    "create_enchantment_industry.gui.blaze_composer.mode.merge": "병합",
    "create_enchantment_industry.gui.blaze_composer.mode_selector": "조율 모드",
    "create_enchantment_industry.gui.blaze_composer.super_mode.normal": "일반",
    "create_enchantment_industry.gui.blaze_composer.super_mode.super": "슈퍼",
    "create_enchantment_industry.gui.blaze_enchanter.blaze_mode.normal": "일반",
    "create_enchantment_industry.gui.blaze_enchanter.blaze_mode.super": "슈퍼",
    "create_enchantment_industry.gui.blaze_enchanter.level": "마법 부여 레벨",
    "create_enchantment_industry.gui.blaze_enchanter.mode.direct": "직접",
    "create_enchantment_industry.gui.blaze_enchanter.mode.template": "형판",
    "create_enchantment_industry.gui.blaze_enchanter.template.invalid": "이 아이템은 형판으로 사용할 수 없습니다.",
    "create_enchantment_industry.gui.blaze_forger.blaze_mode.normal": "일반",
    "create_enchantment_industry.gui.blaze_forger.blaze_mode.super": "슈퍼",
    "create_enchantment_industry.gui.blaze_forger.mode.apply": "적용",
    "create_enchantment_industry.gui.blaze_forger.mode.extract": "추출",
    "create_enchantment_industry.gui.blaze_forger.mode.merge": "병합",
    "create_enchantment_industry.gui.blaze_forger.mode_selector": "단조 모드",
    "create_enchantment_industry.gui.bookshelf.stat_type": "능력치 종류",
    "create_enchantment_industry.gui.bookshelf.stat_value": "능력치 값",
    "create_enchantment_industry.gui.experience_hatch.all": "전부",
    "create_enchantment_industry.gui.experience_hatch.exchange": "경험치 교환",
    "create_enchantment_industry.gui.experience_hatch.points": "포인트",
    "create_enchantment_industry.gui.goggles.blaze_experience.experience": "액체 경험치",
    "create_enchantment_industry.gui.goggles.blaze_experience.super_experience": "슈퍼 액체 경험치",
    "create_enchantment_industry.gui.goggles.bookshelf.allow_treasure": " - 보물 마법 허용",
    "create_enchantment_industry.gui.goggles.bookshelf.inactive": " (비활성)",
    "create_enchantment_industry.gui.goggles.captured_mob": "포획한 몹:",
    "create_enchantment_industry.gui.goggles.classic_enchanting.available_target": "사용 가능한 마법 부여 대상:",
    "create_enchantment_industry.gui.goggles.classic_enchanting.available_targets": "사용 가능한 마법 부여 대상:",
    "create_enchantment_industry.gui.goggles.enchanting.available_targets": "사용 가능한 마법:",
    "create_enchantment_industry.gui.goggles.enchanting.available_targets.more": "...외 %1$s개",
    "create_enchantment_industry.gui.goggles.enchanting.blaze_mode": "블레이즈 모드: %1$s",
    "create_enchantment_industry.gui.goggles.enchanting.blocked_super_penalty": "번개 경로가 막힘: 슈퍼 마법 부여 결과에 저주가 붙을 수 있습니다.",
    "create_enchantment_industry.gui.goggles.enchanting.completed": "마법 부여 완료!",
    "create_enchantment_industry.gui.goggles.enchanting.cost": "마법 부여 시 소모: %1$s",
    "create_enchantment_industry.gui.goggles.enchanting.insufficient_experience": "액체 경험치 부족: %1$s / %2$s",
    "create_enchantment_industry.gui.goggles.enchanting.insufficient_super_experience": "슈퍼 액체 경험치 부족: %1$s / %2$s",
    "create_enchantment_industry.gui.goggles.enchanting.invalid_item": "마법을 부여할 수 없는 아이템입니다!",
    "create_enchantment_industry.gui.goggles.enchanting.level": "마법 부여 레벨: %1$s",
    "create_enchantment_industry.gui.goggles.enchanting.level.not_set": "마법 부여 레벨이 설정되지 않았습니다!",
    "create_enchantment_industry.gui.goggles.enchanting.mode": "마법 부여 모드: %1$s",
    "create_enchantment_industry.gui.goggles.enchanting.mode_help.direct": "선택한 마법 부여 레벨로 호환되는 아이템에 무작위 마법을 부여합니다.",
    "create_enchantment_industry.gui.goggles.enchanting.mode_help.template": "형판 아이템에 맞는 마법 하나를 빈 마법 부여 형판에 기록합니다.",
    "create_enchantment_industry.gui.goggles.enchanting.requires": "필요한 입력:",
    "create_enchantment_industry.gui.goggles.enchanting.requires.direct": "마법을 부여할 수 있는 아이템 또는 책",
    "create_enchantment_industry.gui.goggles.enchanting.requires.template": "현재 블레이즈 모드와 일치하는 빈 마법 부여 형판",
    "create_enchantment_industry.gui.goggles.enchanting.template": "사용할 마법 부여 형판:",
    "create_enchantment_industry.gui.goggles.forging.blaze_mode": "블레이즈 모드: %1$s",
    "create_enchantment_industry.gui.goggles.forging.blocked_super_penalty": "번개 경로가 막힘: 슈퍼 단조 시 결과의 수리 비용이 증가합니다.",
    "create_enchantment_industry.gui.goggles.forging.completed": "단조 완료!",
    "create_enchantment_industry.gui.goggles.forging.conflicting": "결과에 원래 함께 붙을 수 없는 마법이 포함되어 있습니다.",
    "create_enchantment_industry.gui.goggles.forging.cost": "단조 시 소모: %1$s",
    "create_enchantment_industry.gui.goggles.forging.failure.apply_requires_enchanted_addition": "적용 모드의 두 번째 입력에는 마법이 부여된 책이나 마법이 든 형판이 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.apply_requires_target_item": "적용 모드에는 마법을 받을 수 있는 아이템이 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.curse_extraction_requires_super_mode": "저주만 남았습니다. 저주를 추출하려면 슈퍼 모드가 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.enchantment_cannot_apply": "두 번째 입력의 마법 중 첫 번째 입력에 적용할 수 있는 것이 없습니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.merge_requires_filled_templates": "병합 모드에는 마법이 든 형판 두 개가 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.merge_requires_matching_carriers": "병합 모드에는 서로 맞는 마법 운반체 또는 같은 장비 두 개가 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.missing_first_input": "첫 번째 입력이 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.missing_second_input": "두 번째 입력이 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.normal_template_requires_normal_mode": "일반 마법 부여 형판은 일반 모드에서 처리해야 합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.requires_blank_template": "추출 모드의 두 번째 입력에는 빈 마법 부여 형판이 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.requires_enchanted_addition": "두 번째 입력에 저장된 마법이 없습니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.requires_filled_template": "이 작업에는 마법이 든 형판이 필요합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.source_has_no_enchantments": "첫 번째 입력에 추출할 마법이 없습니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.source_has_no_extractable_enchantments": "첫 번째 입력에서 추출할 수 있는 마법이 없습니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.super_template_requires_super_mode": "슈퍼 마법 부여 형판은 슈퍼 모드에서 처리해야 합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.template_type_mismatch": "두 형판의 종류가 같아야 합니다.",
    "create_enchantment_industry.gui.goggles.forging.failure.would_not_improve": "이 조합으로는 결과가 향상되지 않습니다.",
    "create_enchantment_industry.gui.goggles.forging.insufficient_experience": "액체 경험치 부족: %1$s / %2$s",
    "create_enchantment_industry.gui.goggles.forging.insufficient_super_experience": "슈퍼 액체 경험치 부족: %1$s / %2$s",
    "create_enchantment_industry.gui.goggles.forging.invalid_items": "단조 아이템 조합이 잘못되었습니다!",
    "create_enchantment_industry.gui.goggles.forging.invalid_template_type.normal": "일반 마법 부여 형판은 슈퍼 마법 부여 모드에서 사용할 수 없습니다!",
    "create_enchantment_industry.gui.goggles.forging.invalid_template_type.special": "슈퍼 마법 부여 형판을 사용하려면 슈퍼 마법 부여 모드가 필요합니다!",
    "create_enchantment_industry.gui.goggles.forging.lost_enchantments": "손실된 마법:",
    "create_enchantment_industry.gui.goggles.forging.lost_reason.cannot_apply_to_item": "%1$s에 적용할 수 없음",
    "create_enchantment_industry.gui.goggles.forging.lost_reason.incompatible_with_output": "%1$s와 충돌함",
    "create_enchantment_industry.gui.goggles.forging.lost_reason.would_not_improve": "결과가 향상되지 않음",
    "create_enchantment_industry.gui.goggles.forging.mode": "단조 모드: %1$s",
    "create_enchantment_industry.gui.goggles.forging.mode_help.apply": "마법이 부여된 책이나 마법이 든 형판을 대상 아이템에 적용합니다.",
    "create_enchantment_industry.gui.goggles.forging.mode_help.extract": "아이템, 책 또는 형판에서 마법 하나를 추출해 빈 마법 부여 형판에 담습니다.",
    "create_enchantment_industry.gui.goggles.forging.mode_help.merge": "서로 맞는 마법 운반체, 책, 형판 또는 같은 장비를 합칩니다.",
    "create_enchantment_industry.gui.goggles.forging.output_blocked": "다른 작업을 시작하기 전에 단조 결과를 꺼내세요.",
    "create_enchantment_industry.gui.goggles.forging.over_cap": "결과가 기본 마법 레벨 상한을 넘습니다.",
    "create_enchantment_industry.gui.goggles.forging.rejected_enchantments": "거부된 마법:",
    "create_enchantment_industry.gui.goggles.forging.repair_cost_penalty": "수리 비용: %1$s -> %2$s",
    "create_enchantment_industry.gui.goggles.forging.requires": "필요한 입력:",
    "create_enchantment_industry.gui.goggles.forging.requires.apply.first": "호환되는 대상 아이템",
    "create_enchantment_industry.gui.goggles.forging.requires.apply.second": "마법이 부여된 책 또는 마법이 든 형판",
    "create_enchantment_industry.gui.goggles.forging.requires.extract.first": "마법이 있는 아이템, 책 또는 형판",
    "create_enchantment_industry.gui.goggles.forging.requires.extract.second": "빈 마법 부여 형판",
    "create_enchantment_industry.gui.goggles.forging.requires.first": "첫 번째: %1$s",
    "create_enchantment_industry.gui.goggles.forging.requires.merge.first": "마법 운반체 또는 수리 대상",
    "create_enchantment_industry.gui.goggles.forging.requires.merge.second": "서로 맞는 마법 운반체 또는 수리 재료",
    "create_enchantment_industry.gui.goggles.forging.requires.second": "두 번째: %1$s",
    "create_enchantment_industry.gui.goggles.forging.result": "단조 결과:",
    "create_enchantment_industry.gui.goggles.forging.result.lost_enchantment": "%1$s 손실: %2$s",
    "create_enchantment_industry.gui.goggles.forging.result.rejected_enchantment": "%1$s: %2$s",
    "create_enchantment_industry.gui.goggles.infuser.incorrect_liquid": "잘못된 주입 시약입니다!",
    "create_enchantment_industry.gui.goggles.no_captured_entity": "비어 있음",
    "create_enchantment_industry.gui.goggles.printer.banner_pattern": "현수막 무늬 인쇄:",
    "create_enchantment_industry.gui.goggles.printing": "인쇄 중:",
    "create_enchantment_industry.gui.goggles.printing.address": "주소 인쇄 중:",
    "create_enchantment_industry.gui.goggles.printing.copy": "복사 중:",
    "create_enchantment_industry.gui.goggles.printing.cost": "인쇄 비용: %1$s",
    "create_enchantment_industry.gui.goggles.printing.custom_name": "사용자 지정 이름 인쇄 중:",
    "create_enchantment_industry.gui.goggles.printing.incorrect_liquid": "잘못된 유체입니다!",
    "create_enchantment_industry.gui.goggles.printing.pattern": "소포 무늬 변경 중",
    "create_enchantment_industry.gui.goggles.printing.template": "사용할 인쇄 형판:",
    "create_enchantment_industry.gui.printer.banner_pattern.multiple_pattern": "이 현수막에는 복사할 무늬가 여러 개 있습니다.",
    "create_enchantment_industry.gui.printer.banner_pattern.no_pattern": "이 현수막에는 복사할 무늬가 없습니다.",
    "create_enchantment_industry.gui.printer.copy.invalid": "이 아이템에는 복사할 수 있는 내용이 없습니다.",
    "create_enchantment_industry.gui.printer.enchanted_book.all_denied": "이 책에는 복사할 수 있는 마법이 없습니다.",
    "create_enchantment_industry.gui.printer.enchanted_book.denied": "이 책에 복사할 수 없는 마법이 들어 있습니다.",
    "create_enchantment_industry.gui.printer.enchanted_book.invalid": "이 책에는 복사할 마법이 없습니다.",
    "create_enchantment_industry.gui.printer.written_book.invalid": "이 책에는 복사할 내용이 없습니다.",
    "create_enchantment_industry.ponder.blaze_enchanter.automate.header": "기계식 팔로 자동화하기",
    "create_enchantment_industry.ponder.blaze_enchanter.automate.text_1": "블레이즈 마법 부여기는 기계식 팔로 자동화할 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.automate.text_2": "기계식 팔로 마법을 부여할 아이템을 넣을 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.automate.text_3": "기계식 팔로 경험치 연료도 공급할 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.automate.text_4": "기계식 팔로 마법이 부여된 아이템과 유효하지 않은 아이템을 꺼낼 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.header": "블레이즈 마법 부여기 소개",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_1": "블레이즈 마법 부여기입니다. 마법 부여대처럼 작동합니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_10": "금 흉갑은 다이아몬드 흉갑보다 마법 부여 적성이 높아 비교적 더 좋은 마법이 붙습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_11": "하지만 마법 부여 레벨이 항상 높다고 좋은 것은 아닙니다. 너무 높으면 나타나지 않는 마법도 있습니다!",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_2": "액체 경험치를 공급해 활성화하세요",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_3": "마법을 부여하기 전에 패널에서 레벨을 설정해야 합니다. 기본 마법 부여대의 레벨 상한은 30입니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_4": "패널은 필터 슬롯이기도 합니다. 아이템을 든 채 슬롯을 우클릭하면 형판으로 지정되며, 이를 형판 마법 부여 모드라고 합니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_5": "형판 마법 부여 모드에서는 마법 부여 형판에 마법을 부여할 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_6": "형판 마법 부여 모드는 형판 아이템이 지원하는 마법만 만들 때 사용합니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_7": "예를 들어 필터 슬롯에 다이아몬드 흉갑을 놓으면 다이아몬드 흉갑용 마법만 생성됩니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_8": "빈 마법 부여 형판을 넣으면 앞서 설명한 마법이 형판에 추가됩니다",
    "create_enchantment_industry.ponder.blaze_enchanter.intro.text_9": "재료와 형판 아이템의 종류에 따라 서로 다른 마법이 생성됩니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.header": "블레이즈 마법 부여기로 슈퍼 마법 부여하기",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_1": "블레이즈 마법 부여기에는 '배'가 두 개 있습니다. 마법 부여 케이크를 먹이면...",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_2": "...들끓기 시작하며 슈퍼 마법 부여 모드가 됩니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_3": "두 번째 탱크에는 파이프로 액체 경험치를 넣을 수 없습니다. 마법 부여 케이크 같은 적합한 슈퍼 경험치 아이템을 사용해야 합니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_4": "슈퍼 마법 부여 모드에서는 마법 레벨 상한이 크게 오르고 보물 마법도 만들 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_5": "슈퍼 마법 부여 모드에서는 슈퍼 마법 부여 형판만 처리합니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_6": "근처에 피뢰침을 설치하세요",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_7": "슈퍼 마법 부여는 번개를 일으킬 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_8": "블레이즈 마법 부여기를 블록으로 덮어 번개를 막을 수 있지만 저주가 붙을 수 있습니다",
    "create_enchantment_industry.ponder.blaze_enchanter.super_enchant.text_9": "피뢰침이 없으면...",
    "create_enchantment_industry.ponder.blaze_forger.automate.header": "기계식 팔로 자동화하기",
    "create_enchantment_industry.ponder.blaze_forger.automate.text_1": "블레이즈 단조기는 기계식 팔로 자동화할 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.automate.text_2": "기계식 팔로 단조할 아이템을 넣을 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.automate.text_3": "기계식 팔로 경험치 연료도 공급할 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.automate.text_4": "기계식 팔로 단조된 아이템과 유효하지 않은 아이템을 꺼낼 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.intro.header": "블레이즈 단조기 소개",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_1": "블레이즈 단조기입니다. 모루처럼 작동합니다",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_2": "액체 경험치를 공급해 활성화하세요",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_3": "블레이즈 단조기는 모루처럼 같은 아이템의 마법을 합치지만 수리 비용이 들지 않습니다",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_4": "마법 부여 형판도 합칠 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_5": "옆면 패널에서 작업 모드를 바꿀 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_6": "적용 모드로 바꾸면 마법 부여 형판을 아이템에 적용할 수 있습니다!",
    "create_enchantment_industry.ponder.blaze_forger.intro.text_7": "추출 모드로 바꾸면 장비, 책 또는 형판의 마법 하나를 빈 마법 부여 형판에 옮길 수 있습니다!",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.header": "블레이즈 단조기로 슈퍼 마법 부여하기",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_1": "블레이즈 단조기에는 '배'가 두 개 있습니다. 마법 부여 케이크를 먹이면...",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_2": "...들끓기 시작하며 슈퍼 마법 부여 모드가 됩니다",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_3": "두 번째 탱크에는 파이프로 액체 경험치를 넣을 수 없습니다. 마법 부여 케이크 같은 적합한 슈퍼 경험치 아이템을 사용해야 합니다",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_4": "슈퍼 마법 부여 모드에서는 마법을 합칠 때 기본 레벨 상한을 넘을 수 있고 서로 충돌하는 마법도 합칠 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_5": "슈퍼 마법 부여 모드에서는 슈퍼 마법 부여 형판만 처리하고 적용합니다",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_6": "근처에 피뢰침을 설치하세요",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_7": "슈퍼 마법 부여는 번개를 일으킬 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_8": "블레이즈 단조기를 블록으로 덮어 번개를 막을 수 있지만 수리 비용이 생길 수 있습니다",
    "create_enchantment_industry.ponder.blaze_forger.super_enchant.text_9": "피뢰침이 없으면...",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.automate.header": "자동화하기",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.automate.text_1": "클래식 블레이즈 마법 부여기는 기계식 팔로 자동화할 수 있습니다. 마법을 부여할 아이템과 경험치 연료를 넣을 수 있습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.automate.text_2": "벨트로도 자동화할 수 있습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.automate.text_3": "경험치 연료는 벨트로 공급할 수 없습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.header": "클래식 블레이즈 마법 부여기 소개",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_1": "클래식 블레이즈 마법 부여기입니다. 지정한 마법 부여 형판에 따라 아이템에 계속 마법을 부여합니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_10": "슈퍼 마법 부여는 번개를 일으킬 수 있습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_11": "블록으로 덮어 번개를 막을 수 있지만 기존 마법의 레벨이 낮아질 수 있습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_2": "액체 경험치를 공급해 활성화하세요",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_3": "마법을 부여하기 전에 필터 슬롯에 마법 부여 형판을 설정해야 합니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_4": "형판의 마법이 아이템에 부여되며 형판이나 형판의 마법은 소모되지 않습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_5": "적용할 수 있는 마법이 여러 개면 하나가 무작위로 적용됩니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_6": "클래식 블레이즈 마법 부여기도 마법 부여 케이크를 먹여 같은 방식으로 슈퍼 마법 부여 모드에 들어갑니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_7": "슈퍼 마법 부여 모드에서는 슈퍼 마법 부여 형판만 사용할 수 있습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_8": "아이템에 같은 종류와 레벨의 마법이 이미 있으면 레벨이 하나 오르며 기본 마법 레벨 상한도 넘을 수 있습니다",
    "create_enchantment_industry.ponder.classic_blaze_enchanter.intro.text_9": "근처에 피뢰침을 설치하세요",
    "create_enchantment_industry.ponder.ender_woven_bag.header": "엔더 직조 가방으로 몹 포획하기",
    "create_enchantment_industry.ponder.ender_woven_bag.text_1": "엔더 끈으로 만드는 장치인 엔더 직조 가방입니다",
    "create_enchantment_industry.ponder.ender_woven_bag.text_2": "주변 몹을 끌어당겨 포획합니다",
    "create_enchantment_industry.ponder.ender_woven_bag.text_3": "가방이 가득 차면 표시등이 켜집니다",
    "create_enchantment_industry.ponder.ender_woven_bag.text_4": "레드스톤 신호를 받으면 포획한 몹을 풀어 줍니다",
    "create_enchantment_industry.ponder.ender_woven_bag_on_contraption.header": "움직이는 장치에서 엔더 직조 가방 사용하기",
    "create_enchantment_industry.ponder.ender_woven_bag_on_contraption.text_1": "엔더 직조 가방은 움직이는 장치에서도 작동합니다",
    "create_enchantment_industry.ponder.ender_woven_bag_on_contraption.text_2": "움직이는 장치의 엔더 직조 가방이 레드스톤 블록을 향하면 포획한 몹을 풀어 줍니다",
    "create_enchantment_industry.ponder.experience.advance.header": "알아 두면 좋은 것",
    "create_enchantment_industry.ponder.experience.advance.text_1": "Enchantment Industry를 사용하기 전에 몇 가지를 더 알아야 합니다",
    "create_enchantment_industry.ponder.experience.advance.text_2": "경험치 블록은 이제 장식과 저장만을 위한 블록이 아닙니다. 나중에 필요합니다",
    "create_enchantment_industry.ponder.experience.advance.text_3": "마법 부여 형판과 슈퍼 경험치 블록을 만들려면 경험치 블록이 필요합니다",
    "create_enchantment_industry.ponder.experience.advance.text_4": "슈퍼 마법 부여 형판을 만드는 데 사용하는 슈퍼 경험치 블록입니다",
    "create_enchantment_industry.ponder.experience.advance.text_5": "블레이즈 마법 부여기",
    "create_enchantment_industry.ponder.experience.advance.text_6": "블레이즈 단조기",
    "create_enchantment_industry.ponder.experience.advance.text_7": "들끓는 블레이즈 단조기와 마법 부여기는 슈퍼 마법 부여 모드입니다",
    "create_enchantment_industry.ponder.experience.advance.text_8": "슈퍼 마법 부여를 사용하면 기존 마법 부여의 한계를 넘을 수 있습니다",
    "create_enchantment_industry.ponder.experience.advance.text_9": "기본 마법 레벨 상한을 넘고, 충돌하는 마법을 합치며, 보물 마법을 직접 얻을 수 있습니다",
    "create_enchantment_industry.ponder.experience.beacon_base_block.header": "신호기 기반 블록으로 사용하기",
    "create_enchantment_industry.ponder.experience.intro.header": "경험치 처리 소개",
    "create_enchantment_industry.ponder.experience.intro.text_1": "액체 경험치 탱크입니다. Enchantment Industry에서 경험치를 주로 다루는 형태입니다",
    "create_enchantment_industry.ponder.experience.intro.text_10": "주입구로 액체 경험치를 용기 아이템에 다시 채우세요",
    "create_enchantment_industry.ponder.experience.intro.text_11": "파이프에서 새어 나온 액체 경험치는 경험치 구슬이 됩니다",
    "create_enchantment_industry.ponder.experience.intro.text_2": "보유한 경험치를 액체로 바꾸려면 두 구성 요소가 필요합니다",
    "create_enchantment_industry.ponder.experience.intro.text_3": "아이템의 유체에 직접 접근하는 유체 해치",
    "create_enchantment_industry.ponder.experience.intro.text_4": "플레이어의 경험치에 직접 접근하는 경험치 해치",
    "create_enchantment_industry.ponder.experience.intro.text_5": "하지만 Create의 일부인 만큼 자동화가 빠질 수는 없겠죠?",
    "create_enchantment_industry.ponder.experience.intro.text_6": "아이템 배수구로 아이템에서 액체 경험치를 빼내세요",
    "create_enchantment_industry.ponder.experience.intro.text_7": "기계식 숫돌은 아이템도 분쇄합니다. 예를 들어 경험치 조각을 액체 경험치로 바꿀 수 있습니다",
    "create_enchantment_industry.ponder.experience.intro.text_8": "분쇄 바퀴에 새로운 기능이 생겼습니다. 생물을 처치하면 낮은 확률로 경험치 조각을 소량 떨어뜨립니다",
    "create_enchantment_industry.ponder.experience.intro.text_9": "배치기도 생물을 처치하면 경험치 조각을 떨어뜨립니다",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.header": "슈퍼 마법 부여 재료 준비하기",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_1": "먼저 슈퍼 마법 부여 형판의 재료인 슈퍼 경험치 블록을 얻으세요. 경험치 블록이 필요합니다",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_2": "다음으로 피뢰침을 설치하세요",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_3": "번개가 내리칩니다!",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_4": "대부분의 번개는 일정 확률로만 경험치 블록을 변환하지만 슈퍼 마법 부여로 생긴 번개는 반드시 변환합니다",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_5": "두 번째로 마법 부여 케이크를 얻으세요. '슈퍼 경험치'로 작동해 블레이즈를 슈퍼 마법 부여 모드로 만듭니다.",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_6": "마법 부여 케이크가 블레이즈를 슈퍼 마법 부여 모드로 만든다면 슈퍼 경험치 블록은 어디에 쓸까요?",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_7": "정답: 슈퍼 마법 부여 형판 제작",
    "create_enchantment_industry.ponder.experience.prepare_for_super_enchant.text_8": "슈퍼 마법 부여 모드의 블레이즈 단조기와 마법 부여기는 일반 형판을 받지 않으며 슈퍼 마법 부여 형판만 사용합니다",
    "create_enchantment_industry.ponder.experience_hatch.intro.header": "경험치 해치 소개",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_1": "경험치 해치는 사용하기 쉽습니다. 우클릭하면 경험치를 보관하고...",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_2": "...Shift를 누른 채 우클릭하면 보관된 경험치를 꺼냅니다",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_3": "해치에는 필터 슬롯과 스크롤 패널이 있습니다. 패널에서 상호작용 한 번에 넣거나 꺼낼 경험치 양을 설정할 수 있습니다",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_4": "필터 슬롯은 다른 모드의 경험치 유체를 다룰 때 사용합니다",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_5": "예를 들어 액체 청록색 염료가 다른 모드의 경험치 유체라고 가정해 봅시다",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_6": "필터 슬롯에 청록색 염료 양동이를 놓으세요",
    "create_enchantment_industry.ponder.experience_hatch.intro.text_7": "이제 청록색 염료를 '청록색 경험치'로 직접 넣고 꺼낼 수 있습니다",
    "create_enchantment_industry.ponder.experience_lantern.intro.header": "경험치 랜턴 소개",
    "create_enchantment_industry.ponder.experience_lantern.intro.text_1": "경험치 랜턴은 주변 플레이어와 경험치 구슬의 경험치를 흡수합니다. 내부에 저장된 양에 따라 빛납니다",
    "create_enchantment_industry.ponder.experience_lantern.intro.text_2": "경험치 랜턴은 움직이는 장치에서도 작동합니다",
    "create_enchantment_industry.ponder.mechanical_grindstone.extra.header": "기계식 숫돌로 사포질하기",
    "create_enchantment_industry.ponder.mechanical_grindstone.extra.text_1": "기계식 숫돌은 숫돌의 모든 기능을 갖췄을 뿐만 아니라...",
    "create_enchantment_industry.ponder.mechanical_grindstone.extra.text_2": "...사포의 기능도 갖추고 있습니다",
    "create_enchantment_industry.ponder.mechanical_grindstone.extra.text_3": "아이템을 기계식 숫돌에 직접 사용할 수 있습니다",
    "create_enchantment_industry.ponder.mechanical_grindstone.intro.header": "기계식 숫돌 소개",
    "create_enchantment_industry.ponder.mechanical_grindstone.intro.text_1": "기계식 숫돌을 든 채 아이템 배수구를 우클릭하면...",
    "create_enchantment_industry.ponder.mechanical_grindstone.intro.text_2": "숫돌 배수구가 됩니다. 사용하려면 위에 기계식 숫돌을 하나 더 놓으세요",
    "create_enchantment_industry.ponder.mechanical_grindstone.intro.text_3": "아이템 형태의 경험치를 기계식 숫돌로 분쇄해 액체로 바꿀 수 있습니다",
    "create_enchantment_industry.ponder.printer.intro.header": "인쇄기 소개",
    "create_enchantment_industry.ponder.printer.intro.text_1": "인쇄기입니다",
    "create_enchantment_industry.ponder.printer.intro.text_2": "사용하기 전에 필터 슬롯에서 인쇄할 아이템을 설정하고...",
    "create_enchantment_industry.ponder.printer.intro.text_3": "...알맞은 유체를 공급하세요",
    "create_enchantment_industry.ponder.printer.intro.text_4": "쓰인 책 복사",
    "create_enchantment_industry.ponder.printer.intro.text_5": "소포 무늬 변경",
    "create_enchantment_industry.ponder.printer.intro.text_6": "마법이 부여된 책 복제",
    "create_enchantment_industry.ponder.printer.intro.text_7": "아이템 이름 지정, 열차 운행 일정 복사, 클립보드 복사, 소포 주소 변경 등도 할 수 있습니다. JEI에서 인쇄 조합법을 확인하세요",
    "create_enchantment_industry.ponder.tag.experience_appliances": "경험치 관련 장치",
    "create_enchantment_industry.ponder.tag.experience_appliances.description": "경험치를 처리하고 적용할 때 사용하는 구성 요소",
    "create_enchantment_industry.ponder.tag.super_experience_related": "슈퍼 경험치 관련 장치",
    "create_enchantment_industry.ponder.tag.super_experience_related.description": "슈퍼 경험치를 처리하고 적용할 때 사용하는 구성 요소",
    "create_enchantment_industry.recipe.assembly.grinding": "숫돌로 갈기",
    "create_enchantment_industry.recipe.assembly.grinding.needs_fluid": "숫돌로 갈기, %1$s 소모",
    "create_enchantment_industry.recipe.assembly.printing": "형판으로 인쇄: %1$s, %2$s 소모",
    "create_enchantment_industry.recipe.grinding": "분쇄",
    "create_enchantment_industry.recipe.infusing": "주입",
    "create_enchantment_industry.recipe.printing": "인쇄",
    "create_enchantment_industry.recipe.printing.banner_pattern.base": "아무 현수막",
    "create_enchantment_industry.recipe.printing.banner_pattern.color_follow_dye": "인쇄된 무늬의 색은 유체 염료를 따름",
    "create_enchantment_industry.recipe.printing.banner_pattern.template": "단일 현수막 무늬",
    "create_enchantment_industry.recipe.printing.copy.template": "복사 가능한 내용",
    "create_enchantment_industry.recipe.printing.custom_name.base": "모든 아이템 사용 가능",
    "create_enchantment_industry.recipe.printing.custom_name.template": "사용자 지정 이름",
    "death.attack.create_enchantment_industry.grind": "기계식 숫돌이 %1$s의 손을 날려 버렸습니다.",
    "fluid.create_enchantment_industry.infused_dragon_breath": "주입된 드래곤의 숨결",
    "item.create_enchantment_industry.blazes_enchanting_handbook": "블레이즈의 마법 부여 안내서",
    "item.create_enchantment_industry.crystal_essence_bucket": "수정 정수 양동이",
    "item.create_enchantment_industry.enchanting_template": "마법 부여 형판",
    "item.create_enchantment_industry.experience_bucket": "마법 부여 양동이",
    "item.create_enchantment_industry.experience_cake": "마법 부여 케이크",
    "item.create_enchantment_industry.experience_cake_base": "마법 부여 케이크 바탕",
    "item.create_enchantment_industry.experience_cake_slice": "마법 부여 케이크 조각",
    "item.create_enchantment_industry.incomplete_brass_bookshelf": "미완성 황동 책장",
    "item.create_enchantment_industry.infused_dragon_breath_bucket": "주입된 드래곤의 숨결 양동이",
    "item.create_enchantment_industry.super_enchanting_template": "슈퍼 마법 부여 형판",
    "item.create_enchantment_industry.super_experience_nugget": "슈퍼 경험치 조각",
    "itemGroup.create_enchantment_industry.base": "Create: Enchantment Industry",
    "stat.create_enchantment_industry.classic_enchant": "클래식 블레이즈 마법 부여기 사용",
    "stat.create_enchantment_industry.enchant": "블레이즈 마법 부여기 사용",
    "stat.create_enchantment_industry.forge": "블레이즈 단조기 사용",
    "stat.create_enchantment_industry.mechanical_grindstone_experience": "생산한 경험치(기계식 숫돌)",
    "stat.create_enchantment_industry.print": "인쇄기 사용",
    "stat.create_enchantment_industry.super_enchant": "슈퍼 마법 부여",
    "tag.block.create_enchantment_industry.fan_processing_catalysts.salvaging": "대량 분해 촉매",
    "tag.fluid.create_enchantment_industry.fan_processing_catalysts.salvaging": "대량 분해 촉매",
    "tag.fluid.create_enchantment_industry.infusing.ingredients": "주입 시약",
    "tag.item.create_enchantment_industry.blaze_composer.super_activators": "블레이즈 조율기 슈퍼 활성화 아이템",
}


def build_cei_overrides() -> dict[str, str]:
    """검수된 프로젝트 연동 번역을 보존하고 CEI 신규 원문을 직접 번역한다."""
    root = WORK_ROOT / "create_enchantment_industry"
    english = load_json(root / "en_us.json")
    korean = load_json(root / "ko_kr.json")
    sources = load_json(root / "candidate_sources.json")
    translated = {
        key: korean[key]
        for key, source_kind in sources.items()
        if source_kind == "project_output_review"
    }
    translated.update(CEI_NEW)
    missing = sorted(set(english) - set(translated))
    extra = sorted(set(translated) - set(english))
    if missing or extra:
        raise KeyError(
            f"Enchantment Industry 번역 범위 불일치: missing={missing}, extra={extra}"
        )
    return translated


OVERRIDES["create_enchantment_industry"] = build_cei_overrides()


CREATE_RECHECK_TERM_REPLACEMENTS: dict[str, tuple[tuple[str, str], ...]] = {
    "create": (
        ("순서 기어쉬프트", "순차 기어변환기"),
        ("기어쉬프트", "기어변환기"),
        ("기계 손", "배치기"),
        ("기계 팔", "기계식 팔"),
        ("아이템 거치대", "보관소"),
        ("퍼널", "깔때기"),
        ("엔지니어의 고글", "기술자의 고글"),
        ("증기 엔진", "증기 기관"),
        ("엔진", "기관"),
        ("투척기", "무게 추 달린 배출기"),
        ("재고 확인기", "재고 표시기"),
        ("재고 링크", "재고 연결기"),
        ("개구리포트", "소포 개구리항"),
        ("사슬 컨베이어", "체인 컨베이어"),
        ("동형 감지기", "레드스톤 접점"),
        ("엘리베이터 감지기", "엘리베이터 접점"),
        ("아이템 금고", "아이템 저장고"),
        ("물레바퀴", "수차"),
        ("기차 계획표", "열차 운행 일정"),
        ("계획표", "운행 일정"),
        ("기차 조종기", "열차 조종석"),
        ("기차 정거장", "열차역"),
        ("정거장", "역"),
        ("기차", "열차"),
        ("택배", "소포"),
        ("우체통", "우편함"),
        ("금고", "저장고"),
        ("한계점", "임계값"),
        ("케이스", "케이싱"),
        ("주입기", "주입구"),
        ("핸드 크랭크", "손 크랭크"),
        ("분쇄 휠", "분쇄 바퀴"),
        ("디스플레이 화면", "디스플레이 보드"),
        ("기적 장치", "증기 기적"),
        ("연장 축", "연장봉"),
        ("원형 섀시", "방사형 섀시"),
        ("직선 섀시", "선형 섀시"),
        ("호박금", "일렉트럼"),
    ),
    "createaddition": (
        ("호박금", "일렉트럼"),
        ("애뮬럿", "애뮬릿"),
        ("교류발전기", "교류 발전기"),
    ),
    "create_dragons_plus": (
        ("엔딩", "엔드 가공"),
        ("팬 가공", "선풍기 가공"),
    ),
}


CREATE_RECHECK_FIXES: dict[str, dict[str, str]] = {
    "create": {
        "advancement.create.long_travel.desc": "여행을 시작한 곳에서 5000블록 이상 떨어진 곳에서 하차하세요",
        "advancement.create.saw_processing.desc": "위를 향한 기계식 톱으로 재료를 가공하세요",
        "advancement.create.track_0.desc": "열차 선로를 얻으세요",
        "advancement.create.track_crafting_factory.desc": "하나의 기계식 압착기로 열차 선로를 1000개 넘게 생산하세요",
        "advancement.create.windmill_maxed.desc": "최대 세기의 풍차를 조립하세요",
        "block.create.adjustable_chain_gearshift": "조정 가능한 체인 기어변환기",
        "block.create.content_observer": "스마트 감지기",
        "block.create.contraption_controls": "움직이는 장치 조작기",
        "block.create.controller_rail": "조종 레일",
        "block.create.controls": "열차 조종석",
        "block.create.copycat_step": "모방 단차 블록",
        "block.create.crushing_wheel": "분쇄 바퀴",
        "block.create.crushing_wheel_controller": "분쇄 바퀴 조작기",
        "block.create.display_board": "디스플레이 보드",
        "block.create.elevator_contact": "엘리베이터 접점",
        "block.create.encased_chain_drive": "케이싱 체인 드라이브",
        "block.create.framed_glass": "틀 유리",
        "block.create.framed_glass_door": "틀 유리문",
        "block.create.framed_glass_pane": "틀 유리판",
        "block.create.framed_glass_trapdoor": "틀 유리 다락문",
        "block.create.horizontal_framed_glass": "수평 틀 유리",
        "block.create.horizontal_framed_glass_pane": "수평 틀 유리판",
        "block.create.item_vault": "아이템 저장고",
        "block.create.linear_chassis": "선형 섀시",
        "block.create.mechanical_roller": "기계식 롤러",
        "block.create.package_frogport": "소포 개구리항",
        "block.create.peculiar_bell": "기묘한 종",
        "block.create.piston_extension_pole": "피스톤 연장봉",
        "block.create.radial_chassis": "방사형 섀시",
        "block.create.railway_casing": "열차 케이싱",
        "block.create.redstone_contact": "레드스톤 접점",
        "block.create.secondary_linear_chassis": "보조 선형 섀시",
        "block.create.steam_whistle": "증기 기적",
        "block.create.steam_whistle_extension": "증기 기적 연장관",
        "block.create.stockpile_switch": "임계값 스위치",
        "block.create.track": "열차 선로",
        "block.create.track_signal": "열차 신호기",
        "block.create.track_station": "열차역",
        "block.create.vertical_framed_glass": "수직 틀 유리",
        "block.create.vertical_framed_glass_pane": "수직 틀 유리판",
        "block.create.water_wheel": "수차",
        "block.create.large_water_wheel": "대형 수차",
        "block.create.water_wheel_structure": "대형 수차",
        "create.contraptions.roller_mode.straight_fill": "아래를 평평하게 채우기",
        "create.contraptions.roller_mode.wide_fill": "아래를 경사지게 채우기",
        "create.crafting_blueprint.filter_items_viable": "고급 필터 아이템도 사용 가능",
        "create.crafting_blueprint.inferred": "조합법에서 자동 추론",
        "create.crafting_blueprint.manually_assigned": "직접 지정",
        "create.crafting_blueprint.optional": "선택 사항",
        "create.crafting_blueprint.secondary_display_slot": "두 번째 전시 슬롯",
        "create.display_source.station_summary.now": "지금",
        "create.gui.assembly.exception": "이 움직이는 장치를 조립할 수 없습니다:",
        "create.gui.assembly.exception.column_conflict": "이미 다른 엘리베이터가 이 접점 열을 대상으로 지정했습니다",
        "create.gui.assembly.exception.noPistonPoles": "피스톤에 연장봉이 부족합니다",
        "create.gui.assembly.exception.no_contacts": "엘리베이터 구조물에 수평 _레드스톤_ _접점_이 필요합니다",
        "create.gui.assembly.exception.tooManyPistonPoles": "이 피스톤에 연장봉이 너무 많이 부착되어 있습니다.\n설정된 최댓값: %1$s개",
        "create.gui.assembly.exception.too_many_contacts": "엘리베이터에는 _레드스톤_ _접점_을 두 개 이상 부착할 수 없습니다",
        "create.gui.factory_panel.expected_output": "예상 출력: %1$s",
        "create.gui.factory_panel.expected_output_tip": "되돌아오는 출력 수량",
        "create.gui.factory_panel.expected_output_tip_1": "요청이 성공할 때마다",
        "create.gui.schematicannon.option.dontReplaceSolid.description": "대포는 작업 구역의 고체 블록을 절대 교체하지 않고 비고체 블록과 공기만 교체합니다.",
        "create.gui.schematicannon.option.replaceWithAny.description": "설계도의 해당 위치에 블록이 하나라도 있으면 대포가 작업 구역의 고체 블록을 교체합니다.",
        "create.gui.schematicannon.option.replaceWithEmpty.description": "대포가 공기로 바뀔 위치까지 포함해 작업 구역의 모든 블록을 제거합니다.",
        "create.gui.schematicannon.option.replaceWithSolid.description": "설계도의 해당 위치가 고체 블록일 때만 대포가 작업 구역의 고체 블록을 교체합니다.",
        "create.gui.schematicannon.option.skipBlockEntities.description": "대포가 상자처럼 데이터를 저장하는 블록은 교체하지 않습니다.",
        "create.gui.threshold_switch.title": "임계값 스위치",
        "create.hint.empty_bearing": "_빈_ _손_으로 베어링을 _우클릭_하여 앞에 지은 구조물을 _부착_하세요.",
        "create.hint.full_deployer": "이 _배치기_에는 _꺼내야_ 할 _넘친_ _아이템_이 있습니다. _호퍼_나 _깔때기_ 등으로 아이템을 빼내세요.",
        "create.hint.full_deployer.title": "배치기가 작동할 수 없음",
        "create.hint.mechanical_arm_no_targets": "이 _기계식_ _팔_에는 _대상_이 지정되지 않았습니다. _손에_ _기계식_ _팔_을 _들고_ 벨트, 보관소, 깔때기 등을 _우클릭_하여 대상으로 지정하세요.",
        "create.ponder.andesite_tunnel.text_2": "안산암 터널의 옆면에 연결된 벨트가 있으면...",
        "create.ponder.auto_schedule.text_1": "운행 일정으로 기관사에게 목적지를 지정할 수 있습니다.",
        "create.ponder.auto_schedule.text_3": "역에는 표시된 방향으로만 접근할 수 있다는 점에 유의하세요.",
        "create.ponder.auto_schedule.text_5": "역에 놓인 운행 일정은 도착한 열차에 자동으로 복사됩니다.",
        "create.ponder.auto_schedule.text_6": "직접 전달할 때와 달리 기관사는 운행 일정 아이템을 가져가지 않습니다.",
        "create.ponder.basin.text_3": "알맞은 부품이 있으면 대야에 배출구가 나타납니다.",
        "create.ponder.basin.text_6": "배출구가 없으면 대야는 가공 결과물을 보관합니다.",
        "create.ponder.bearing_modes.text_1": "멈추면 베어링이 구조물을 격자에 맞는 가장 가까운 각도로 배치합니다.",
        "create.ponder.brass_funnel.text_3": "값 패널에서 추출할 묶음 크기를 정확히 설정할 수 있습니다.",
        "create.ponder.cart_assembler.text_2": "레드스톤 신호가 없으면 지나가는 수레 장치를 다시 블록으로 해체합니다.",
        "create.ponder.deployer_redstone.text_3": "따라서 신호가 잠깐 꺼지는 펄스로 정확히 한 번만 작동시킬 수 있습니다.",
        "create.ponder.display_board.text_1": "디스플레이 보드는 크기를 확장할 수 있는 표지판입니다.",
        "create.ponder.factory_gauge_links.text_3": "재고 수준이 목표치 이상이면 레드스톤 링크에 신호를 보냅니다.",
        "create.ponder.factory_gauge_recipe.text_11": "게이지를 우클릭한 채로 유지할 목표 수량을 설정할 수 있습니다.",
        "create.ponder.factory_gauge_recipe.text_13": "...지정된 주소로 새 재료를 보냅니다.",
        "create.ponder.factory_gauge_recipe.text_14": "그런 다음 결과물은 연결된 인벤토리 중 하나로 돌아와야 합니다.",
        "create.ponder.factory_gauge_restocker.text_10": "...물류 네트워크가 지정된 주소로 부족한 아이템을 더 보냅니다.",
        "create.ponder.fan_processing.text_7": "선풍기의 속도는 가공 속도에 영향을 주지 않고 범위만 바꿉니다.",
        "create.ponder.fluid_pipe_flow.text_1": "유체 파이프는 두 곳 이상의 유체 공급원과 대상을 연결할 수 있습니다.",
        "create.ponder.fluid_pipe_interaction.text_3": "열린 끝 바로 앞의 유체 원천 블록을 흡수할 수 있고...",
        "create.ponder.fluid_tank_sizes.text_4": "렌치로 탱크의 창을 열거나 닫을 수 있습니다.",
        "create.ponder.funnel_compat.text_1": "깔때기는 여러 다른 부품과도 원활하게 상호작용합니다.",
        "create.ponder.funnel_direction.text_2": "웅크린 채 설치하면 인벤토리에 아이템을 넣습니다.",
        "create.ponder.funnel_intro.text_1": "깔때기는 인벤토리에서 아이템을 넣고 빼는 데 적합합니다.",
        "create.ponder.gantry_cascaded.text_3": "이렇게 갠트리 시스템을 연쇄 연결해 여러 이동 축을 지원할 수 있습니다.",
        "create.ponder.gantry_redstone.text_2": "대신 회전력이 운반대의 출력 축으로 전달됩니다.",
        "create.ponder.gearbox.text_1": "회전축 사이로 동력을 옮기려면 장치가 금세 커집니다.",
        "create.ponder.gearbox.text_2": "기어박스는 같은 구성을 더 작게 만들 수 있습니다.",
        "create.ponder.hose_pulley.text_7": "도르래의 흡입과 배출 속도는 유체 네트워크의 처리량에 따라 결정됩니다.",
        "create.ponder.hose_pulley_infinite.text_3": "파이프 망은 이런 도르래에서 유체를 무한히 가져오거나 내보낼 수 있습니다.",
        "create.ponder.item_vault_sizes.text_1": "아이템 저장고를 연결하면 총 저장 용량을 늘릴 수 있습니다.",
        "create.ponder.large_cogwheel.text_1": "큰 톱니바퀴는 서로 직각으로 맞물릴 수 있습니다.",
        "create.ponder.large_water_wheel.text_2": "다른 면을 더 덮어도 회전력 출력은 더 늘어나지 않습니다.",
        "create.ponder.mechanical_arm_filtering.text_6": "기계식 팔은 분배할 수 없는 아이템은 집지 않습니다.",
        "create.ponder.mechanical_arm_modes.text_8": "'강제 순환' 모드는 출력 대상을 건너뛰지 않고 공간이 생길 때까지 기다립니다.",
        "create.ponder.mechanical_arm_redstone.text_3": "따라서 신호가 잠깐 꺼지는 펄스로 정확히 한 번만 작동시킬 수 있습니다.",
        "create.ponder.mechanical_crafter.text_7": "경로의 모든 슬롯에 아이템이 들어가면 조합이 시작됩니다.",
        "create.ponder.mechanical_crafter_covers.text_3": "뒤쪽을 렌치로 연결해 만든 공유 입력은 덮인 조합기 너머까지 이어질 수 있습니다.",
        "create.ponder.mechanical_harvester.text_2": "지나는 길의 다 자란 작물을 수확한 뒤 다시 심습니다.",
        "create.ponder.mechanical_pump_speed.text_4": "같은 파이프 망에 연결된 펌프의 처리량은 합산됩니다.",
        "create.ponder.mechanical_drill.text_2": "채굴 속도는 입력 회전 속도에 비례합니다.",
        "create.ponder.mechanical_pump_speed.text_1": "회전 속도와 관계없이 기계식 펌프는 최대 16블록 떨어진 연결 파이프까지 영향을 줍니다.",
        "create.ponder.mechanical_pump_speed.text_2": "입력 회전 속도를 높이면 유체 흐름이 전파되는 속도가 빨라지고...",
        "create.ponder.mechanical_saw_breaker.text_2": "나무 전체를 베려면 땅과 이어진 마지막 원목 블록을 톱으로 잘라야 합니다.",
        "create.ponder.package_frogport.text_17": "소포 주소를 '피터'로 지정합니다.",
        "create.ponder.package_frogport.text_7": "유효한 목적지가 없으면 소포가 제자리에서 맴돕니다.",
        "create.ponder.portable_fluid_interface.text_5": "연결된 동안 고정 인터페이스가 장치의 모든 탱크를 대신합니다.",
        "create.ponder.portable_storage_interface.text_1": "움직이는 인벤토리는 자동화 장치로 접근하기 어렵습니다.",
        "create.ponder.portable_storage_interface.text_5": "연결된 동안 고정 인터페이스가 장치의 모든 인벤토리를 대신합니다.",
        "create.ponder.powered_latch.text_1": "레드스톤 걸쇠는 레드스톤으로 제어하는 레버입니다.",
        "create.ponder.powered_latch.text_2": "뒤쪽에서 신호를 받으면 켜지고...",
        "create.ponder.powered_latch.text_3": "...옆쪽에서 신호를 받으면 다시 꺼집니다.",
        "create.ponder.powered_latch.text_4": "레드스톤 걸쇠는 직접 전환할 수도 있습니다.",
        "create.ponder.powered_toggle_latch.text_1": "레드스톤 토글 걸쇠는 레드스톤으로 제어하는 레버입니다.",
        "create.ponder.powered_toggle_latch.text_2": "뒤쪽에서 신호를 받으면 상태가 전환되어...",
        "create.ponder.powered_toggle_latch.text_3": "...켜지거나 다시 꺼집니다.",
        "create.ponder.powered_toggle_latch.text_4": "레드스톤 토글 걸쇠는 직접 전환할 수도 있습니다.",
        "create.ponder.rope_pulley_attachment.text_3": "도르래 자체는 멈춘 상태에서만 구조물과 함께 움직일 수 있습니다.",
        "create.ponder.rotation_speed_controller.text_1": "회전 속도 제어기는 축의 회전을 위쪽 큰 톱니바퀴로 전달합니다.",
        "create.ponder.smart_observer.text_2": "일반 보관함 안의 아이템이나 유체를 감지할 수 있습니다.",
        "create.ponder.spout_filling.text_1": "주입구는 아래에 놓인 유체 용기 아이템을 채울 수 있습니다.",
        "create.ponder.steam_engine.text_2": "증기 기관에 축을 사용하면 회전력 출력이 만들어집니다.",
        "create.ponder.steam_engine.text_6": "블레이즈 버너를 사용하면 출력 회전력을 높일 수 있습니다.",
        "create.ponder.steam_engine.text_9": "출력 단계가 오를 때마다 증기 기관 하나가 최대 용량으로 더 작동할 수 있습니다.",
        "create.ponder.steam_engine.text_11": "증기 기관 4개",
        "create.ponder.steam_engine.text_13": "증기 기관 8개",
        "create.ponder.steam_whistle.text_2": "탱크에 충분한 열이 있으면...",
        "create.ponder.steam_whistle.text_4": "증기 기적 아이템을 블록에 사용하면 음높이가 낮아집니다.",
        "create.ponder.steam_whistle.text_6": "기술자의 고글로 증기 기적의 현재 음높이를 확인할 수 있습니다.",
        "create.ponder.stock_link.text_7": "최대 세기의 레드스톤 신호를 받으면 재고 연결기가 송출을 멈춥니다.",
        "create.ponder.stressometer.text_1": "피로도 계측기는 연결된 회전망의 현재 피로도 용량을 표시합니다.",
        "create.ponder.table_cloth.text_4": "재고 표시기를 재고 연결기에 연결한 뒤 상점에 놓으세요.",
        "create.ponder.threshold_switch.text_3": "...스위치의 레드스톤 출력 상태가 바뀝니다.",
        "create.ponder.threshold_switch.text_4": "신호는 하한에 도달할 때까지 유지됩니다.",
        "create.ponder.tag.windmill_sails": "풍차 베어링용 날개",
        "create.ponder.track_observer.text_3": "필터를 설정하면 일치하는 화물을 실은 열차에만 작동합니다.",
        "create.ponder.track_placement.text_6": "달리기 키를 누른 채 연결하면...",
        "create.ponder.train_assembly.text_2": "역은 선로망의 경유지입니다.",
        "create.ponder.train_signal_signaling.text_5": "황동 신호기로 시작한 구간은 보통 일반 신호기로 끝납니다.",
        "create.ponder.train_signal_signaling.text_7": "이 특수 신호기는 구간에 들어간 열차가...",
        "create.ponder.train_signal_signaling.text_8": "...구간을 즉시 빠져나갈 수 없다면 정지시킵니다.",
        "create.ponder.valve_pipe.text_3": "열리는 방향으로 회전력을 공급하면 밸브가 열립니다.",
        "create.ponder.weighted_ejector.text_1": "무게 추 달린 배출기를 든 채 웅크리고 우클릭하면 목표 위치를 지정할 수 있습니다.",
        "create.ponder.weighted_ejector.text_11": "몹이나 플레이어가 밟으면 무게 추 달린 배출기가 항상 작동합니다.",
        "create.ponder.windmill_source.text_5": "풍차 날개 블록 수가 회전 속도를 결정합니다.",
        "create.schedule.condition.player_count.or_above": "이상",
        "create.schedule.no_stops": "이 운행 일정에는 아직 정차 지점이 없습니다",
        "create.schematic.invalid": "[!] 잘못된 아이템 - 대신 설계도 탁자를 사용하세요",
        "create.schematics.wrongFormat": "업로드하려는 설계도가 손상되었거나 잘못 인코딩되었습니다! GZIP 호환 형식으로 인코딩해야 합니다.",
        "create.stock_keeper.cash_register_full": "구매 취소: 계산대에 공간이 부족합니다",
        "create.track.slope_turn": "회전 구간에서는 경사로에 들어가거나 경사로를 벗어날 수 없습니다",
        "create.train.status.no_package_target": "화물에 든 소포의 주소와 일치하는 우편함이 없습니다",
        "create.train.status.opposite_driver": "이 경로에는 반대 방향을 바라보는 기관사가 필요합니다",
        "item.create.attribute_filter": "속성 필터",
        "item.create.attribute_filter.tooltip.behaviour1": "속성 필터의 _설정 창_을 엽니다.",
        "item.create.crafting_blueprint.behaviour1": "전시할 아이템과 _조합법_을 _설정_할 수 있는 _조합_ _메뉴_를 엽니다.",
        "item.create.crafting_blueprint.behaviour2": "_인벤토리_에서 찾은 일치하는 재료로 _설정된_ _조합법_을 _적용_합니다. _웅크리면_ 최대 _한 묶음_까지 조합합니다.",
        "item.create.crafting_blueprint.tooltip.summary": "벽에 _설치_하면 손으로 쉽게 조합하도록 _재료_ _배치_를 _지정_할 수 있습니다. 각 슬롯은 조합법 하나를 나타냅니다.",
        "item.create.electron_tube": "전자관",
        "item.create.experience_nugget.tooltip.behaviour1": "담긴 _경험치_를 _획득_합니다.",
        "item.create.extendo_grip": "연장 손잡이",
        "item.create.extendo_grip.tooltip.behaviour1": "_주로 사용하는 손_에 든 아이템의 _도달 거리_를 늘립니다.",
        "item.create.filter": "목록 필터",
        "item.create.filter.tooltip.behaviour1": "목록 필터의 _설정 창_을 엽니다.",
        "item.create.goggles.tooltip.behaviour1": "_회전 장치_는 추가되는 _피로도 부하_나 _용량_을 보여 줍니다. _피로도 계측기_는 _연결된 회전망의 통계_를 보여 줍니다. 일부 블록은 아이템과 유체 내용물도 표시합니다.",
        "item.create.linked_controller.tooltip.behaviour1": "조작기를 _켜고 끕니다_. 활성화된 동안 _이동_ _키_로 조작합니다.",
        "item.create.package": "골판지 소포",
        "item.create.package_filter": "소포 필터",
        "item.create.package_filter.tooltip.behaviour1": "소포 필터의 _설정 창_을 엽니다.",
        "item.create.rare_package": "희귀 소포",
        "item.create.sturdy_sheet": "견고한 판",
        "item.create.sweet_roll": "달콤한 롤",
        "item.create.whisk": "거품기",
        "item.create.wand_of_symmetry.tooltip.behaviour2": "활성화된 거울을 _제거합니다_.",
        "item.create.wrench.tooltip.summary": "여러 회전 장치를 다루는 다목적 도구입니다.",
        "advancement.create.package_chute_throw.desc": "골판지 소포를 아이템 슈트로 던지세요\n§7(숨겨진 발전과제)",
        "create.subtitle.package_pop": "소포가 부서짐",
    },
    "createaddition": {
        "block.createaddition.accumulator.tooltip.behaviour1": "위 화살표가 그려진 _단자_에서 연결된 _전선_으로 _FE_를 공급합니다.",
        "block.createaddition.accumulator.tooltip.behaviour2": "아래 화살표가 그려진 _단자_가 연결된 _전선_에서 _FE_를 공급받습니다.",
        "block.createaddition.digital_adapter.tooltip.summary": "컴퓨터가 _디스플레이 보드_, _속도 계측기_, _피로도 계측기_, _밧줄 도르래_, _호스 도르래_, _엘리베이터 도르래_, _기계식 피스톤_, _기계식 베어링_, _회전 속도 제어기_와 상호작용하도록 하는 _ComputerCraft 주변기기_입니다.",
        "createaddition.schedule.condition.energy_threshold": "에너지 화물 조건",
        "effect.createaddition.shocking": "감전",
        "fluid.createaddition.bioethanol": "바이오연료",
        "item.createaddition.bioethanol_bucket": "바이오연료 양동이",
        "item.createaddition.electrum_amulet": "연한 금빛 애뮬릿",
        "item.createaddition.electrum_amulet.tooltip": "연한 금빛 애뮬릿",
        "item.createaddition.electrum_amulet.tooltip.summary": "이 _애뮬릿_은 충전식 아이템에 _짜릿한⚡_ 효과를 줍니다! 손에 들고 있으면 다른 손의 아이템을 가끔 충전합니다.",
        "item.createaddition.electrum_ingot": "일렉트럼 주괴",
        "item.createaddition.electrum_nugget": "일렉트럼 조각",
        "item.createaddition.electrum_rod": "일렉트럼 막대기",
        "item.createaddition.electrum_sheet": "일렉트럼 판",
        "item.createaddition.electrum_spool": "일렉트럼 전선 타래",
        "item.createaddition.electrum_wire": "일렉트럼 철사",
        "item.createaddition.brass_rod": "황동 막대기",
        "item.createaddition.bronze_rod": "청동 막대기",
        "item.createaddition.copper_rod": "구리 막대기",
        "item.createaddition.gold_rod": "금 막대기",
        "item.createaddition.iron_rod": "철 막대기",
        "tag.fluid.c.ignites": "점화 가능한 유체",
    },
    "create_dragons_plus": {
        "create.item_attributes.create_dragons_plus.endable": "엔드 가공 가능",
        "create.item_attributes.create_dragons_plus.endable.inverted": "엔드 가공 불가",
        "create_dragons_plus.ponder.bulk_ending.header": "대량 엔드 가공",
        "create_dragons_plus.ponder.bulk_ending.text_1": "드래곤 머리 또는 용의 숨결을 통과한 바람은 대량 엔드 가공 장치를 만듭니다",
        "recipe.create_dragons_plus.fan_ending": "대량 엔드 가공",
        "tag.block.create_dragons_plus.fan_processing_catalysts.ending": "대량 엔드 가공 촉매",
        "tag.fluid.create_dragons_plus.fan_processing_catalysts.ending": "대량 엔드 가공 촉매",
    },
    "create_enchantment_industry": {
        "fluid.create_enchantment_industry.infused_dragon_breath": "주입된 용의 숨결",
        "item.create_enchantment_industry.infused_dragon_breath_bucket": "주입된 용의 숨결 양동이",
        "itemGroup.create_enchantment_industry.apotheotic": "Create: Apotheotic Industry",
    },
}


CREATE_TOOLTIP_MARKUP_FIXES: dict[str, str] = {
    "block.create.copycat_panel.tooltip.behaviour1": "가능하면 _손에 든 아이템_을 _재료_로 적용합니다. _다시 클릭_하면 _방향_ 또는 _레드스톤 동력_ 상태를 전환합니다. _렌치_로 _재료를 초기화_합니다.",
    "block.create.copycat_step.tooltip.behaviour1": "가능하면 _손에 든 아이템_을 _재료_로 적용합니다. _다시 클릭_하면 _방향_ 또는 _레드스톤 동력_ 상태를 전환합니다. _렌치_로 _재료를 초기화_합니다.",
    "block.create.cuckoo_clock.tooltip.behaviour1": "_현재 시각_을 보여 주고 하루에 두 번 곡을 연주합니다. _정오_와 _플레이어가 잘 수 있는 저녁_에 한 번씩 _작동_합니다.",
    "block.create.cuckoo_clock.tooltip.summary": "공간을 _꾸미고_ _시간을 확인하기_ 좋은 정교한 공예품입니다.",
    "block.create.haunted_bell.tooltip.behaviour1": "_적대적 몹_이 생성될 수 있는 주변의 _빛이 없는 지점_을 표시합니다.",
    "block.create.item_hatch.tooltip.behaviour1": "설치된 _보관함_에 _손에 든 아이템_을 _넣습니다_. _웅크려 우클릭_하면 단축 바 아이템을 제외한 _모든 아이템_을 _넣습니다_.",
    "block.create.metal_bracket.tooltip.summary": "_축과 톱니바퀴_ 및 _파이프_를 견고한 산업풍 부품으로 _장식_합니다.",
    "block.create.nozzle.tooltip.summary": "_선풍기_ 앞에 부착해 개체에 미치는 효과를 _모든 방향_으로 퍼뜨립니다.",
    "block.create.placard.tooltip.behaviour2": "현재 _아이템_을 _제거_합니다.",
    "block.create.schematic_table.tooltip.summary": "저장된 설계도를 _빈 설계도_에 기록합니다.",
    "block.create.schematicannon.tooltip.behaviour1": "설계도 대포의 _설정 창_을 엽니다.",
    "block.create.seat.tooltip.behaviour1": "플레이어가 _좌석_에 앉습니다. 왼쪽 Shift를 누르면 _좌석_에서 내립니다.",
    "block.create.seat.tooltip.summary": "앉아서 이동을 즐기세요! 플레이어를 움직이는 _장치_에 고정합니다. 가구로도 좋고 여러 색이 있습니다.",
    "block.create.toolbox.tooltip.behaviour1": "_인벤토리 내용물_을 _보존_합니다.",
    "block.create.toolbox.tooltip.behaviour2": "_근처_ _플레이어_가 _공구상자_ _단축키_를 눌러 내용물에 _원격으로_ 접근할 수 있습니다.",
    "block.create.toolbox.tooltip.behaviour3": "_보관함 창_을 엽니다.",
    "block.create.turntable.tooltip.summary": "_회전력_으로 멀미를 일으킵니다.",
    "block.create.wooden_bracket.tooltip.summary": "_축과 톱니바퀴_ 및 _파이프_를 아늑한 나무 부품으로 _장식_합니다.",
    "create.gui.contraptions.not_fast_enough": "이 %1$s은(는) _충분한_ _회전_ _속도_로 돌고 있지 않은 것 같습니다.",
    "item.create.blaze_cake.tooltip.summary": "열심히 일하는 _블레이즈 버너_를 위한 맛있는 간식입니다. 힘껏 불타오르게 합니다!",
    "item.create.builders_tea.tooltip.summary": "하루를 시작하기에 완벽한 음료로, _의욕_과 _포만감_을 줍니다.",
    "item.create.cardboard_armor.tooltip.summary": "_착용 가능한_ _장비_로 _멋_과 _은신_을 높입니다.",
    "item.create.cardboard_sword.tooltip.summary": "콩! _대체로_ _해롭지 않은_ 강력한 무기입니다.",
    "item.create.copper_backtank.tooltip.behaviour1": "필요한 장비에 _압축_ _공기_를 공급합니다.",
    "item.create.copper_backtank.tooltip.behaviour2": "회전 속도에 따라 _압축_ _공기_를 _모읍니다_.",
    "item.create.copper_diving_boots.tooltip.behaviour1": "착용자는 액체에서 _더 빨리_ _가라앉고_, 물속에서 _걷고_ _뛸_ 수 있습니다. 또한 _기계식_ _벨트_의 영향을 받지 않습니다.",
    "item.create.creative_blaze_cake.tooltip.summary": "_블레이즈 버너_를 위한 아주 특별한 간식입니다. 먹은 블레이즈 버너는 _연료가 절대 떨어지지 않습니다_.",
    "item.create.extendo_grip.tooltip.behaviour2": "_내구도_를 _전혀_ 소모하지 않고 탱크의 _공기_ _압력_을 사용합니다.",
    "item.create.extendo_grip.tooltip.summary": "사용자의 _도달 거리를 크게 늘립니다_. _산소통_의 _공기_ _압력_으로 작동할 수 있습니다.",
    "item.create.handheld_worldshaper.tooltip.behaviour1": "_대상 블록_을 세계편집기가 설치할 _재료_로 지정합니다.",
    "item.create.handheld_worldshaper.tooltip.behaviour3": "세계편집기의 _설정 창_을 엽니다.",
    "item.create.linked_controller.tooltip.behaviour2": "_수동 설정 창_을 엽니다.",
    "item.create.linked_controller.tooltip.behaviour3": "_연결 모드_를 켠 뒤 _버튼 여섯 개_ 중 하나를 눌러 _레드스톤 링크의 주파수_에 연결합니다.",
    "item.create.linked_controller.tooltip.summary": "_손에 들고_ _조작_할 수 있으며, _레드스톤 링크_ 주파수를 _여섯_ _버튼_에 할당합니다.",
    "item.create.netherite_backtank.tooltip.behaviour1": "필요한 장비에 _압축_ _공기_를 공급합니다.",
    "item.create.netherite_backtank.tooltip.behaviour2": "회전 속도에 따라 _압축_ _공기_를 _모읍니다_.",
    "item.create.netherite_diving_boots.tooltip.behaviour1": "착용자는 액체에서 _더 빨리_ _가라앉고_, 물속에서 _걷고_ _뛸_ 수 있습니다. 또한 _기계식_ _벨트_의 영향을 받지 않습니다.",
    "item.create.netherite_diving_helmet.tooltip.summary": "_네더라이트 산소통_과 함께 착용하면 _극한의 열_로부터 보호받습니다. 효과를 보려면 _다리와 발_도 _네더라이트_로 덮어야 합니다.",
    "item.create.potato_cannon.tooltip.behaviour2": "_내구도_를 _전혀_ 소모하지 않고 탱크의 _공기_ _압력_을 사용합니다.",
    "item.create.potato_cannon.tooltip.summary": "집에서 기른 작물을 적에게 발사합니다. _산소통_의 _공기_ _압력_으로 작동할 수 있습니다.",
    "item.create.sand_paper.tooltip.behaviour1": "_보조 손_에 들고 있거나 _바닥_에 놓인 아이템을 _바라보며_ 사용하면 광택을 냅니다.",
    "item.create.schematic.tooltip.behaviour1": "화면의 도구로 위치를 지정할 수 있습니다.",
    "item.create.schematic.tooltip.behaviour2": "정확한 _좌표_를 입력하는 _설정 창_을 엽니다.",
    "item.create.schematic.tooltip.summary": "구조물의 홀로그램을 원하는 위치에 놓고 _설계도 대포_로 건설할 수 있습니다.",
    "item.create.schematic_and_quill.tooltip.summary": "세계의 _구조물을 저장_해 _.nbt 파일_로 만들 때 사용합니다.",
    "item.create.tree_fertilizer.tooltip.behaviour1": "_공간 조건_과 _관계없이_ 나무를 자라게 합니다.",
}


CREATE_RECHECK_FIXES["create"].update(CREATE_TOOLTIP_MARKUP_FIXES)
CREATE_RECHECK_FIXES["createaddition"].update(
    {
        "block.createaddition.connector.tooltip.behaviour2": "_구리 전선 타래_, _금 전선 타래_, 또는 _일렉트럼 전선 타래_를 사용해 최대 4개의 다른 단자와 _전선으로 연결_합니다.",
        "block.createaddition.small_light_connector.tooltip.behaviour2": "_구리 전선 타래_, _금 전선 타래_, 또는 _일렉트럼 전선 타래_를 사용해 최대 4개의 다른 단자와 _전선으로 연결_합니다.",
        "block.createaddition.large_connector.tooltip.behaviour2": "_금 전선 타래_ 또는 _일렉트럼 전선 타래_를 사용해 최대 6개의 다른 단자와 _전선으로 연결_합니다.",
    }
)
CREATE_RECHECK_FIXES["create_dragons_plus"].update(
    {
        "block.create_dragons_plus.fluid_hatch.tooltip.behaviour1": "_손에 든 아이템_의 _담긴 유체_를 설치된 _탱크_에 _넣습니다_. 아이템을 비울 수 없으면 반대로 _탱크_에서 아이템을 _채웁니다_.",
    }
)


def build_recheck_overrides(namespace: str) -> dict[str, str]:
    """검수한 기존 문구의 용어를 정규화하고 근거가 있는 교정을 덧씌운다."""
    english = load_json(WORK_ROOT / namespace / "en_us.json")
    korean = load_json(WORK_ROOT / namespace / "ko_kr.json")
    translated: dict[str, str] = {}
    replacements = CREATE_RECHECK_TERM_REPLACEMENTS.get(namespace, ())

    def apply_replacements(source: str, target: str) -> str:
        updated = target
        for before, after in replacements:
            updated = updated.replace(before, after)
        if "날개" in updated and "풍차 날개" not in updated and "Sail" in source:
            updated = updated.replace("날개", "풍차 날개")
        if any(
            token in source
            for token in (
                "Kinetic Input",
                "Kinetic components",
                "Kinetic Appliances",
                "Kinetic Blocks",
                "Kinetic Sources",
                "Powered by Kinetics",
                "Rotational Force",
                "Rotational Input",
                "Rotational Power",
                "input rotation",
                "kinetic contraptions",
                "kinetic network",
                "rotational force",
                "rotational power",
            )
        ):
            updated = updated.replace("동력", "회전력")
        return updated

    for key, source in english.items():
        target = korean[key]
        if not isinstance(source, str) or not isinstance(target, str):
            continue
        updated = apply_replacements(source, target)
        if updated != target:
            translated[key] = updated
    for key, target in OVERRIDES[namespace].items():
        source = english[key]
        if not isinstance(source, str) or not isinstance(target, str):
            continue
        updated = apply_replacements(source, target)
        if updated != target:
            translated[key] = updated
    translated.update(CREATE_RECHECK_FIXES.get(namespace, {}))
    return translated


for recheck_namespace in CREATE_RECHECK_FIXES | CREATE_RECHECK_TERM_REPLACEMENTS:
    OVERRIDES[recheck_namespace].update(build_recheck_overrides(recheck_namespace))


ALLOWED_ORIGINALS = {
    "",
    ".",
    '"%1$s"',
    "%1$s: %2$s",
    "%1$s -> %2$s",
    "%1$s: %2$s -> %3$s",
    " - %1$s",
    "%1$s:%3$s %4$s",
    "> %1$s x%2$s",
    " >| %1$s",
    " >> %1$s (%2$sm)",
    " ; ",
    " ;0;1;2;3;4;5;6;7;8;9",
    " ;A;B;C;D;E;F;G;H;I;J;K;L;M;N;O;P;Q;R;S;T;U;V;X;Y;Z",
    " ;K;M",
    "█;▓;▒",
    "3:00",
    "4:00",
    "8 RPM",
    "12 RPM",
    "16 RPM",
    "32 RPM",
    "Alt",
    "B",
    "Create",
    "Create Crafts & Additions",
    "Create: Dragons Plus",
    "Create: Enchantment Industry",
    "killtps",
    "tickTime",
    "Ctrl",
    "F#;F;E;D#;D;C#;C;B;A#;A;G#;G",
    "K;M",
    "K⚡",
    "m",
    "mB",
    "mB;B ",
    "pm",
    "RPM",
    "Shift",
    "su",
    "am",
    "k",
    "°",
    "Bells & Whistles",
    "Create: Aquatic Ambitions",
    "Create: Apotheotic Industry",
    "Create: Hypertube",
}


def dump_json(path: Path, value: object) -> None:
    """UTF-8 JSON을 안정된 형식으로 기록한다."""
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def normalize() -> dict[str, object]:
    """검수가 끝난 소규모 네임스페이스와 본체 신규 키를 반영한다."""
    rows = []
    for namespace, overrides in OVERRIDES.items():
        root = WORK_ROOT / namespace
        english = load_json(root / "en_us.json")
        korean = load_json(root / "ko_kr.json")
        unknown = sorted(set(overrides) - set(english))
        if unknown:
            raise KeyError(f"{namespace} 원문에 없는 키: {unknown}")
        changed = 0
        for key, translated in overrides.items():
            errors = validate_value(key, english[key], translated)
            if errors:
                raise ValueError("; ".join(errors))
            if korean[key] != translated:
                korean[key] = translated
                changed += 1
        dump_json(root / "ko_kr.json", korean)
        rows.append(
            {
                "namespace": namespace,
                "keys": len(english),
                "reviewed_overrides": len(overrides),
                "changed": changed,
            }
        )
    return {"namespaces": rows}


def verify_selected() -> tuple[dict[str, object], list[str]]:
    """현재 완성 대상으로 선택한 네임스페이스의 미번역과 형식을 검사한다."""
    errors = []
    rows = []
    complete_namespaces = {
        "create",
        "createaddition",
        "create_hypertube",
        "bellsandwhistles",
        "create_aquatic_ambitions",
        "create_dragons_plus",
        "create_enchantment_industry",
    }
    for namespace in OVERRIDES:
        root = WORK_ROOT / namespace
        english = load_json(root / "en_us.json")
        korean = load_json(root / "ko_kr.json")
        if list(english) != list(korean):
            errors.append(f"키 또는 순서 불일치: {namespace}")
            continue
        untranslated = []
        for key, source in english.items():
            target = korean[key]
            errors.extend(validate_value(key, source, target))
            if (
                isinstance(source, str)
                and isinstance(target, str)
                and not source.isupper()
                and source.count("_") != target.count("_")
            ):
                errors.append(f"강조 표식 불일치: {namespace}:{key}")
            if source == target and source not in ALLOWED_ORIGINALS:
                untranslated.append(key)
        if namespace in complete_namespaces and untranslated:
            errors.append(f"미번역: {namespace}:{untranslated[:30]}")
        rows.append(
            {
                "namespace": namespace,
                "keys": len(english),
                "untranslated": len(untranslated),
                "complete": namespace in complete_namespaces and not untranslated,
            }
        )
    report = {
        "namespaces": rows,
        "errors": errors,
        "status": "complete" if not errors else "incomplete",
    }
    dump_json(WORK_ROOT / "selected_validation.json", report)
    return report, errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("normalize", "verify-selected"))
    args = parser.parse_args()
    if args.command == "normalize":
        report = normalize()
        errors = []
    else:
        report, errors = verify_selected()
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
