#!/usr/bin/env python3
"""Eternal Starlight의 이름형 표시 문구를 일관된 한국어로 변환한다."""

from __future__ import annotations

import re

PHRASES = {
    "Eternal Starlight": "Eternal Starlight",
    "Starlight Dimension": "별빛 차원",
    "Red Starlight Crystal": "붉은 별빛 수정",
    "Blue Starlight Crystal": "푸른 별빛 수정",
    "Thermal Springstone": "열기 스프링스톤",
    "Oxidized Golem Steel": "산화된 골렘 강철",
    "Golem Steel": "골렘 강철",
    "Starlit Diamond": "별빛 다이아몬드",
    "Swamp Silver": "늪지 은",
    "Doomeden Bone": "둠든 뼈",
    "Lunar Monstrosity": "달빛 괴수",
    "Starlight Golem": "별빛 골렘",
    "Astral Golem": "별자리 골렘",
    "Grimstone Golem": "그림스톤 골렘",
    "Lonestar Skeleton": "외별 스켈레톤",
    "Nightfall Spider": "해질녘 거미",
    "Thirst Walker": "갈증 방랑자",
    "Shimmer Lacewing": "반짝날개풀잠자리",
    "Crystallized Moth": "결정화 나방",
    "Twilight Gaze": "황혼눈 물고기",
    "Starfire Bird": "별불꽃새",
    "Shadow Snail": "그림자 달팽이",
    "Tangled Hatred": "뒤엉킨 원한",
    "Lunar Dragonfly": "달빛 잠자리",
    "Aethersent Meteor": "에테르센트 유성",
    "Orb of Prophecy": "예언의 구체",
    "Seeking Eye": "탐색의 눈",
    "Chain of Souls": "영혼의 사슬",
    "Soulit Spectator": "영혼빛 관측기",
    "Dagger of Hunger": "허기의 단검",
    "Tooth of Hunger": "허기의 이빨",
    "Moonring Greatsword": "달고리 대검",
    "Crescent Spear": "초승달 창",
    "Moonring Bow": "달고리 활",
    "Moonring Longbow": "달고리 장궁",
    "Wand of Teleportation": "순간이동 지팡이",
    "Rage of Stars": "별의 격노",
    "Crystalborn Catalyst": "수정 태생 촉매기",
    "Energy Transmitter": "에너지 송신기",
    "Energy Emitter": "에너지 방출기",
    "Energy Accumulator": "에너지 축적기",
    "Energy Sword": "에너지 검",
    "Crystal Greatsword": "수정 대검",
    "Mechanical Crossbow": "기계식 쇠뇌",
    "Crystal Crossbow": "수정 쇠뇌",
    "Seeds Launcher": "씨앗 발사기",
    "Aetherstrike Rocket": "에테르 폭격 로켓",
    "Saltpeter Matchbox": "초석 성냥갑",
    "Butterfly Wings Amulet": "나비 날개 부적",
    "Battleaxe Pendant": "전투 도끼 펜던트",
    "Warhammer Pendant": "전투 망치 펜던트",
    "Crescent Pendant": "초승달 펜던트",
    "Fungus Amulet": "균류 부적",
    "Pearl Necklace": "진주 목걸이",
    "Glimmering Tablet": "희미하게 빛나는 서판",
    "Pungency Fruit": "알싸한 열매",
    "Silver Pungency Fruit": "은빛 알싸한 열매",
    "Tenacious Petal": "끈질긴 꽃잎",
    "Tenacious Vine": "끈질긴 덩굴",
    "Shivering Gel": "오한 젤",
    "Frozen Tube": "냉동관",
    "Sonar Bomb": "음파 폭탄",
    "Tear Bomb": "눈물 폭탄",
    "Tangled Skull": "뒤엉킨 해골",
    "Shattered Blade": "산산조각 칼날",
    "Shattered Sword": "산산조각 검",
    "Aurora Deer": "오로라 사슴",
    "Aurora Deer Antler": "오로라 사슴뿔",
    "Aurora Deer Steak": "오로라 사슴 스테이크",
    "Lunar Berries": "달빛 열매",
    "Nocturnal Millet": "야광 기장",
    "Forgotten Nocturnal Millet": "망각의 야광 기장",
    "Rotten Flesh Jerky": "썩은 살점 육포",
    "Ratlin Meat": "래틀린 고기",
    "Pungency Stew": "알싸한 스튜",
    "Silver Pungency Stew": "은빛 알싸한 스튜",
    "Ether River": "에테르 강",
    "Shimmer River": "반짝임 강",
    "Starlit Sea": "별빛 바다",
    "The Abyss": "심연",
    "Dark Swamp": "어두운 늪",
    "Cursed Garden": "저주받은 정원",
    "Golem Forge": "골렘 제련소",
    "Crystallized Desert": "결정화 사막",
    "Starlight Forest": "별빛 숲",
    "Dense Starlight Forest": "울창한 별빛 숲",
    "Starlight Dense Forest": "울창한 별빛 숲",
    "Starlight Permafrost Forest": "별빛 영구동토 숲",
    "Permafrost Forest": "영구동토 숲",
    "Permafrost Peaks": "영구동토 봉우리",
    "Starlight Taiga": "별빛 타이가",
    "Torreya Forest": "개비자나무 숲",
    "Scarlet Forest": "진홍 숲",
    "Warm Shore": "따뜻한 해안",
    "Icy Sea": "얼어붙은 바다",
    "Spiral Kelp Forest": "나선 켈프 숲",
    "Lush Shallow Sea": "무성한 얕은 바다",
    "Lucent Mycelium Isle": "빛나는 균사체 섬",
    "Umbral Plains": "그늘 평원",
    "Glimmer Scrubland": "희미한 관목지",
    "Portal Ruins": "차원문 폐허",
    "Stranghoul Den": "스트랭구울 소굴",
    "Lunar Wood": "달빛나무 목재",
    "Lunar Log": "달빛나무 원목",
    "Lunar Planks": "달빛나무 판자",
    "Lunar Leaves": "달빛나무 잎",
    "Lunar Sapling": "달빛나무 묘목",
    "Northland Wood": "북방나무 목재",
    "Northland Log": "북방나무 원목",
    "Northland Planks": "북방나무 판자",
    "Northland Leaves": "북방나무 잎",
    "Northland Sapling": "북방나무 묘목",
    "Scarlet Wood": "진홍나무 목재",
    "Scarlet Log": "진홍나무 원목",
    "Scarlet Planks": "진홍나무 판자",
    "Scarlet Leaves": "진홍나무 잎",
    "Scarlet Sapling": "진홍나무 묘목",
    "Torreya Wood": "개비자나무 목재",
    "Torreya Log": "개비자나무 원목",
    "Torreya Planks": "개비자나무 판자",
    "Torreya Leaves": "개비자나무 잎",
    "Torreya Sapling": "개비자나무 묘목",
    "Cradlewood Wood": "요람나무 목재",
    "Cradlewood Log": "요람나무 원목",
    "Cradlewood Planks": "요람나무 판자",
    "Cradlewood Leaves": "요람나무 잎",
    "Cradlewood Sapling": "요람나무 묘목",
    "Jinglestem Wood": "방울줄기 목재",
    "Jinglestem Log": "방울줄기 원목",
    "Jinglestem Planks": "방울줄기 판자",
    "Jinglestem Leaves": "방울줄기 잎",
    "Jinglestem Sapling": "방울줄기 묘목",
    "Banyin Wood": "바닌나무 목재",
    "Banyin Log": "바닌나무 원목",
    "Banyin Planks": "바닌나무 판자",
    "Banyin Leaves": "바닌나무 잎",
    "Banyin Sapling": "바닌나무 묘목",
    "Red Velvetumoss": "붉은 벨베투모스",
    "Blue Crystal Moss": "푸른 수정 이끼",
    "Red Crystal Moss": "붉은 수정 이끼",
    "Blue Crystal Roots": "푸른 수정 뿌리",
    "Red Crystal Roots": "붉은 수정 뿌리",
    "Blue Crystallized": "푸르게 결정화된",
    "Red Crystallized": "붉게 결정화된",
    "Glowing Mushroom": "발광 버섯",
    "Budding Thioquartz": "싹트는 티오쿼츠",
    "Block of Thioquartz": "티오쿼츠 블록",
    "Block of Saltpeter": "초석 블록",
    "Muddy Banyin Roots": "진흙 묻은 바닌나무 뿌리",
    "Scarlet Leaves Pile": "진홍나무 잎 더미",
    "Cake with Amaramber Candle": "아마램버 양초가 놓인 케이크",
    "Minecart with Tear Bomb": "눈물 폭탄이 실린 광산 수레",
    "The Gatekeeper": "문지기",
    "The Gatekeeper Spawn Egg": "문지기 생성 알",
    "The Gatekeeper Spawner": "문지기 생성기",
    "Eye of Seeking": "탐색의 눈",
    "Blossom of Stars": "별의 꽃",
    "Bow of Blood": "피의 활",
    "Eye of Doom": "파멸의 눈",
    "Ball Lightning": "구형 번개",
    "Potion of Hunger": "허기의 물약",
    "Splash Potion of Hunger": "투척용 허기의 물약",
    "Lingering Potion of Hunger": "잔류형 허기의 물약",
    "Arrow of Hunger": "허기의 화살",
    "Malarite Axe or Spear": "말라라이트 도끼 또는 창",
    "Moonring Material": "달고리 재료",
    "Raw Aethersent": "에테르센트 원석",
    "Raw Deepsilver": "심층 은 원석",
    "Raw Amaramber": "아마램버 원석",
    "Raw Flowglaze": "플로글레이즈 원석",
    "Banyin Roots": "바닌나무 뿌리",
    "Moonlight Bush": "월광 덤불",
    "Flare Bricks": "섬광 벽돌 블록",
    "Drying Rack": "건조대",
    "Abyssal Fire": "심연의 불",
    "Amaramber Fire": "아마램버 불꽃",
    "Starcore Light": "별핵 조명",
    "Orbflora Light": "구체꽃 조명",
    "Dusk Light": "땅거미 조명",
    "Reinforced Dusk Light": "보강된 땅거미 조명",
    "Doomeden Light": "둠든 조명",
    "Etheric Eye": "에테르의 눈",
    "Shattered Sword Blade": "산산조각 검의 칼날",
    "Glistering Morning Star": "반짝이는 모닝스타",
    "Starlight Silver Coin": "별빛 은화",
    "Energized Flame": "충전된 화염",
    "Meteor Shower": "유성우",
    "Thrown Potion Distance": "투척용 물약 사거리",
    "Switch Crest": "문장 전환",
    "Tangled": "뒤엉킨 자",
    "Tangled Spawn Egg": "뒤엉킨 자 생성 알",
    "Jinglestem Crisp": "바삭한 방울줄기",
    "Frozen Bomb": "냉동 폭탄",
    "Velvetumoss Ball": "벨베투모스 뭉치",
    "Crinoa Ball": "크리노아 뭉치",
    "Shot Seeds": "발사된 씨앗",
    "Block of": "블록",
    "Boat with Chest": "상자가 실린 보트",
    "Raft with Chest": "상자가 실린 뗏목",
    "Minecart with Chest": "상자가 실린 광산 수레",
    "Spawn Egg": "생성 알",
    "Smithing Template": "대장장이 형판",
    "Armor Trim": "갑옷 장식",
    "Trim Material": "장식 재료",
    "Music Disc": "음반",
    "Hanging Sign": "매달린 표지판",
    "Pressure Plate": "감압판",
    "Fence Gate": "울타리 문",
    "Coral Block": "산호 블록",
    "Coral Fan": "부채형 산호",
    "Potted": "화분에 심은",
    "Stripped": "껍질 벗긴",
    "Cracked": "금이 간",
    "Chiseled": "조각된",
    "Polished": "윤나는",
    "Cobbled": "조약돌",
    "Cut": "깎인",
    "Waxed": "밀랍칠한",
    "Oxidized": "산화된",
    "Reinforced": "보강된",
    "Suspicious": "수상한",
    "Glistering": "반짝이는",
    "Molten": "용융",
    "Raw": "원석",
    "Cooked": "익힌",
    "Wilted": "시든",
    "Withered": "말라죽은",
    "Dead": "죽은",
    "Tiny": "작은",
    "Small": "소형",
    "Tall": "키 큰",
    "Dense": "울창한",
    "Common": "일반",
    "Forest": "숲",
    "Desert": "사막",
    "Jungle": "정글",
    "Cold": "한랭",
    "Warm": "따뜻한",
    "Red": "붉은",
    "Blue": "푸른",
    "Green": "초록색",
    "Golden": "황금",
    "Silver": "은빛",
    "White": "하얀",
    "Black": "검은",
    "Gray": "회색",
    "Pink": "분홍색",
    "Purple": "보라색",
    "Orange": "주황색",
    "Magenta": "자홍색",
    "Yellow": "노란색",
    "Lime": "연두색",
    "Cyan": "청록색",
    "Brown": "갈색",
    "Dark Oak": "짙은 참나무",
    "Light Blue": "하늘색",
    "Light Gray": "회백색",
}

WORDS = {
    "Lunar": "달빛",
    "Starlight": "별빛",
    "Starlit": "별빛",
    "Starfire": "별불꽃",
    "Starcore": "별핵",
    "Aethersent": "에테르센트",
    "Thioquartz": "티오쿼츠",
    "Glacite": "글라사이트",
    "Amaramber": "아마램버",
    "Deepsilver": "심층 은",
    "Unrealium": "언리얼리움",
    "Malarite": "말라라이트",
    "Flowglaze": "플로글레이즈",
    "Radianite": "라디아나이트",
    "Nebulaite": "네뷸라이트",
    "Toxite": "톡사이트",
    "Atalphaite": "아탈파이트",
    "Stellagmite": "스텔라그마이트",
    "Grimstone": "그림스톤",
    "Voidstone": "공허석",
    "Springstone": "스프링스톤",
    "Abysslate": "심연판암",
    "Thermabysslate": "열심연판암",
    "Thermabyssal": "열심연",
    "Cryobysslate": "냉기심연판암",
    "Cryobyssal": "냉기심연",
    "Dimslag": "딤슬래그",
    "Amethysia": "아메티시아",
    "Crystallum": "크리스탈룸",
    "Crystalfleur": "수정꽃",
    "Crinoa": "크리노아",
    "Velvetumoss": "벨베투모스",
    "Bouldershroom": "바위버섯",
    "Nightfan": "밤부채",
    "Gladespike": "숲터가시",
    "Conebloom": "원뿔꽃",
    "Whisperbloom": "속삭임꽃",
    "Vividstalk": "선명줄기",
    "Fantabud": "환상꽃봉오리",
    "Thornbloom": "가시꽃",
    "Lumenstem": "빛줄기",
    "Fantafern": "환상고사리",
    "Fantagrass": "환상잔디",
    "Glintgrass": "반짝잔디",
    "Gloomcandle": "어둠양초",
    "Blazebank": "불꽃둑",
    "Circulush": "서큘러시",
    "Stonett": "스토넷",
    "Luminis": "루미니스",
    "Glowlis": "글로울리스",
    "Gloreed": "빛갈대",
    "Twilvewyrm": "트윌브웜",
    "Stellafly": "별파리",
    "Glimmerfly": "희미빛파리",
    "Jingling": "방울",
    "Orbflora": "구체꽃",
    "Marimold": "마리몰드",
    "Algaleaves": "해조잎",
    "Banyin": "바닌",
    "Cradlewood": "요람나무",
    "Jinglestem": "방울줄기",
    "Northland": "북방",
    "Scarlet": "진홍",
    "Torreya": "개비자나무",
    "Lunaris": "루나리스",
    "Mauve": "연보라",
    "Rosa": "로사",
    "Villi": "빌리",
    "Aureate": "황금빛",
    "Boarwarf": "보어워프",
    "Gleech": "글리치",
    "Seeker": "시커",
    "Creteor": "크리에터",
    "Stranghoul": "스트랭구울",
    "Ent": "엔트",
    "Ratlin": "래틀린",
    "Zombified": "좀비화된",
    "Yeti": "예티",
    "Freeze": "프리즈",
    "Permafrost": "퍼머프로스트",
    "Luminaris": "루미나리스",
    "Luminofish": "루미노피시",
    "Rookfish": "룩피시",
    "Tangled": "뒤엉킨",
    "Monstrosity": "괴수",
    "Gatekeeper": "문지기",
    "Astral": "별자리",
    "Galactic": "은하",
    "Etheric": "에테르",
    "Soulit": "영혼빛",
    "Bonemore": "본모어",
    "Candlash": "캔들래시",
    "Shadegrieve": "셰이드그리브",
    "Coldsnap": "콜드스냅",
    "Underminer": "언더마이너",
    "Twilight": "황혼",
    "Nightfall": "해질녘",
    "Nocturnal": "야광",
    "Abyssal": "심연",
    "Eternal": "영원한",
    "Shadow": "그림자",
    "Shimmer": "반짝임",
    "Aurora": "오로라",
    "Crystalborn": "수정 태생",
    "Crystal": "수정",
    "Crystallized": "결정화된",
    "Glowing": "발광",
    "Blazing": "타오르는",
    "Solar": "태양",
    "Eclipse": "일식",
    "Charged": "충전된",
    "Enchanted": "마법이 깃든",
    "Crisp": "바삭한",
    "Cinder": "잿불",
    "Popped": "튀긴",
    "Roasted": "구운",
    "Voracious": "탐욕스러운",
    "Blooming": "꽃피는",
    "Twining": "휘감는",
    "Keeper": "수호자",
    "Forge": "제련소",
    "Terra": "대지",
    "Wind": "바람",
    "Water": "물",
    "Blaze": "화염",
    "Light": "빛",
    "Absolute": "절대",
    "Zero": "영도",
    "Monstrous": "괴이한",
    "Energized": "충전됨",
    "Guardian": "수호자",
    "Original": "원본",
    "Umbrous": "어두운",
    "Riven": "갈라진",
    "Welkin": "창공",
    "Extinguished": "꺼진",
    "Novus": "노부스",
    "Sol": "태양",
    "Wall": "벽",
    "Slab": "반 블록",
    "Stairs": "계단",
    "Brick": "벽돌",
    "Bricks": "벽돌",
    "Tile": "타일",
    "Tiles": "타일",
    "Block": "블록",
    "Ore": "광석",
    "Log": "원목",
    "Wood": "목재",
    "Planks": "판자",
    "Leaves": "잎",
    "Sapling": "묘목",
    "Sign": "표지판",
    "Door": "문",
    "Trapdoor": "다락문",
    "Button": "버튼",
    "Fence": "울타리",
    "Grass": "잔디",
    "Dirt": "흙",
    "Mud": "진흙",
    "Sand": "모래",
    "Sandstone": "사암",
    "Gravel": "자갈",
    "Farmland": "경작지",
    "Path": "길",
    "Podzol": "회백토",
    "Moss": "이끼",
    "Carpet": "카펫",
    "Roots": "뿌리",
    "Root": "뿌리",
    "Vines": "덩굴",
    "Vine": "덩굴",
    "Plant": "식물",
    "Flower": "꽃",
    "Bush": "덤불",
    "Fern": "고사리",
    "Reed": "갈대",
    "Cactus": "선인장",
    "Mushroom": "버섯",
    "Orchid": "난초",
    "Lily": "수련",
    "Pad": "잎",
    "Duckweed": "개구리밥",
    "Sprouts": "새싹",
    "Stem": "줄기",
    "Bud": "꽃봉오리",
    "Berries": "열매",
    "Fruit": "열매",
    "Herb": "약초",
    "Kelp": "켈프",
    "Seagrass": "해초",
    "Coral": "산호",
    "Tentacles": "촉수",
    "Tentacle": "촉수",
    "Fan": "부채형",
    "Pillar": "기둥",
    "Bars": "창살",
    "Pane": "판",
    "Glass": "유리",
    "Grate": "격자",
    "Lantern": "랜턴",
    "Torch": "횃불",
    "Candle": "양초",
    "Campfire": "모닥불",
    "Icicle": "고드름",
    "Ice": "얼음",
    "Snow": "눈",
    "Magma": "마그마",
    "Geyser": "간헐천",
    "Cloud": "구름",
    "Air": "공기",
    "Bale": "꾸러미",
    "Panicle": "이삭",
    "Stalk": "줄기",
    "Cake": "케이크",
    "Cluster": "군집",
    "Shard": "조각",
    "Ingot": "주괴",
    "Nugget": "조각",
    "Powder": "가루",
    "Gel": "젤",
    "Hide": "가죽",
    "Fur": "털",
    "Shell": "껍데기",
    "Antler": "사슴뿔",
    "Bone": "뼈",
    "Blood": "피",
    "Soul": "영혼",
    "Souls": "영혼",
    "Petal": "꽃잎",
    "Vein": "광맥",
    "Sac": "주머니",
    "Egg": "알",
    "Spawner": "생성기",
    "Boat": "보트",
    "Raft": "뗏목",
    "Chest": "상자",
    "Minecart": "광산 수레",
    "Bucket": "양동이",
    "Sword": "검",
    "Greatsword": "대검",
    "Longbow": "장궁",
    "Bow": "활",
    "Crossbow": "쇠뇌",
    "Arrow": "화살",
    "Spear": "창",
    "Scythe": "대낫",
    "Sickle": "낫",
    "Dagger": "단검",
    "Axe": "도끼",
    "axe": "도끼",
    "Pickaxe": "곡괭이",
    "Shovel": "삽",
    "Hoe": "괭이",
    "Hammer": "망치",
    "Battleaxe": "전투 도끼",
    "Warhammer": "전투 망치",
    "Rapier": "레이피어",
    "Whip": "채찍",
    "Blade": "칼날",
    "Shield": "방패",
    "Hood": "두건",
    "Cape": "망토",
    "Bottoms": "하의",
    "Helmet": "투구",
    "Chestplate": "흉갑",
    "Leggings": "레깅스",
    "Boots": "부츠",
    "Armor": "갑옷",
    "Equipment": "장비",
    "Quiver": "화살통",
    "Mask": "가면",
    "Robe": "로브",
    "Skewer": "꼬치",
    "Brush": "붓",
    "Rocket": "로켓",
    "Bomb": "폭탄",
    "Snowball": "눈덩이",
    "Potion": "물약",
    "Splash": "투척용",
    "Lingering": "잔류형",
    "Stew": "스튜",
    "Porridge": "죽",
    "Sandwich": "샌드위치",
    "Pie": "파이",
    "Escargot": "에스카르고",
    "Meat": "고기",
    "Steak": "스테이크",
    "Jerky": "육포",
    "Flesh": "살점",
    "Ham": "햄",
    "Feast": "만찬",
    "Launcher": "발사기",
    "Matchbox": "성냥갑",
    "Pendant": "펜던트",
    "Amulet": "부적",
    "Wings": "날개",
    "Fungus": "균류",
    "Pearl": "진주",
    "Necklace": "목걸이",
    "Bag": "가방",
    "Coin": "동전",
    "Tablet": "서판",
    "Dew": "이슬",
    "Wand": "지팡이",
    "Teleportation": "순간이동",
    "Gravity": "중력",
    "Broken": "부서진",
    "Living": "살아 있는",
    "Arm": "팔",
    "Carrion": "썩은 고기",
    "Doom": "파멸",
    "Rag": "누더기",
    "Grinder": "분쇄기",
    "Orb": "구체",
    "Prophecy": "예언",
    "Meteor": "유성",
    "Flare": "섬광",
    "Haze": "안개",
    "Fire": "불",
    "Flame": "화염",
    "Fireball": "화염구",
    "Laser": "레이저",
    "Beam": "광선",
    "Spit": "침",
    "Breath": "숨결",
    "Spore": "포자",
    "Thorn": "가시",
    "Poisonous": "독성",
    "Husk": "허물",
    "Shot": "발사체",
    "Spark": "불꽃",
    "Lightning": "번개",
    "Falling": "떨어지는",
    "Painting": "그림",
    "Apple": "사과",
    "Starflowers": "별꽃",
    "Anomaly": "변칙",
    "Hut": "오두막",
    "Rat": "쥐",
    "Head": "머리",
    "Squid": "오징어",
    "Power": "동력",
    "Pot": "화분",
    "Crests": "문장",
    "Thirsty": "목마른",
    "Stack": "더미",
    "Slate": "판암",
    "Insect": "곤충",
    "Specimen": "표본",
    "Lake": "호수",
    "Hymn": "찬가",
    "Rats": "쥐들",
    "Cooler": "냉각기",
    "Gate": "문",
    "Ruins": "폐허",
    "Den": "소굴",
    "Aviary": "새장",
    "Bird": "새",
    "Snail": "달팽이",
    "Moth": "나방",
    "Lacewing": "풀잠자리",
    "Gaze": "응시",
    "Deer": "사슴",
    "Golem": "골렘",
    "Skeleton": "스켈레톤",
    "Spider": "거미",
    "Walker": "방랑자",
    "Material": "재료",
    "Trim": "장식",
    "Upgrade": "업그레이드",
    "Keyhole": "열쇠 구멍",
    "Key": "열쇠",
    "Lockbox": "잠금 상자",
    "Crate": "나무 상자",
    "Rack": "진열대",
    "Furnace": "화로",
    "Alloy": "합금",
    "Drying": "건조",
    "Accumulator": "축적기",
    "Transmitter": "송신기",
    "Emitter": "방출기",
    "Core": "핵",
    "Mat": "매트",
    "Mosaic": "모자이크",
    "Thin": "얇은",
    "Packed": "꽉 찬",
    "Mossy": "이끼 낀",
    "Dusted": "가루 묻은",
    "Cave": "동굴",
    "Night": "밤",
    "Morning": "아침",
    "Star": "별",
    "Sun": "태양",
    "Moonlight": "달빛",
    "Crescent": "초승달",
    "Aetherstrike": "에테르 폭격",
    "Mana": "마나",
    "Crest": "문장",
    "Shower": "소나기",
    "River": "강",
    "Sea": "바다",
    "Shore": "해안",
    "Plains": "평원",
    "Scrubland": "관목지",
    "Peaks": "봉우리",
    "Taiga": "타이가",
    "Lucent": "빛나는",
    "Mycelium": "균사체",
    "Isle": "섬",
    "Icy": "얼어붙은",
    "Lush": "무성한",
    "Shallow": "얕은",
    "Abyss": "심연",
    "Garden": "정원",
    "Thrown": "투척",
    "Distance": "거리",
    "Resistance": "저항",
    "Counterattack": "반격",
    "Chance": "확률",
    "Heal": "회복",
    "Multiplier": "배율",
    "Enemy": "적",
    "Follow": "추적",
    "Range": "범위",
    "Fog": "안개",
    "Vision": "시야",
    "Switch": "전환",
    "Smoking": "훈연",
    "Cooling": "냉각",
    "Overheat": "과열",
    "Time": "시간",
    "Add": "추가",
    "Muddy": "진흙 묻은",
    "Pile": "더미",
    "Hanging": "매달린",
    "Ashen": "잿빛",
    "Rose": "장미",
    "Torchflower": "횃불꽃",
    "Parasol": "파라솔",
    "Shining": "빛나는",
    "Swamp": "늪지",
    "Sunset": "노을",
    "Spiral": "나선",
    "Wick": "심지",
    "Pickle": "해삼",
    "Tenacious": "끈질긴",
    "Fantasy": "환상",
    "Nest": "둥지",
    "Oak": "참나무",
    "Spruce": "가문비나무",
    "Birch": "자작나무",
    "Acacia": "아카시아나무",
    "Cherry": "벚나무",
    "Crimson": "진홍빛",
    "Warped": "뒤틀린",
    "Mangrove": "맹그로브나무",
    "Bamboo": "대나무",
    "Saltpeter": "초석",
    "Redstone": "레드스톤",
    "Ether": "에테르",
    "Loot": "전리품",
    "Jet": "분사구",
    "Mechanical": "기계식",
    "Energy": "에너지",
    "Dusk": "땅거미",
    "Doomed": "파멸의",
    "Doomeden": "둠든",
    "Stellar": "별의",
    "Portal": "차원문",
    "Seeds": "씨앗",
    "Starfall": "별똥별",
    "Tear": "눈물",
    "or": "또는",
    "Weapon": "무기",
    "Tool": "도구",
    "Alchemist": "연금술사",
    "Eye": "눈",
    "Spike": "가시",
    "Boomerang": "부메랑",
    "Rotten": "썩은",
    "Hunger": "허기",
    "Grim": "음산한",
    "Seeking": "탐색",
    "Ball": "구체",
    "Carved": "조각된",
    "Frozen": "얼어붙은",
}

_WOOD_FAMILIES = {
    "Lunar": "달빛나무",
    "Northland": "북방나무",
    "Banyin": "바닌나무",
    "Scarlet": "진홍나무",
    "Torreya": "개비자나무",
    "Jinglestem": "방울줄기",
    "Cradlewood": "요람나무",
}

_WOOD_PRODUCTS = {
    "Sapling": "묘목",
    "Leaves": "잎",
    "Log": "원목",
    "Wood": "목재",
    "Planks": "판자",
    "Roots": "뿌리",
    "Door": "문",
    "Trapdoor": "다락문",
    "Pressure Plate": "감압판",
    "Button": "버튼",
    "Fence": "울타리",
    "Fence Gate": "울타리 문",
    "Slab": "반 블록",
    "Stairs": "계단",
    "Sign": "표지판",
    "Wall Sign": "벽걸이 표지판",
    "Hanging Sign": "매달린 표지판",
    "Wall Hanging Sign": "벽걸이 매달린 표지판",
    "Boat": "보트",
    "Boat with Chest": "상자가 실린 보트",
    "Raft": "뗏목",
    "Raft with Chest": "상자가 실린 뗏목",
    "Starfire Bird Aviary": "별불꽃새 새장",
}

for _wood_source, _wood_target in _WOOD_FAMILIES.items():
    for _product_source, _product_target in _WOOD_PRODUCTS.items():
        PHRASES.setdefault(
            f"{_wood_source} {_product_source}",
            f"{_wood_target} {_product_target}",
        )

_REPLACEMENTS = tuple(
    (
        re.compile(rf"(?<![A-Za-z]){re.escape(source)}(?![A-Za-z])"),
        target,
    )
    for source, target in sorted(
        {**WORDS, **PHRASES}.items(), key=lambda item: len(item[0]), reverse=True
    )
)


def translate_name(source: str) -> str | None:
    """이름형 영어 값을 용어집 기반 한국어로 바꾸고 미지원 값은 돌려보내지 않는다."""
    if source == "Eternal Starlight":
        return source
    block_match = re.fullmatch(r"(?:(Waxed) )?Block of (.+)", source)
    if block_match:
        content = translate_name(block_match.group(2))
        if content is None:
            return None
        prefix = "밀랍칠한 " if block_match.group(1) else ""
        return f"{prefix}{content} 블록"
    value = source
    for pattern, replacement in _REPLACEMENTS:
        value = pattern.sub(replacement, value)
    value = re.sub(r"\s+", " ", value).strip()
    if re.search(r"[A-Za-z]", value):
        return None
    return value
