#!/usr/bin/env python3
"""Eternal Starlight 효과·마법·툴팁·대화·명령 표시 문구의 검수 번역이다."""

TRANSLATIONS = {
    "effect.eternal_starlight.crystal_infection": "수정 감염",
    "effect.eternal_starlight.crystal_infection.description": "시간이 지날수록 치명적인 피해를 주고 방어력을 낮춥니다. 단계가 높을수록 피해와 방어력 감소량이 커집니다.",
    "effect.eternal_starlight.dream_catcher": "꿈잡이",
    "effect.eternal_starlight.dream_catcher.description": "방어력을 높입니다. 단계가 높을수록 더 많이 높입니다.",
    "effect.eternal_starlight.sticky": "달라붙음",
    "effect.eternal_starlight.sticky.description": "속도를 조금 낮추지만 어떤 블록이든 기어오를 수 있게 합니다. 단계가 높을수록 속도가 더 많이 낮아집니다.",
    "effect.eternal_starlight.flammable": "인화성",
    "effect.eternal_starlight.flammable.description": "대상이 받는 화염 피해를 높입니다. 단계가 높을수록 더 많이 높입니다.",
    "effect.eternal_starlight.brittle": "취성",
    "effect.eternal_starlight.brittle.description": "대상이 받는 동결 피해를 높입니다. 단계가 높을수록 더 많이 높입니다.",
    "effect.eternal_starlight.numbness": "무감각",
    "effect.eternal_starlight.numbness.description": "플레이어가 받는 피해의 4분의 3을 흡수했다가 효과가 끝날 때 다시 적용합니다.",
    "effect.eternal_starlight.teary": "눈물범벅",
    "effect.eternal_starlight.teary.description": "플레이어의 시야를 흐리고 몹의 공격 대상을 해제합니다. 영향을 받은 몹은 일정 시간이 지나면 이 효과에 면역이 됩니다.",
    "effect.eternal_starlight.starfire": "별불꽃",
    "effect.eternal_starlight.starfire.description": "효과를 받은 대상이 피해를 입으면 주변 몹도 피해를 입고, 대상이 죽으면 효과가 주변 몹에게 퍼집니다.",
    "effect.eternal_starlight.oblivion": "망각",
    "effect.eternal_starlight.oblivion.description": "발밑 블록의 지지는 받으면서 벽을 통과할 수 있습니다. 웅크리면 블록 아래로 내려갑니다. 이동 속도도 높이고 중력을 낮추며 적의 추적 범위를 줄입니다.",
    "enchantment.eternal_starlight.poisoning": "중독",
    "enchantment.eternal_starlight.poisoning.desc": "피해를 받으면 공격자를 중독시킵니다",
    "enchantment.eternal_starlight.fearless": "두려움 없음",
    "enchantment.eternal_starlight.fearless.desc": "밀치기를 강화하고 공격할 때 적에게 돌진합니다",
    "enchantment.eternal_starlight.soul_snatcher": "영혼 강탈",
    "enchantment.eternal_starlight.soul_snatcher.desc": "영혼의 사슬 피해를 높입니다",
    "enchantment.eternal_starlight.tracing": "추적",
    "enchantment.eternal_starlight.tracing.desc": "영혼의 사슬에 맞은 대상에게 발광 효과를 부여합니다",
    "enchantment.eternal_starlight.tearing": "눈물샘 자극",
    "enchantment.eternal_starlight.tearing.desc": "창으로 맞힌 대상에게 눈물범벅 효과를 부여합니다",
    "enchantment.eternal_starlight.overheat": "과열",
    "enchantment.eternal_starlight.overheat.desc": "발사한 씨앗에 불을 붙입니다",
    "enchantment.eternal_starlight.glacial_sowing": "빙하 파종",
    "enchantment.eternal_starlight.glacial_sowing.desc": "씨앗에 맞은 대상을 얼립니다",
    "enchantment.eternal_starlight.fertile": "다산",
    "enchantment.eternal_starlight.fertile.desc": "발사하는 씨앗 수를 늘립니다",
    "enchantment.eternal_starlight.precision": "정밀",
    "enchantment.eternal_starlight.precision.desc": "던진 부메랑으로 치명타를 가할 수 있습니다",
    "enchantment.eternal_starlight.homing": "유도",
    "enchantment.eternal_starlight.homing.desc": "던진 부메랑이 주변의 적을 추적합니다",
    "enchantment.eternal_starlight.gathering": "수집",
    "enchantment.eternal_starlight.gathering.desc": "던진 부메랑이 이동 경로의 아이템을 모읍니다",
    "enchantment.eternal_starlight.swift_lash": "신속한 채찍질",
    "enchantment.eternal_starlight.swift_lash.desc": "채찍의 공격 속도를 높입니다",
    "enchantment.eternal_starlight.abyssal_touch": "심연의 손길",
    "enchantment.eternal_starlight.abyssal_touch.desc": "적중한 대상을 심연의 불로 태웁니다",
    "tooltip.eternal_starlight.accessory_combined": "장비와 결합했을 때:",
    "tooltip.eternal_starlight.accessory_combination_target": "적용 대상:",
    "tooltip.eternal_starlight.accessory_combination_target.chestplate": "흉갑",
    "tooltip.eternal_starlight.accessory_combination_target.axe": "도끼",
    "tooltip.eternal_starlight.accessory_combination_target.hammer": "망치",
    "tooltip.eternal_starlight.accessories": "장신구:",
    "tooltip.eternal_starlight.accessory_slot_count": "장신구 슬롯 %1$s개",
    "tooltip.eternal_starlight.battleaxe_pendant.durability": "도끼로 공격할 때 줄어드는 내구도를 낮춥니다",
    "tooltip.eternal_starlight.battleaxe_pendant.strip": "도끼가 나무껍질을 벗기지 않게 합니다",
    "tooltip.eternal_starlight.warhammer_pendant.speed_based_damage": "이동 속도에 따라 피해가 증가합니다",
    "tooltip.eternal_starlight.butterfly_wings_amulet.armor_erosion": "에테르를 소모해 착용자를 공격하거나 착용자에게 공격받은 몹의 방어력을 깎습니다",
    "tooltip.eternal_starlight.fungus_amulet.consume_fungus": "착용자가 균류를 먹을 수 있게 합니다",
    "tooltip.eternal_starlight.pearl_necklace.instant_air_recovery": "착용자가 물 밖으로 나오면 산소를 즉시 채웁니다",
    "tooltip.eternal_starlight.crescent_pendant.damage_cap": "받는 피해를 착용자 최대 체력의 75% 이하로 제한합니다",
    "tooltip.eternal_starlight.crescent_pendant.repair": "달빛 괴수의 무기를 천천히 수리합니다",
    "tooltip.eternal_starlight.unwearable": "착용 불가",
    "tooltip.eternal_starlight.crest_spell_elements": "주문 원소:",
    "tooltip.eternal_starlight.use": "사용했을 때:",
    "tooltip.eternal_starlight.full_set": "한 벌을 모두 착용했을 때:",
    "tooltip.eternal_starlight.dual_wielding": "쌍수로 들었을 때:",
    "tooltip.eternal_starlight.dual_wielding.offhand_attack": "사용 키를 눌러 보조 손 무기로 공격합니다",
    "tooltip.eternal_starlight.seeking_eye.target": "특정 대상을 찾을 때:",
    "tooltip.eternal_starlight.seeking_eye.associated_item": "다른 손에 관련 아이템을 드세요",
    "tooltip.eternal_starlight.etheric_eye": "사용자를 지상으로 순간이동시킵니다",
    "tooltip.eternal_starlight.thermal_springstone_armor": "피해를 받으면 적에게 불을 붙입니다",
    "tooltip.eternal_starlight.glacite_armor": "피해를 받으면 적을 얼립니다",
    "tooltip.eternal_starlight.deepsilver_armor": "특정 부정적 효과에 면역이 됩니다",
    "tooltip.eternal_starlight.unrealium_helmet": "블록 안 질식 피해에 면역이 됩니다",
    "tooltip.eternal_starlight.unrealium_chestplate": "개체 밀집 피해에 면역이 됩니다",
    "tooltip.eternal_starlight.unrealium_helmet.mute": "먹는 소리를 음소거합니다",
    "tooltip.eternal_starlight.unrealium_chestplate.mute": "피해 소리를 음소거합니다",
    "tooltip.eternal_starlight.unrealium_leggings.mute": "낙하 및 물 튀는 소리를 음소거합니다",
    "tooltip.eternal_starlight.unrealium_boots.mute": "발걸음 소리를 음소거합니다",
    "tooltip.eternal_starlight.seeds_launcher.ammo": "씨앗 발사기 탄약으로 사용 시: ",
    "tooltip.eternal_starlight.seeds_launcher.damage_multiplier": "피해 %1$s",
    "tooltip.eternal_starlight.seeds_launcher.speed_multiplier": "속도 %1$s",
    "tooltip.eternal_starlight.seeds_launcher.cooldown": "재사용 대기시간 %1$s초",
    "tooltip.eternal_starlight.flowglaze_weapon": "같은 대상을 연속 공격하면 피해가 증가합니다",
    "tooltip.eternal_starlight.flowglaze_tool": "채굴 시간이 기준을 넘으면 블록을 즉시 파괴합니다",
    "tooltip.eternal_starlight.flowglaze_bow": "화살이 날아간 시간에 따라 피해가 증가합니다",
    "tooltip.eternal_starlight.flowglaze_shield": "방어할 때 투사체를 반사합니다",
    "tooltip.eternal_starlight.underminer": "깊이 내려갈수록 채굴 속도가 증가합니다",
    "tooltip.eternal_starlight.blossom_of_stars": "사색하는 이에게!",
    "crest.eternal_starlight.boulders_shield": "바위의 방패",
    "crest.eternal_starlight.boulders_shield.desc": "저항 효과를 부여합니다",
    "crest.eternal_starlight.guidance_of_stars": "별의 인도",
    "crest.eternal_starlight.guidance_of_stars.desc": "강력한 생물이 사는 폐허를 찾도록 도와줍니다",
    "crest.eternal_starlight.blazing_beam": "타오르는 광선",
    "crest.eternal_starlight.blazing_beam.desc": "바라보는 방향으로 레이저 광선을 발사합니다",
    "message.eternal_starlight.enchanted_grimstone_pre": "꺼... 꺼내... 꺼내 줘...",
    "message.eternal_starlight.enchanted_grimstone_post": "고... 고... 고마워...",
    "message.eternal_starlight.no_crest": "현재 보유한 문장이 없습니다.",
    "message.eternal_starlight.gatekeeper_intro": "어서 오십시오, 모험가여! 무엇을 도와드릴까요?",
    "message.eternal_starlight.gatekeeper_challenge": "도전한다",
    "message.eternal_starlight.gatekeeper_rematch": "나 또는 엔더 드래곤을 쓰러뜨렸으니 그대의 힘은 의심할 여지가 없군요. 다시 나와 겨루고 싶다면 도전을 받아들이겠습니다.",
    "message.eternal_starlight.gatekeeper_challenge_confirm": "그 용기는 존중합니다! 하지만 이 도전을 가볍게 보아서는 안 됩니다. 지금... 정말 나와 맞설 준비가 되었습니까?",
    "message.eternal_starlight.gatekeeper_do_not": "아니요",
    "message.eternal_starlight.gatekeeper_trade": "거래한다",
    "message.eternal_starlight.gatekeeper_deny_trade": "나와 거래하려면 먼저 전투에서 그대의 가치를 증명해야 합니다.",
    "message.eternal_starlight.gatekeeper_confirm": "예",
    "message.eternal_starlight.gatekeeper_leave": "이곳을 떠나 달라고 한다",
    "message.eternal_starlight.gatekeeper_leave_confirm": "아주 오랫동안 이곳을 지켰으니 어쩌면 내게도 휴식이 필요하겠지요. 하지만 내가 떠나면 더는 내게 도전하거나 나와 거래할 수 없습니다. 정말... 그것이 그대의 뜻입니까?",
    "message.eternal_starlight.gatekeeper_nothing": "아무것도 아닙니다",
    "message.eternal_starlight.gatekeeper_farewell": "그럼 작별입니다. 부디 안전한 여정이 되기를.",
    "message.eternal_starlight.dream_catcher_0": "그 무엇도 당신을 꺾을 수 없어요...",
    "message.eternal_starlight.dream_catcher_1": "절대 포기하지 마세요...",
    "message.eternal_starlight.dream_catcher_2": "당신이라면 할 수 있어요...",
    "message.eternal_starlight.dream_catcher_3": "꿈을 좇으세요...",
    "message.eternal_starlight.dream_catcher_4": "힘내요!",
    "message.eternal_starlight.dream_catcher_5": "넘어지고 쓰러져도 다시 땅을 딛고 일어나세요...",
    "message.eternal_starlight.dream_catcher_6": "갑옷을 다시 하나로 잇는 거예요!",
    "commands.eternal_starlight.weather.set": "날씨를 %s(으)로 설정했습니다",
    "commands.eternal_starlight.weather.fail": "날씨를 %s(으)로 설정하지 못했습니다",
    "commands.eternal_starlight.weather.clear": "날씨를 맑음으로 설정했습니다",
    "commands.eternal_starlight.weather.clear_fail": "날씨를 맑음으로 설정하지 못했습니다",
    "commands.eternal_starlight.crest.give": "문장을 지급했습니다",
    "commands.eternal_starlight.crest.give_fail": "문장을 지급하지 못했습니다",
    "commands.eternal_starlight.crest.remove": "문장을 제거했습니다",
    "commands.eternal_starlight.crest.remove_fail": "문장을 제거하지 못했습니다",
    "gui.eternal_starlight.jei.category.geyser_smoking": "간헐천 훈연",
    "gui.eternal_starlight.jei.category.drying": "건조",
    "gui.eternal_starlight.jei.category.alloy": "합금",
    "gui.eternal_starlight.jei.category.alloy_furnace_cooling": "합금 화로 냉각",
    "gui.eternal_starlight.jei.category.alloy_furnace_cooling.efficiency": "과열 시간 %s배",
    "item.eternal_starlight.smithing_template.pungency_fruit_upgrade.base_slot_description": "말라라이트 도끼 또는 창을 추가하세요",
    "item.eternal_starlight.smithing_template.starfire_upgrade.base_slot_description": "열기 스프링스톤 무기 또는 도구를 추가하세요",
    "item.eternal_starlight.smithing_template.flowglaze_upgrade.base_slot_description": "글라사이트 무기 또는 도구를 추가하세요",
    "item.eternal_starlight.smithing_template.pungency_fruit_upgrade.additions_slot_description": "알싸한 열매를 추가하세요",
    "item.eternal_starlight.smithing_template.starfire_upgrade.additions_slot_description": "별불꽃을 추가하세요",
    "item.eternal_starlight.smithing_template.flowglaze_upgrade.additions_slot_description": "플로글레이즈를 추가하세요",
}
