#!/usr/bin/env python3
"""Eternal Starlight의 사망 메시지와 소리 자막 검수 번역이다."""

DEATH_TRANSLATIONS = {
    "death.attack.eternal_starlight.ether": "%1$s이(가) 허공으로 흩어졌습니다",
    "death.attack.eternal_starlight.ether.player": "%1$s이(가) %2$s에게서 도망치려다 허공으로 흩어졌습니다",
    "death.attack.eternal_starlight.ether.item": "%1$s이(가) %3$s의 영향으로 허공에 흩어졌습니다",
    "death.attack.eternal_starlight.meteor": "%1$s이(가) 유성에 맞았습니다",
    "death.attack.eternal_starlight.meteor.player": "%1$s이(가) %2$s에게서 도망치려다 유성에 맞았습니다",
    "death.attack.eternal_starlight.meteor.item": "%1$s이(가) %3$s에서 날아온 유성에 맞았습니다",
    "death.attack.eternal_starlight.crystal_infection": "%1$s이(가) 수정으로 뒤덮였습니다",
    "death.attack.eternal_starlight.crystal_infection.player": "%1$s이(가) %2$s에게서 도망치려다 수정으로 뒤덮였습니다",
    "death.attack.eternal_starlight.wilt": "%1$s이(가) 시들어 먼지가 되었습니다",
    "death.attack.eternal_starlight.wilt.player": "%1$s이(가) %2$s에게서 도망치려다 시들어 먼지가 되었습니다",
    "death.attack.eternal_starlight.wilt.item": "%1$s이(가) %3$s의 영향으로 시들어 먼지가 되었습니다",
    "death.attack.eternal_starlight.ground_smash": "%1$s이(가) 지진을 온몸으로 겪었습니다",
    "death.attack.eternal_starlight.ground_smash.player": "%1$s이(가) %2$s에게서 도망치려다 지진을 온몸으로 겪었습니다",
    "death.attack.eternal_starlight.shattered_blade": "%1$s이(가) 산산조각 났습니다",
    "death.attack.eternal_starlight.shattered_blade.player": "%1$s이(가) %2$s에게서 도망치려다 산산조각 났습니다",
    "death.attack.eternal_starlight.shattered_blade.item": "%1$s이(가) %3$s을(를) 든 %2$s에게 산산조각 났습니다",
    "death.attack.eternal_starlight.sonar": "%1$s의 고막이 터졌습니다",
    "death.attack.eternal_starlight.sonar.player": "%1$s이(가) %2$s에게서 도망치려다 고막이 터졌습니다",
    "death.attack.eternal_starlight.dagger_of_hunger": "%1$s이(가) 먹어 치워졌습니다",
    "death.attack.eternal_starlight.dagger_of_hunger.player": "%1$s이(가) %2$s에게서 도망치려다 먹어 치워졌습니다",
    "death.attack.eternal_starlight.soul_absorb": "%1$s이(가) 영혼을 잃었습니다",
    "death.attack.eternal_starlight.soul_absorb.player": "%1$s이(가) %2$s에게서 도망치려다 영혼을 잃었습니다",
    "death.attack.eternal_starlight.soul_absorb.item": "%1$s의 영혼이 %3$s을(를) 든 %2$s에게 빼앗겼습니다",
    "death.attack.eternal_starlight.numbness": "%1$s의 몸이 뒤늦게 피해를 깨달았습니다",
    "death.attack.eternal_starlight.numbness.player": "%1$s이(가) %2$s에게서 도망치려다 뒤늦게 피해를 깨달았습니다",
    "death.attack.eternal_starlight.seeds": "%1$s이(가) 고속으로 날아온 씨앗에 꿰뚫렸습니다",
    "death.attack.eternal_starlight.seeds.player": "%1$s이(가) %2$s에게서 도망치려다 고속으로 날아온 씨앗에 꿰뚫렸습니다",
    "death.attack.eternal_starlight.seeds.item": "%1$s이(가) %3$s에서 발사된 고속 씨앗에 꿰뚫렸습니다",
    "death.attack.eternal_starlight.starfire": "%1$s이(가) 별불꽃에 타서 재가 되었습니다",
    "death.attack.eternal_starlight.starfire.player": "%1$s이(가) %2$s에게서 도망치려다 별불꽃에 타서 재가 되었습니다",
    "death.attack.eternal_starlight.starfire.item": "%1$s이(가) %3$s의 별불꽃에 타서 재가 되었습니다",
    "death.attack.eternal_starlight.laser": "%1$s이(가) 레이저에 꿰뚫렸습니다",
    "death.attack.eternal_starlight.laser.player": "%1$s이(가) %2$s에게서 도망치려다 레이저에 꿰뚫렸습니다",
    "death.attack.eternal_starlight.laser.item": "%1$s이(가) %3$s에서 발사된 레이저에 꿰뚫렸습니다",
    "death.attack.eternal_starlight.energized_flame": "%1$s이(가) 과부하되었습니다",
    "death.attack.eternal_starlight.energized_flame.player": "%1$s이(가) %2$s에게서 도망치려다 과부하되었습니다",
    "death.attack.eternal_starlight.freeze": "%1$s이(가) 얼음 조각상으로 얼어붙었습니다",
    "death.attack.eternal_starlight.freeze.player": "%1$s이(가) %2$s에게서 도망치려다 얼음 조각상으로 얼어붙었습니다",
    "death.attack.eternal_starlight.electric_shock": "%1$s이(가) 감전되었습니다",
    "death.attack.eternal_starlight.electric_shock.player": "%1$s이(가) %2$s에게서 도망치려다 감전되었습니다",
    "death.attack.eternal_starlight.electric_shock.item": "%1$s이(가) %3$s에 감전되었습니다",
    "death.attack.eternal_starlight.poison": "%1$s이(가) 맹독으로 죽었습니다",
    "death.attack.eternal_starlight.poison.player": "%1$s이(가) %2$s에게서 도망치려다 맹독으로 죽었습니다",
    "death.attack.eternal_starlight.poison.item": "%1$s이(가) %3$s에서 나온 맹독으로 죽었습니다",
    "death.attack.eternal_starlight.bite": "%1$s이(가) 물려 죽었습니다",
    "death.attack.eternal_starlight.bite.player": "%1$s이(가) %2$s에게서 도망치려다 물려 죽었습니다",
}

SUBTITLE_TRANSLATIONS = {
    "subtitles.item.armor.eternal_starlight.equip_amaramber": "아마램버 갑옷이 바스락거림",
    "subtitles.item.armor.eternal_starlight.equip_aethersent": "에테르센트 갑옷이 바스락거림",
    "subtitles.item.armor.eternal_starlight.equip_alchemist": "연금술사 갑옷이 바스락거림",
    "subtitles.item.armor.eternal_starlight.equip_thermal_springstone": "열기 스프링스톤 갑옷이 철컹거림",
    "subtitles.item.armor.eternal_starlight.equip_glacite": "글라사이트 갑옷이 철컹거림",
    "subtitles.item.armor.eternal_starlight.equip_starlit_diamond": "별빛 다이아몬드 갑옷이 철컹거림",
    "subtitles.item.armor.eternal_starlight.equip_deepsilver": "심층 은 갑옷이 철컹거림",
    "subtitles.item.armor.eternal_starlight.equip_unrealium": "언리얼리움 갑옷이 철컹거림",
    "subtitles.item.eternal_starlight.whip.swish": "채찍이 바람을 가름",
    "subtitles.item.eternal_starlight.whip.crack": "채찍이 터지는 소리를 냄",
    "subtitles.item.eternal_starlight.crystal_greatsword.chime": "수정 대검이 울림",
    "subtitles.item.eternal_starlight.chain_of_souls.absorb": "영혼의 사슬이 흡수함",
    "subtitles.item.eternal_starlight.crescent_spear.throw": "초승달 창이 던져짐",
    "subtitles.item.eternal_starlight.seeds_launcher.shoot": "씨앗 발사기가 발사됨",
    "subtitles.entity.eternal_starlight.aethersent_meteor.whoosh": "에테르센트 유성이 날아감",
    "subtitles.entity.eternal_starlight.laser_beam.hum": "레이저 광선이 윙윙거림",
    "subtitles.entity.eternal_starlight.frozen_tube.throw": "냉동관이 던져짐",
    "subtitles.entity.eternal_starlight.frozen_tube.break": "냉동관이 깨짐",
    "subtitles.entity.eternal_starlight.sonar_bomb.explode": "음파 폭탄이 폭발함",
    "subtitles.entity.eternal_starlight.starfire.whoosh": "별불꽃이 날아감",
    "subtitles.entity.eternal_starlight.seeking_eye.launch": "탐색의 눈이 발사됨",
    "subtitles.entity.eternal_starlight.seeking_eye.death": "탐색의 눈이 떨어짐",
    "subtitles.entity.eternal_starlight.boarwarf.ambient": "보어워프가 코웃음 침",
    "subtitles.entity.eternal_starlight.boarwarf.hurt": "보어워프가 다침",
    "subtitles.entity.eternal_starlight.boarwarf.death": "보어워프가 죽음",
    "subtitles.entity.eternal_starlight.boarwarf.yes": "보어워프가 동의함",
    "subtitles.entity.eternal_starlight.boarwarf.no": "보어워프가 반대함",
    "subtitles.entity.eternal_starlight.boarwarf.trade": "보어워프가 거래함",
    "subtitles.entity.eternal_starlight.astral_golem.attack": "별자리 골렘이 공격함",
    "subtitles.entity.eternal_starlight.astral_golem.death": "별자리 골렘이 죽음",
    "subtitles.entity.eternal_starlight.astral_golem.hurt": "별자리 골렘이 다침",
    "subtitles.entity.eternal_starlight.astral_golem.repair": "별자리 골렘이 수리됨",
    "subtitles.entity.eternal_starlight.ent.hurt": "엔트가 다침",
    "subtitles.entity.eternal_starlight.aurora_deer.ambient": "오로라 사슴이 욺",
    "subtitles.entity.eternal_starlight.aurora_deer.hurt": "오로라 사슴이 다침",
    "subtitles.entity.eternal_starlight.aurora_deer.death": "오로라 사슴이 죽음",
    "subtitles.entity.eternal_starlight.starfire_bird.ambient": "별불꽃새가 지저귐",
    "subtitles.entity.eternal_starlight.starfire_bird.hurt": "별불꽃새가 다침",
    "subtitles.entity.eternal_starlight.starfire_bird.death": "별불꽃새가 죽음",
    "subtitles.entity.eternal_starlight.aethersent_golem.hurt": "에테르센트 골렘이 다침",
    "subtitles.entity.eternal_starlight.aethersent_golem.death": "에테르센트 골렘이 죽음",
    "subtitles.entity.eternal_starlight.aethersent_golem.shoot": "에테르센트 골렘이 발사함",
    "subtitles.entity.eternal_starlight.seeker.hurt": "시커가 다침",
    "subtitles.entity.eternal_starlight.seeker.death": "시커가 죽음",
    "subtitles.entity.eternal_starlight.thirst_walker.ambient": "갈증 방랑자가 신음함",
    "subtitles.entity.eternal_starlight.thirst_walker.hurt": "갈증 방랑자가 다침",
    "subtitles.entity.eternal_starlight.thirst_walker.death": "갈증 방랑자가 죽음",
    "subtitles.entity.eternal_starlight.creteor.roll": "크리에터가 구름",
    "subtitles.entity.eternal_starlight.creteor.hurt": "크리에터가 다침",
    "subtitles.entity.eternal_starlight.creteor.death": "크리에터가 죽음",
    "subtitles.entity.eternal_starlight.creteor.charge": "크리에터가 돌진을 준비함",
    "subtitles.entity.eternal_starlight.creteor.explode": "크리에터가 폭발함",
    "subtitles.entity.eternal_starlight.stranghoul.ambient": "스트랭구울이 으르렁거림",
    "subtitles.entity.eternal_starlight.stranghoul.hurt": "스트랭구울이 다침",
    "subtitles.entity.eternal_starlight.stranghoul.death": "스트랭구울이 죽음",
    "subtitles.entity.eternal_starlight.stranghoul.shoot": "스트랭구울이 발사함",
    "subtitles.entity.eternal_starlight.luminofish.hurt": "루미노피시가 다침",
    "subtitles.entity.eternal_starlight.luminofish.death": "루미노피시가 죽음",
    "subtitles.entity.eternal_starlight.luminofish.flop": "루미노피시가 퍼덕임",
    "subtitles.entity.eternal_starlight.luminaris.hurt": "루미나리스가 다침",
    "subtitles.entity.eternal_starlight.luminaris.death": "루미나리스가 죽음",
    "subtitles.entity.eternal_starlight.luminaris.flop": "루미나리스가 퍼덕임",
    "subtitles.entity.eternal_starlight.twilight_gaze.hurt": "황혼눈 물고기가 다침",
    "subtitles.entity.eternal_starlight.twilight_gaze.death": "황혼눈 물고기가 죽음",
    "subtitles.entity.eternal_starlight.the_gatekeeper.parry": "문지기가 공격을 쳐냄",
    "subtitles.entity.eternal_starlight.starlight_golem.hurt": "별빛 골렘이 다침",
    "subtitles.entity.eternal_starlight.starlight_golem.block": "별빛 골렘이 막음",
    "subtitles.entity.eternal_starlight.starlight_golem.death": "별빛 골렘이 죽음",
    "subtitles.entity.eternal_starlight.starlight_golem.prepare_beam": "별빛 골렘이 광선 공격을 준비함",
    "subtitles.entity.eternal_starlight.starlight_golem.prepare_charge": "별빛 골렘이 돌진을 준비함",
    "subtitles.entity.eternal_starlight.freeze.hurt": "프리즈가 다침",
    "subtitles.entity.eternal_starlight.freeze.death": "프리즈가 죽음",
    "subtitles.entity.eternal_starlight.permafrost.hurt": "퍼머프로스트가 다침",
    "subtitles.entity.eternal_starlight.permafrost.death": "퍼머프로스트가 죽음",
    "subtitles.entity.eternal_starlight.permafrost.sneeze": "퍼머프로스트가 재채기함",
    "subtitles.entity.eternal_starlight.lunar_monstrosity.hurt": "달빛 괴수가 다침",
    "subtitles.entity.eternal_starlight.lunar_monstrosity.death": "달빛 괴수가 죽음",
    "subtitles.entity.eternal_starlight.lunar_monstrosity.bite": "달빛 괴수가 물어뜯음",
    "subtitles.entity.eternal_starlight.lunar_monstrosity.roar": "달빛 괴수가 포효함",
    "subtitles.entity.eternal_starlight.tangled_skull.ambient": "뒤엉킨 해골이 속삭임",
    "subtitles.entity.eternal_starlight.tangled_skull.roar": "뒤엉킨 해골이 포효함",
    "subtitles.block.eternal_starlight.ether.transform": "에테르가 변형됨",
    "subtitles.block.eternal_starlight.stellar_rack.ambient": "별의 진열대가 불길하게 윙윙거림",
}
