#!/usr/bin/env python3
"""Eternal Starlight 발전 과제 122개 표시 문구의 검수 번역이다."""

TRANSLATIONS = {
    "advancements.eternal_starlight.root.title": "Eternal Starlight",
    "advancements.eternal_starlight.root.description": "별빛 차원을 탐험하세요!",
    "advancements.eternal_starlight.challenge_gatekeeper.title": "한판 붙자!",
    "advancements.eternal_starlight.challenge_gatekeeper.description": "문지기의 시험을 통과하세요",
    "advancements.eternal_starlight.obtain_orb_of_prophecy.title": "심오한 마법",
    "advancements.eternal_starlight.obtain_orb_of_prophecy.description": "차원문을 열 수 있는 예언의 구체를 획득하세요",
    "advancements.eternal_starlight.enter_starlight.title": "백만 별의 하늘",
    "advancements.eternal_starlight.enter_starlight.description": "별빛 차원에 들어가세요",
    "advancements.eternal_starlight.obtain_seeking_eye.title": "별빛의 인도",
    "advancements.eternal_starlight.obtain_seeking_eye.description": "탐색의 눈을 획득하세요",
    "advancements.eternal_starlight.obtain_scythe.title": "혼돈, 혼돈",
    "advancements.eternal_starlight.obtain_scythe.description": "대낫을 제작하세요",
    "advancements.eternal_starlight.enter_abyss.title": "마리아나 해구",
    "advancements.eternal_starlight.enter_abyss.description": "심연 생물 군계에 들어가세요",
    "advancements.eternal_starlight.obtain_red_velvetumoss_flower.title": "심연의 낭만",
    "advancements.eternal_starlight.obtain_red_velvetumoss_flower.description": "붉은 벨베투모스 꽃을 획득하세요",
    "advancements.eternal_starlight.under_permafrost_forest.title": "영구동토 아래",
    "advancements.eternal_starlight.under_permafrost_forest.description": "영구동토 숲의 잿빛 눈 지층에 들어가세요",
    "advancements.eternal_starlight.obtain_glacite_shard.title": "나의 12월",
    "advancements.eternal_starlight.obtain_glacite_shard.description": "글라사이트 조각을 획득하세요",
    "advancements.eternal_starlight.obtain_glacite_arrow.title": "눈 완두콩",
    "advancements.eternal_starlight.obtain_glacite_arrow.description": "글라사이트 화살을 제작하세요",
    "advancements.eternal_starlight.obtain_frozen_bomb.title": "먼지 낀 하늘 아래",
    "advancements.eternal_starlight.obtain_frozen_bomb.description": "냉동 폭탄을 제작하세요",
    "advancements.eternal_starlight.obtain_aurora_deer_antler.title": "긁어 부스럼",
    "advancements.eternal_starlight.obtain_aurora_deer_antler.description": "오로라 사슴을 화나게 해 단단한 블록에 부딪치게 한 뒤 사슴뿔을 챙기세요",
    "advancements.eternal_starlight.enter_crystallized_desert.title": "유리의 성",
    "advancements.eternal_starlight.enter_crystallized_desert.description": "결정화 사막 생물 군계에 들어가세요",
    "advancements.eternal_starlight.obtain_crinoa_seeds.title": "한 알의 수정",
    "advancements.eternal_starlight.obtain_crinoa_seeds.description": "크리노아 씨앗을 획득하세요",
    "advancements.eternal_starlight.obtain_tooth_of_hunger.title": "치과 수술",
    "advancements.eternal_starlight.obtain_tooth_of_hunger.description": "갈증 방랑자를 처치하거나 공격을 막아 허기의 이빨을 획득하세요",
    "advancements.eternal_starlight.obtain_dagger_of_hunger.title": "채울 수 없는 허기",
    "advancements.eternal_starlight.obtain_dagger_of_hunger.description": "허기의 단검을 제작하세요",
    "advancements.eternal_starlight.saturate_dagger_of_hunger.title": "잘 먹었습니다",
    "advancements.eternal_starlight.saturate_dagger_of_hunger.description": "몹을 계속 공격해 허기의 단검을 배부르게 만드세요",
    "advancements.eternal_starlight.obtain_tooth_of_hunger_blocks.title": "배고픈 꽥꽥이",
    "advancements.eternal_starlight.obtain_tooth_of_hunger_blocks.description": "허기의 이빨 건축 블록을 제작하세요",
    "advancements.eternal_starlight.obtain_crystalborn_catalyst.title": "수정 사막화",
    "advancements.eternal_starlight.obtain_crystalborn_catalyst.description": "수정을 연료로 쓰고 레드스톤으로 작동하는 수정 태생 촉매기를 제작하세요",
    "advancements.eternal_starlight.summon_grimstone_golem.title": "아이템 판암",
    "advancements.eternal_starlight.summon_grimstone_golem.description": "그림스톤 벽돌 위에 조각된 루나리스 선인장 열매를 놓아 그림스톤 골렘을 소환하세요",
    "advancements.eternal_starlight.throw_gleech_egg.title": "사혈 요법",
    "advancements.eternal_starlight.throw_gleech_egg.description": "글리치 알을 던져 생물을 맞히세요",
    "advancements.eternal_starlight.tame_crystallized_moth.title": "메아리 속에서 길을 잃다",
    "advancements.eternal_starlight.tame_crystallized_moth.description": "충분한 고기를 먹여 음파 공격을 사용하는 결정화 나방을 길들이세요",
    "advancements.eternal_starlight.in_ether_fluid.title": "수소 이온 냄새",
    "advancements.eternal_starlight.in_ether_fluid.description": "에테르 액체 속에 서 보세요",
    "advancements.eternal_starlight.obtain_thioquartz_shard.title": "에테르에는 잘 안 녹아요",
    "advancements.eternal_starlight.obtain_thioquartz_shard.description": "티오쿼츠 조각을 획득하세요",
    "advancements.eternal_starlight.obtain_forgotten_nocturnal_millet.title": "망각으로 돌아가다",
    "advancements.eternal_starlight.obtain_forgotten_nocturnal_millet.description": "망각의 야광 기장을 획득하세요",
    "advancements.eternal_starlight.obtain_alchemist_mask.title": "마지막 가면무도회",
    "advancements.eternal_starlight.obtain_alchemist_mask.description": "연금술사 가면을 제작하세요",
    "advancements.eternal_starlight.witness_meteor_shower.title": "별에 소원을",
    "advancements.eternal_starlight.witness_meteor_shower.description": "유성우를 목격하세요",
    "advancements.eternal_starlight.obtain_aethersent_ingot.title": "하늘이 준 선물",
    "advancements.eternal_starlight.obtain_aethersent_ingot.description": "에테르센트 주괴를 획득하세요",
    "advancements.eternal_starlight.summon_aethersent_golem.title": "행성 방위 정책",
    "advancements.eternal_starlight.summon_aethersent_golem.description": "에테르센트 블록 위에 조각된 루나리스 선인장 열매를 놓아 에테르센트 골렘을 소환하세요",
    "advancements.eternal_starlight.kill_creteor.title": "어서, 타스!",
    "advancements.eternal_starlight.kill_creteor.description": "유성우 때 하늘에서 떨어지는 크리에터를 처치하세요",
    "advancements.eternal_starlight.obtain_aetherstrike_rocket.title": "우주의 기우제",
    "advancements.eternal_starlight.obtain_aetherstrike_rocket.description": "유성우를 불러오는 에테르 폭격 로켓을 제작하세요",
    "advancements.eternal_starlight.obtain_deepsilver_ingot.title": "진흙에도 때 묻지 않는",
    "advancements.eternal_starlight.obtain_deepsilver_ingot.description": "심층 은 주괴를 획득하세요",
    "advancements.eternal_starlight.obtain_starlit_diamond.title": "오, 반짝인다!",
    "advancements.eternal_starlight.obtain_starlit_diamond.description": "별빛 다이아몬드를 획득하세요",
    "advancements.eternal_starlight.obtain_numbness_effect.title": "아무 감각도 없어",
    "advancements.eternal_starlight.obtain_numbness_effect.description": "은빛 알싸한 열매로 피해를 잠시 흡수하는 무감각 효과를 얻으세요",
    "advancements.eternal_starlight.ignite_tear_bomb.title": "누구라도 울 수 있어",
    "advancements.eternal_starlight.ignite_tear_bomb.description": "눈물 폭탄에 불을 붙이세요",
    "advancements.eternal_starlight.witness_stranghoul_hunt.title": "죽음조차 죽을 수 있다",
    "advancements.eternal_starlight.witness_stranghoul_hunt.description": "스트랭구울이 먹잇감을 사냥하는 모습을 목격하세요",
    "advancements.eternal_starlight.hire_stranghoul.title": "누구나 요리할 수 있어",
    "advancements.eternal_starlight.hire_stranghoul.description": "알싸한 스튜 한 그릇으로 스트랭구울을 하루 동안 고용하세요",
    "advancements.eternal_starlight.hammer_critical_hit.title": "정의의 망치",
    "advancements.eternal_starlight.hammer_critical_hit.description": "공격 강도가 가득 찼을 때 망치로 치명타를 가해 특수 공격을 발동하세요",
    "advancements.eternal_starlight.put_seeds_into_starfire_bird_nest.title": "뿌리를 보살피며",
    "advancements.eternal_starlight.put_seeds_into_starfire_bird_nest.description": "별불꽃새가 번식하도록 둥지에 씨앗을 넣으세요",
    "advancements.eternal_starlight.obtain_starfire.title": "수정 불꽃",
    "advancements.eternal_starlight.obtain_starfire.description": "별불꽃새의 번식을 도와 별불꽃 한 조각을 획득하세요",
    "advancements.eternal_starlight.obtain_flowglaze.title": "흐르는 광휘",
    "advancements.eternal_starlight.obtain_flowglaze.description": "모래에 별불꽃을 던져 플로글레이즈 한 조각을 획득하세요",
    "advancements.eternal_starlight.obtain_thermal_springstone.title": "손 데이지 않게 조심!",
    "advancements.eternal_starlight.obtain_thermal_springstone.description": "열기 스프링스톤을 획득하세요. 도움말: 이곳의 거대 식물은 불꽃으로만 파괴할 수 있습니다...",
    "advancements.eternal_starlight.obtain_raw_amaramber.title": "까다롭기는!",
    "advancements.eternal_starlight.obtain_raw_amaramber.description": "개비자나무 원목의 껍질을 벗겨 아마램버 원석 한 조각을 획득하세요",
    "advancements.eternal_starlight.obtain_stellagmite.title": "남은 열기",
    "advancements.eternal_starlight.obtain_stellagmite.description": "지하에서 용암에 녹는 스텔라그마이트를 획득하세요",
    "advancements.eternal_starlight.obtain_bouldershroom_stew.title": "다람쥐처럼 날쌔게",
    "advancements.eternal_starlight.obtain_bouldershroom_stew.description": "어디든 기어오를 수 있게 해 주는 바위버섯 스튜 한 그릇을 제작하세요",
    "advancements.eternal_starlight.obtain_dusted_shard.title": "고대의 눈물",
    "advancements.eternal_starlight.obtain_dusted_shard.description": "해저에서 찾을 수 있는 가루 묻은 조각을 획득하세요",
    "advancements.eternal_starlight.obtain_jinglestem_sandwich.title": "자연 패티",
    "advancements.eternal_starlight.obtain_jinglestem_sandwich.description": "방울줄기 샌드위치를 제작하세요",
    "advancements.eternal_starlight.all_starlight_biomes.title": "별빛 탐험가",
    "advancements.eternal_starlight.all_starlight_biomes.description": "별빛 차원의 모든 생물 군계를 탐험하세요",
    "advancements.eternal_starlight.enter_golem_forge.title": "군단의 요람",
    "advancements.eternal_starlight.enter_golem_forge.description": "골렘 제련소에 들어가세요",
    "advancements.eternal_starlight.kill_permafrost.title": "겨울이 떠나간다",
    "advancements.eternal_starlight.kill_permafrost.description": "퍼머프로스트를 처치하세요",
    "advancements.eternal_starlight.freeze_starlight_golem.title": "진정해, 친구!",
    "advancements.eternal_starlight.freeze_starlight_golem.description": "별빛 골렘에게 냉동관을 던져 더 빨리 충전 상태에 들어가게 하세요",
    "advancements.eternal_starlight.deactivate_energy_block.title": "뒤통수 치기",
    "advancements.eternal_starlight.deactivate_energy_block.description": "에너지 블록을 비활성화해 별빛 골렘을 공격할 수 있게 만드세요",
    "advancements.eternal_starlight.kill_golem.title": "고대의 지혜",
    "advancements.eternal_starlight.kill_golem.description": "별빛 골렘을 처치하세요",
    "advancements.eternal_starlight.obtain_golem_steel_ingot.title": "산화 환원 반응",
    "advancements.eternal_starlight.obtain_golem_steel_ingot.description": "골렘 강철 주괴를 획득하세요",
    "advancements.eternal_starlight.ignite_lunar_monstrosity.title": "모조리 불태워라",
    "advancements.eternal_starlight.ignite_lunar_monstrosity.description": "달빛 괴수에 불을 붙여 공격할 수 있게 만드세요",
    "advancements.eternal_starlight.kill_lunar_monstrosity.title": "가시를 헤치고",
    "advancements.eternal_starlight.kill_lunar_monstrosity.description": "달빛 괴수를 처치하세요",
    "advancements.eternal_starlight.obtain_crescent_spear.title": "완전한 어둠",
    "advancements.eternal_starlight.obtain_crescent_spear.description": "초승달 창을 획득하세요",
    "advancements.eternal_starlight.chain_tangled_skull_explosion.title": "그냥 아군 공격이야",
    "advancements.eternal_starlight.chain_tangled_skull_explosion.description": "뒤엉킨 해골을 처치하고 그 폭발로 다른 뒤엉킨 해골을 처치하세요",
    "advancements.eternal_starlight.full_unrealium_armor.title": "보이지 않는 곳으로",
    "advancements.eternal_starlight.full_unrealium_armor.description": "언리얼리움 갑옷 한 벌을 모두 갖추세요",
    "advancements.eternal_starlight.use_blossom_of_stars.title": "끝없는 은하수에서 그네 타기",
    "advancements.eternal_starlight.use_blossom_of_stars.description": "사색하는 이에게!",
}
