#!/usr/bin/env python3
"""Immersive Engineering 언어 파일을 영어 원문 기준으로 전체 재검수한다."""

from __future__ import annotations

import argparse
from collections import Counter
import json
import re
import sys
from pathlib import Path

from five_family_goal import PROJECT_ROOT, load_json, validate_value

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

WORK_ROOT = PROJECT_ROOT / "working/immersive_engineering/immersiveengineering"

COLORS = {
    "black": "검은색",
    "blue": "파란색",
    "brown": "갈색",
    "cyan": "청록색",
    "gray": "회색",
    "green": "초록색",
    "light_blue": "하늘색",
    "light_gray": "회백색",
    "lime": "연두색",
    "magenta": "자홍색",
    "orange": "주황색",
    "pink": "분홍색",
    "purple": "보라색",
    "red": "빨간색",
    "white": "흰색",
    "yellow": "노란색",
}

BANNER_PATTERNS = {
    "bevels": "빗면 테두리",
    "hammer": "망치",
    "hammer_grip": "망치 손잡이",
    "hammer_head": "망치 머리",
    "ornate": "화려한 무늬",
    "screwdriver": "드라이버",
    "screwdriver_grip": "드라이버 손잡이",
    "screwdriver_head": "드라이버 머리",
    "treated_wood": "방부목",
    "warning": "경고",
    "warning_cat": "고양이 경고",
    "warning_cold": "저온 경고",
    "warning_ear_defenders": "청력 보호 경고",
    "warning_electric": "감전 경고",
    "warning_falling": "낙하물 경고",
    "warning_fire": "인화물 경고",
    "warning_hot": "고온 표면 경고",
    "warning_magnet": "자기장 경고",
    "warning_sound": "소음 경고",
    "warning_turret": "포탑 경고",
    "warning_warden": "워든 경고",
    "windmill": "풍차",
    "wirecutter": "전선 절단기",
    "wirecutter_grip": "전선 절단기 손잡이",
    "wirecutter_head": "전선 절단기 머리",
    "wolf": "늑대",
    "wolf_l": "늑대 왼쪽",
    "wolf_r": "늑대 오른쪽",
}

WARNING_SIGNS = {
    "arrow_double_down": "아래쪽 이중 화살표",
    "arrow_double_left": "왼쪽 이중 화살표",
    "arrow_double_right": "오른쪽 이중 화살표",
    "arrow_double_up": "위쪽 이중 화살표",
    "arrow_down": "아래쪽 화살표",
    "arrow_left": "왼쪽 화살표",
    "arrow_right": "오른쪽 화살표",
    "arrow_up": "위쪽 화살표",
    "attention": "일반 경고",
    "cat": "고양이 귀",
    "cold": "저온",
    "creeper": "크리퍼",
    "ear_defenders": "청력 보호",
    "electric": "감전 위험",
    "falling": "낙하물",
    "fire": "인화물",
    "hot": "고온 표면",
    "magnet": "자기장",
    "shrieker": "스컬크 비명체",
    "sound": "소음",
    "turret": "포탑",
    "villager": "주민",
    "warden": "워든",
}

NAME_TRANSLATIONS = {
    "Acetaldehyde": "아세트알데히드",
    "Aluminium Catwalk": "알루미늄 캣워크",
    "Aluminium Catwalk Stairs": "알루미늄 캣워크 계단",
    "Aluminium Fence Gate": "알루미늄 울타리 문",
    "Aluminium Framed Window": "알루미늄 프레임 창문",
    "Aluminum Hanging Sign": "알루미늄 매달린 표지판",
    "Aluminum Sign": "알루미늄 표지판",
    "Basic Engineering Block": "기본 공학 블록",
    "Biodiesel": "바이오디젤",
    "Blueprint Shelf": "설계도 선반",
    "Cage Lamp": "케이지 램프",
    "Resonanz Observer": "Resonanz 관측기",
    "Clinker Bricks": "클링커 벽돌",
    "Clinker Brick Quoin": "클링커 벽돌 모서리",
    "Clinker Brick Sill": "클링커 벽돌 창턱",
    "Concrete Brick": "콘크리트 벽돌",
    "Cracked Concrete Brick": "금 간 콘크리트 벽돌",
    "Chiseled Concrete": "조각된 콘크리트",
    "Liquid Concrete": "액체 콘크리트",
    "Concrete Pillar": "콘크리트 기둥",
    "Reinforced Concrete": "철근 콘크리트",
    "Reinforced Concrete Tile": "철근 콘크리트 타일",
    "Creosote Oil": "크레오소트유",
    "Deepslate Bauxite Ore": "심층암 보크사이트 광석",
    "Deepslate Lead Ore": "심층암 납 광석",
    "Deepslate Nickel Ore": "심층암 니켈 광석",
    "Deepslate Silver Ore": "심층암 은 광석",
    "Deepslate Uranium Ore": "심층암 우라늄 광석",
    "Duroplast Block": "듀로플라스트 블록",
    "Electromagnet": "전자석",
    "Ethanol": "에탄올",
    "Fiberboard": "섬유판",
    "Grit Sand": "거친 모래",
    "Item Hatch": "아이템 해치",
    "Hempcrete Brick": "헴프크리트 벽돌",
    "Cracked Hempcrete Brick": "금 간 헴프크리트 벽돌",
    "Chiseled Hempcrete": "조각된 헴프크리트",
    "Hempcrete Pillar": "헴프크리트 기둥",
    "Herbicide": "제초제",
    "High-Cetane Biodiesel": "고세탄가 바이오디젤",
    "Machine Interface": "기계 인터페이스",
    "Phenolic Resin": "페놀 수지",
    "Pipe Valve": "파이프 밸브",
    "Plant Oil": "식물성 기름",
    "Radio Tower": "무선 통신탑",
    "Block of Raw Bauxite": "보크사이트 원석 블록",
    "Block of Raw Lead": "납 원석 블록",
    "Block of Raw Nickel": "니켈 원석 블록",
    "Block of Raw Silver": "은 원석 블록",
    "Block of Raw Uranium": "우라늄 원석 블록",
    "Redstone Acid": "레드스톤 산",
    "Redstone State Cell": "레드스톤 상태 셀",
    "Redstone Switchboard": "레드스톤 배전반",
    "Redstone Timer": "레드스톤 타이머",
    "Panzerglass Window": "판처글라스 창문",
    "Resonanz Engineering Block": "Resonanz 공학 블록",
    "Crate Storage Shelf": "상자 보관 선반",
    "Warning Siren": "경고 사이렌",
    "Clinker Brick Slab": "클링커 벽돌 반 블록",
    "Concrete Brick Slab": "콘크리트 벽돌 반 블록",
    "Reinforced Concrete Slab": "철근 콘크리트 반 블록",
    "Reinforced Concrete Tile Slab": "철근 콘크리트 타일 반 블록",
    "Hempcrete Brick Slab": "헴프크리트 벽돌 반 블록",
    "Slag Brick Slab": "슬래그 벽돌 반 블록",
    "Slag Bricks": "슬래그 벽돌",
    "Slag Glass": "슬래그 유리",
    "Slag Gravel": "슬래그 자갈",
    "Clinker Brick Stairs": "클링커 벽돌 계단",
    "Concrete Brick Stairs": "콘크리트 벽돌 계단",
    "Hempcrete Brick Stairs": "헴프크리트 벽돌 계단",
    "Slag Brick Stairs": "슬래그 벽돌 계단",
    "Steel Catwalk": "강철 캣워크",
    "Steel Catwalk Stairs": "강철 캣워크 계단",
    "Steel Door": "강철 문",
    "Steel Fence Gate": "강철 울타리 문",
    "Steel Hanging Sign": "강철 매달린 표지판",
    "Steel Sign": "강철 표지판",
    "Steel Trapdoor": "강철 다락문",
    "Steel Framed Window": "강철 프레임 창문",
    "Treated Wood Catwalk": "방부목 캣워크",
    "Treated Wood Catwalk Stairs": "방부목 캣워크 계단",
    "Treated Wood Door": "방부목 문",
    "Treated Wood Fence Gate": "방부목 울타리 문",
    "Treated Wood Trapdoor": "방부목 다락문",
    "Treated Wood Window": "방부목 창문",
    "Treated Wood Hanging Sign": "방부목 매달린 표지판",
    "Treated Wood Sign": "방부목 표지판",
    "Clinker Brick Wall": "클링커 벽돌 담장",
    "Concrete Wall": "콘크리트 담장",
    "Concrete Brick Wall": "콘크리트 벽돌 담장",
    "Leaded Concrete Wall": "납 차폐 콘크리트 담장",
    "Concrete Tile Wall": "콘크리트 타일 담장",
    "Hempcrete Wall": "헴프크리트 담장",
    "Hempcrete Brick Wall": "헴프크리트 벽돌 담장",
    "Slag Brick Wall": "슬래그 벽돌 담장",
    "Banner Pattern": "현수막 무늬",
    "Screwdriver": "드라이버",
    "Warning Signs": "경고 표지",
    "Wirecutter": "전선 절단기",
    "Armor-Piercing Cartridge": "철갑탄 탄약통",
    "Buckshot Cartridge": "산탄 탄약통",
    "Casull Cartridge": "카술 탄약통",
    "Dragon's Breath Cartridge": "용의 숨결 탄약통",
    "Firework Cartridge": "폭죽 탄약통",
    "Flare Cartridge": "조명탄 탄약통",
    "High-Explosive Cartridge": "고폭탄 탄약통",
    "Homing Cartridge": "유도탄 탄약통",
    "Phial Cartridge": "약병탄 탄약통",
    "Silver Cartridge": "은탄 탄약통",
    "Wolfpack Cartridge": "울프팩 탄약통",
    "Bulwark Spawn Egg": "불워크 생성 알",
    "Commando Spawn Egg": "코만도 생성 알",
    "Electronic Component": "전자 부품",
    "Advanced Electronic Component": "고급 전자 부품",
    "Ersatz Leather": "대체 가죽",
    "Industrial Fertilizer": "산업용 비료",
    "Fusilier Spawn Egg": "퓨질리어 생성 알",
    "Collapsible Glider": "접이식 글라이더",
    "Grinding Disk": "연마 디스크",
    "Incandescent Light Bulb": "백열전구",
    "Netherite Nugget": "네더라이트 조각",
    "Duroplast Sheet": "듀로플라스트 판",
    "HOP Graphite Plate": "HOP 흑연 판",
    "Raw Bauxite": "보크사이트 원석",
    "Raw Lead": "납 원석",
    "Raw Nickel": "니켈 원석",
    "Raw Silver": "은 원석",
    "Raw Uranium": "우라늄 원석",
    "Eu-K508 S 'Einhorn'": "Eu-K508 S 'Einhorn'",
    "Automaton Wolf": "자동기계 늑대",
    "Masterwork Shader Grabbag": "걸작 셰이더 꾸러미",
    "Netherite Rod": "네더라이트 막대",
    "Rock Softening Acid": "암석 연화 산",
    "Charging Antenna": "충전 안테나",
    "Induction Charger": "유도 충전기",
    "Portable Electromagnet": "휴대용 전자석",
    "Miniaturized Tesla Coil": "소형 테슬라 코일",
    "Insulated Grip": "절연 손잡이",
    "Heavy Impact Hooks": "고충격 갈고리",
    "High Torque Motor": "고토크 모터",
    "Potion": "물약",
}

TEXT_TRANSLATIONS = {
    "X Marks the Spot": "보물은 X 표시",
    "Buy a Mineral Deposit Map from the Structural Engineer": "구조 공학자에게서 광물 매장지 지도를 구매하세요",
    "Fashion Spree": "패션 쇼핑",
    "Buy a Shader Grabbag from the Outfitter": "의상 제작자에게서 셰이더 꾸러미를 구매하세요",
    "Alien Greenhouse": "외계 온실",
    "Grow a Chorus Fruit in the Garden Cloche": "원예용 온실에서 후렴과를 재배하세요",
    "Uncomfortable Shortcut": "불편한 지름길",
    "Bounce around the Sheetmetal Chutes": "판금 슈트 안에서 이리저리 튕기세요",
    "Holding Back": "쌓아 두기",
    "Craft an Item Batcher": "아이템 배치 처리기를 제작하세요",
    "Going Down": "아래로 갑니다",
    "Craft a Dropping Conveyor Belt": "낙하 컨베이어 벨트를 제작하세요",
    "Modern Materials": "현대식 소재",
    "Craft a Duroplast Sheet": "듀로플라스트 판을 제작하세요",
    "Moving Out": "밖으로 이동",
    "Craft an Extracting Conveyor Belt": "추출 컨베이어 벨트를 제작하세요",
    "Portable Particle Supply": "휴대용 전력 공급",
    "Craft the Accumulator Backpack": "축전기 배낭을 제작하세요",
    "Colour-coded!": "색상으로 구분!",
    "Craft an Item Router": "아이템 라우터를 제작하세요",
    "Decorative and Sturdy": "장식성과 견고함",
    "Craft some Sheetmetal": "판금을 제작하세요",
    "Oiled Up and Ready to Go": "기름칠 완료, 출발 준비",
    "Craft some Treated Wood": "방부목을 제작하세요",
    "Don't Drink This...": "이건 마시지 마세요...",
    "Collect a bucket of Creosote Oil": "크레오소트유 한 양동이를 모으세요",
    "Superior Weaponry": "우월한 무기",
    "Kill an Illager with Revolver, Railgun or Chemthrower. Beware of the new raiders!": "리볼버, 레일건 또는 화학 분사기로 우민을 처치하세요. 새로운 약탈자를 조심하세요!",
    "What Happens to Snitches...": "밀고자의 최후...",
    "Get trapped in concrete feet": "콘크리트 족쇄에 갇히세요",
    "RTFM!": "설명서를 읽으세요!",
    "Concentrated Carbon": "농축 탄소",
    "Form the Coke Oven": "코크스로를 완성하세요",
    "Moonshine!": "밀주!",
    "Form the Fermenter": "발효기를 완성하세요",
    "Industrial Potionmaking": "산업식 물약 제조",
    "Form the Mixer": "혼합기를 완성하세요",
    "Chemical Processing": "화학 처리",
    "Form the Refinery": "정유기를 완성하세요",
    "Can it Make Nutmilk?": "견과류 우유도 되나요?",
    "Form the Squeezer": "압착기를 완성하세요",
    "Water Tower": "급수탑",
    "Form the Tank": "탱크를 완성하세요",
    "Multiblocks": "멀티블록",
    "Large machines for large factories": "대형 공장을 위한 대형 기계",
    "Inverted Motor": "거꾸로 된 모터",
    "Place a Kinetic Dynamo": "운동 에너지 발전기를 설치하세요",
    "ACHTUNG! ACHTUNG!": "경고! 경고!",
    "1.21 Gigawatts!": "1.21기가와트!",
    "When this baby hits 88 mph, you're gonna see some serious s-": "이 녀석이 시속 88마일에 도달하면 엄청난 일이 벌어질 거예요-",
    "Fried Bird": "튀겨진 새",
    "Insulation unavailable": "절연 기능 없음",
    "Alert!": "경보다!",
    "Uncover an intruder": "침입자를 찾아내세요",
    "Booker, Catch!": "부커, 받아!",
    "Travel a total of 1km with the Skyhook": "스카이훅으로 총 1km를 이동하세요",
    "Tools & Upgrades": "도구 및 업그레이드",
    "The Engineer's Workbench can be used to modify your tools": "공학자의 작업대로 도구를 개조할 수 있습니다",
    "The Spengler & Stantz Special": "스펭글러와 스탠츠 특제",
    "Apply the maximum Upgrades to the Accumulator Backpack": "축전기 배낭에 최대 수의 업그레이드를 적용하세요",
    "Fellow Engineers": "동료 공학자",
    "Meet an Engineer Villager": "공학자 주민을 만나세요",
    "Inputs:": "입력:",
    "Operator:": "연산자:",
    "Outputs:": "출력:",
    "Add Condition": "조건 추가",
    "Additive Input": "첨가제 입력",
    "Electrode Integrity": "전극 내구도",
    "Slag Output": "슬래그 출력",
    "First Input Tank": "첫 번째 입력 탱크",
    "Second Input Tank": "두 번째 입력 탱크",
    "Third Input Tank": "세 번째 입력 탱크",
    "Machine Active": "기계 작동 중",
    "Energy Storage": "에너지 저장량",
    "Fluid Input": "유체 입력",
    "Fluid Output": "유체 출력",
    "Item Input": "아이템 입력",
    "Item Output": "아이템 출력",
    "Fluid Stored": "저장된 유체",
    "Left Input Tank": "왼쪽 입력 탱크",
    "Right Input Tank": "오른쪽 입력 탱크",
    "Sawblade Integrity": "톱날 내구도",
    "Control Signal Input:": "제어 신호 입력:",
    "The Machine Interface is not attached to a valid machine.\nPlease ensure that the interface was placed against the redstone control port of an Immersive Engineering multiblock.": "기계 인터페이스가 올바른 기계에 연결되지 않았습니다.\n인터페이스가 Immersive Engineering 멀티블록의 레드스톤 제어 포트에 닿도록 설치했는지 확인하세요.",
    "Comparator Output": "비교기 출력",
    "Empty": "비어 있음",
    "100% Filled": "100% 채움",
    "50% Filled": "50% 채움",
    "No": "아니요",
    "25% Filled": "25% 채움",
    "75% Filled": "75% 채움",
    "Yes": "예",
    "Remove Condition": "조건 제거",
    "Signal threshold: ": "신호 임계값: ",
    "Frequency": "주파수",
    "Shift + click to load": "Shift + 클릭하여 불러오기",
    "Range": "범위",
    "Click to save": "클릭하여 저장",
    "Saved Frequencies:": "저장된 주파수:",
    "Control Signal Color:": "제어 신호 색상:",
    "Input Signal Color:": "입력 신호 색상:",
    "Output Signal Color:": "출력 신호 색상:",
    "Resetting Signal Color:": "초기화 신호 색상:",
    "Setting Signal Color:": "설정 신호 색상:",
    "Require control signal": "제어 신호 필요",
    "Swap to other side": "반대쪽으로 전환",
    "Buzzer": "버저",
    "Klaxon": "클랙슨",
    "Siren": "사이렌",
    "EUREKA!!": "유레카!!",
    "Manual Entry Unlocked!": "설명서 항목 해금!",
    "Rule of §m6§r 8": "§m6§r이 아닌 8의 법칙",
    "Increases the drops from ores": "광석에서 나오는 아이템이 증가합니다",
    "Charge the Accumulator Backpack from wires": "전선에서 축전기 배낭을 충전합니다",
    "Charge your entire inventory": "인벤토리 전체를 충전합니다",
    "Attract nearby items": "주변 아이템을 끌어당깁니다",
    "Electrocute your attackers": "공격한 대상을 감전시킵니다",
    "Prevent electrocution from riding the Skyhook along live wires": "전류가 흐르는 전선에서 스카이훅을 탈 때 감전되지 않습니다",
    "Deal greatly increased damage when falling towards an enemy": "적을 향해 낙하할 때 피해가 크게 증가합니다",
    "Move faster up slopes with the Skyhook": "스카이훅으로 경사면을 더 빠르게 오릅니다",
    "Up to %1$s at a time": "한 번에 최대 %1$s개",
    "Automatons": "자동기계",
    "Input %1$s": "입력 %1$s",
    "Output": "출력",
    "Circuit Name": "회로 이름",
    "Place logic circuit here to edit": "편집할 논리 회로를 여기에 놓으세요",
    "Filter: Components<br>Filters items with respect<br>to their additional data components.": "필터: 구성 요소<br>추가 데이터 구성 요소를 기준으로<br>아이템을 거릅니다.",
    "Filter: Components<br>Filters fluids with respect<br>to their additional data components.": "필터: 구성 요소<br>추가 데이터 구성 요소를 기준으로<br>유체를 거릅니다.",
    "Item added by: %1$s": "추가한 모드: %1$s",
    "§o§8No tags available, will filter by item instead.§r": "§o§8사용 가능한 태그가 없어 아이템 자체로 거릅니다.§r",
    "§6Selected tag: §o§8(scroll to change)§r": "§6선택한 태그: §o§8(스크롤하여 변경)§r",
    "Alluvial Sift": "충적층 체",
    "Amethyst Crevasse": "자수정 균열",
    "Ancient Seabed": "고대 해저",
    "Banded Iron": "호상 철광층",
    "Cooled Lava Tube": "식은 용암 동굴",
    "Hardened Claypan": "굳은 점토층",
    "Lazulitic Intrusion": "청금석 관입층",
    "Soul Silt": "영혼 실트",
    "Rich Auricupride": "풍부한 금동광",
    "Can not be charged while attached to armor": "방어구에 부착된 상태에서는 충전할 수 없습니다",
    "Redstone Level: %1$s": "레드스톤 신호 세기: %1$s",
    "%1$s on %2$s": "%2$s의 %1$s",
    "Catalyst": "촉매",
    "Just cuddle instead!": "그냥 서로 안아 주세요!",
    "It's not a phase.": "한때의 감정이 아닙니다.",
    "Gender is not binary!": "성별은 이분법이 아닙니다!",
    "Even the penguins do it!": "펭귄도 그렇게 합니다!",
    "Archeologists will call them roommates.": "고고학자들은 둘을 룸메이트라고 부르겠죠.",
    "Protect trans kids! Trans rights are human rights, now and forever!": "트랜스젠더 아동을 보호하세요! 트랜스젠더의 권리는 지금도 영원히 인권입니다!",
    " - Bucket Filling": " - 양동이 채우기",
    "Garden Cloche Fertilizer": "원예용 온실 비료",
    " - Potions": " - 물약",
    " - Recycling": " - 재활용",
    "Growth Modifier: %1$s": "성장 배수: %1$s",
    "Arc Furnace causes lightning": "아크로에서 번개가 튐",
    "Rhythmic Assembler clockwork": "조립기가 리듬에 맞춰 작동함",
    "Bottling Machine fills a container": "병입기가 용기를 채움",
    "Buzzer warning": "버저 경고음",
    "Buzzsaw revs up high": "원형톱의 회전수가 높아짐",
    "Grinding": "연마함",
    "Sawing": "톱질함",
    "Buzzsaw motor running": "원형톱 모터가 작동함",
    "Drill revs up high": "드릴의 회전수가 높아짐",
    "Drilling": "드릴로 뚫음",
    "Drill motor running": "드릴 모터가 작동함",
    "Electromagnet hums": "전자석이 웅웅거림",
    "Fermenter whirrs": "발효기가 윙윙거림",
    "Glider taking damage": "글라이더가 손상됨",
    "Klaxon blaring": "클랙슨이 울림",
    "Mill wheel creaks": "물레방아가 삐걱거림",
    "Mixer churns and scrapes": "혼합기가 휘젓고 긁음",
    "Excavator transports ore": "굴착기가 광석을 운반함",
    "Excavator dumps ore into hopper": "굴착기가 호퍼에 광석을 쏟음",
    "Preheater air blast wooshes": "예열기에서 공기가 세차게 뿜어져 나옴",
    "Automatic Engineer's Workbench drills": "자동 공학자의 작업대가 구멍을 뚫음",
    "Automatic Engineer's Workbench whirrs": "자동 공학자의 작업대가 윙윙거림",
    "Automatic Engineer's Workbench solders": "자동 공학자의 작업대가 납땜함",
    "Refinery whirrs": "정유기가 윙윙거림",
    "Sawmill whines without wood": "제재소가 나무 없이 헛돌음",
    "Sawmill shrieks cutting wood": "제재소가 나무를 자르며 날카로운 소리를 냄",
    "Sawmill blade spins down": "제재소 톱날 회전이 느려짐",
    "Sawmill blade spins up": "제재소 톱날 회전이 빨라짐",
    "Siren howling": "사이렌이 울부짖음",
    "Electrical Grids": "전력망",
    "Explosives & Weaponry": "폭발물 및 무기",
    "Heavy Machinery": "중장비",
    "Introduction": "소개",
    "Multiblock Constructions": "멀티블록 구조물",
    "Other Engineers": "다른 공학자들",
    "Redstone Control": "레드스톤 제어",
    "Resources": "자원",
    "Storage & Transport": "저장 및 운송",
    "!!Update News!!": "!!업데이트 소식!!",
    "Weird Science": "기묘한 과학",
    "Workbenches & Machinery": "작업대 및 기계",
    "Hold containers until full": "용기가 가득 찰 때까지 유지",
    "Allow partial filling": "일부만 채우기 허용",
    "Will extract %1$s items per second": "초당 아이템 %1$s개를 추출합니다",
    "The crate is now sealed and can be picked up": "이제 상자가 밀봉되어 회수할 수 있습니다",
    "Dig multiple blocks": "여러 블록 채굴",
    "Dig single block": "단일 블록 채굴",
    "This speed is too fast and will damage the glider": "속도가 너무 빨라 글라이더가 손상됩니다",
    "Light Level: %1$s": "밝기: %1$s",
    "This crate is not sealed": "이 상자는 밀봉되지 않았습니다",
    "Chemthrower Droplet": "화학 분사기 액적",
    "Railgun Rod": "레일건 탄자",
    "Bullet": "탄환",
    "Flare": "조명탄",
    "Homing Bullet": "유도탄",
    "Wolfpack Round": "울프팩 탄환",
    "Sawblade": "톱날",
    "Electrician": "전기 기술자",
    "Structural Engineer": "구조 공학자",
    "Gunsmith": "총기 제작자",
    "Machinist": "기계 기술자",
    "Outfitter": "의상 제작자",
    "swamps": "늪지",
    "swampy or growing corals": "늪지이거나 산호가 자라는",
    "flat and dry": "평평하고 건조한",
    "badlands": "악지",
    "mountainous": "산악 지형",
    "in the nether": "네더에 있는",
    "oceanic": "해양",
    "in the overworld": "오버월드에 있는",
    "rivers": "강",
    "taigas": "타이가",
    "Industrial Hemp Crop Growth": "산업용 대마 작물 성장",
    "Multiblock Icons": "멀티블록 아이콘",
    "Multiblock Inventory": "멀티블록 인벤토리",
    "Multiblock Tank": "멀티블록 탱크",
    "§l%1$s§r is a mineral vein found in biomes that are %2$s.": "§l%1$s§r 광맥은 %2$s 생물군계에서 발견됩니다.",
    "%1$s and are %2$s": "%1$s이면서 %2$s",
    "%1$s or %2$s": "%1$s 또는 %2$s",
    "Distance by Skyhook": "스카이훅 이동 거리",
    "Deaths due to Wires": "전선으로 인한 사망 횟수",
    "Incognito": "익명",
    "Immersive Engineering detected an incompatible version of Optifine. Due to Optifine's patching process, this version of Optifine removes Forge-added methods which are used, directly or indirectly, by Immersive Engineering and many other mods. As a result, you will probably experience a crash at virtually random times, e.g. when a search matches certain items. It is recommended that you do not use Optifine until this is fixed.": "Immersive Engineering에서 호환되지 않는 OptiFine 버전을 감지했습니다. OptiFine의 패치 과정에서 Immersive Engineering과 여러 모드가 직간접적으로 사용하는 Forge 추가 메서드가 제거되었습니다. 이 때문에 특정 아이템이 검색 결과에 나타날 때처럼 거의 무작위로 게임이 충돌할 수 있습니다. 문제가 해결될 때까지 OptiFine을 사용하지 않는 것이 좋습니다.",
}

REVIEWED_VALUE_TRANSLATIONS = {
    "Improved Blast Furnace": "개량 용광로",
    "Aluminium Post": "알루미늄 기둥",
    "Aluminium Structural Arm": "알루미늄 구조 지지대",
    "Arc Furnace": "아크로",
    "Assembler": "조립기",
    "Automated Engineer's Workbench": "자동 공학자의 작업대",
    "Crude Blast Furnace": "조잡한 용광로",
    "Bottling Machine": "병입기",
    "Bucket Wheel": "버킷 휠",
    "Creative Accumulator": "크리에이티브 축전기",
    "HV Accumulator": "HV 축전기",
    "LV Accumulator": "LV 축전기",
    "MV Accumulator": "MV 축전기",
    "Aluminium Sheetmetal Chute": "알루미늄 판금 슈트",
    "Copper Sheetmetal Chute": "구리 판금 슈트",
    "Iron Sheetmetal Chute": "철 판금 슈트",
    "Steel Sheetmetal Chute": "강철 판금 슈트",
    "Engineer's Circuit Workbench": "공학자의 회로 작업대",
    "Garden Cloche": "원예용 온실",
    "Coke Oven": "코크스로",
    "Quickdry Concrete": "속건 콘크리트",
    "Structural Cable Connector": "구조 케이블 연결기",
    "Covered Conveyor Belt": "덮개형 컨베이어 벨트",
    "Dropping Conveyor Belt": "낙하 컨베이어 벨트",
    "Dropping Covered Conveyor Belt": "덮개형 낙하 컨베이어 벨트",
    "Covered Extracting Conveyor Belt": "덮개형 추출 컨베이어 벨트",
    "Redstone Controlled Conveyor Belt": "레드스톤 제어 컨베이어 벨트",
    "Splitting Conveyor Belt": "분배 컨베이어 벨트",
    "Covered Splitting Conveyor Belt": "덮개형 분배 컨베이어 벨트",
    "Vertical Covered Conveyor Belt": "덮개형 수직 컨베이어 벨트",
    "Engineer's Crafting Table": "공학자의 제작대",
    "Current Transformer": "전류 변성기",
    "Kinetic Dynamo": "운동 에너지 발전기",
    "Feedthrough Insulator": "관통 절연체",
    "Industrial Fermenter": "산업용 발효기",
    "Heavy Engineering Block": "중공학 블록",
    "Hempcrete": "헴프크리트",
    "Item Batcher": "아이템 배치 처리기",
    "Light Engineering Block": "경공학 블록",
    "Logic Unit": "논리 장치",
    "Metal Press": "금속 프레스",
    "Molten Constantan": "용융 콘스탄탄",
    "Molten Uranium": "용융 우라늄",
    "Refinery": "정유기",
    "Reinforced Storage Crate": "강화 저장 상자",
    "Redstone Engineering Block": "레드스톤 공학 블록",
    "Core Sample Drill": "코어 샘플 드릴",
    "White Sheetmetal": "흰색 판금",
    "White Sheetmetal Slab": "흰색 판금 반 블록",
    "Steel Post": "강철 기둥",
    "Steel Structural Arm": "강철 구조 지지대",
    "Strip Curtain": "띠 커튼",
    "Structural Arm": "구조 지지대",
    "Engineer's Toolbox": "공학자의 도구상자",
    "Transformer": "변압기",
    "HV Transformer": "HV 변압기",
    "Wooden Post": "나무 기둥",
    "Chemthrower Turret": "화학 분사기 포탑",
    "Improved Windmill": "개량 풍차",
    "Engineer's Workbench": "공학자의 작업대",
    "Plating": "장갑판",
    "Wooden Paneling": "목재 판넬",
    "Engineer's Blueprint": "공학자의 설계도",
    "Crystalized Will Cartridge": "결정화된 의지 탄약통",
    "Lingering Phial Cartridge": "잔류형 약병탄 탄약통",
    "Splash Phial Cartridge": "투척용 약병탄 탄약통",
    "Buzzsaw": "원형톱",
    "Chemical Thrower": "화학 분사기",
    "Circuit Backplane": "회로 백플레인",
    "Iron Mechanical Component": "철 기계 부품",
    "Steel Mechanical Component": "강철 기계 부품",
    "Ear Defenders": "방음 귀마개",
    "Empty Casing": "빈 탄피",
    "Empty Shell": "빈 포탄",
    "Revolver Barrel": "리볼버 총열",
    "Revolver Drum": "리볼버 실린더",
    "Engineer's Hammer": "공학자의 망치",
    "Tough Fabric": "질긴 천",
    "Aluminium Ingot": "알루미늄 주괴",
    "Constantan Ingot": "콘스탄탄 주괴",
    "Copper Ingot": "구리 주괴",
    "Electrum Ingot": "일렉트럼 주괴",
    "HOP Graphite Ingot": "HOP 흑연 주괴",
    "Lead Ingot": "납 주괴",
    "Nickel Ingot": "니켈 주괴",
    "Silver Ingot": "은 주괴",
    "Steel Ingot": "강철 주괴",
    "Uranium Ingot": "우라늄 주괴",
    "Mineral Deposit Map": "광물 매장지 지도",
    "Metal Press Mold: Bullet Casing": "금속 프레스 주형: 탄피",
    "Metal Press Mold: Gear": "금속 프레스 주형: 기어",
    "Metal Press Mold: Packing 2x2": "금속 프레스 주형: 2x2 포장",
    "Metal Press Mold: Packing 3x3": "금속 프레스 주형: 3x3 포장",
    "Metal Press Mold: Plate": "금속 프레스 주형: 판",
    "Metal Press Mold: Rod": "금속 프레스 주형: 막대",
    "Metal Press Mold: Unpacking": "금속 프레스 주형: 포장 해제",
    "Metal Press Mold: Wire": "금속 프레스 주형: 전선",
    "Bucket of Plant Oil": "식물성 기름 양동이",
    "Accumulator Backpack": "축전기 배낭",
    "Beevolver": "비볼버",
    "Oathkeeper": "맹세수호자",
    "§6Last Word§r": "§6최후의 한마디§r",
    "Steamroller": "로드 롤러",
    "The Coilgun": "코일건",
    "Rockcutter Blade": "암석 절단 톱날",
    "Engineer's Screwdriver": "공학자의 드라이버",
    "Shader": "셰이더",
    "Shader Grabbag": "셰이더 꾸러미",
    "Common Shader Grabbag": "일반 셰이더 꾸러미",
    "Uncommon Shader Grabbag": "고급 셰이더 꾸러미",
    "Rare Shader Grabbag": "희귀 셰이더 꾸러미",
    "Epic Shader Grabbag": "영웅 셰이더 꾸러미",
    "Heavy Plated Shield": "중장갑 방패",
    "Engineer's Skyhook": "공학자의 스카이훅",
    "Revolver Speedloader": "리볼버 스피드로더",
    "Treated Stick": "방부목 막대",
    "Blade Quiver": "톱날통",
    "Additional Augers": "추가 오거",
    "Pressurized Air Tank": "가압 공기 탱크",
    "Amplifier Electron Tubes": "증폭 전자관",
    "Flashbulb": "섬광 전구",
    "Shock Emitters": "충격 방출기",
    "Engineer's Multimeter": "공학자의 멀티미터",
    "Waterwheel Segment": "물레방아 조각",
    "LV Wire Coil": "LV 전선 코일",
    "Insulated LV Wire Coil": "절연 LV 전선 코일",
    "MV Wire Coil": "MV 전선 코일",
    "Insulated MV Wire Coil": "절연 MV 전선 코일",
    "Redstone Wire Coil": "레드스톤 전선 코일",
    "HV Wire Coil": "HV 전선 코일",
    "Hemp Rope Coil": "대마 밧줄 코일",
    "Engineer's Wire Cutters": "공학자의 전선 절단기",
    "Treecapitation": "일격 벌목",
    "Spray and Pray": "뿌리고 기도하라",
    "Craft the Chemical Thrower": "화학 분사기를 제작하세요",
    "Craft an Engineer's Hammer": "공학자의 망치를 제작하세요",
    "Spread the Warmth": "온기를 퍼뜨리세요",
    "Craft an External Heater": "외부 가열기를 제작하세요",
    "Under Pressure": "압박감",
    "Make My Day": "날 기쁘게 해 봐",
    "Craft a Wolfpack Cartridge": "울프팩 탄약통을 제작하세요",
    "Time to Tinker": "손볼 시간",
    "Craft an Engineer's Workbench": "공학자의 작업대를 제작하세요",
    "Create a Steel Ingot": "강철 주괴를 제작하세요",
    "Form the Arc Furnace": "아크로를 완성하세요",
    "Form the Crude Blast Furnace": "조잡한 용광로를 완성하세요",
    "Form the Crusher": "분쇄기를 완성하세요",
    "Form the Diesel Generator": "디젤 발전기를 완성하세요",
    "Form the Excavator": "굴착기를 완성하세요",
    "Form the Improved Blast Furnace": "개량 용광로를 완성하세요",
    "Form the Metal Press": "금속 프레스를 완성하세요",
    "Form the Silo": "사일로를 완성하세요",
    "Acquire the Engineer's Manual": "공학자의 설명서를 획득하세요",
    "Road to Nowhere": "아무 데도 가지 않는 길",
    "JUST WHO THE HELL DO YOU THINK I AM?!": "내가 누구라고 생각하느냐?!",
    "Luck of the Draw": "추첨 운",
    "All or nothing": "모 아니면 도",
    "We Don't Go To Ravenholm...": "우리는 레이븐홈에 가지 않아요...",
    "Total Evisceration": "완전 절단",
    "Apply the maximum Upgrades to the Buzzsaw": "원형톱에 최대 수의 업그레이드를 적용하세요",
    "Apply the maximum Upgrades to the Mining Drill": "채굴 드릴에 최대 수의 업그레이드를 적용하세요",
    "Apply the maximum Upgrades to the Railgun": "레일건에 최대 수의 업그레이드를 적용하세요",
    "Apply the maximum Upgrades to the Revolver": "리볼버에 최대 수의 업그레이드를 적용하세요",
    "Preheaters": "예열기",
    "Clear Recipe": "제작법 지우기",
    "Redstone Signal Color:": "레드스톤 신호 색상:",
    "Receiving Signal Color:": "수신 신호 색상:",
    "Sending Signal Color:": "송신 신호 색상:",
    "Redstone IO Mode:": "레드스톤 입출력 모드:",
    "Keep Casings": "탄피 유지",
    "Expel Casings": "탄피 배출",
    "Ignite Fluid": "유체 점화",
    "Minerals found at %1$s, %2$s": "%1$s, %2$s에서 광물을 발견했습니다.",
    "No minerals found at %1$s, %2$s": "%1$s, %2$s에서 광물을 발견하지 못했습니다.",
    "Mineral vein '%1$s' with radius %2$s placed at %3$s, %4$s": "반경 %2$s의 '%1$s' 광맥을 %3$s, %4$s에 배치했습니다.",
    "No minerals present at %1$s, %2$s": "%1$s, %2$s에 광물이 없습니다.",
    "Mineral depletion set to %1$s": "광물 고갈도를 %1$s(으)로 설정했습니다.",
    "§6Usage: /ie shaders <clear>§r": "§6사용법: /ie shaders <clear>§r",
    "Average loss between points: %1$s%%": "두 지점 사이 평균 손실률: %1$s%%",
    "Core Sample in progress: %1$s": "코어 샘플 채취 중: %1$s",
    "§7Mineral vein at %1$s§7 integrity": "§7%1$s§7 지점 광맥의 건전도",
    "§7Core Sample evaluated, %1$s§7 vein found": "§7코어 샘플 분석 완료, %1$s§7 광맥을 발견했습니다",
    "Core Sample evaluated, no minerals found": "코어 샘플 분석 완료, 광물을 발견하지 못했습니다",
    "The sample is not within the same dimension as this map": "샘플이 이 지도와 같은 차원에 있지 않습니다",
    "The sample is not within the borders of this map": "샘플이 이 지도의 범위 안에 있지 않습니다",
    "This container can't store gasses!": "이 용기는 기체를 저장할 수 없습니다!",
    "This pump will no longer replace fluid blocks with cobblestone. §6WARNING:§f This can cause lag and is not adviseable when dealing with large amounts of fluid!": "이 펌프는 더 이상 유체 블록을 조약돌로 대체하지 않습니다. §6경고:§f 지연을 일으킬 수 있으므로 대량의 유체를 처리할 때는 권장하지 않습니다!",
    "This pump will now replace fluids with cobblestone.": "이 펌프는 이제 유체를 조약돌로 대체합니다.",
    "This fluid is too hot for the container!": "이 유체는 용기에 담기에는 너무 뜨겁습니다!",
    "You are too far away from the previous connection": "이전 연결 지점에서 너무 멀리 떨어져 있습니다.",
}

KEY_TRANSLATIONS = {
    "entity.immersiveengineering.bulwark": "불워크",
    "entity.immersiveengineering.commando": "코만도",
    "entity.immersiveengineering.fusilier": "퓨질리어",
}

ALLOWED_KEYS = {
    "advancement.immersiveengineering.main_root",
    "advancement.immersiveengineering.secret_achtung.desc",
    "desc.immersiveengineering.flavour.fluidStack",
    "desc.immersiveengineering.info.fluidStored",
    "desc.immersiveengineering.info.percent",
    "gui.immersiveengineering.config.radio_tower.khz",
    "gui.immersiveengineering.config.radio_tower.range_m",
    "immersiveengineering.config.title",
    "itemGroup.immersiveengineering",
    "item.immersiveengineering.revolver.einhorn",
    "key.categories.immersiveengineering",
}

BUNDLED_KEY_OVERRIDES = {
    "immersiveengineering.config.title": "",
    "itemGroup.immersiveengineering": "Immersive Engineering",
    "key.categories.immersiveengineering": "Immersive Engineering",
    "entity.minecraft.villager.immersiveengineering.electrician": "전기 기술자",
    "entity.minecraft.villager.immersiveengineering.engineer": "구조 공학자",
    "entity.minecraft.villager.immersiveengineering.outfitter": "의상 제작자",
    "entity.immersiveengineering.cart_reinforcedcrate": "강화 저장 상자가 실린 광산 수레",
    "entity.immersiveengineering.explosive.name": "폭발물",
    "key.immersiveengineering.chemthrowerSwitch": "화학 분사기 탱크 전환",
    "key.immersiveengineering.magnetEquip": "자석 방패 장갑 착용(두 번 누르기)",
    "key.immersiveengineering.railgunZoom": "레일건으로 확대",
    "ie.manual.entry.mineral_subtitle": "광장하군요!",
    "death.attack.ieRazorShock": "%1$s이(가) 철조망에 감전되었습니다.",
    "death.attack.ieRazorWire": "%1$s이(가) 철조망에 난도질당했습니다.",
    "death.attack.ieRevolver_armorPiercing": "%1$s이(가) %2$s에게 총에 맞았습니다.",
    "death.attack.ieRevolver_armorPiercing.item": "%1$s이(가) %3$s을(를) 사용한 %2$s에게 총에 맞았습니다.",
    "death.attack.ieRevolver_armorPiercing.turret": "%1$s이(가) 포탑의 총격을 받았습니다.",
    "death.attack.ieRevolver_buckshot": "%1$s이(가) %2$s의 산탄에 벌집이 되었습니다.",
    "death.attack.ieRevolver_buckshot.item": "%1$s이(가) %3$s을(를) 사용한 %2$s의 산탄에 벌집이 되었습니다.",
    "death.attack.ieRevolver_buckshot.turret": "%1$s이(가) 포탑의 산탄에 벌집이 되었습니다.",
    "death.attack.ieRevolver_casull": "%1$s이(가) %2$s에게 총에 맞았습니다.",
    "death.attack.ieRevolver_casull.item": "%1$s이(가) %3$s을(를) 사용한 %2$s에게 총에 맞았습니다.",
    "death.attack.ieRevolver_casull.turret": "%1$s이(가) 포탑의 총격을 받았습니다.",
    "death.attack.ieRevolver_dragonsbreath.item": "%1$s이(가) %3$s을(를) 사용한 %2$s에게 소각당했습니다.",
    "death.attack.ieRevolver_dragonsbreath.turret": "%1$s이(가) 포탑에게 소각당했습니다.",
    "death.attack.ieRevolver_homing": "%1$s이(가) %2$s의 유도탄에 맞았습니다.",
    "death.attack.ieRevolver_homing.item": "%1$s이(가) %2$s의 %3$s에서 발사된 유도탄에 맞았습니다.",
    "death.attack.ieRevolver_homing.turret": "%1$s이(가) 포탑의 유도탄에 맞았습니다.",
    "death.attack.ieRevolver_potion": "%1$s이(가) %2$s의 약병탄에 흠뻑 젖었습니다.",
    "death.attack.ieRevolver_potion.item": "%1$s이(가) %2$s의 %3$s에서 발사된 약병탄에 흠뻑 젖었습니다.",
    "death.attack.ieRevolver_potion.turret": "%1$s이(가) 포탑의 약병탄에 흠뻑 젖었습니다.",
    "death.attack.ieRevolver_silver": "%1$s이(가) %2$s의 은탄에 정화되었습니다.",
    "death.attack.ieRevolver_silver.item": "%1$s이(가) %2$s의 %3$s에서 발사된 은탄에 정화되었습니다.",
    "death.attack.ieRevolver_silver.turret": "%1$s이(가) 포탑의 은탄에 정화되었습니다.",
    "death.attack.ieRevolver_wolfpack": "%1$s이(가) %2$s의 울프팩 탄환에 갈기갈기 찢어졌습니다.",
    "death.attack.ieRevolver_wolfpack.item": "%1$s이(가) %2$s의 %3$s에서 발사된 울프팩 탄환에 갈기갈기 찢어졌습니다.",
    "death.attack.ieRevolver_wolfpack.turret": "%1$s이(가) 포탑의 울프팩 탄환에 갈기갈기 찢어졌습니다.",
    "death.attack.ieTeslaPrimary": "%1$s이(가) 작동 중인 테슬라 코일의 1차 회로를 만졌습니다.",
    "death.attack.ieWireShock": "%1$s이(가) 전기가 흐르는 전선에 충분히 주의하지 않았습니다.",
    "death.attack.ieWireShock.player": "%1$s이(가) %2$s에게 밀려 전선에 닿았습니다.",
    "subtitle.immersiveengineering.chargeFast": "축전기 급속 충전",
    "subtitle.immersiveengineering.chargeSlow": "축전기 충전",
    "subtitle.immersiveengineering.chute": "아이템이 슈트를 통과함",
    "subtitle.immersiveengineering.crusher": "분쇄기가 광석을 분쇄함",
    "subtitle.immersiveengineering.dieselGenerator": "디젤 발전기가 시끄럽게 작동함",
    "subtitle.immersiveengineering.direSwitch": "Direwolf20가 나이프 스위치를 흉내 냄",
    "subtitle.immersiveengineering.metalPressPiston": "금속 프레스 피스톤",
    "subtitle.immersiveengineering.metalPressSmash": "금속 프레스가 쾅 소리를 냄",
    "subtitle.immersiveengineering.railgunFire": "레일건 발사",
    "subtitle.immersiveengineering.skyhook": "스카이훅이 전선을 따라 미끄러짐",
    "subtitle.immersiveengineering.spray": "유체 분사",
    "subtitle.immersiveengineering.sprayFire": "불붙은 유체 분사",
    "desc.immersiveengineering.info.durability": "내구도:",
    "ie.manual.entry.minerals_desc": "%1$s\n구성 광물: %2$s\n\n부산물:%3$s",
    "block.immersiveengineering.alu_scaffolding_grate_top": "격자형 알루미늄 비계",
    "block.immersiveengineering.alu_scaffolding_standard": "알루미늄 비계",
    "block.immersiveengineering.alu_scaffolding_wooden_top": "방부목 상판 알루미늄 비계",
    "block.immersiveengineering.slab_alu_scaffolding_grate_top": "격자형 알루미늄 비계 반 블록",
    "block.immersiveengineering.slab_alu_scaffolding_standard": "알루미늄 비계 반 블록",
    "block.immersiveengineering.slab_alu_scaffolding_wooden_top": "방부목 상판 알루미늄 비계 반 블록",
    "block.immersiveengineering.stairs_alu_scaffolding_grate_top": "격자형 알루미늄 비계 계단",
    "block.immersiveengineering.stairs_alu_scaffolding_standard": "알루미늄 비계 계단",
    "block.immersiveengineering.stairs_alu_scaffolding_wooden_top": "방부목 상판 알루미늄 비계 계단",
    "block.immersiveengineering.steel_scaffolding_grate_top": "격자형 강철 비계",
    "block.immersiveengineering.steel_scaffolding_standard": "강철 비계",
    "block.immersiveengineering.steel_scaffolding_wooden_top": "방부목 상판 강철 비계",
    "block.immersiveengineering.slab_steel_scaffolding_grate_top": "격자형 강철 비계 반 블록",
    "block.immersiveengineering.slab_steel_scaffolding_standard": "강철 비계 반 블록",
    "block.immersiveengineering.slab_steel_scaffolding_wooden_top": "방부목 상판 강철 비계 반 블록",
    "block.immersiveengineering.stairs_steel_scaffolding_grate_top": "격자형 강철 비계 계단",
    "block.immersiveengineering.stairs_steel_scaffolding_standard": "강철 비계 계단",
    "block.immersiveengineering.stairs_steel_scaffolding_wooden_top": "방부목 상판 강철 비계 계단",
    "block.immersiveengineering.metal_ladder_alu": "알루미늄 비계 덮개형 사다리",
    "block.immersiveengineering.metal_ladder_steel": "강철 비계 덮개형 사다리",
    "block.immersiveengineering.treated_wood_horizontal": "수평 방부목 판자",
    "block.immersiveengineering.treated_wood_packaged": "묶음 방부목 판자",
    "block.immersiveengineering.treated_wood_vertical": "수직 방부목 판자",
    "block.immersiveengineering.slab_treated_wood_horizontal": "수평 방부목 반 블록",
    "block.immersiveengineering.slab_treated_wood_packaged": "묶음 방부목 반 블록",
    "block.immersiveengineering.slab_treated_wood_vertical": "수직 방부목 반 블록",
    "block.immersiveengineering.stairs_treated_wood_horizontal": "수평 방부목 계단",
    "block.immersiveengineering.stairs_treated_wood_packaged": "묶음 방부목 계단",
    "block.immersiveengineering.stairs_treated_wood_vertical": "수직 방부목 계단",
    "desc.immersiveengineering.flavour.barrel": "유체를 보관합니다.",
    "desc.immersiveengineering.flavour.barrelTemp": "너무 뜨거운 기체나 유체는 보관할 수 없습니다!",
    "desc.immersiveengineering.flavour.noBlade": "톱날이 장착되지 않았습니다.",
    "desc.immersiveengineering.flavour.noDrillhead": "드릴 헤드가 장착되지 않았습니다.",
    "desc.immersiveengineering.flavour.rose": "겉모습에 속을 수 있습니다.",
    "desc.immersiveengineering.info.buzzsaw.spareblades": "원형톱에 추가 톱날을 보관합니다.",
    "desc.immersiveengineering.info.railgun.scope": "원거리 무기에 확대 기능을 추가합니다.",
    "desc.immersiveengineering.info.mineral.cinnabar": "진사",
    "desc.immersiveengineering.info.mineral.mephitic_quarzite": "유독성 규암",
    "desc.immersiveengineering.info.mineral.uraninite": "우라닌석",
    "desc.immersiveengineering.info.mineral.wolframite": "볼프라마이트",
    "desc.immersiveengineering.info.mininglvl.obsidian": "§d흑요석",
    "desc.immersiveengineering.info.shader.ancient": "고대에 전쟁터를 누볐던 병사들을 연상시키는 무늬입니다.",
    "desc.immersiveengineering.info.shader.angelsthesis": "날개 무늬와 선명한 하늘색 색조로 전설 속 천사를 떠올리게 합니다.",
    "desc.immersiveengineering.info.shader.argo": "Argo의 색상과 문양을 바탕으로 한 스타일입니다.",
    "desc.immersiveengineering.info.shader.astartes": "Astartes의 갑옷을 연상시키는 묵직한 색상과 문양입니다.",
    "desc.immersiveengineering.info.shader.chloris": "Chloris의 색상과 문양을 바탕으로 한 스타일입니다.",
    "desc.immersiveengineering.info.shader.crescentrose": "Ruby Rose가 사용하는 '대구경 저격소총 겸 낫' Crescent Rose를 본뜬 무늬입니다.",
    "desc.immersiveengineering.info.shader.crimsonlotus": "주인공 Crimson Lotus와 동명의 총잡이를 연상시키는 무늬입니다.",
    "desc.immersiveengineering.info.shader.darkfire": "Riku와 Terra가 사용하는 Dark Fire 마법을 본뜬 무늬입니다.",
    "desc.immersiveengineering.info.shader.dominator": "애니메이션 시리즈에 등장하는 거대한 핸드캐논을 본뜬 무늬입니다. 아쉽지만 변신하지는 않습니다.",
    "desc.immersiveengineering.info.shader.eruption": "Eruption의 불꽃처럼 강렬한 색상과 문양입니다.",
    "desc.immersiveengineering.info.shader.exia": "근접전에 특화된 건담 모빌 슈트 Exia를 본뜬 무늬입니다.",
    "desc.immersiveengineering.info.shader.eyas": "Eyas의 색상과 문양을 바탕으로 한 스타일입니다.",
    "desc.immersiveengineering.info.shader.felix": "용병 Felix의 갑옷을 연상시키는 색상과 문양입니다.",
    "desc.immersiveengineering.info.shader.fox": "여우의 털빛과 특징을 살린 무늬입니다.",
    "desc.immersiveengineering.info.shader.glacis": "Glacis의 차가운 색상과 문양을 바탕으로 한 스타일입니다.",
    "desc.immersiveengineering.info.shader.hollow": "Hollow Bastion을 연상시키는 색상과 문양입니다.",
    "desc.immersiveengineering.info.shader.ikelos": "I-KELOS 무기의 색상과 문양을 바탕으로 한 스타일입니다.",
    "desc.immersiveengineering.info.shader.kindled": "Kindled의 색상과 문양을 바탕으로 한 스타일입니다.",
    "desc.immersiveengineering.info.shader.locus": "용병 Locus의 갑옷을 연상시키는 색상과 문양입니다.",
    "desc.immersiveengineering.info.shader.massfusion": "Mass Fusion의 색상과 문양을 바탕으로 한 스타일입니다.",
    "desc.immersiveengineering.info.shader.matrix": "검은 바탕에 흐르는 초록색 코드로 가상 세계를 표현한 무늬입니다.",
    "desc.immersiveengineering.info.shader.milo": "Pyrrha의 무기 Miló를 본뜬 무늬입니다.",
    "desc.immersiveengineering.info.shader.n7": "N7 특수부대의 갑옷을 연상시키는 무늬입니다.",
    "desc.immersiveengineering.info.shader.omnitool": "Omni-Tool의 빛나는 색상과 문양을 본뜬 스타일입니다.",
    "desc.immersiveengineering.info.shader.qrow": "Qrow Branwen의 무기 Harbinger를 본뜬 무늬입니다.",
    "desc.immersiveengineering.info.shader.radiantgarden": "Radiant Garden의 색상과 문양을 바탕으로 한 스타일입니다.",
    "desc.immersiveengineering.info.shader.rosequartz": "Inkheart의 Rose Quartz를 연상시키는 색상과 문양입니다.",
    "desc.immersiveengineering.info.shader.sharkface": "시즌 11~13에 등장한 Sharkface의 갑옷을 연상시키는 무늬입니다.",
    "desc.immersiveengineering.info.shader.stormflower": "StormFlower의 칼날 달린 기관단총을 본뜬 무늬입니다.",
    "desc.immersiveengineering.info.shader.sunstrike": "Sunstrike의 눈부신 빛에서 영감을 받은 무늬입니다.",
    "desc.immersiveengineering.info.shader.sutherland": "Sutherland의 색상과 문양을 바탕으로 한 스타일입니다.",
    "desc.immersiveengineering.info.shader.twili": "Twili 종족의 어두운 색상과 빛나는 문양을 본뜬 스타일입니다.",
    "desc.immersiveengineering.info.shader.usurper": "찬탈자 Zant를 연상시키는 색상과 문양입니다.",
    "desc.immersiveengineering.info.shader.vaulttec": "Vault-Tec의 상징적인 파란색과 노란색을 사용한 무늬입니다.",
    "desc.immersiveengineering.info.shader.waaagh": "오크의 거친 전쟁 도색을 연상시키는 무늬입니다. WAAAGH!",
    "desc.immersiveengineering.info.shader.rarity.common": "일반",
    "desc.immersiveengineering.info.shader.rarity.epic": "영웅",
    "desc.immersiveengineering.info.shader.rarity.masterwork": "걸작",
    "desc.immersiveengineering.info.shader.rarity.rare": "희귀",
    "desc.immersiveengineering.info.shader.rarity.uncommon": "고급",
    "desc.immersiveengineering.info.shader.shield": "장갑 방패",
    "desc.immersiveengineering.info.shader.set": "셰이더 세트",
    "chat.immersiveengineering.command.mineral.get.pos": "중심: %1$s, %2$s, 반경: %3$s",
    "chat.immersiveengineering.info.survey.finished": "이 광맥에서 더 발견할 정보가 없습니다.",
    "chat.immersiveengineering.info.survey.hint.3": "%1$s 광맥이 %3$s으로 약 %2$s걸음 떨어진 곳에 있습니다.",
    "chat.immersiveengineering.warning.invalidPoint": "연결 지점 중 하나가 잘못되었습니다.",
    "gui.immersiveengineering.config.earmuffs.soundcategory.record": "음반",
    "gui.immersiveengineering.config.item_batcher.batchmode.SINGLE": "개별 필터 조건을 만족할 때 출력",
    "advancement.immersiveengineering.craft_buzzsaw.desc": "원형톱을 제작하세요.",
    "advancement.immersiveengineering.mb_blastfurnace": "진짜 뜨거운 화제",
    "advancement.immersiveengineering.mb_metalpress": "시급한 문제",
}

KOREAN_REPLACEMENTS = (
    ("화학 투척기", "화학 분사기"),
    ("데미지", "피해"),
    ("쉐이더", "셰이더"),
    ("엔지니어의", "공학자의"),
    ("레시피", "제작법"),
    ("텍스쳐", "텍스처"),
    ("만들수", "만들 수"),
    ("알수", "알 수"),
    ("씨끄러운", "시끄러운"),
    ("채글 등급", "채굴 등급"),
    ("광성", "광석"),
    ("고 통", "고통"),
)


def dump_json(path: Path, value: object) -> None:
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def translate_new(key: str, source: str) -> str | None:
    banner = re.fullmatch(
        r"block\.minecraft\.banner\.immersiveengineering\.([^.]+)\.([^.]+)", key
    )
    if banner:
        pattern, color = banner.groups()
        return f"{COLORS[color]} {BANNER_PATTERNS[pattern]}"
    chute = re.fullmatch(r"block\.immersiveengineering\.chute_colored_(.+)", key)
    if chute:
        return f"{COLORS[chute.group(1)]} 판금 슈트"
    warning = re.fullmatch(r"block\.immersiveengineering\.warning_sign_(.+)", key)
    if warning:
        return f"경고 표지 - {WARNING_SIGNS[warning.group(1)]}"
    if key.startswith("item.immersiveengineering.shader.name."):
        return source
    if key in KEY_TRANSLATIONS:
        return KEY_TRANSLATIONS[key]
    if source.startswith("Bucket of "):
        content = source.removeprefix("Bucket of ")
        if content in NAME_TRANSLATIONS:
            return f"{NAME_TRANSLATIONS[content]} 양동이"
    return TEXT_TRANSLATIONS.get(source, NAME_TRANSLATIONS.get(source))


def is_allowed_original(key: str) -> bool:
    return (
        key in ALLOWED_KEYS
        or key.startswith("item.immersiveengineering.shader.name.")
        or key.startswith("desc.immersiveengineering.info.operator.")
    )


def normalize() -> dict[str, object]:
    english = load_json(WORK_ROOT / "en_us.json")
    korean = load_json(WORK_ROOT / "ko_kr.json")
    sources = load_json(WORK_ROOT / "candidate_sources.json")
    changed = 0
    translated_new = 0
    unresolved = []
    for key, source in english.items():
        translated = korean[key]
        if key in BUNDLED_KEY_OVERRIDES:
            translated = BUNDLED_KEY_OVERRIDES[key]
        elif isinstance(source, str) and source in REVIEWED_VALUE_TRANSLATIONS:
            translated = REVIEWED_VALUE_TRANSLATIONS[source]
        elif sources[key] == "new_translation_required" and isinstance(source, str):
            translated = translate_new(key, source)
            if translated is None:
                unresolved.append(key)
                continue
            translated_new += 1
        elif sources[key] != "bundled_ko_kr":
            continue
        if sources[key] == "bundled_ko_kr" and isinstance(translated, str):
            for old, new in KOREAN_REPLACEMENTS:
                translated = translated.replace(old, new)
        errors = validate_value(key, source, translated)
        if errors:
            raise ValueError("; ".join(errors))
        if korean[key] != translated:
            korean[key] = translated
            changed += 1
    dump_json(WORK_ROOT / "ko_kr.json", korean)
    report = {
        "keys": len(english),
        "changed": changed,
        "newly_translated_or_allowed": translated_new,
        "unresolved": len(unresolved),
        "unresolved_examples": unresolved[:50],
    }
    dump_json(WORK_ROOT.parent / "normalization.json", report)
    return report


def verify() -> tuple[dict[str, object], list[str]]:
    english = load_json(WORK_ROOT / "en_us.json")
    korean = load_json(WORK_ROOT / "ko_kr.json")
    errors = []
    untranslated = []
    categories = Counter()
    if list(english) != list(korean):
        errors.append("키 또는 순서가 영어 원문과 다릅니다.")
    for key, source in english.items():
        target = korean.get(key)
        errors.extend(validate_value(key, source, target))
        if source == target and not is_allowed_original(key):
            untranslated.append(key)
            categories[".".join(key.split(".")[:2])] += 1
    report = {
        "keys": len(english),
        "untranslated": len(untranslated),
        "untranslated_by_category": dict(categories.most_common()),
        "untranslated_examples": untranslated[:50],
        "errors": errors,
        "status": "complete" if not errors and not untranslated else "incomplete",
    }
    dump_json(WORK_ROOT.parent / "specialized_language_validation.json", report)
    if untranslated:
        errors.append(f"미번역 {len(untranslated)}개")
    return report, errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("normalize", "verify"))
    args = parser.parse_args()
    if args.command == "normalize":
        report = normalize()
        errors = []
    else:
        report, errors = verify()
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
